/* =========================================================
   WISEBYTE — THE INNER CIRCLE (the Adyton)
   Unlocked only when every lesson is complete and every
   course is mastered. Expert questions, riddles and an
   advanced lexicon. Inner words use audience "inner" so they
   never appear in the normal word library.
   ========================================================= */
window.WB = window.WB || {};

WB.INNER = {
  questions: [
    { q: "What is the only positive whole number that is exactly twice the sum of its digits?", o: ["12", "18", "24", "36"], a: 1, e: "1 + 8 = 9, and 9 × 2 = 18." },
    { q: "Which war did the Peace of Westphalia (1648) bring to an end?", o: ["The Hundred Years' War", "The Thirty Years' War", "The War of the Roses", "The Seven Years' War"], a: 1, e: "It also helped establish the modern idea of sovereign states." },
    { q: "What does the Chandrasekhar limit describe?", o: ["The maximum mass of a stable white dwarf, about 1.4 solar masses", "The speed at which galaxies recede", "The size of the observable universe", "The minimum mass of a planet"], a: 0, e: "Above it, a white dwarf can't support itself against gravity." },
    { q: "Which language family does Finnish belong to?", o: ["Indo-European", "Uralic", "Turkic", "Germanic"], a: 1, e: "Along with Estonian and Hungarian, unlike most European languages." },
    { q: "Who proved Fermat's Last Theorem, announced in 1993 and completed in 1994?", o: ["Andrew Wiles", "Grigori Perelman", "Terence Tao", "Kurt Gödel"], a: 0, e: "It had resisted proof for over 350 years." },
    { q: "What do Gödel's incompleteness theorems show?", o: ["Every true statement can be proved", "Any consistent system capable of basic arithmetic contains true statements it cannot prove", "Mathematics is inconsistent", "Infinity doesn't exist"], a: 1, e: "Published by Kurt Gödel in 1931." },
    { q: "Which enzyme unwinds the DNA double helix during replication?", o: ["Ligase", "Helicase", "Polymerase", "Amylase"], a: 1, e: "Polymerase builds the new strands; ligase joins fragments." },
    { q: "In 1952 Michael Ventris deciphered the Linear B script. What language did it turn out to record?", o: ["Egyptian", "An early form of Greek", "Latin", "Phoenician"], a: 1, e: "The clay tablets were Mycenaean palace records, written centuries before Homer." },
    { q: "What does Gresham's law state?", o: ["Prices rise with demand", "Bad money drives out good", "Taxes reduce spending", "Trade benefits both sides"], a: 1, e: "People hoard more valuable coins and spend debased ones." },
    { q: "What are telomeres?", o: ["Enzymes that copy DNA", "Protective caps on the ends of chromosomes that shorten as cells divide", "Pores in the cell membrane", "Proteins that fold RNA"], a: 1, e: "Hobart-born Elizabeth Blackburn shared the 2009 Nobel Prize in Medicine for discovering how they are protected." },
    { q: "What is a Lagrange point?", o: ["The centre of a black hole", "A spot where the pull of two large bodies and orbital motion balance, so a small object can keep its position", "The lowest point of an orbit", "The edge of the solar system"], a: 1, e: "Every pair, such as the Sun and Earth, has five. Space telescopes are often parked near them." },
    { q: "Who composed The Rite of Spring, whose 1913 Paris premiere caused a near-riot?", o: ["Claude Debussy", "Igor Stravinsky", "Maurice Ravel", "Sergei Rachmaninoff"], a: 1, e: "Its dissonance and rhythms shocked the audience." },
    { q: "Which metal has the highest melting point?", o: ["Iron", "Titanium", "Tungsten", "Platinum"], a: 2, e: "About 3,422°C, which is why it is used in rocket nozzles and was used for light-bulb filaments." },
    { q: "What is a 'hapax legomenon'?", o: ["A Greek poem", "A word that appears only once in a text or body of writing", "A legal precedent", "A mathematical proof"], a: 1, e: "They can make ancient words very hard to translate." },
    { q: "Which of the Seven Wonders of the Ancient World stood at Alexandria?", o: ["The Colossus", "The Lighthouse (Pharos)", "The Hanging Gardens", "The Mausoleum"], a: 1, e: "It stood over 100 metres tall by some estimates." },
    { q: "What is the most abundant protein in the human body?", o: ["Keratin", "Collagen", "Haemoglobin", "Insulin"], a: 1, e: "It's a major component of skin, bone, tendons and ligaments." },
    { q: "Which moon of Saturn has a thick nitrogen-rich atmosphere and liquid methane lakes?", o: ["Europa", "Titan", "Enceladus", "Io"], a: 1, e: "Europa and Io orbit Jupiter." },
    { q: "In what year was the Treaty of Waitangi signed in New Zealand?", o: ["1788", "1840", "1901", "1907"], a: 1, e: "Between the British Crown and many Māori chiefs." },
    { q: "Who painted The Garden of Earthly Delights?", o: ["Pieter Bruegel", "Hieronymus Bosch", "Jan van Eyck", "Albrecht Dürer"], a: 1, e: "A strange, crowded triptych from around 1500." },
    { q: "Which mineral sits at 1, the softest, on the Mohs hardness scale?", o: ["Gypsum", "Talc", "Calcite", "Quartz"], a: 1, e: "Diamond sits at 10." },
    { q: "What does the Drake equation estimate?", o: ["The age of the universe", "The number of detectable alien civilisations in our galaxy", "The mass of a black hole", "The speed of continental drift"], a: 1, e: "Frank Drake wrote it in 1961. Most of its factors, like how often life arises, are still unknown." },
    { q: "Which philosopher wrote the Critique of Pure Reason (1781)?", o: ["Hegel", "Immanuel Kant", "David Hume", "Descartes"], a: 1, e: "Kant was 'awakened from his dogmatic slumber' by Hume." },
    { q: "In economics, what is a 'Giffen good'?", o: ["A luxury item", "A good whose demand rises as its price rises, due to poverty", "A free public good", "An imported good"], a: 1, e: "A rare exception to the usual law of demand." },
    { q: "Leonhard Euler's 1736 solution to the Seven Bridges of Königsberg problem founded which branch of maths?", o: ["Calculus", "Graph theory", "Probability", "Number theory"], a: 1, e: "He proved no walk could cross each of the city's seven bridges exactly once, by reducing the map to points and lines." },
    { q: "Which is the only sea with no coastline?", o: ["The Sargasso Sea", "The Coral Sea", "The Caspian Sea", "The Tasman Sea"], a: 0, e: "It lies in the North Atlantic, bounded by ocean currents rather than land, and is named after its floating Sargassum seaweed." },
    { q: "What does the Latin legal phrase 'habeas corpus' literally mean?", o: ["Let the buyer beware", "You shall have the body", "In good faith", "The thing speaks for itself"], a: 1, e: "It protects against unlawful detention." },
    { q: "The Hanseatic League, a powerful medieval trading network, was centred on which sea?", o: ["The Mediterranean", "The Baltic", "The Black Sea", "The Caspian"], a: 1, e: "Merchant towns such as Lübeck, Hamburg and Riga dominated northern European trade from the 1200s to the 1400s." },
    { q: "What is the smallest prime number greater than 100?", o: ["101", "103", "107", "109"], a: 0, e: "101 has no divisors other than 1 and itself." },
    { q: "Which physicist predicted antimatter in 1928, from an equation combining quantum mechanics and relativity?", o: ["Paul Dirac", "Enrico Fermi", "Richard Feynman", "Niels Bohr"], a: 0, e: "The positron, the electron's antimatter twin, was found by Carl Anderson in 1932." },
    { q: "The Voynich manuscript is famous for what?", o: ["Being the oldest printed book", "Being written in an unknown script that no one has deciphered", "Containing Leonardo da Vinci's secret notes", "Being the first English dictionary"], a: 1, e: "Its vellum dates to the early 1400s. The strange text and drawings of unknown plants still baffle cryptographers." },
  ],
  riddles: [
    { q: "What has cities but no houses, forests but no trees, and water but no fish?", o: ["A globe", "A map", "A dream", "A painting"], a: 1, e: "A map shows everything, but contains none of it." },
    { q: "What walks on four legs in the morning, two at noon, and three in the evening?", o: ["A cat", "A human", "A table", "A shadow"], a: 1, e: "The Sphinx's riddle: a baby crawls, an adult walks, an elder uses a cane." },
    { q: "The more you take, the more you leave behind. What are they?", o: ["Photos", "Footsteps", "Breaths", "Memories"], a: 1, e: "Every step taken leaves a footprint." },
    { q: "A man looks at a portrait and says: 'Brothers and sisters I have none, but that man's father is my father's son.' Who is in the portrait?", o: ["Himself", "His son", "His father", "His nephew"], a: 1, e: "'My father's son' is himself, so the man's father is him: it's his son." },
    { q: "What can run but never walks, has a mouth but never talks, has a head but never weeps, and a bed but never sleeps?", o: ["A clock", "A river", "A road", "A candle"], a: 1, e: "A river runs, has a mouth, a head and a bed." },
    { q: "What comes next: 1, 11, 21, 1211, 111221, ?", o: ["312211", "1112221", "211211", "122111"], a: 0, e: "Each term describes the one before: 111221 is 'three 1s, two 2s, one 1', so 312211." },
    { q: "What comes once in a minute, twice in a moment, but never in a thousand years?", o: ["A second", "The letter M", "A heartbeat", "Luck"], a: 1, e: "Count the letters." },
    { q: "Two ropes each take exactly an hour to burn, but they burn unevenly. How can you time exactly 45 minutes?", o: ["It can't be done", "Light rope A at both ends and rope B at one end; when A burns out, light B's other end", "Cut each rope into quarters", "Burn one rope, then half of the other"], a: 1, e: "Lit at both ends, A finishes in 30 minutes. B then has 30 minutes of burning left; lit at both ends, that takes 15 more." },
    { q: "How many times do a clock's hour and minute hands overlap in a full 24-hour day?", o: ["24", "22", "23", "48"], a: 1, e: "The minute hand laps the hour hand 11 times every 12 hours, not 12, so 22 times a day." },
    { q: "Eight identical-looking balls include one that is slightly heavier. What is the fewest weighings on a balance scale that guarantees finding it?", o: ["1", "2", "3", "4"], a: 1, e: "Weigh 3 against 3. If they balance, weigh the last 2 against each other. If not, take the heavier 3 and weigh 1 against 1." },
    { q: "What is so fragile that saying its name breaks it?", o: ["Glass", "Silence", "A promise", "Trust"], a: 1, e: "Say 'silence' and it's gone." },
    { q: "On an island, knights always tell the truth and knaves always lie. A says: 'We are both knaves.' What are A and B?", o: ["Both knaves", "A is a knave, B is a knight", "Both knights", "A is a knight, B is a knave"], a: 1, e: "A knight couldn't say it, so A lies; then 'both knaves' is false, so B is a knight." },
    { q: "Four cards show A, K, 4 and 7. Each has a letter on one side and a number on the other. To test the rule 'If a card has a vowel on one side, it has an even number on the other', which cards must you turn over?", o: ["A and 4", "A and 7", "A only", "A, 4 and 7"], a: 1, e: "Turn A (it must hide an even number) and 7 (it must not hide a vowel). The 4 can't break the rule whatever is behind it." },
    { q: "A rooster lays an egg on the peak of a sloped roof. Which way does it roll?", o: ["Left", "Right", "It stays", "Roosters don't lay eggs"], a: 3, e: "Only hens lay eggs." },
    { q: "Three switches downstairs control one bulb upstairs. You may go upstairs once. How do you find the right switch?", o: ["Guess", "Turn one on for minutes, off, turn a second on, then go up and check light and warmth", "Flick all three", "Unscrew the bulb"], a: 1, e: "On = second switch; off but warm = first; off and cold = third." },
  ],
};

WB.WORDS.push(
{ w: "perspicacious", audience: "inner", pos: "adjective", ipa: "/ˌpɜːspɪˈkeɪʃəs/", say: "per-spih-KAY-shus", lvl: 3, cat: "academic",
  def: "Having a ready insight into and understanding of things; shrewd.", ex: ["A perspicacious reader will spot the twist early.", "Her perspicacious questions exposed the flaw in the plan."],
  syn: ["astute", "shrewd", "discerning"], ant: ["obtuse", "dim"], origin: "From Latin perspicax, 'seeing clearly'.", blank: "The ___ investor saw the crash coming." },
{ w: "sesquipedalian", audience: "inner", pos: "adjective", ipa: "/ˌseskwɪpɪˈdeɪliən/", say: "ses-kwih-pih-DAY-lee-un", lvl: 3, cat: "academic",
  def: "Given to using long words; (of a word) having many syllables.", ex: ["His sesquipedalian lectures lost half the class.", "'Sesquipedalian' is itself a sesquipedalian word."],
  syn: ["long-winded", "verbose", "grandiloquent"], ant: ["concise", "plain"], origin: "From Latin sesquipedalis, 'a foot and a half long', mocking long words.", blank: "The ___ report used ten syllables where two would do." },
{ w: "pusillanimous", audience: "inner", pos: "adjective", ipa: "/ˌpjuːsɪˈlænɪməs/", say: "pyoo-sih-LAN-ih-mus", lvl: 3, cat: "people",
  def: "Showing a lack of courage or determination; timid.", ex: ["The pusillanimous response let the bully win.", "Critics called the policy pusillanimous."],
  syn: ["cowardly", "timid", "faint-hearted"], ant: ["brave", "bold"], origin: "From Latin pusillus, 'very small', and animus, 'mind'.", blank: "A ___ leader avoids every hard decision." },
{ w: "obsequious", audience: "inner", pos: "adjective", ipa: "/əbˈsiːkwiəs/", say: "ub-SEE-kwee-us", lvl: 3, cat: "people",
  def: "Excessively eager to please or obey.", ex: ["The obsequious waiter hovered all night.", "He was obsequious to the boss and rude to everyone else."],
  syn: ["servile", "fawning", "sycophantic"], ant: ["assertive", "independent"], origin: "From Latin obsequiosus, from obsequi, 'to comply'.", blank: "The ___ assistant laughed at every one of her jokes." },
{ w: "lugubrious", audience: "inner", pos: "adjective", ipa: "/lʊˈɡuːbriəs/", say: "loo-GOO-bree-us", lvl: 3, cat: "everyday",
  def: "Looking or sounding sad and dismal.", ex: ["A lugubrious tune played at the funeral.", "His lugubrious expression never changed."],
  syn: ["mournful", "gloomy", "doleful"], ant: ["cheerful", "jovial"], origin: "From Latin lugubris, from lugere, 'to mourn'.", blank: "The bloodhound gave a ___ howl." },
{ w: "pellucid", audience: "inner", pos: "adjective", ipa: "/pɪˈluːsɪd/", say: "peh-LOO-sid", lvl: 3, cat: "academic",
  def: "Translucently clear; (of writing) easily understood.", ex: ["The pellucid water showed every pebble.", "Her pellucid prose made a hard topic easy."],
  syn: ["limpid", "lucid", "transparent"], ant: ["murky", "obscure"], origin: "From Latin pellucidus, 'shining through'.", blank: "The textbook's ___ explanations won praise." },
{ w: "recondite", audience: "inner", pos: "adjective", ipa: "/ˈrekəndaɪt/", say: "REK-un-dyt", lvl: 3, cat: "academic",
  def: "Little known; abstruse and requiring specialist knowledge.", ex: ["He loved recondite facts about medieval heraldry.", "The paper was too recondite for most readers."],
  syn: ["obscure", "esoteric", "arcane"], ant: ["common", "familiar"], origin: "From Latin reconditus, 'hidden, put away'.", blank: "The quiz winner knew the most ___ trivia." },
{ w: "apotheosis", audience: "inner", pos: "noun", ipa: "/əˌpɒθiˈəʊsɪs/", say: "uh-poth-ee-OH-sis", lvl: 3, cat: "academic",
  def: "The highest point or perfect example of something; elevation to divine status.", ex: ["The cathedral is the apotheosis of Gothic design.", "Roman emperors sometimes received apotheosis after death."],
  syn: ["epitome", "pinnacle", "deification"], ant: ["nadir"], origin: "From Greek apotheoun, 'to make a god of'.", blank: "The final album was the ___ of her career." },
{ w: "defenestration", audience: "inner", pos: "noun", ipa: "/diːˌfenɪˈstreɪʃn/", say: "dee-fen-ih-STRAY-shun", lvl: 3, cat: "law",
  def: "The act of throwing someone out of a window; (informally) removing someone from power.", ex: ["The Defenestration of Prague in 1618 helped spark the Thirty Years' War.", "The board's defenestration of the CEO surprised investors."],
  syn: ["ejection", "ousting"], ant: [], origin: "From Latin de-, 'out of', and fenestra, 'window'.", blank: "The sudden ___ of the party leader shocked voters." },
{ w: "ineffable", audience: "inner", pos: "adjective", ipa: "/ɪnˈefəbl/", say: "in-EF-uh-bul", lvl: 3, cat: "everyday",
  def: "Too great or extreme to be expressed in words.", ex: ["The view from the summit was ineffable.", "They felt an ineffable joy at the birth."],
  syn: ["indescribable", "inexpressible", "unspeakable"], ant: ["describable"], origin: "From Latin ineffabilis, 'unutterable'.", blank: "Words failed her; the beauty was ___." },
{ w: "obstreperous", audience: "inner", pos: "adjective", ipa: "/əbˈstrepərəs/", say: "ub-STREP-uh-rus", lvl: 3, cat: "people",
  def: "Noisy and difficult to control.", ex: ["The obstreperous crowd drowned out the speaker.", "An obstreperous toddler refused to sit."],
  syn: ["unruly", "boisterous", "rowdy"], ant: ["quiet", "docile"], origin: "From Latin obstrepere, 'to make a noise against'.", blank: "Security removed the ___ fan." },
{ w: "tergiversate", audience: "inner", pos: "verb", ipa: "/ˈtɜːdʒɪvəseɪt/", say: "TER-jih-ver-sayt", lvl: 3, cat: "law",
  def: "To make conflicting or evasive statements; to change sides.", ex: ["The minister continued to tergiversate under questioning.", "He tergiversated so often no one trusted him."],
  syn: ["equivocate", "prevaricate", "hedge"], ant: ["commit"], origin: "From Latin tergiversari, 'to turn one's back'.", blank: "Pressed for an answer, the witness began to ___." },
{ w: "crepuscular", audience: "inner", pos: "adjective", ipa: "/krɪˈpʌskjələ/", say: "krih-PUS-kyoo-lur", lvl: 3, cat: "science",
  def: "Relating to twilight; (of animals) active at dawn and dusk.", ex: ["Kangaroos are largely crepuscular.", "The crepuscular light turned the hills purple."],
  syn: ["twilit", "dim"], ant: ["diurnal", "nocturnal"], origin: "From Latin crepusculum, 'twilight'.", blank: "Wombats and rabbits are ___ feeders." },
{ w: "susurrus", audience: "inner", pos: "noun", ipa: "/sjuːˈsʌrəs/", say: "soo-SUR-us", lvl: 3, cat: "everyday",
  def: "A whispering or rustling sound.", ex: ["The susurrus of leaves filled the valley.", "A susurrus ran through the audience."],
  syn: ["murmur", "whisper", "rustle"], ant: ["roar", "din"], origin: "Latin for 'a murmuring, whispering'.", blank: "We fell asleep to the ___ of the waves." },
{ w: "sempiternal", audience: "inner", pos: "adjective", ipa: "/ˌsempɪˈtɜːnl/", say: "sem-pih-TER-nul", lvl: 3, cat: "academic",
  def: "Eternal and unchanging; everlasting.", ex: ["Poets wrote of the sempiternal stars.", "The monks sought sempiternal truths."],
  syn: ["everlasting", "eternal", "perpetual"], ant: ["ephemeral", "transient"], origin: "From Latin semper, 'always', and aeternus, 'eternal'.", blank: "The mountains seemed ___, unchanged by time." },
{ w: "vicissitude", audience: "inner", pos: "noun", ipa: "/vɪˈsɪsɪtjuːd/", say: "vih-SIS-ih-tyood", lvl: 3, cat: "academic",
  def: "A change of circumstances, typically one that is unwelcome or unpleasant.", ex: ["The vicissitudes of fortune tested his Stoicism.", "The company survived the vicissitudes of the market."],
  syn: ["change", "fluctuation", "upheaval"], ant: ["stability", "constancy"], origin: "From Latin vicissitudo, from vicis, 'turn, change'.", blank: "Life's ___ taught her resilience." },
{ w: "apophenia", audience: "inner", pos: "noun", ipa: "/ˌæpəˈfiːniə/", say: "ap-uh-FEE-nee-uh", lvl: 3, cat: "science",
  def: "The tendency to perceive meaningful connections between unrelated things.", ex: ["Seeing faces in clouds is a form of apophenia.", "Conspiracy theories often feed on apophenia."],
  syn: ["pattern-seeking"], ant: [], origin: "Coined in German (Apophänie) by psychiatrist Klaus Conrad in 1958.", blank: "Finding secret codes in random numbers is classic ___." },
{ w: "petrichor", audience: "inner", pos: "noun", ipa: "/ˈpetrɪkɔː/", say: "PET-rih-kor", lvl: 3, cat: "science",
  def: "The pleasant, earthy smell produced when rain falls on dry ground.", ex: ["The first storm of summer brought the scent of petrichor.", "Petrichor filled the air after weeks of drought."],
  syn: ["rain scent"], ant: [], origin: "Coined in 1964 by Australian CSIRO scientists Isabel Bear and Richard Thomas, from Greek petra, 'stone', and ichor, the fluid in gods' veins.", blank: "After the drought, the ___ was glorious." },
{ w: "eleemosynary", audience: "inner", pos: "adjective", ipa: "/ˌeliːˈmɒsɪnəri/", say: "el-ee-MOS-ih-nuh-ree", lvl: 3, cat: "business",
  def: "Relating to or dependent on charity; charitable.", ex: ["The foundation's eleemosynary work fed thousands.", "Monasteries once had eleemosynary duties to the poor."],
  syn: ["charitable", "philanthropic"], ant: ["mercenary"], origin: "From Greek eleēmosynē, 'pity, alms'.", blank: "The trust exists for purely ___ purposes." },
{ w: "antediluvian", audience: "inner", pos: "adjective", ipa: "/ˌæntidɪˈluːviən/", say: "an-tee-dih-LOO-vee-un", lvl: 3, cat: "everyday",
  def: "Ridiculously old-fashioned; (literally) from before the biblical Flood.", ex: ["The office still runs on antediluvian computers.", "His antediluvian views shocked the younger staff."],
  syn: ["antiquated", "archaic", "obsolete"], ant: ["modern", "cutting-edge"], origin: "From Latin ante, 'before', and diluvium, 'flood'.", blank: "Grandpa's ___ phone had a rotary dial." },
{ w: "lachrymose", audience: "inner", pos: "adjective", ipa: "/ˈlækrɪməʊs/", say: "LAK-rih-mohs", lvl: 3, cat: "people",
  def: "Tearful or given to weeping; tending to cause tears.", ex: ["The lachrymose farewell went on for an hour.", "It was a lachrymose film about lost love."],
  syn: ["tearful", "weepy", "maudlin"], ant: ["cheerful", "dry-eyed"], origin: "From Latin lacrima, 'tear'.", blank: "The wedding speeches left everyone ___." },
{ w: "mellifluous", audience: "inner", pos: "adjective", ipa: "/məˈlɪfluəs/", say: "meh-LIF-loo-us", lvl: 3, cat: "everyday",
  def: "(Of a voice or words) sweet and smooth to hear.", ex: ["The narrator's mellifluous voice was perfect for audiobooks.", "She spoke in mellifluous Italian."],
  syn: ["dulcet", "honeyed", "melodious"], ant: ["harsh", "grating"], origin: "From Latin mel, 'honey', and fluere, 'to flow'.", blank: "The cellist drew a ___ tone from the old instrument." },
{ w: "pernicious", audience: "inner", pos: "adjective", ipa: "/pəˈnɪʃəs/", say: "per-NISH-us", lvl: 3, cat: "academic",
  def: "Having a harmful effect, especially gradually or subtly.", ex: ["Misinformation has a pernicious effect on trust.", "The pernicious habit crept up on him."],
  syn: ["harmful", "insidious", "destructive"], ant: ["benign", "beneficial"], origin: "From Latin perniciosus, 'destructive', from pernicies, 'ruin'.", blank: "Gossip had a ___ influence on the team." },
{ w: "loquacious", audience: "inner", pos: "adjective", ipa: "/ləˈkweɪʃəs/", say: "loh-KWAY-shus", lvl: 3, cat: "people",
  def: "Tending to talk a great deal; talkative.", ex: ["Our loquacious tour guide never paused for breath.", "Wine made him loquacious."],
  syn: ["talkative", "garrulous", "voluble"], ant: ["taciturn", "reticent"], origin: "From Latin loqui, 'to talk'.", blank: "The ___ passenger chatted the whole flight." },
);
