/* WISEBYTE INNER CIRCLE (part 3): more Arcane Lexicon words and expert riddles */
WB.WORDS.push(
  { w: "quotidian", audience: "inner", pos: "adjective", ipa: "/kwɒˈtɪdiən/", say: "kwo-TID-ee-un", lvl: 3, cat: "everyday", def: "Occurring every day; ordinary and commonplace to the point of dullness.", ex: ["She found poetry in the quotidian rhythm of the 7:42 train into Flinders Street.", "The novel lingers on quotidian details: burnt toast, school lunches, the bins on a Tuesday night."], syn: ["daily", "mundane", "humdrum"], ant: ["extraordinary", "rare"], origin: "From Latin quotidianus, from quotidie 'every day' (quot 'how many' + dies 'day').", blank: "After a month of travel, he was oddly glad to return to the ___ routine of commuting, cooking and sleeping." },
  { w: "insouciant", audience: "inner", pos: "adjective", ipa: "/ɪnˈsuːsiənt/", say: "in-SOO-see-unt", lvl: 3, cat: "people", def: "Showing a casual, carefree lack of concern, especially where worry would be expected.", ex: ["He strolled into the exam ten minutes late with an insouciant grin.", "Her insouciant shrug suggested the parking fine was the least of her worries."], syn: ["nonchalant", "carefree", "unconcerned"], ant: ["anxious", "worried"], origin: "From French, in- 'not' + soucier 'to worry, care', from Latin sollicitare 'to disturb'.", blank: "Despite the storm warnings, the surfer remained ___, waxing his board as the sky turned black." },
  { w: "palimpsest", audience: "inner", pos: "noun", ipa: "/ˈpælɪmpsest/", say: "PAL-imp-sest", lvl: 3, cat: "academic", def: "A manuscript page scraped or washed and written over, with traces of the earlier text still visible; by extension, anything bearing layers of its own history.", ex: ["Multispectral imaging revealed lost works of Archimedes hidden beneath the prayers of a medieval palimpsest.", "The old terrace in Fitzroy is a palimpsest of painted signs, each fading through the next."], syn: ["overwritten manuscript", "layered record"], ant: [], origin: "Via Latin from Greek palimpsestos 'scraped again', from palin 'again' + psen 'to rub smooth'.", blank: "Under ultraviolet light the parchment proved to be a ___, with an older Greek text beneath the Latin." },
  { w: "numinous", audience: "inner", pos: "adjective", ipa: "/ˈnjuːmɪnəs/", say: "NYOO-min-us", lvl: 3, cat: "academic", def: "Having a strong spiritual or religious quality; suggesting the presence of something divine or awe-inspiring.", ex: ["At dawn, Uluru glowing red felt almost numinous to the silent crowd.", "The cathedral's vast, dim nave produced a numinous hush."], syn: ["sacred", "transcendent", "awe-inspiring"], ant: ["profane", "mundane"], origin: "From Latin numen, numinis 'divine power, nod of the gods'; popularised by Rudolf Otto's The Idea of the Holy (1917).", blank: "Standing alone among the ancient redwoods, she felt a ___ sense of being in the presence of something holy." },
  { w: "ineluctable", audience: "inner", pos: "adjective", ipa: "/ˌɪnɪˈlʌktəbl/", say: "in-ih-LUK-tuh-bul", lvl: 3, cat: "academic", def: "Impossible to escape or avoid, however hard one struggles.", ex: ["Rising sea levels are an ineluctable concern for low-lying Pacific nations.", "The tragedy moves with ineluctable logic towards its final scene."], syn: ["inescapable", "inevitable", "unavoidable"], ant: ["avoidable", "escapable"], origin: "From Latin ineluctabilis, from in- 'not' + eluctari 'to struggle out of'.", blank: "Ageing is ___: no diet, cream or surgery can hold it off forever." },
  { w: "lacuna", audience: "inner", pos: "noun", ipa: "/ləˈkjuːnə/", say: "luh-KYOO-nuh", lvl: 3, cat: "academic", def: "An unfilled space or gap, especially a missing section in a manuscript, argument or body of knowledge.", ex: ["The thesis fills a lacuna in research on early colonial Tasmania.", "A water-damaged lacuna in the diary leaves three crucial days unexplained."], syn: ["gap", "hiatus", "omission"], ant: [], origin: "From Latin lacuna 'pool, pit, gap', from lacus 'lake'.", blank: "Scholars have long puzzled over the ___ in the poem, where an entire stanza was torn from the page." },
  { w: "perfidious", audience: "inner", pos: "adjective", ipa: "/pəˈfɪdiəs/", say: "per-FID-ee-us", lvl: 3, cat: "people", def: "Deliberately faithless and treacherous; betraying trust.", ex: ["The perfidious adviser sold the campaign's strategy to the rival party.", "'Perfidious Albion' was a long-standing French jibe at supposed English treachery."], syn: ["treacherous", "traitorous", "duplicitous"], ant: ["loyal", "faithful"], origin: "From Latin perfidiosus, from perfidia 'treachery', from per- 'away from' + fides 'faith'.", blank: "The ___ ally signed the treaty in the morning and invaded by nightfall." },
  { w: "verisimilitude", audience: "inner", pos: "noun", ipa: "/ˌverɪsɪˈmɪlɪtjuːd/", say: "veh-rih-sih-MIL-ih-tyood", lvl: 3, cat: "academic", def: "The appearance of being true or real, especially in fiction or art.", ex: ["The film's verisimilitude owes much to shooting on location in outback Queensland.", "Small, precise details lend a story verisimilitude."], syn: ["realism", "plausibility", "authenticity"], ant: ["implausibility"], origin: "From Latin verisimilitudo, from verisimilis 'probable', literally 'like the truth' (verum 'true' + similis 'like').", blank: "The novelist interviewed retired detectives to give her crime scenes greater ___." },
  { w: "anodyne", audience: "inner", pos: "adjective", ipa: "/ˈænədaɪn/", say: "AN-uh-dine", lvl: 3, cat: "everyday", def: "Deliberately inoffensive and bland, so as to avoid provoking any reaction; (originally) relieving pain.", ex: ["The press release was a page of anodyne corporate phrases that said nothing at all.", "He gave an anodyne answer about 'learning from the process'."], syn: ["bland", "innocuous", "inoffensive"], ant: ["provocative", "controversial"], origin: "Via Latin from Greek anodunos 'painless', from an- 'without' + odune 'pain'.", blank: "Fearing a backlash, the minister replaced her fiery speech with a few ___ remarks about working together." },
  { w: "halcyon", audience: "inner", pos: "adjective", ipa: "/ˈhælsiən/", say: "HAL-see-un", lvl: 3, cat: "everyday", def: "Denoting a past period remembered as idyllically happy and peaceful.", ex: ["He spoke wistfully of the halcyon summers of his youth on the Mornington Peninsula.", "Those were the halcyon days before mortgages and deadlines."], syn: ["idyllic", "golden", "serene"], ant: ["turbulent", "troubled"], origin: "From Greek alkuon 'kingfisher'; in legend the bird calmed the sea to nest on it around the winter solstice, the 'halcyon days'.", blank: "Grandma still talks about the ___ days of the 1960s, when the whole street left their doors unlocked." },
  { w: "diaphanous", audience: "inner", pos: "adjective", ipa: "/daɪˈæfənəs/", say: "dy-AF-uh-nus", lvl: 3, cat: "everyday", def: "(Especially of fabric) so light, delicate and fine that it is almost transparent.", ex: ["A diaphanous curtain stirred in the sea breeze.", "The dragonfly's diaphanous wings caught the afternoon light."], syn: ["sheer", "gauzy", "translucent"], ant: ["opaque", "thick"], origin: "From medieval Latin diaphanus, from Greek diaphanes 'see-through', from dia 'through' + phainein 'to show'.", blank: "The bride wore a ___ veil of silk so fine you could read print through it." },
  { w: "evanescent", audience: "inner", pos: "adjective", ipa: "/ˌiːvəˈnesnt/", say: "ee-vuh-NES-unt", lvl: 3, cat: "everyday", def: "Vanishing gradually from sight or memory; fading away almost as soon as it appears.", ex: ["The evanescent glow of the aurora australis faded before she could find her camera.", "Fame on social media is evanescent."], syn: ["fleeting", "transient", "vanishing"], ant: ["permanent", "enduring"], origin: "From Latin evanescere 'to disappear', from e- 'out' + vanescere 'to vanish' (vanus 'empty').", blank: "The scent of the jasmine was ___, gone the moment the wind changed." },
  { w: "sybarite", audience: "inner", pos: "noun", ipa: "/ˈsɪbəraɪt/", say: "SIB-uh-rite", lvl: 3, cat: "people", def: "A person who is self-indulgently devoted to luxury and sensual pleasure.", ex: ["A true sybarite, he booked the spa, the degustation and the penthouse in a single weekend.", "The resort markets itself to sybarites who never want to lift a finger."], syn: ["hedonist", "voluptuary", "epicure"], ant: ["ascetic"], origin: "From Sybaris, an ancient Greek city in southern Italy whose citizens were famed for their luxury.", blank: "Only a committed ___ would insist on silk sheets and champagne while camping." },
  { w: "peripatetic", audience: "inner", pos: "adjective", ipa: "/ˌperɪpəˈtetɪk/", say: "peh-rih-puh-TET-ik", lvl: 3, cat: "people", def: "Travelling from place to place, especially working or living in a series of locations for short periods.", ex: ["As a peripatetic music teacher, she visits six schools across the Riverina each week.", "His peripatetic childhood, following his father's mining jobs, meant nine schools in ten years."], syn: ["itinerant", "nomadic", "roving"], ant: ["settled", "sedentary"], origin: "From Greek peripatetikos, from peripatein 'to walk up and down'; applied to Aristotle's school, which taught in a covered walkway of the Lyceum.", blank: "The ___ surgeon flew between remote clinics in the Kimberley, never staying more than a week." },
  { w: "ultracrepidarian", audience: "inner", pos: "noun", ipa: "/ˌʌltrəˌkrepɪˈdeəriən/", say: "ul-truh-krep-ih-DAIR-ee-un", lvl: 3, cat: "people", def: "A person who confidently gives opinions on matters beyond their knowledge or expertise.", ex: ["The comment section was full of ultracrepidarians explaining virology to virologists.", "A celebrity turned ultracrepidarian, he now lectures economists on monetary policy."], syn: ["know-all", "armchair expert"], ant: ["specialist", "expert"], origin: "From Latin ultra crepidam 'beyond the sandal', from Pliny's story of the painter Apelles telling a cobbler who criticised more than a sandal to stick to his trade; used by William Hazlitt in 1819.", blank: "The footballer was an ___, offering his views on quantum physics and climate science with equal confidence." },
  { w: "desuetude", audience: "inner", pos: "noun", ipa: "/dɪˈsjuːɪtjuːd/", say: "dih-SYOO-ih-tyood", lvl: 3, cat: "law", def: "A state of disuse, especially of a law or custom that is no longer observed or enforced.", ex: ["The old statute against Sunday trading had long fallen into desuetude.", "The tradition of formal calling cards has passed into desuetude."], syn: ["disuse", "obsolescence", "abeyance"], ant: ["use", "currency"], origin: "From Latin desuetudo, from desuescere 'to become unaccustomed', from de- 'away' + suescere 'to grow used to'.", blank: "No one had been prosecuted under the archaic law for a century, and judges agreed it had fallen into ___." },
  { w: "usufruct", audience: "inner", pos: "noun", ipa: "/ˈjuːzjuːfrʌkt/", say: "YOO-zyoo-frukt", lvl: 3, cat: "law", def: "The legal right to use and enjoy the income or produce of another's property, without owning it and without damaging or diminishing its substance.", ex: ["Under the will, she held a usufruct of the farm for life, after which it passed to her nephews.", "The usufruct let him keep the rents from the building but not sell it."], syn: ["right of use", "life interest"], ant: ["ownership"], origin: "From Latin usufructus, from usus et fructus 'use and enjoyment (of the fruits)'.", blank: "He could harvest the orchard's apples under his ___, but he could not fell the trees or sell the land." },
  { w: "sinecure", audience: "inner", pos: "noun", ipa: "/ˈsaɪnɪkjʊə/", say: "SY-nih-kyoor", lvl: 3, cat: "business", def: "A paid position that requires little or no work but brings status or income.", ex: ["Critics called the ambassadorship a sinecure for retired politicians.", "His board seat was a sinecure: four meetings a year and a generous fee."], syn: ["cushy job", "soft option"], ant: ["hard slog"], origin: "From Latin sine cura 'without care', originally a church benefice without the 'cure' (care) of souls.", blank: "The so-called advisory role was a ___, paying a full salary for one lunch a month." },
  { w: "prolix", audience: "inner", pos: "adjective", ipa: "/ˈprəʊlɪks/", say: "PROH-liks", lvl: 3, cat: "academic", def: "(Of speech or writing) using too many words and therefore tediously long.", ex: ["The judge criticised the prolix submissions, which ran to four hundred pages.", "Her early drafts were prolix, but the editor cut them to the bone."], syn: ["verbose", "long-winded", "wordy"], ant: ["concise", "terse"], origin: "From Latin prolixus 'poured forth, extended', from pro- 'forward' + liquere 'to be liquid'.", blank: "The report was so ___ that its key finding was buried on page ninety." },
  { w: "ataraxia", audience: "inner", pos: "noun", ipa: "/ˌætəˈræksiə/", say: "at-uh-RAK-see-uh", lvl: 3, cat: "academic", def: "A state of serene calm and freedom from mental disturbance, prized as the goal of life by Epicureans and Sceptics.", ex: ["Epicurus taught that ataraxia comes from limiting desires and banishing fear of the gods.", "After a week offline in the Daintree, he felt something close to ataraxia."], syn: ["tranquillity", "equanimity", "serenity"], ant: ["agitation", "turmoil"], origin: "From Greek ataraxia 'impassiveness', from a- 'not' + tarassein 'to disturb'.", blank: "The Epicureans sought ___, an untroubled calm of mind, rather than wild pleasure." },
  { w: "cynosure", audience: "inner", pos: "noun", ipa: "/ˈsɪnəzjʊə/", say: "SIN-uh-zyoor", lvl: 3, cat: "people", def: "A person or thing that is the centre of attention or admiration.", ex: ["The young Matilda was the cynosure of every scout at the national championships.", "Her gold gown made her the cynosure of the Logies red carpet."], syn: ["focal point", "centre of attention", "lodestar"], ant: [], origin: "Via Latin from Greek kunosoura 'dog's tail', the name for the constellation Ursa Minor, which contains the Pole Star used for guidance.", blank: "The moment the champion walked in, she became the ___ of the room, every eye turning to her." },
  { w: "farrago", audience: "inner", pos: "noun", ipa: "/fəˈrɑːɡəʊ/", say: "fuh-RAH-goh", lvl: 3, cat: "everyday", def: "A confused, jumbled mixture of things, often used scornfully of ideas or claims.", ex: ["The defence's story was a farrago of half-truths and invented alibis.", "The website was a farrago of conspiracy theories and miracle cures."], syn: ["hotchpotch", "jumble", "mishmash"], ant: [], origin: "From Latin farrago 'mixed fodder for cattle', from far 'spelt, grain'.", blank: "The so-called evidence was a ___ of rumours, misquotes and outright fabrications." },
  { w: "inchoate", audience: "inner", pos: "adjective", ipa: "/ɪnˈkəʊeɪt/", say: "in-KOH-ate", lvl: 3, cat: "academic", def: "Only just begun and so not yet fully formed or developed; rudimentary.", ex: ["The policy was still inchoate, a few bullet points on a whiteboard.", "Her inchoate fears took shape only when the letter arrived."], syn: ["embryonic", "nascent", "unformed"], ant: ["developed", "mature"], origin: "From Latin inchoatus, past participle of incohare 'to begin'.", blank: "At this stage the plan is ___, more a vague ambition than a strategy." },
  { w: "otiose", audience: "inner", pos: "adjective", ipa: "/ˈəʊtiəʊs/", say: "OH-tee-ohs", lvl: 3, cat: "academic", def: "Serving no practical purpose or result; superfluous.", ex: ["Once the new law passed, the old clause became otiose.", "The editor struck out every otiose adjective."], syn: ["superfluous", "redundant", "pointless"], ant: ["essential", "useful"], origin: "From Latin otiosus 'at leisure, unemployed', from otium 'leisure'.", blank: "With automatic backups in place, the nightly manual copy is now ___ and can be dropped." },
  { w: "tendentious", audience: "inner", pos: "adjective", ipa: "/tenˈdenʃəs/", say: "ten-DEN-shus", lvl: 3, cat: "academic", def: "Written or said to promote a particular point of view, especially a controversial one, rather than to present the facts fairly.", ex: ["The documentary's tendentious editing left out every inconvenient interview.", "Reviewers dismissed the history as tendentious, more pamphlet than scholarship."], syn: ["partisan", "biased", "slanted"], ant: ["impartial", "even-handed"], origin: "Early 20th century, from 'tendency' modelled on German tendenziös; ultimately from Latin tendere 'to stretch, aim'.", blank: "The so-called independent review was ___, written to justify a decision already made." },
  { w: "syzygy", audience: "inner", pos: "noun", ipa: "/ˈsɪzɪdʒi/", say: "SIZ-ih-jee", lvl: 3, cat: "science", def: "The near-straight-line alignment of three celestial bodies, such as the Sun, Earth and Moon at new or full moon.", ex: ["Spring tides occur at syzygy, when the pull of the Sun and Moon combine.", "A total solar eclipse is a particularly precise syzygy."], syn: ["alignment", "conjunction"], ant: [], origin: "Via late Latin from Greek suzugia 'a yoking together', from suzugos 'yoked'.", blank: "Eclipses can happen only at ___, when the Sun, Earth and Moon fall into line." },
  { w: "anagnorisis", audience: "inner", pos: "noun", ipa: "/ˌænəɡˈnɒrɪsɪs/", say: "an-ag-NOR-ih-sis", lvl: 3, cat: "academic", def: "The moment in a drama when a character makes a critical discovery or recognises the truth of their situation.", ex: ["Oedipus's anagnorisis, realising he has killed his father, is the model Aristotle admired.", "The film's anagnorisis comes when the detective sees her own handwriting on the note."], syn: ["recognition", "discovery", "revelation"], ant: [], origin: "From Greek anagnorisis 'recognition', from anagnorizein 'to recognise'; analysed in Aristotle's Poetics.", blank: "In Aristotle's terms, the play's ___ comes when the king finally recognises the beggar as his lost son." },
  { w: "sedulous", audience: "inner", pos: "adjective", ipa: "/ˈsedjʊləs/", say: "SED-yoo-lus", lvl: 3, cat: "people", def: "Showing steady, careful and persevering diligence.", ex: ["Years of sedulous practice turned a shy student into a concert pianist.", "The archivist's sedulous cataloguing saved the collection from chaos."], syn: ["assiduous", "diligent", "painstaking"], ant: ["careless", "negligent"], origin: "From Latin sedulus 'zealous, careful', perhaps from se dolo 'without guile'.", blank: "Thanks to her ___ attention to every receipt, the audit found nothing amiss." },
  { w: "rebarbative", audience: "inner", pos: "adjective", ipa: "/rɪˈbɑːbətɪv/", say: "rih-BAR-buh-tiv", lvl: 3, cat: "people", def: "Unattractive and objectionable; off-putting and repellent.", ex: ["His rebarbative manner alienated even his allies.", "The brutalist car park was condemned as rebarbative."], syn: ["repellent", "off-putting", "disagreeable"], ant: ["attractive", "appealing"], origin: "From French rebarbatif, from se rebarber 'to face each other beard to beard', from barbe 'beard'.", blank: "Critics found the building ___: a grim slab of raw concrete that seemed designed to repel visitors." },
  { w: "emolument", audience: "inner", pos: "noun", ipa: "/ɪˈmɒljʊmənt/", say: "ih-MOL-yoo-ment", lvl: 3, cat: "business", def: "A salary, fee or other payment received from employment or holding an office.", ex: ["The directors' emoluments are disclosed in the annual report.", "Judges' emoluments are set by an independent tribunal."], syn: ["remuneration", "salary", "stipend"], ant: [], origin: "From Latin emolumentum, probably originally 'payment to a miller for grinding corn', from emolere 'to grind out'.", blank: "The annual report lists each director's ___, including salary, bonus and superannuation." },
  { w: "pecuniary", audience: "inner", pos: "adjective", ipa: "/pɪˈkjuːniəri/", say: "pih-KYOO-nee-uh-ree", lvl: 3, cat: "business", def: "Relating to or consisting of money.", ex: ["Members of parliament must declare any pecuniary interest in matters they vote on.", "The penalty was purely pecuniary: a fine, with no jail time."], syn: ["monetary", "financial", "fiscal"], ant: [], origin: "From Latin pecuniarius, from pecunia 'money', from pecu 'cattle', the earliest form of wealth.", blank: "Councillors with a ___ interest in the development, such as shares in the builder, had to leave the room." },
  { w: "defalcation", audience: "inner", pos: "noun", ipa: "/ˌdiːfælˈkeɪʃn/", say: "dee-fal-KAY-shun", lvl: 3, cat: "law", def: "The misappropriation of money by a person entrusted with looking after it, such as a trustee or treasurer.", ex: ["The club treasurer's defalcation came to light during the annual audit.", "Bankruptcy does not wipe out debts arising from a trustee's defalcation."], syn: ["embezzlement", "misappropriation", "peculation"], ant: [], origin: "From medieval Latin defalcare 'to lop off', from falx, falcis 'sickle'.", blank: "The trustee's ___ left the estate $2 million short when the beneficiaries finally checked the accounts." },
  { w: "amanuensis", audience: "inner", pos: "noun", ipa: "/əˌmænjuˈensɪs/", say: "uh-man-yoo-EN-sis", lvl: 3, cat: "people", def: "A literary or artistic assistant, especially one who writes from dictation or copies manuscripts.", ex: ["Blind by then, Milton dictated Paradise Lost to a series of amanuenses.", "She served as the composer's amanuensis, writing out the scores he sang to her."], syn: ["scribe", "secretary", "copyist"], ant: [], origin: "From Latin (servus) a manu 'slave at hand(writing)' + -ensis 'belonging to'.", blank: "Unable to hold a pen after the stroke, the novelist dictated her final book to an ___." },
  { w: "autodidact", audience: "inner", pos: "noun", ipa: "/ˈɔːtəʊdaɪdækt/", say: "AW-toh-dy-dakt", lvl: 3, cat: "people", def: "A self-taught person, especially one who has mastered a subject without formal instruction.", ex: ["An autodidact, he learned Mandarin from library books and podcasts.", "Ramanujan was largely an autodidact before he wrote to Hardy."], syn: ["self-taught person", "self-educated person"], ant: [], origin: "From Greek autodidaktos 'self-taught', from autos 'self' + didaskein 'to teach'.", blank: "Never having attended university, the brilliant ___ taught herself calculus from secondhand textbooks." },
  { w: "nacreous", audience: "inner", pos: "adjective", ipa: "/ˈneɪkriəs/", say: "NAY-kree-us", lvl: 3, cat: "science", def: "Having the iridescent, shimmering lustre of mother-of-pearl.", ex: ["The inside of the abalone shell was smooth and nacreous.", "Nacreous clouds glow in pastel colours high in the polar stratosphere after sunset."], syn: ["iridescent", "pearly", "opalescent"], ant: ["dull", "matt"], origin: "From nacre 'mother-of-pearl', via French from Italian naccaro, probably of Arabic origin.", blank: "Polar stratospheric clouds are also called ___ clouds for their shimmering mother-of-pearl colours." },
  { w: "contumacious", audience: "inner", pos: "adjective", ipa: "/ˌkɒntjuˈmeɪʃəs/", say: "kon-tyoo-MAY-shus", lvl: 3, cat: "law", def: "Stubbornly or wilfully disobedient to authority, especially to the orders of a court.", ex: ["The judge found the witness contumacious for refusing three times to answer.", "A contumacious refusal to pay the fine led to a warrant."], syn: ["defiant", "insubordinate", "recalcitrant"], ant: ["compliant", "obedient"], origin: "From Latin contumax, contumacis 'stubborn, insolent'.", blank: "Having ignored three court orders to produce the documents, the director was held in contempt for ___ conduct." }
);
WB.INNER_RIDDLES_HARD = [
  { q: "A game show has three doors: a car behind one, goats behind two. You pick a door. The host, who knows where the car is and always opens an unpicked goat door, opens one and offers you a switch. If you always switch, what is your chance of winning the car?", o: ["1/2", "1/3", "2/3", "3/4"], a: 2, e: "Your first pick is right 1/3 of the time, so switching loses then; the other 2/3 of the time the host's forced reveal leaves the car behind the remaining door, so switching wins 2/3." },
  { q: "Consider all two-child families that have at least one boy. Assuming each child is independently equally likely to be a boy or a girl, what fraction of those families have two boys?", o: ["1/3", "1/2", "1/4", "2/3"], a: 0, e: "The equally likely families are BB, BG, GB and GG; ruling out GG leaves three, and only one of them (BB) has two boys." },
  { q: "Ignoring leap years and assuming all 365 birthdays are equally likely, what is the smallest group in which the chance that at least two people share a birthday exceeds 50%?", o: ["183", "57", "32", "23"], a: 3, e: "With 23 people there are 253 possible pairs, and the probability that all birthdays differ drops to about 49.3%, so a shared birthday is slightly more likely than not." },
  { q: "On an island, knights always tell the truth and knaves always lie. A says: 'B is a knave.' B says: 'A and I are the same type.' What are they?", o: ["A is a knave, B is a knight", "A is a knight, B is a knave", "Both are knaves", "Both are knights"], a: 1, e: "If A were a knave, B would be a knight, but then B's true statement would make them the same type, a contradiction. So A is a knight and B a knave, whose claim of 'same type' is duly false." },
  { q: "Exactly one of three suspects is guilty, and exactly one of their statements is true. A: 'I am innocent.' B: 'A is guilty.' C: 'I am innocent.' Who is guilty?", o: ["A", "B", "C", "It cannot be determined"], a: 2, e: "If A were guilty, B and C would both be telling the truth; if B were guilty, A and C would both be truthful. Only C guilty leaves exactly one true statement (A's)." },
  { q: "Two guards stand at a fork: one road is safe. One guard always tells the truth, the other always lies, and you don't know which is which. With one question to one guard, what is a sure way to choose the safe road?", o: ["Ask 'Which road is safe?' and take it", "Ask 'Are you the truthful guard?' and decide from the answer", "Ask 'Which road would the other guard say is safe?' and take that one", "Ask 'Which road would the other guard say is safe?' and take the other one"], a: 3, e: "Whichever guard you ask, the answer passes through exactly one lie, so it always names the dangerous road; take the opposite one." },
  { q: "Among 12 identical-looking coins, one is counterfeit and is either heavier or lighter, you don't know which. What is the minimum number of uses of a balance scale that guarantees finding the fake and whether it is heavy or light?", o: ["2", "3", "4", "5"], a: 1, e: "There are 24 possibilities (12 coins times heavy or light). Two weighings give only 3 x 3 = 9 outcomes, while three give 27, and a known scheme does it in three." },
  { q: "Using a balance scale where weights may go in either pan, what is the fewest whole-kilogram weights needed to weigh every whole number of kilograms from 1 to 40?", o: ["4", "6", "3", "5"], a: 0, e: "Weights of 1, 3, 9 and 27 kg work, since each can sit on the load side, the other side, or off the scale. Three weights can give at most (27 minus 1) / 2 = 13 distinct positive values, too few." },
  { q: "A farmer must ferry a wolf, a goat and a cabbage across a river. The boat carries him plus one item. Left alone, the wolf eats the goat and the goat eats the cabbage. What is the minimum number of one-way crossings?", o: ["5", "9", "7", "11"], a: 2, e: "Goat over, return, wolf over, bring the goat back, cabbage over, return, goat over: 7 crossings. Fewer is impossible because the goat must be brought back once." },
  { q: "Four people must cross a bridge at night with one torch. At most two cross at once, carrying the torch, at the slower person's pace. They take 1, 2, 5 and 10 minutes. What is the shortest total time?", o: ["19 minutes", "18 minutes", "16 minutes", "17 minutes"], a: 3, e: "1 and 2 cross (2), 1 returns (1), 5 and 10 cross together (10), 2 returns (2), 1 and 2 cross (2): 17. Having the 1-minute person escort everyone takes 19." },
  { q: "What is the angle between the hour and minute hands of an analogue clock at exactly 3:15?", o: ["0 degrees", "7.5 degrees", "15 degrees", "22.5 degrees"], a: 1, e: "The minute hand points at the 3 (90 degrees), but the hour hand has moved a quarter of the way from 3 to 4, an extra 7.5 degrees, to 97.5 degrees." },
  { q: "A clock takes 5 seconds to strike six o'clock, timed from the first chime to the last. At the same rate, how long does it take to strike twelve?", o: ["10 seconds", "12 seconds", "11 seconds", "13 seconds"], a: 2, e: "Six chimes have five gaps, so each gap is 1 second. Twelve chimes have eleven gaps, taking 11 seconds." },
  { q: "In a non-leap year, 1 January falls on a Monday. On what day does 31 December fall?", o: ["Monday", "Tuesday", "Sunday", "Wednesday"], a: 0, e: "365 days is 52 weeks plus 1 day, so day 365 is the same weekday as day 1. The next 1 January is then a Tuesday." },
  { q: "What is the greatest number of Friday the 13ths that can occur in a single calendar year?", o: ["2", "4", "3", "5"], a: 2, e: "Every year has at least one and at most three. For example, a common year starting on a Thursday has them in February, March and November." },
  { q: "What number comes next: 2, 3, 5, 9, 17, 33, ?", o: ["49", "64", "66", "65"], a: 3, e: "Each term is double the previous one minus 1 (equivalently, the gaps double: 1, 2, 4, 8, 16, 32), so 33 x 2 minus 1 = 65." },
  { q: "What number comes next: 61, 52, 63, 94, 46, ?", o: ["18", "57", "81", "37"], a: 0, e: "These are the squares 16, 25, 36, 49 and 64 written backwards. The next square, 81, reversed is 18." },
  { q: "Why are the digits arranged in this order: 8, 5, 4, 9, 1, 7, 6, 3, 2, 0?", o: ["They follow the order of keys on a phone keypad", "Their English names are in alphabetical order", "Each is the previous one minus 3, wrapping round", "They are ordered by how many strokes it takes to write them"], a: 1, e: "Eight, five, four, nine, one, seven, six, three, two, zero: the English names run in alphabetical order." },
  { q: "A bat and a ball cost $1.10 in total. The bat costs $1.00 more than the ball. How much does the ball cost?", o: ["10 cents", "1 cent", "5 cents", "55 cents"], a: 2, e: "If the ball is x, the bat is x + 1.00, so 2x + 1.00 = 1.10 and x = 0.05. A 10-cent ball would make the bat $1.10 and the total $1.20." },
  { q: "A patch of lily pads doubles in size every day. It takes 48 days to cover the whole lake. On which day did it cover half the lake?", o: ["Day 24", "Day 47", "Day 46", "Day 36"], a: 1, e: "It doubles each day, so it was half the size the day before it was full: day 47." },
  { q: "If 5 machines take 5 minutes to make 5 widgets, how long would 100 machines take to make 100 widgets?", o: ["100 minutes", "20 minutes", "1 minute", "5 minutes"], a: 3, e: "Each machine makes one widget in 5 minutes, so 100 machines working in parallel make 100 widgets in the same 5 minutes." },
  { q: "Three guests pay $30 for a room. The manager realises it costs $25 and sends the porter with $5. The porter keeps $2 and gives each guest $1 back. Each has now paid $9: 3 x $9 = $27, plus the porter's $2 makes $29. Where is the missing dollar?", o: ["The manager kept it", "It was lost in rounding", "There is none: the $2 is part of the $27, so adding it is wrong", "The porter actually kept $3"], a: 2, e: "The guests' $27 equals the $25 room plus the porter's $2. The $2 should be subtracted from $27, not added; $27 + $3 refunded = $30 is the correct tally." },
  { q: "Which common English word contains three consecutive pairs of double letters?", o: ["Committee", "Mississippi", "Balloon", "Bookkeeper"], a: 3, e: "Book-keeper: oo, kk, ee appear back to back. Committee and Mississippi have double letters, but never three pairs in a row." },
  { q: "Which nine-letter word can lose one letter at a time, staying a real English word at every step, all the way down to a single letter?", o: ["Something", "Startling", "Stretched", "Stringent"], a: 1, e: "Startling, starting, staring, string, sting, sing, sin, in, I." },
  { q: "Consider all rolls of two fair dice that show at least one six. What fraction of those rolls show two sixes?", o: ["1/6", "1/12", "1/11", "1/36"], a: 2, e: "Of the 36 equally likely outcomes, 11 contain at least one six (6 + 6 minus the double-counted 6 and 6), and only one of them is a double six." },
  { q: "Three boxes hold two gold coins, two silver coins, and one of each. You pick a box at random and draw a coin at random from it: it is gold. What is the probability the other coin in that box is gold?", o: ["1/2", "1/3", "3/4", "2/3"], a: 3, e: "There are three equally likely gold coins you could have drawn, and two of them sit in the gold-gold box, so the chance is 2/3, not 1/2." },
  { q: "Three logicians walk into a bar. The bartender asks: 'Does everyone want a drink?' The first says 'I don't know.' The second says 'I don't know.' The third says 'Yes!' What can you conclude?", o: ["All three want a drink", "Only the third wants a drink", "None of them knows what the others want", "The first two do not want a drink"], a: 0, e: "If the first didn't want one, he would answer 'No'; 'I don't know' shows he does. The same goes for the second, so the third, who also wants one, can answer 'Yes'." },
  { q: "A dark drawer holds 10 black socks and 10 white socks. What is the fewest you must take out, without looking, to be certain of getting a pair of black socks?", o: ["3", "11", "12", "20"], a: 2, e: "In the worst case you draw all 10 white socks first, then need 2 black ones: 12 in total. Three guarantees a matching pair, but not a black one." },
  { q: "'The day before yesterday I was 25. Next year I will turn 28.' This is true if today is which date?", o: ["31 December", "1 January", "29 February", "30 December"], a: 1, e: "With a 31 December birthday and today 1 January: on 30 December the speaker was 25, turned 26 on 31 December, turns 27 this year and 28 next year." },
  { q: "You drive 60 km at 30 km/h. How fast must you drive the 60 km back to average 60 km/h for the whole round trip?", o: ["90 km/h", "120 km/h", "180 km/h", "It is impossible"], a: 3, e: "Averaging 60 km/h over 120 km takes exactly 2 hours, but the first leg alone has already used 2 hours, so no finite speed works." }
];

/* Expert riddles: keep the genuine logic puzzles from the original set, drop the
   well-known children's riddles, and add the harder set above. */
(function () {
  const keep = ["His son", "312211", "Light rope A at both ends", "22", "2", "A is a knave, B is a knight", "A and 7",
    "Turn one on for minutes", "Facetious", "Queue", "N", "T"];
  const isKept = r => keep.some(k => { const ans = String(r.o[r.a]); return k.length > 3 ? ans.startsWith(k) : ans === k; });
  WB.INNER.riddles = WB.INNER.riddles.filter(isKept).concat(WB.INNER_RIDDLES_HARD || []);
})();
