/* WISEBYTE LESSONS · Money and Economics (batch y) */
WB.L("history-of-money", "money", "beginner", "Shells, silver and plastic: a history of money", "Money is one of humanity's strangest inventions: a shared story that strangers agree to believe. Here's how it went from clay tablets to tap and go.",
  [
    ["The barter myth", "Economists long imagined money grew out of barter, but anthropologists have found little evidence of whole barter economies.",
      "Picture the classic textbook scene: a baker wants shoes, but the shoemaker wants fish, so nobody can trade until someone invents money. It's a tidy story, told since Adam Smith's day. The trouble is that anthropologists have struggled to find any society that actually ran on everyday barter. In small communities, people tended to share, give gifts and keep informal track of who owed whom. Barter mostly showed up between strangers, or where money had collapsed, such as prisoner of war camps where cigarettes became currency. The anthropologist David Graeber made this argument famous in his 2011 book Debt: The First 5,000 Years. His point was that credit and obligation, people owing each other, probably came before coins, not after them. Money began as a way of keeping score."],
    ["Debts written in clay", "In ancient Mesopotamia, money first worked as a unit of account recorded by temples and palaces.",
      "More than 4,000 years ago in Mesopotamia, in what is now Iraq, scribes pressed marks into wet clay to record who owed what. Temples and palaces collected grain, managed workers and lent out goods, and they needed a common yardstick to compare very different things. They settled on weights of silver, measured in shekels, alongside measures of barley. A farmer might owe a debt valued in silver but pay it in grain at harvest time. The silver itself often stayed locked in the temple. This is a key idea: one of money's oldest jobs is as a unit of account, a shared measuring stick for value. Paying with a physical object came later. The first 'money' many people dealt with was a line in someone else's ledger."],
    ["Shells, stones and the first coins", "Many objects have served as money, and the first true coins appeared in Lydia, in modern Turkey, around the 600s BC.",
      "Across history, people have used remarkable things as money. Cowrie shells circulated for centuries across parts of Africa and Asia because they were durable, hard to fake and easy to count. On the Pacific island of Yap, people used huge carved stone discs called rai, some too heavy to move, so ownership simply changed by community agreement while the stone stayed put. The first stamped coins appeared in Lydia, in what is now western Turkey, around the 600s BC. They were made of electrum, a natural mix of gold and silver, and stamped by the state to vouch for their weight. The idea spread quickly through the Greek world and beyond. A ruler's stamp turned a lump of metal into something people could trust without weighing it."],
    ["Paper promises", "China pioneered paper money around a thousand years ago, and it worked because people trusted the issuer.",
      "Carrying heavy iron or copper coins was a nuisance, so merchants in Sichuan, China, began depositing coins and receiving paper receipts instead. During the Song dynasty, around the early 1000s, the government took over and issued official paper money. When Marco Polo later described Chinese paper notes, European readers found the idea astonishing. Paper money works only if people believe it can be spent, and that belief depends on the issuer. Chinese dynasties learned the hard way that printing too many notes made them lose value. In Europe, paper money grew out of goldsmiths and banks writing receipts for deposits of gold. Over time those receipts were passed around as payment themselves. The paper wasn't valuable; the promise behind it was."],
    ["Australia's homegrown money", "Colonial Australia was so short of coins that Governor Macquarie had Spanish silver dollars cut in two in 1813.",
      "Early colonial New South Wales had a chronic shortage of coins. People paid with promissory notes, foreign coins and, notoriously, rum, which was so widely traded that it acted like a currency. In 1813 Governor Lachlan Macquarie came up with a clever fix. He imported Spanish silver dollars and had a hole punched out of the middle of each one. The ring, called the holey dollar, and the small centre piece, called the dump, became two separate coins worth more together than the original. Because the cut coins were worth more in the colony than elsewhere, they were less likely to leave. Australia later used British pounds, then its own pounds, before switching to decimal dollars and cents in February 1966."],
    ["From gold to faith", "For much of modern history money was tied to gold, but today's currencies are backed by trust in governments and central banks.",
      "By the late 1800s many leading economies were on the gold standard, meaning their paper money could, in principle, be swapped for a fixed amount of gold. This gave people confidence, but it also tied a country's hands during crises, because it could not easily create more money when the economy needed it. During the Great Depression, countries abandoned gold one after another. After the Second World War, a new system linked major currencies to the US dollar, which was itself convertible to gold for foreign governments. In 1971 President Richard Nixon ended that link. Since then, most of the world has used fiat money: currency that has value because governments declare it legal tender, accept it for taxes, and central banks try to keep its value stable."],
    ["Money becomes data", "Today most money exists as digital entries in bank computers, and Australia has been a world leader in going cashless.",
      "In 1988 Australia issued the world's first polymer banknote, a plastic ten dollar note designed to be hard to forge, and the technology was later adopted by many other countries. Yet cash itself has been shrinking. Australians have embraced tap and go cards and phone payments, and the Reserve Bank of Australia has tracked a steep fall in the share of payments made with notes and coins. Most money now is not physical at all. It's numbers in accounts, moved between banks electronically. Cryptocurrencies such as Bitcoin, launched in 2009, tried to create money without any central issuer, though their prices swing wildly. Through all these changes, the core truth from Mesopotamia remains: money works because enough people agree that it does."]
  ],
  [
    [0, "What did anthropologists find about barter economies?", ["They were common in every early society", "There is little evidence that whole societies ran on everyday barter", "They existed only in ancient Egypt", "They replaced money during the Middle Ages"], 1, "Barter mostly appeared between strangers or when money collapsed; everyday life ran on credit, sharing and obligation."],
    [1, "In ancient Mesopotamia, what was silver mainly used as?", ["Decoration for temples only", "Coins stamped by the king", "A unit of account for measuring debts and value", "Payment for foreign soldiers"], 2, "Scribes recorded debts in weights of silver, even when the debts were paid in grain."],
    [2, "Where did the first stamped coins appear?", ["Lydia, in modern Turkey", "Ancient Rome", "Song dynasty China", "Mesopotamia"], 0, "Lydian electrum coins from around the 600s BC are generally considered the first true coins."],
    [4, "What was the 'holey dollar'?", ["An Aboriginal trade token", "A gold coin from the gold rushes", "A note printed during the Depression", "A Spanish silver dollar with its centre punched out"], 3, "Governor Macquarie's 1813 fix turned one coin into two: the holey dollar and the dump."],
    [5, "What happened in 1971?", ["Australia adopted decimal currency", "The US ended the dollar's convertibility to gold", "The first polymer banknote was issued", "Bitcoin was launched"], 1, "President Nixon cut the dollar's link to gold, ushering in the era of fiat money."]
  ]);

WB.L("how-banks-create-money", "money", "intermediate", "How banks create money out of thin air", "When a bank approves a home loan, it doesn't hand over someone else's savings. It creates brand new money with a few keystrokes.",
  [
    ["The loan that made money", "When a bank makes a loan, it creates a new deposit, and that deposit is new money.",
      "Imagine a couple borrowing $600,000 to buy a house. Most people assume the bank takes that money from other customers' savings and passes it along. That's not quite how it works. When the loan is approved, the bank simply records two things on its books: a loan the couple owes the bank, and a matching deposit that is paid out to the seller's account. That deposit didn't exist a moment earlier. It is brand new money, spendable just like any other money in a bank account. The Bank of England explained this plainly in a widely read 2014 article called 'Money creation in the modern economy', and the Reserve Bank of Australia describes it the same way. Most money in the economy is created like this."],
    ["What counts as money", "Most money is not notes and coins but bank deposits, which are really IOUs from banks to their customers.",
      "Open your banking app and you'll see a balance. That number is not cash sitting in a vault with your name on it. It is a promise from your bank to pay you, an IOU you can use to make payments. When you tap your card, the bank moves that promise to someone else's account. Economists count these deposits as part of the money supply, and they dwarf the physical cash in circulation. Banknotes are issued by the central bank, in Australia's case the Reserve Bank, while coins are issued by the federal government and made by the Royal Australian Mint. But the money most of us use day to day is bank deposits. In other words, private banks create most of a modern country's money, under rules set by public authorities."],
    ["The textbook story", "The traditional 'money multiplier' model suggests banks only lend out deposits they already have, but central banks say it's misleading.",
      "Many economics textbooks tell a different story. Savers deposit money, the bank keeps a fraction in reserve and lends out the rest, which gets deposited elsewhere and lent again, multiplying the original amount. This is called the money multiplier. It isn't completely wrong, because lending does ripple through the system. But central banks have said it gets the cause and effect backwards. Banks don't usually wait for deposits before lending. They make loans when they find creditworthy borrowers, and the deposits are created in the process. Afterwards, banks manage the consequences, such as making sure they have enough reserves to settle payments with other banks. The shift in thinking matters, because it shows that the amount of money depends heavily on how much people and businesses want to borrow."],
    ["Money can be destroyed too", "When a loan is repaid, the money it created disappears from the economy.",
      "If lending creates money, repaying a loan does the opposite. When the couple from our example makes a mortgage repayment, money leaves their deposit account and the loan balance shrinks. Both entries fall, and that money effectively vanishes. Across the whole economy, money is constantly being created by new loans and destroyed by repayments. The total money supply grows when new lending outpaces repayments, and it can shrink when people and businesses rush to pay down debt. This happened in some economies after the 2008 global financial crisis, when households cut back on borrowing. It also helps explain why credit booms can feel so powerful while they last: a surge in lending pumps new money into spending on houses, cars and businesses, which can push prices up."],
    ["So why can't banks lend forever?", "Banks are limited by borrower demand, profitability, regulation and the central bank's interest rate.",
      "If banks can create money by typing, what stops them going wild? Several things. First, a bank needs willing borrowers who are likely to pay it back, because bad loans cost money. Second, regulators insist banks hold enough capital, their own funds to absorb losses, and enough liquid assets to survive if depositors withdraw. In Australia, the Australian Prudential Regulation Authority, APRA, sets and enforces these rules. Third, banks compete for deposits and funding, which costs them interest. And fourth, the Reserve Bank's cash rate influences what banks pay to borrow and what they charge customers. When the RBA raises rates, loans become more expensive, fewer people borrow, and less new money is created. It's a powerful lever, but not a precise one."],
    ["When trust breaks", "Because banks lend out far more than they keep in cash, a sudden rush of withdrawals can threaten even a healthy bank.",
      "Banks only hold a small portion of their assets as ready cash and central bank reserves. That's normally fine, because depositors don't all want their money on the same day. But if people start to fear a bank is in trouble, they may rush to withdraw, and the fear can become self fulfilling. This is a bank run. In 2007 customers queued outside branches of the British bank Northern Rock, and in 2023 depositors pulled billions from Silicon Valley Bank in the United States in a matter of hours, largely through phone apps. To prevent panics, many countries guarantee deposits. Australia's Financial Claims Scheme protects deposits up to a set limit per person per bank; check the current figure at the official fcs.gov.au site."],
    ["Why it matters to you", "Understanding money creation helps make sense of house prices, interest rates and debates about the economy.",
      "Once you see that most money is created through lending, a lot of economic news clicks into place. When banks lend freely for housing, new money flows into property, which can help push prices up. When interest rates rise, borrowing slows, money creation slows, and spending cools. It also explains why regulators watch lending standards so closely, and why a banking crisis can choke the whole economy: if banks stop lending, the money supply can stall just when businesses need it. None of this means banks are printing free money for themselves, since every loan carries risk and has to be repaid. This is general information rather than financial advice, and moneysmart.gov.au has plain guides to how loans and interest work."]
  ],
  [
    [0, "What happens when a bank approves a new loan?", ["It transfers money from other customers' savings", "It borrows the money from the government", "It creates a new deposit, which is new money", "It prints new banknotes"], 2, "The loan and a matching deposit appear on the bank's books, creating new money."],
    [1, "What makes up most of the money people use day to day?", ["Bank deposits", "Coins", "Banknotes", "Gold reserves"], 0, "Deposits, which are banks' IOUs to customers, far outweigh physical cash."],
    [3, "What happens to money when a loan is repaid?", ["It goes to the Reserve Bank", "It effectively disappears from the economy", "It is automatically lent out again", "It becomes cash in the bank's vault"], 1, "Repayment shrinks both the deposit and the loan, destroying that money."],
    [4, "Which Australian body sets capital and liquidity rules for banks?", ["The ATO", "ASIC", "The Royal Australian Mint", "APRA"], 3, "The Australian Prudential Regulation Authority supervises banks' financial safety."],
    [5, "Why can a bank run threaten even a healthy bank?", ["Banks keep only a small share of assets as ready cash", "Banks are not allowed to hold cash", "Deposits are illegal to withdraw quickly", "Banks store all deposits overseas"], 0, "If many depositors withdraw at once, a bank may not have enough liquid funds on hand."]
  ]);

WB.L("hyperinflation", "money", "intermediate", "Hyperinflation: when money stops working", "Imagine your wages losing half their value before you can spend them. In Weimar Germany and Zimbabwe, that nightmare became daily life.",
  [
    ["Wheelbarrows of cash", "In 1923 German prices rose so fast that people were paid daily and rushed to spend their wages.",
      "In the autumn of 1923, a German worker might be paid twice a day and hurry out at lunchtime to buy food before prices rose again. Photographs from the time show children building towers out of bundles of banknotes and people burning money because it was cheaper than firewood. By November 1923, one US dollar was worth about 4.2 trillion German marks. Savings built up over a lifetime were wiped out. A pension that once supported a comfortable retirement could barely buy a loaf of bread. This was hyperinflation, the most extreme form of inflation. Normal inflation slowly nibbles away at money's value. Hyperinflation devours it, until people stop trusting money altogether and the basic machinery of buying and selling breaks down."],
    ["What counts as hyperinflation", "Economists often define hyperinflation as prices rising by 50 per cent or more in a single month.",
      "Inflation is a general rise in prices over time. Central banks such as the Reserve Bank of Australia aim to keep it low and steady, at around 2 to 3 per cent a year. Hyperinflation is a different beast. A common definition, from the economist Phillip Cagan in the 1950s, is prices rising at least 50 per cent in a month. At that pace, prices more than double every couple of months and rise well over a hundredfold in a year. In the worst cases it is far faster. Hungary after the Second World War holds the record: in July 1946 prices were doubling roughly every 15 hours. Episodes like this are rare, but they have happened on almost every continent, and they share some striking patterns."],
    ["The printing press problem", "Hyperinflation usually begins when a government pays its bills by creating huge amounts of new money.",
      "Almost every hyperinflation starts with a government in deep trouble. It owes more than it can raise through taxes or borrowing, so it turns to the central bank to create money to pay its bills. In Germany after the First World War, the government faced war debts and reparations demanded by the victors. In 1923 French and Belgian troops occupied the Ruhr, Germany's industrial heartland, after Germany fell behind on payments. Germany backed a campaign of passive resistance there, paying striking workers with newly printed money while output collapsed. When more and more money chases fewer and fewer goods, prices climb. And once prices rise, the government needs even more money to pay its bills, so it prints faster. The cycle feeds itself."],
    ["When confidence collapses", "Once people expect money to lose value, they spend it instantly, which makes prices rise even faster.",
      "Printing money alone doesn't fully explain the speed of hyperinflation. Psychology does the rest. When people expect money to be worth less tomorrow, nobody wants to hold it. Workers spend wages immediately, shops raise prices pre emptively, and businesses demand payment in foreign currency or goods. Economists call this a rise in the velocity of money: each note changes hands faster and faster. That rush to spend pushes prices up even further than the extra money alone would suggest. People find workarounds, such as bartering, using foreign currencies like the US dollar, or holding real assets such as land, gold and goods. In a sense, the public quietly abandons the official currency. Once that trust is lost, it is very hard to win back."],
    ["Zimbabwe's trillion dollar notes", "In the late 2000s Zimbabwe printed a 100 trillion dollar note before abandoning its currency.",
      "One of the best known modern examples happened in Zimbabwe. During the 2000s, the economy was hit by a collapse in farm production after controversial land seizures, falling exports and heavy government spending, which was increasingly funded by creating money. Inflation spiralled through the decade. By 2008 it had reached levels so extreme that official statistics stopped being reliable, with estimates running into the billions of per cent a year. The central bank issued ever larger notes, culminating in a 100 trillion Zimbabwean dollar note, which soon became a collector's novelty. In 2009 the country effectively gave up on its own currency, and people began using foreign money such as the US dollar and the South African rand. Prices stabilised almost immediately once that happened."],
    ["How hyperinflations end", "Hyperinflation usually ends with a new currency, a credible budget plan and restored trust.",
      "Strangely, hyperinflations can end very quickly. Germany's ended in late 1923 with a new currency, the Rentenmark, introduced alongside strict limits on how much could be issued and efforts to balance the government's budget. Within weeks, prices steadied. The pattern repeats elsewhere: a new or foreign currency, a government that stops funding itself with the printing press, and often outside help. The crucial ingredient is credibility. People need to believe the new money will hold its value, so the rules must be strict and seen to be enforced. That's one reason many countries now give their central banks independence from day to day politics, so leaders can't simply create money to pay for promises when times get tough."],
    ["Long shadows", "Hyperinflation leaves deep economic and political scars, which is why central banks fear runaway prices.",
      "The damage from hyperinflation goes well beyond prices. It tends to hit savers, pensioners and people on fixed incomes hardest, while those with debts, land or foreign currency may come out ahead. That shift can feel deeply unfair and can erode trust in institutions. Historians still debate how much Germany's 1923 crisis contributed to the political turmoil that followed, though many argue the Great Depression a few years later did more direct damage. Either way, the memory of 1923 shaped Germany's later caution about inflation, which in turn influenced the design of the European Central Bank. For ordinary people, the lesson is that stable money is a public good. It's easy to take for granted until it disappears."]
  ],
  [
    [1, "A common definition of hyperinflation is prices rising by at least:", ["10 per cent a year", "50 per cent a month", "100 per cent a year", "5 per cent a week"], 1, "Economist Phillip Cagan's widely used threshold is 50 per cent or more in a single month."],
    [2, "How do most hyperinflations begin?", ["A government creates large amounts of money to pay its bills", "Banks stop lending", "Interest rates are raised too fast", "A country exports too much"], 0, "When a government funds itself with newly created money, prices start to spiral."],
    [3, "What is the 'velocity of money'?", ["How quickly banks transfer funds overseas", "The speed of printing new notes", "How fast money changes hands in the economy", "The rate at which coins wear out"], 2, "During hyperinflation people spend money as fast as possible, so velocity soars."],
    [4, "How did Zimbabwe's hyperinflation largely end?", ["By printing larger notes", "By banning all imports", "By raising taxes on farms", "By people switching to foreign currencies like the US dollar"], 3, "After 2009 Zimbabweans used foreign money, and prices stabilised quickly."],
    [5, "What was the Rentenmark?", ["Germany's new currency introduced to end the 1923 hyperinflation", "A French reparations bond", "A Hungarian banknote", "A type of gold coin"], 0, "The Rentenmark, issued under strict limits, helped steady prices within weeks."]
  ]);

WB.L("financial-bubbles", "money", "beginner", "Bubbles and manias: when prices lose their minds", "Tulip bulbs, shipping shares and internet start ups have all sold for wildly more than they were worth. Why do sensible people keep getting swept up?",
  [
    ["What makes a bubble", "A bubble is when prices soar far above any sensible value, driven mostly by the expectation of selling to someone else for more.",
      "Picture a street where house prices have doubled in two years. Neighbours brag about their gains at barbecues. People who've never invested start buying, not because they want to live there, but because they're sure prices will keep rising. That's the feeling of a bubble. Economists define it roughly as a period when the price of an asset climbs far above what its future income or usefulness could justify, kept aloft mainly by people expecting to sell to someone else at a higher price. This is sometimes called the 'greater fool' theory: you don't need something to be worth the price, as long as someone more optimistic will pay more later. Bubbles are notoriously hard to spot for certain while they are happening."],
    ["Tulip mania", "In the 1630s Dutch traders paid extraordinary prices for rare tulip bulbs, though historians now think the crash was less dramatic than legend says.",
      "In the Dutch Republic in the 1630s, tulips were a luxury import, and rare varieties with flamed, streaked petals became status symbols. Prices for the most prized bulbs rose to astonishing levels, with some single bulbs reportedly selling for more than a skilled worker earned in years. Traders began buying and selling contracts for bulbs still in the ground. In February 1637 the market suddenly collapsed as buyers vanished. For centuries tulip mania has been told as the ultimate tale of collective madness, partly thanks to the 1841 book Extraordinary Popular Delusions and the Madness of Crowds by Charles Mackay. Modern historians, including Anne Goldgar, argue the craze involved fewer people and caused less economic damage than the legend suggests. Still, the story endures for good reason."],
    ["The South Sea Bubble", "In 1720 shares in Britain's South Sea Company soared and crashed, ruining many investors, reportedly including Isaac Newton.",
      "The South Sea Company was set up in Britain in 1711, supposedly to trade with Spanish South America, though its real business became managing government debt. In 1720 the company offered to take over much of Britain's national debt in exchange for its shares, and a frenzy followed. The share price rose roughly tenfold in a few months. Other schemes popped up to ride the wave, some with vague or absurd business plans. Then confidence cracked and the price collapsed later that year. Thousands lost fortunes. Isaac Newton is reported to have lost a large sum after buying back in near the top. At the same time in France, a similar scheme linked to John Law's Mississippi Company also boomed and spectacularly burst."],
    ["Dot com and housing", "Modern bubbles include the late 1990s internet boom and the US housing bubble that led to the 2008 financial crisis.",
      "Bubbles didn't stop with powdered wigs. In the late 1990s, investors poured money into almost any company with '.com' in its name, many of which had little revenue and no profits. The technology heavy Nasdaq index in the US soared, then fell by roughly three quarters between 2000 and 2002. Some companies, like Amazon, survived and thrived; many others vanished. A few years later came the US housing bubble. Easy lending, including loans to people unlikely to repay, pushed house prices up across much of America. When prices began to fall from around 2006, defaults rose and losses spread through banks worldwide, contributing to the global financial crisis of 2008. Australia was cushioned more than many countries, but felt the shock too."],
    ["The anatomy of a mania", "Bubbles often follow a pattern: an exciting new story, rising prices, euphoria, then panic.",
      "The economists Hyman Minsky and Charles Kindleberger described a pattern that many bubbles follow. It begins with a displacement, something genuinely new and exciting, such as railways, the internet or a new kind of financial product. Early investors make real money. Credit expands, more people pile in, and rising prices seem to prove the optimists right. Then comes euphoria, when caution is mocked and people say 'this time is different'. Eventually some insiders quietly sell. Prices wobble, borrowers who bought with debt are forced to sell, and selling feeds more selling until panic sets in. Not every boom follows the script exactly, but the shape is remarkably familiar across centuries, from canal shares in the 1790s to more recent crypto crazes."],
    ["Why smart people join in", "Social proof, fear of missing out and the ability to borrow all make bubbles hard to resist.",
      "It's tempting to think only foolish people get caught in bubbles, but history is full of intelligent, experienced investors who joined in. Several forces are at work. Watching friends and neighbours get rich is powerful social proof, and nobody wants to be the cautious one left behind. Rising prices create their own story, because each gain seems to confirm the last. Professional investors may feel pressure to follow the crowd, since being wrong alongside everyone else is less risky for their careers than being wrong alone. Easy credit lets people buy more than they could otherwise afford, magnifying both gains and losses. And there's often a genuine innovation underneath, which makes the hype feel reasonable. Railways and the internet really did change the world."],
    ["Living with bubbles", "No one can reliably time a bubble, which is why spreading risk and avoiding heavy borrowing for speculation matters.",
      "If bubbles are so common, why not just sell at the top? Because almost nobody can reliably tell where the top is. Prices can stay wildly high for years, and people who call a bubble too early can lose as much as those who call it too late. That's one reason many experts suggest that ordinary investors focus less on predicting manias and more on not being wiped out by them: avoid putting everything into one hot asset, be wary of borrowing heavily to speculate, and be sceptical when everyone says prices can only go up. This lesson is general information, not financial advice. For independent guidance on investing and risk, moneysmart.gov.au, run by ASIC, is a good starting point."]
  ],
  [
    [0, "What is the 'greater fool' theory?", ["Only foolish investors buy shares", "Buying something because you expect someone else to pay more later", "Governments always cause bubbles", "Prices always return to their true value"], 1, "In a bubble, people buy mainly because they expect to sell to someone more optimistic."],
    [1, "What do modern historians like Anne Goldgar say about tulip mania?", ["It never happened at all", "It caused the collapse of the Dutch Republic", "It was smaller and less damaging than the legend suggests", "It involved gold, not tulips"], 2, "Recent research suggests the craze involved fewer people and less damage than often told."],
    [2, "What was the South Sea Company's real main business in 1720?", ["Managing British government debt", "Trading spices with India", "Building ships for the navy", "Mining silver in Mexico"], 0, "Its big scheme involved swapping government debt for company shares."],
    [3, "Roughly how much did the Nasdaq fall between 2000 and 2002?", ["About 10 per cent", "About a quarter", "About half", "About three quarters"], 3, "The tech heavy index lost roughly three quarters of its value after the dot com peak."],
    [5, "Why might professional investors follow the crowd in a bubble?", ["They are required to by law", "Being wrong with everyone else is less risky for their careers", "Bubbles never affect professionals", "They can always predict the top"], 1, "Career pressures can make following the crowd feel safer than standing apart."]
  ]);

WB.L("opportunity-cost", "money", "beginner", "Opportunity cost: the hidden price of every choice", "Everything you choose to do means something else you didn't. Economists call that missing alternative the opportunity cost, and it changes how you see every decision.",
  [
    ["The cost you can't see", "The true cost of anything is the best alternative you give up to get it.",
      "Say you've got a free Saturday and $100. You could spend both at a music festival. The ticket price is obvious, but what else did that day cost you? Perhaps a beach trip with friends, a shift that would have paid $200, or simply a lazy day of rest. Economists call the value of the best option you gave up the opportunity cost. It's one of the most useful ideas in economics, because it reminds us that every choice involves a trade off, even when no money changes hands. The festival might still be the right call. The point is not to feel guilty about choices, but to see clearly what you're really choosing between, rather than only noticing the price tag in front of you."],
    ["No free lunch", "Even things that seem free use up time, attention or resources that could have gone elsewhere.",
      "There's an old saying, popularised by the economist Milton Friedman, that 'there's no such thing as a free lunch'. It dates back to American saloons that offered free food to customers who bought drinks. The lunch wasn't really free; its cost was built into the price of beer. The same logic applies widely. A free app may be paid for with your data and attention. A free public park was paid for with taxes, and the land could have been used for housing or shops. Your own time is never free, because an hour spent scrolling is an hour not spent sleeping, exercising or talking to someone you love. Recognising hidden costs doesn't mean refusing free things. It means knowing what you're actually trading."],
    ["Time is the scarcest resource", "Because time can't be stored or replaced, it often carries the biggest opportunity costs in our lives.",
      "Money can be earned again, but time only runs one way. That makes it one of the most important places to think about opportunity cost. Should you spend two hours driving across town to save $20 on a purchase? It depends on what else those two hours could give you. Studying for a qualification means giving up income or leisure now in the hope of higher earnings or more satisfying work later. Economists apply this to education constantly: a big cost of university for many students is not the fees but the wages they could have earned instead. None of these choices has a universal right answer. Opportunity cost simply turns a vague feeling into a clearer question: is this the best use of my time?"],
    ["The seen and the unseen", "The French writer Frederic Bastiat warned that good economics looks beyond obvious effects to the hidden ones.",
      "In 1850 the French writer Frederic Bastiat published an essay with a memorable title, That Which Is Seen and That Which Is Not Seen. In it he told the parable of a broken window. A boy smashes a shop window, and onlookers console the shopkeeper by pointing out that at least the glazier gets work, which helps the economy. Bastiat's reply: what about the unseen? The shopkeeper would have spent that money on something else, perhaps new shoes, so the shoemaker loses the work the glazier gains. And the town is now a window poorer. This 'broken window fallacy' warns against counting only visible benefits. Whenever someone says a disaster or a project will create jobs, it's worth asking what the money would otherwise have done."],
    ["Sunk costs: let them sink", "Money or time you've already spent and can't recover shouldn't drive your next decision, though our brains find this hard.",
      "Imagine you've paid $150 for a concert ticket, but on the night you're sick and exhausted, and it's pouring with rain. Many people drag themselves along anyway, because they've 'already paid'. Economists call that $150 a sunk cost: it's gone whether you go or not. The only real question is whether the night out is better than staying home now. Thinking about opportunity cost helps here, because it points forward to what you'll gain or lose next, rather than backward to what's already spent. Businesses and governments fall into the same trap, pouring more money into failing projects because so much has already been invested. Letting sunk costs go isn't wasteful. Throwing good resources after bad, simply to avoid admitting a loss, often is."],
    ["Trade offs at national scale", "Governments face opportunity costs too: every dollar spent on one priority is a dollar not spent on another.",
      "Economics textbooks often illustrate opportunity cost with an old example: a country choosing between 'guns and butter', military spending and civilian goods. With limited workers, money and materials, making more of one means making less of the other. Real budgets work the same way. When governments decide to fund a new hospital, a road, a tax cut or a defence program, they're also choosing not to spend that money elsewhere, or to borrow more and pay interest later. Debates about public spending are often really debates about opportunity cost, even when nobody uses the term. Asking 'compared with what?' is one of the most useful questions in politics. A project may sound good on its own, but the real test is whether it beats the alternatives."],
    ["Using the idea well", "Opportunity cost is a thinking tool for clearer choices, not a reason to agonise over every decision.",
      "Taken too far, opportunity cost could make life miserable. You could worry that every coffee should have been invested or every evening spent more productively. That's not the point. The idea works best for decisions that really matter: a job offer, a big purchase, how to spend a windfall, or whether to keep pouring effort into something that isn't working. Try a simple habit. Before a significant choice, name the realistic next best alternative out loud. 'If I buy this car, I'm not doing that trip.' 'If I take this job, I'm giving up that flexibility.' Often the decision stays the same, but you'll make it with open eyes. And sometimes, rest or fun is exactly the best use of your time."]
  ],
  [
    [0, "What is opportunity cost?", ["The price printed on a product", "The value of the best alternative you give up", "Any cost paid in cash", "The tax added to a purchase"], 1, "Opportunity cost is what you forgo by choosing one option over the next best."],
    [1, "Where does the phrase 'no such thing as a free lunch' come from?", ["Saloons that gave free food to drinking customers", "A school canteen policy", "A Roman banquet", "A government budget speech"], 0, "The 'free' lunch was paid for through the price of drinks."],
    [3, "What does Bastiat's broken window parable warn against?", ["Breaking windows on purpose", "Hiring glaziers", "Counting only visible benefits and ignoring hidden costs", "Spending money on shoes"], 2, "The money spent fixing the window would otherwise have gone elsewhere, unseen."],
    [4, "What is a sunk cost?", ["A cost that rises over time", "A cost paid by the government", "A future expense you can avoid", "Money or time already spent that can't be recovered"], 3, "Sunk costs are gone either way, so they shouldn't drive the next decision."],
    [5, "What does the 'guns and butter' example illustrate?", ["A country trading weapons for food", "Nations face trade offs between priorities with limited resources", "Military spending always boosts dairy farming", "Butter was once used as money"], 1, "More of one thing means less of another when resources are limited."]
  ]);

WB.L("externalities", "money", "intermediate", "Externalities: the costs nobody pays for", "When a factory pollutes a river, someone pays the price, just not the factory or its customers. That gap is one of the biggest ideas in economics.",
  [
    ["The neighbour's leaf blower", "An externality is a cost or benefit that spills onto people who didn't choose it.",
      "It's 7am on Sunday, and your neighbour fires up a petrol leaf blower. They get a tidy driveway. You get a ruined sleep in. Your lost rest doesn't appear on their bill, so it doesn't factor into their decision. Economists call this an externality: a side effect of an activity that falls on people outside the transaction. Externalities can be negative, like noise, pollution or traffic congestion, or positive, like a neighbour's beautiful garden that brightens the whole street. The concept matters because markets normally work by matching prices to costs and benefits. When some costs or benefits sit outside the price, markets can produce too much of the harmful stuff and too little of the helpful stuff. That's often called a market failure."],
    ["Pigou's big idea", "Economist Arthur Pigou suggested taxing activities that harm others so that prices reflect their full cost.",
      "The English economist Arthur Pigou developed the idea of externalities in his 1920 book The Economics of Welfare. He noticed that the private cost of an activity, what the business or person pays, could differ from its social cost, which includes harm to everyone else. Think of a factory belching smoke: the owner pays for fuel and wages, but not for the coughing of people downwind. Pigou's solution was elegant. Put a tax on the harmful activity equal to the damage it causes, so the price reflects the true cost. Producers and customers would then cut back on their own, without the government having to micromanage. Such charges are still called Pigouvian taxes, and they appeal to economists across much of the political spectrum."],
    ["Coase's twist", "Ronald Coase argued that, in some cases, people can bargain their way to good outcomes if property rights are clear.",
      "In 1960 the British economist Ronald Coase published 'The Problem of Social Cost', which challenged the idea that taxes are always the answer. He pointed out that an externality involves two parties: the factory needs to make smoke, but the neighbours need clean air. If it's clear who has the right to what, and bargaining is cheap, they might negotiate a deal. Perhaps the neighbours pay the factory to install filters, or the factory compensates the neighbours. Coase's insight is that when bargaining is easy, the efficient outcome can emerge either way. The catch, which Coase himself stressed, is that in the real world bargaining is often costly. You can't easily negotiate with millions of people affected by air pollution. That's where governments usually step in."],
    ["Positive spillovers", "Some activities benefit others for free, such as vaccination, education and pollinating bees.",
      "Externalities aren't all bad news. When you get vaccinated, you lower your own risk but also make it harder for a disease to spread to others, including people who can't be vaccinated. When someone gets an education, the benefits often ripple out to employers, colleagues and the wider community. A beekeeper's bees pollinate nearby orchards without sending the orchardist a bill. The problem with positive externalities is the mirror image of the negative ones: because people don't capture all the benefits, they may do less of the good thing than society would like. That's one reason governments subsidise or provide things such as vaccination programs, schooling and research. Healthy debate continues about exactly how much support is justified, but the economic logic is widely accepted."],
    ["The tragedy of the commons", "Shared resources open to everyone can be overused, though Elinor Ostrom showed communities often manage them well.",
      "In 1968 the ecologist Garrett Hardin popularised the 'tragedy of the commons'. He imagined a pasture open to all herders. Each herder gains from adding another cow, while the cost of overgrazing is shared by everyone, so the pasture ends up ruined. Overfishing is a classic real world example: each boat has an incentive to catch more before others do. Hardin thought the only solutions were government control or private ownership. The political economist Elinor Ostrom disagreed. She studied fisheries, forests and irrigation systems around the world and found that many communities successfully manage shared resources with their own local rules, monitoring and penalties. In 2009 she became the first woman to win the Nobel Memorial Prize in Economic Sciences, shared with Oliver Williamson."],
    ["Putting a price on harm", "Congestion charges, carbon pricing and container deposit schemes all try to make prices reflect hidden costs.",
      "Pigou's idea now shows up in daily life. In 2003 London introduced a congestion charge for driving into the city centre at busy times, and Stockholm and Singapore have used similar schemes. Container deposit schemes, now running in every Australian state and territory, put a small refundable value on bottles and cans, nudging people to return rather than litter them. Carbon pricing tries to charge for the climate cost of greenhouse gas emissions, either through a tax or a cap and trade system where companies buy and sell permits. Australia had a carbon price from 2012 until it was repealed in 2014, and the topic remains politically contested. Whatever your view, the underlying economic question is the same: who should pay for harm, and how?"],
    ["Spotting externalities everywhere", "Once you understand externalities, you'll see them in traffic, noise, phones and public health.",
      "Externalities turn up in unexpected places. Each extra car on a busy road slows everyone else down a little, a cost the driver doesn't pay. A person coughing at work without staying home spreads illness to colleagues. A loud phone call on a train costs other passengers their peace. Even attention can be an externality, when apps designed to keep us scrolling spill costs onto relationships and sleep. Not every externality needs a law or a tax; many are handled by manners, social norms, building codes or simple neighbourly conversations. But the idea gives you a powerful question to ask about almost any problem: who gets the benefit, who bears the cost, and do those two groups line up? When they don't, trouble usually follows."]
  ],
  [
    [0, "What is a negative externality?", ["A cost that falls on people outside a transaction", "A tax charged by the government", "A product that sells poorly", "A loss a business reports to shareholders"], 0, "Externalities are side effects borne by people who didn't choose them."],
    [1, "What did Arthur Pigou propose for harmful activities?", ["Banning them all", "A tax equal to the damage they cause", "Letting markets ignore them", "Paying polluters to keep polluting"], 1, "A Pigouvian tax makes the price reflect the full social cost."],
    [2, "According to Coase, when can bargaining solve an externality?", ["Never", "Only when the government sets the price", "When property rights are clear and bargaining is cheap", "Only for positive externalities"], 2, "With clear rights and low bargaining costs, parties can negotiate efficient outcomes."],
    [4, "What did Elinor Ostrom's research show?", ["Commons always end in ruin", "Only private ownership works", "Fisheries cannot be managed", "Communities often manage shared resources well with local rules"], 3, "Ostrom found many successful examples of community management of commons."],
    [5, "How does a container deposit scheme address an externality?", ["It bans plastic bottles", "It puts a refundable value on containers to discourage litter", "It taxes drink companies' profits", "It pays people to buy more drinks"], 1, "The refund gives people a reason to return containers rather than litter them."]
  ]);

WB.L("incentives", "money", "beginner", "Incentives: why rewards so often backfire", "Offer people a reward and they'll respond, just not always the way you hoped. Here's why clever incentives can go spectacularly wrong.",
  [
    ["The great rat hunt", "In colonial Hanoi, a bounty on rat tails led people to cut off tails and let the rats go.",
      "In 1902 the French colonial authorities in Hanoi faced a rat problem in the city's new sewers, and the threat of plague made it urgent. They offered a small bounty for every rat killed, paid on presentation of a tail. Soon officials began noticing rats running around without tails. People were catching rats, cutting off the tails for the reward, and releasing them to breed. According to the historian Michael Vann, who researched the episode, there were even reports of people farming rats. The scheme did what it paid for, not what it meant. This is the heart of incentives: people respond to what is actually rewarded, not to what the designer intended. It's one of the most important and most frequently forgotten lessons in economics."],
    ["People respond to incentives", "Economists see incentives, rewards and penalties, as a key driver of human behaviour.",
      "If there's one sentence many economists would put on a T shirt, it's 'people respond to incentives'. An incentive is anything that makes an action more or less attractive: a price, a bonus, a fine, a deadline, even praise or embarrassment. Raise the price of something and people tend to buy less of it. Offer a cash prize and more people enter the contest. Many of these responses are exactly what policymakers want. Australia's container deposit schemes and incentives to install rooftop solar have both changed behaviour on a large scale. The trouble comes when incentives are designed carelessly, because people are clever, creative and quick to find the easiest path to a reward, whether or not it achieves the actual goal."],
    ["When a measure becomes a target", "Goodhart's law warns that once a number is used as a target, people will game it.",
      "In 1975 the British economist Charles Goodhart observed that statistics used to guide policy tend to break down once they become targets. The anthropologist Marilyn Strathern later summed it up neatly: 'When a measure becomes a target, it ceases to be a good measure.' Examples are everywhere. A call centre rewarding short call times may find staff hanging up on difficult customers. A hospital judged on waiting times may find creative ways to reclassify waits. Schools judged on test scores can end up teaching to the test. There's an old Soviet era joke about a nail factory: given a target by weight, it made a few giant useless nails; given a target by number, it made millions of tiny ones. Whatever gets measured gets gamed."],
    ["A fine is a price", "When daycare centres in Israel introduced late fees, more parents started arriving late.",
      "In a famous study published in 2000, the economists Uri Gneezy and Aldo Rustichini looked at day care centres in Israel that had trouble with parents picking up children late. Some centres introduced a small fine for lateness. You'd expect lateness to fall. Instead it rose. The researchers' explanation, captured in their paper's title, 'A Fine Is a Price', was that the fine changed how parents saw the situation. Before, arriving late meant imposing on a teacher's goodwill, which felt bad. Afterwards it felt like a service they could pay for. Even more striking, when the fines were removed, lateness stayed high. The small payment had replaced a social and moral incentive with a cheap financial one, and the old norm didn't come back."],
    ["Crowding out good motives", "Paying for something people already do for good reasons can sometimes weaken their motivation.",
      "The day care study points to a broader idea: money can sometimes crowd out other motivations. In 1970 the British social researcher Richard Titmuss published The Gift Relationship, comparing blood donation systems. He argued that paying for blood could undermine the sense of civic duty that drives voluntary donors, and might attract people more likely to hide health risks. Researchers still debate how strong this effect is, and payment does increase effort in many settings. But the lesson is that people are motivated by more than money: pride, fairness, belonging, curiosity and a desire to do the right thing. Australia's blood donation system relies on unpaid volunteers, through Lifeblood. Good incentive design works with these deeper motives instead of accidentally replacing them with a price."],
    ["Moral hazard", "When people are protected from the consequences of risk, they may take more risks.",
      "Moral hazard is an insurance term for a simple idea: if someone else bears the cost when things go wrong, people may be less careful. A driver with comprehensive insurance might park a little more carelessly. A bank that expects to be rescued by the government might make riskier loans, keeping the profits in good times and passing the losses to taxpayers in bad times. This worry featured in debates after the 2008 global financial crisis, when several governments rescued large banks. Insurers counter moral hazard with tools like excesses, which make customers share part of every claim. Governments use regulation and rules about who loses money first. Like other incentive problems, moral hazard can't be eliminated completely, only managed sensibly."],
    ["Designing better incentives", "Good incentives reward the real goal, consider how people might game them, and respect non financial motives.",
      "Incentive problems have real consequences. Australia's Royal Commission into misconduct in the banking and financial services industry, which delivered its final report in 2019, heard many examples of staff and advisers chasing commissions and sales targets at customers' expense. Its findings prompted changes to how parts of the industry are paid. So how do you design incentives that work? Start by rewarding the true goal rather than an easy proxy. Imagine how a clever, slightly cynical person might game the system, then close those loopholes. Use several measures rather than one. And remember that pride, trust and fairness are incentives too. Whether you're running a business, a household chores chart or a government program, ask the rat tail question: what am I really paying for?"]
  ],
  [
    [0, "What went wrong with the Hanoi rat bounty?", ["Nobody claimed the reward", "People cut off rat tails and released the rats to breed", "The rats moved to another city", "The bounty was too expensive to pay"], 1, "Paying for tails rewarded tails, not fewer rats."],
    [2, "What does Goodhart's law say, in Strathern's phrasing?", ["Money is the root of all evil", "Prices always rise over time", "When a measure becomes a target, it ceases to be a good measure", "People never respond to incentives"], 2, "Once people are rewarded for hitting a number, they find ways to game it."],
    [3, "What happened when Israeli day care centres introduced late fines?", ["Lateness increased", "Lateness disappeared", "Parents moved their children elsewhere", "Teachers stopped working"], 0, "The fine turned a moral obligation into a price parents were willing to pay."],
    [4, "What did Richard Titmuss argue about paying for blood donations?", ["It would greatly increase supply with no downside", "Hospitals should sell blood overseas", "Donors should be paid in shares", "It could undermine donors' sense of civic duty"], 3, "Titmuss worried payment could crowd out voluntary, altruistic motives."],
    [5, "What is moral hazard?", ["Taking more risks when someone else bears the cost", "A law against risky investing", "Refusing to buy insurance", "A tax on bank profits"], 0, "Protection from consequences can encourage less careful behaviour."]
  ]);

WB.L("great-economic-debate", "money", "advanced", "Smith, Marx, Keynes and Hayek: the great economic debate", "Four thinkers shaped how the modern world argues about markets, governments and fairness. Their ideas still echo in every budget and election.",
  [
    ["A pin factory in Scotland", "Adam Smith argued that specialisation and free exchange create wealth, guided by self interest within a framework of rules.",
      "In 1776 the Scottish philosopher Adam Smith published An Inquiry into the Nature and Causes of the Wealth of Nations. He opened with a pin factory. One worker alone, he said, could perhaps make one pin a day and certainly not twenty, but ten workers splitting the job into specialised steps could make around 48,000. This division of labour, combined with trade, was the engine of prosperity. Smith also argued that a butcher or baker feeds us not out of kindness but out of their own interest, and that competition channels that self interest towards serving others. He famously used the phrase 'invisible hand', though only once in the book. Smith was no cheerleader for business, though. He was deeply suspicious of merchants conspiring to raise prices."],
    ["The other Adam Smith", "Smith also wrote about morality and sympathy, and supported a role for government in some areas.",
      "Smith is often treated as the patron saint of pure free markets, but his thinking was richer than that. Before The Wealth of Nations he wrote The Theory of Moral Sentiments, published in 1759, about how human sympathy, our ability to imagine ourselves in someone else's place, underpins moral life. In The Wealth of Nations he supported public spending on defence, justice, infrastructure and some basic education, and he worried that repetitive factory work could dull workers' minds. He criticised monopolies, government protection of favoured industries and the mercantilist idea that a nation's wealth lay in hoarding gold. People of very different political views claim him as an ally today. Reading him directly is a reminder that the founding father of economics was also a moral philosopher."],
    ["Marx and the critique of capitalism", "Karl Marx argued capitalism exploited workers and was prone to crisis, and his ideas inspired revolutions.",
      "Nearly a century later, Karl Marx looked at the same industrial world and saw something darker: crowded slums, long hours and child labour. In works including The Communist Manifesto, written with Friedrich Engels in 1848, and the first volume of Capital in 1867, Marx argued that capitalism was built on a conflict between those who owned factories and those who worked in them. Workers, he claimed, produced more value than they were paid, and owners kept the difference as profit. He predicted that capitalism would suffer repeated crises and eventually be overthrown. His ideas inspired socialist movements and later communist states, whose record of repression and economic failure has been heavily criticised. Many historians still credit Marx with sharpening questions about power, inequality and economic change."],
    ["Keynes and the Great Depression", "John Maynard Keynes argued that during slumps, governments should boost demand by spending.",
      "During the Great Depression of the 1930s, mass unemployment persisted for years, and many economists' advice to wait for markets to correct themselves looked hopeless. The British economist John Maynard Keynes offered a different diagnosis in his 1936 book The General Theory of Employment, Interest and Money. He argued that economies could get stuck with too little total spending, or demand. If households and businesses are frightened, they cut back, which cuts others' incomes, causing more cutbacks. In such times, he said, governments should step in, spending more or cutting taxes to restart demand, even if it meant borrowing. He had earlier written the much quoted line 'In the long run we are all dead', a jab at those who said things would sort themselves out eventually."],
    ["Hayek and the knowledge problem", "Friedrich Hayek argued that prices carry information no central planner could ever gather.",
      "Keynes's great rival was the Austrian born economist Friedrich Hayek. In his 1944 book The Road to Serfdom, Hayek warned that heavy government planning of the economy could gradually erode personal freedom. His most influential economic idea came in a 1945 essay, 'The Use of Knowledge in Society'. Hayek pointed out that useful knowledge about the economy is scattered among millions of people: a farmer knows about the weather on her land, a shopkeeper knows what customers want this week. No central planner could ever gather it all. Prices, he argued, act like a vast communication system. If tin becomes scarce, its price rises, and people everywhere economise on tin without needing to know why. Markets, in this view, are a way of coordinating knowledge."],
    ["The pendulum swings", "After the Second World War Keynesian ideas dominated, until 1970s stagflation brought a shift towards markets and monetary policy.",
      "After the Second World War, Keynesian ideas shaped economic policy in much of the Western world, including Australia, with governments aiming for full employment. Then came the 1970s. Oil price shocks helped trigger stagflation, high inflation combined with high unemployment, something many Keynesian models had struggled to explain. Economists such as Milton Friedman, who argued that 'inflation is always and everywhere a monetary phenomenon', gained influence. Hayek won a share of the Nobel Memorial Prize in 1974, and Friedman won it in 1976. From the 1980s, many governments, including Australia's, floated currencies, deregulated finance, privatised some state enterprises and gave central banks the job of controlling inflation. When the 2008 global financial crisis struck, Keynesian stimulus came roaring back, with Australia among the countries handing out cash payments."],
    ["Why the debate never ends", "Most modern economies blend markets and government, and the arguments are about the balance.",
      "It's tempting to ask which of these thinkers was right. The more honest answer is that each saw something important. Smith showed how specialisation and trade create wealth. Marx highlighted inequality, power and the instability of capitalism. Keynes explained why economies can get stuck in slumps. Hayek showed why prices and markets are remarkable information systems. Today almost every developed economy, including Australia's, is a mixed economy, combining private markets with public services, regulation and a welfare system. Most political arguments are about the balance: how much to tax and spend, how tightly to regulate, how to share the gains from growth. Knowing where these ideas came from won't settle those debates, but it makes them far easier to follow and to judge."]
  ],
  [
    [0, "What did Adam Smith use to illustrate the division of labour?", ["A pin factory", "A shipyard", "A coal mine", "A textile mill in Manchester"], 0, "Smith described how specialised workers could make vastly more pins together."],
    [2, "According to Marx, where did owners' profits come from?", ["Clever investment in gold", "Government subsidies", "Value produced by workers beyond what they were paid", "Trade with colonies"], 2, "Marx argued workers created more value than their wages, and owners kept the surplus."],
    [3, "What did Keynes recommend during deep slumps?", ["Cutting government spending sharply", "Returning to the gold standard", "Waiting for markets to correct themselves", "Governments spending more or cutting taxes to boost demand"], 3, "Keynes argued governments should restart demand when private spending collapses."],
    [4, "What was Hayek's 'knowledge problem'?", ["Workers lacked education", "No central planner can gather the scattered knowledge that prices convey", "Economists don't understand inflation", "Governments keep too many secrets"], 1, "Hayek saw prices as a way of coordinating knowledge spread across millions of people."],
    [5, "What was 'stagflation' in the 1970s?", ["Fast growth with low inflation", "Falling prices and rising wages", "High inflation combined with high unemployment", "A stock market boom"], 2, "The combination challenged Keynesian models and helped shift economic thinking."]
  ]);
