/* WISEBYTE LESSONS · Money & Economics (part 1). General information, not personal financial advice. */
WB.LESSONS.push(
{
  id: "compound-interest", audience: "adult", cat: "money", level: "beginner",
  trending: true, popularity: 95, added: "2026-07-22",
  title: "How compound interest works",
  hook: "Interest that earns interest. It's the most powerful force in personal finance, working for you or against you.",
  sections: [
    { h: "Interest on interest", key: "Compound interest is interest paid on your original money plus the interest already earned.",
      b: "Interest is the price of money: what a bank pays you for keeping your savings, or what a lender charges you for borrowing. Simple interest is paid only on your original amount, called the principal. Compound interest is paid on the principal plus any interest you've already earned. Your money earns money, and then that money earns money too. It starts slowly, then snowballs. The same maths applies to investments that grow and reinvest their returns, not just bank accounts." },
    { h: "A quick example", key: "$10,000 at 5% becomes $10,500, then $11,025, and about $43,000 after 30 years.",
      b: "Put $10,000 in an account paying 5% a year and leave the interest in. After one year, you have $10,500. In year two, you earn 5% on $10,500, not $10,000, so you gain $525 and have $11,025. The extra $25 is interest on interest. It seems trivial at first, but it grows every year. After 10 years you'd have about $16,300; after 20, about $26,500; and after 30 years, about $43,200, more than four times the original, without adding another dollar." },
    { h: "The snowball curve", key: "Compound growth starts slowly and accelerates; most of the gain comes late.",
      b: "Compound growth doesn't rise in a straight line; it curves upward, gently at first, then steeply. In the example above, the first 10 years added about $6,300. The last 10 years added about $16,700, from the same starting $10,000. This is why patience matters so much. Many people give up on saving or investing in the early years because progress feels slow, just before the curve starts to bend upwards." },
    { h: "Time beats amount", key: "Starting early often matters more than how much you invest.",
      b: "Here's a famous comparison. At a 7% annual return, Alex invests $5,000 a year from age 25 to 35, then stops completely: $50,000 in total. Sam starts at 35 and invests $5,000 every year until 65: $150,000 in total. At 65, Alex ends up with more money than Sam, despite contributing a third as much, because Alex's money had an extra decade to compound. The lesson isn't that it's ever too late, but that small amounts started early are extraordinarily powerful." },
    { h: "The rule of 72", key: "Divide 72 by the interest rate to estimate how many years it takes to double.",
      b: "A handy shortcut: divide 72 by the annual rate to estimate how many years it takes to double your money. At 6%, it doubles in about 12 years. At 9%, about 8 years. At 2%, a typical savings rate in some years, about 36 years. It works in reverse too: to double your money in 10 years, you'd need about a 7.2% return. The rule is an approximation, but it's accurate enough for rates between about 2% and 15%." },
    { h: "Frequency matters (a little)", key: "More frequent compounding increases returns slightly; compare accounts by their effective annual rate.",
      b: "Interest can be added annually, monthly or even daily. The more often it's added, the sooner it starts earning interest itself. At the same 5% rate, monthly compounding gives an effective annual return of about 5.12%, compared with 5% for yearly compounding. The difference is small, but it adds up over decades. When comparing savings accounts, look for the effective annual rate, and watch for 'bonus' rates that only apply if you meet conditions each month." },
    { h: "It works against you too", key: "Compounding also makes high-interest debt grow fast.",
      b: "Compounding is just as powerful in reverse. Credit cards in Australia often charge around 20% interest a year. By the rule of 72, an unpaid balance would roughly double in under four years. Paying only the minimum each month can stretch a modest debt out for a decade or more, costing far more in interest than the original purchase. That's why paying down high-interest debt is often one of the best 'returns' you can get: it's a guaranteed saving at that rate." },
    { h: "Fees and inflation compound too", key: "Fees and inflation also compound, quietly eating long-term returns.",
      b: "Anything expressed as a yearly percentage compounds, including things that work against you. A super or investment fund charging 1% more in fees each year doesn't sound like much, but over 30 years it can reduce your final balance by tens of thousands of dollars. Inflation compounds too, shrinking what your money can buy. The takeaway: start early, be patient, keep fees low, pay off expensive debt, and let time do the heavy lifting." },
  ],
  quiz: [
    { s: 0, q: "What makes compound interest different from simple interest?", o: ["You earn interest on your interest", "The rate is always higher", "It's only paid once", "It's tax-free"], a: 0, e: "Interest is added to your balance, so it earns interest too." },
    { s: 1, q: "$10,000 at 5% a year compounds to how much after two years?", o: ["$11,000", "$11,025", "$10,500", "$12,000"], a: 1, e: "$10,000 → $10,500 → $11,025." },
    { s: 3, q: "What's the most powerful ingredient in compound growth?", o: ["A large first deposit", "Time", "Checking your balance often", "Having many accounts"], a: 1, e: "The longer money compounds, the faster it grows." },
    { s: 4, q: "Using the rule of 72, how long does money take to double at 8%?", o: ["6 years", "9 years", "12 years", "72 years"], a: 1, e: "72 ÷ 8 = 9 years." },
    { s: 6, q: "Why is a 20% credit card balance so dangerous?", o: ["It roughly doubles in under four years if unpaid", "It's illegal", "It lowers your salary", "It has no interest"], a: 0, e: "72 ÷ 20 ≈ 3.6 years." },
  ],
  related: ["superannuation", "index-funds"],
},
{
  id: "stock-market", audience: "adult", cat: "money", level: "intermediate",
  popularity: 92, added: "2026-08-08",
  title: "How the stock market works",
  hook: "What you're actually buying when you buy a share, why prices jump around, and how ordinary people build wealth with it.",
  sections: [
    { h: "What a share is", key: "A share is a small slice of ownership in a company.",
      b: "A share, or stock, is a small slice of ownership in a company. If a company has a million shares and you own 1,000, you own 0.1% of it, including a claim on 0.1% of its future profits. Companies sell shares to raise money to grow, without having to borrow. Shareholders can usually vote on some big decisions, like electing the board of directors. If the company does well, your slice becomes more valuable; if it fails, it can become worthless." },
    { h: "The market itself", key: "Exchanges like the ASX are where shares are traded; an IPO is a company's first sale to the public.",
      b: "A stock exchange is a marketplace where shares are bought and sold. Australia's main one is the ASX, founded in 1987 from the merger of earlier state exchanges; the biggest in the world are in New York. Most trading today is electronic, through brokers and investing apps. When a company first sells shares to the public, it's called an initial public offering, or IPO, and it's then 'listed'. After that, investors trade shares with each other; the company doesn't get the money from those trades." },
    { h: "What moves prices", key: "Prices move with supply and demand, driven by expectations of future profits.",
      b: "Share prices move with supply and demand. If more people want to buy than sell, the price rises. Underneath, buyers are betting on a company's future profits: a share is worth what investors expect the business to earn over time. So prices react to earnings reports, new products, scandals, interest rates, the economy and even general mood. In the short term, prices can be driven by fear and excitement; in the long run, they tend to follow real profits." },
    { h: "How investors make money", key: "Investors earn through capital gains (selling higher) and dividends (shared profits).",
      b: "There are two main ways to make money from shares. If the price rises and you sell for more than you paid, that's a capital gain. And many companies pay part of their profits to shareholders as dividends, usually twice a year in Australia. Australian companies often attach franking credits to dividends, representing company tax already paid, which can reduce the tax you owe. Reinvesting dividends to buy more shares is a powerful way to compound growth." },
    { h: "Indexes and index funds", key: "An index tracks a group of stocks; an index fund buys them all to spread risk cheaply.",
      b: "An index tracks a group of stocks to show how part of the market is doing. The ASX 200 tracks the 200 largest companies on the ASX; the S&P 500 tracks 500 large US companies. An index fund, often bought as an exchange-traded fund (ETF), simply buys all the companies in an index. With one purchase, you own a tiny slice of hundreds of businesses, at low cost. Most professional fund managers fail to beat their index over the long term, once fees are included." },
    { h: "Bull and bear markets", key: "Bull markets rise, bear markets fall 20% or more; crashes happen but markets have historically recovered.",
      b: "A rising market is called a bull market, and a fall of 20% or more from a peak is a bear market. Crashes are a normal part of investing. Markets fell sharply in 1987, during the global financial crisis of 2008–09, and briefly in early 2020 when COVID-19 hit, when the ASX lost over a third of its value in about a month. Broad markets have historically recovered and gone on to new highs, though recovery can take years, and past performance never guarantees the future." },
    { h: "Rules of the game", key: "Listed companies must announce price-sensitive news promptly, and trading on inside information is a crime.",
      b: "A fair market needs everyone to have access to the same important information. Under the ASX's continuous disclosure rules, a listed company must immediately announce anything a reasonable person would expect to have a material effect on its share price, such as a big new contract, a profit downgrade or a takeover offer. If news is about to break, a company can ask for a trading halt so no one trades on half the story. Buying or selling shares using price-sensitive information that isn't public, or tipping someone else off, is insider trading. It's a serious crime in Australia, carrying up to 15 years' jail, and the corporate regulator, ASIC, investigates suspicious trades." },
    { h: "Investing vs gambling", key: "Long-term diversified investing differs from short-term trading and speculation.",
      b: "Buying a broad index fund and holding it for decades is very different from day-trading individual stocks or chasing tips on social media. Studies of day traders consistently find that most lose money over time, after costs. Useful principles for most people: invest for the long term, diversify, keep fees low, don't try to time the market, and never invest money you might need soon or can't afford to lose. This is general information, not personal advice; a licensed adviser can help with your situation." },
  ],
  quiz: [
    { s: 0, q: "What does owning a share mean?", o: ["You've lent money to a company", "You own a small part of a company", "You work for the company", "You get free products"], a: 1, e: "A share is part-ownership of the business." },
    { s: 1, q: "What is an IPO?", o: ["A company's first sale of shares to the public", "A type of dividend", "A market crash", "An index of 500 companies"], a: 0, e: "An initial public offering lists a company." },
    { s: 3, q: "What is a dividend?", o: ["A fee for buying shares", "A share of profits paid to shareholders", "A loan", "A drop in price"], a: 1, e: "Companies share profits with shareholders." },
    { s: 5, q: "When COVID-19 hit in early 2020, roughly how much did the ASX fall in about a month?", o: ["About 5%", "About 10%", "Over a third", "Over 80%"], a: 2, e: "Broad markets later recovered, though recoveries can take years." },
    { s: 6, q: "What is insider trading?", o: ["Buying shares through a licensed broker", "Trading shares using price-sensitive information that isn't public", "Owning shares in the company you work for", "Buying every company in an index"], a: 1, e: "It's a serious crime in Australia, investigated by the corporate regulator, ASIC." },
  ],
  related: ["index-funds", "compound-interest"],
},
{
  id: "inflation", audience: "adult", cat: "money", level: "intermediate",
  popularity: 77, added: "2026-09-15",
  title: "What inflation really is",
  hook: "Why a dollar buys less every year, what the Reserve Bank does about it and what it means for your money.",
  sections: [
    { h: "Prices on the rise", key: "Inflation is the general rise in prices, so each dollar buys a bit less.",
      b: "Inflation is the general rise in prices across the economy over time. When inflation is 3%, something that cost $100 last year costs about $103 today. Put another way, each dollar buys a little less. Individual prices always move around; petrol might jump while TVs get cheaper. Inflation is about the overall level. Over decades it adds up: something that cost $1 in 1990 costs well over $2 today." },
    { h: "How it's measured", key: "Australia measures inflation with the Consumer Price Index (CPI), a basket of everyday goods.",
      b: "The Australian Bureau of Statistics tracks the prices of a 'basket' of goods and services a typical household buys, from bread, petrol and electricity to rent, insurance and haircuts. The change in the cost of this basket is the Consumer Price Index, or CPI. Each item is weighted by how much households spend on it, so housing counts for far more than, say, tea. Since late 2025, the ABS has published a complete CPI every month, replacing the quarterly figure as the headline measure of inflation." },
    { h: "What causes it", key: "Inflation comes from demand outstripping supply (demand-pull) or rising costs (cost-push).",
      b: "Inflation has two classic causes. Demand-pull inflation happens when people and businesses want to buy more than the economy can produce, so sellers raise prices. Cost-push inflation happens when the cost of making things rises, such as wages, energy or shipping, and businesses pass it on. The surge of inflation after COVID-19 was both: supply chains were disrupted and energy prices spiked, while demand bounced back strongly. Australia's inflation peaked at 7.8% in late 2022." },
    { h: "Why a little is normal", key: "Central banks aim for low, stable inflation because falling prices (deflation) can be harmful.",
      b: "Why not aim for zero? A little inflation is considered healthy. It gives central banks room to cut interest rates in a downturn and helps wages and prices adjust. Deflation, a general fall in prices, sounds nice but can be damaging: people delay purchases expecting lower prices, businesses cut jobs and debts become harder to repay. Japan struggled with low growth and deflation for years. Very high inflation, though, erodes savings and makes planning difficult." },
    { h: "The Reserve Bank's job", key: "The RBA targets 2–3% inflation and raises interest rates to cool it.",
      b: "The Reserve Bank of Australia aims to keep inflation between 2% and 3%, focusing on the 2.5% midpoint. Its main tool is the cash rate, the interest rate on overnight loans between banks, which flows through to mortgage, loan and savings rates. When inflation is too high, the RBA raises rates. Borrowing becomes more expensive, people with mortgages have less to spend, businesses invest less, and demand cools. When the economy is weak, it cuts rates to encourage spending. Changes take a year or more to fully work through." },
    { h: "Winners and losers", key: "Inflation hurts savers earning low interest and can help borrowers; wages may lag.",
      b: "Inflation doesn't hit everyone equally. Savers lose out when inflation runs higher than the interest they earn, because their money's real buying power shrinks. People on fixed incomes, or whose wages rise slower than prices, see their living standards fall. Borrowers with fixed debts can benefit, because the real value of what they owe shrinks over time. Economists talk about 'real' figures, meaning adjusted for inflation: a 4% pay rise with 5% inflation is actually a 1% real pay cut." },
    { h: "When it spirals", key: "Hyperinflation is extreme, runaway inflation, as in Germany in 1923 and Zimbabwe in the late 2000s.",
      b: "Extreme, runaway inflation is called hyperinflation, often defined as prices rising more than 50% in a month. It usually happens when governments print money to pay debts. In Germany in 1923, prices rose so fast that people carted cash around in wheelbarrows and workers were paid twice a day. Zimbabwe's hyperinflation peaked in 2008, and it went on to print a 100 trillion dollar note. Hyperinflation wipes out savings and can destabilise entire societies." },
    { h: "Protecting yourself", key: "Beat inflation by earning more than it on savings and investments, and reviewing pay and bills.",
      b: "You can't control inflation, but you can soften its effect. Keep an emergency fund in a high-interest savings account rather than a zero-interest transaction account. For long-term money, investments like shares and property have historically outpaced inflation over long periods, though with more risk. Review your pay regularly, since employers may not raise it automatically. And shop around on big recurring bills like insurance, energy and phone plans, which often creep up when you stay with the same provider." },
  ],
  quiz: [
    { s: 0, q: "If inflation is 3%, what does $100 of groceries cost a year later?", o: ["About $97", "About $103", "Still $100", "About $130"], a: 1, e: "Prices rise about 3%." },
    { s: 1, q: "In Australia, what measures inflation?", o: ["The ASX 200", "The Consumer Price Index", "The cash rate", "GDP"], a: 1, e: "The ABS publishes the CPI." },
    { s: 4, q: "How does the Reserve Bank usually fight high inflation?", o: ["By printing more money", "By raising interest rates", "By cutting taxes", "By setting prices"], a: 1, e: "Higher rates cool spending." },
    { s: 5, q: "You get a 4% pay rise but inflation is 5%. What's your real pay change?", o: ["+9%", "+4%", "About −1%", "0%"], a: 2, e: "Prices rose faster than your pay." },
    { s: 6, q: "What is hyperinflation?", o: ["Very low inflation", "Extremely rapid, out-of-control inflation", "Falling prices", "Inflation in one product"], a: 1, e: "Like Germany in 1923 or Zimbabwe in the late 2000s." },
  ],
  related: ["compound-interest", "budgeting"],
},
{
  id: "budgeting", audience: "adult", cat: "money", level: "beginner",
  trending: true, popularity: 87, added: "2026-09-19",
  title: "Budgeting that actually works",
  hook: "A budget isn't a diet for your money. It's a plan that gives every dollar a job, and it takes about 20 minutes to set up.",
  sections: [
    { h: "Why budget at all?", key: "A budget is a plan for your money that reduces stress and helps you reach goals.",
      b: "A budget is simply a plan for your money: deciding in advance where it goes instead of wondering afterwards where it went. It's not about never spending on fun; it's about spending on what matters to you and cutting what doesn't. Surveys consistently find money is one of the biggest sources of stress for Australians. Knowing your numbers, even roughly, replaces vague anxiety with a plan." },
    { h: "Track where it goes", key: "Start by tracking where your money currently goes for a month.",
      b: "Before planning, look at reality. Most banking apps now automatically sort your spending into categories like groceries, transport and entertainment. Look back over the last one to three months. Many people are surprised by the total of small, regular purchases: coffees, takeaway, delivery fees and subscriptions they'd forgotten about. Don't judge yet; just get the facts. Include irregular costs like car rego, insurance and Christmas by dividing their yearly cost by 12." },
    { h: "The 50/30/20 rule", key: "About 50% on needs, 30% on wants, 20% on savings and extra debt repayments.",
      b: "A simple starting framework, popularised by US senator and former Harvard professor Elizabeth Warren, is the 50/30/20 rule. About 50% of after-tax income goes on needs: rent or mortgage, groceries, utilities, transport and insurance. About 30% goes on wants: eating out, entertainment, hobbies and holidays. And 20% goes on savings and paying down debt faster. In high-cost cities, needs often take more than half, so treat the numbers as a guide and adjust them to fit your life." },
    { h: "Pay yourself first", key: "Automatically move savings out on payday, before you can spend it.",
      b: "The most effective budgeting habit is automation. Set up an automatic transfer to a separate savings account on payday, before you have a chance to spend it. Money you never see in your everyday account is much easier not to spend. Many Australians use multiple accounts, sometimes called 'buckets': one for bills, one for everyday spending, one for savings goals and one for emergencies. Several banks let you open these free and nickname them." },
    { h: "An emergency fund", key: "Aim for 3–6 months of essential expenses in an easy-access account.",
      b: "Life guarantees surprises: a car repair, a vet bill, a broken phone or a job loss. An emergency fund turns these from crises into inconveniences. A common target is three to six months of essential expenses, kept in an easy-access, high-interest savings account. That sounds like a lot, so start with a smaller goal, like $1,000, which covers many common emergencies. Without a buffer, unexpected costs tend to end up on a credit card, where they grow." },
    { h: "Clear high-interest debt", key: "Avalanche (highest rate first) saves most; snowball (smallest first) builds momentum.",
      b: "Credit cards often charge around 20% interest, so paying one off is like earning a guaranteed 20% return. Two popular methods: the avalanche, where you pay the minimum on everything and throw extra money at the debt with the highest interest rate, saves the most money. The snowball, where you clear the smallest balance first, builds momentum through quick wins. Also be wary of buy now, pay later services: they're convenient, but missed payments bring fees and they make it easy to overspend." },
    { h: "Cut the leaks", key: "Review subscriptions and shop around on insurance, energy and phone plans each year.",
      b: "The easiest savings are often recurring costs you've stopped noticing. Go through your statements and cancel subscriptions you don't use. Once a year, compare your energy, insurance, internet and phone plans; loyalty is rarely rewarded, and switching can save hundreds of dollars. The Australian Government's Energy Made Easy website compares electricity and gas offers for free (in Victoria, use Victorian Energy Compare). Small recurring savings compound: $50 a month is $600 a year, every year." },
    { h: "Make it stick", key: "Review monthly, allow fun money and focus on goals, not perfection.",
      b: "The best budget is one you'll actually keep. Include some guilt-free fun money, or you'll eventually rebel against it. Check in once a month for 15 minutes to see how you're tracking and adjust. Give your savings a purpose, like a holiday, a house deposit or freedom from debt, because goals motivate more than numbers. And expect imperfect months. This is general information, not personal financial advice; free services like the National Debt Helpline (1800 007 007) can help if debts feel overwhelming." },
  ],
  quiz: [
    { s: 1, q: "What's the first step in making a budget?", o: ["Cut all spending", "Track where your money currently goes", "Open a new account", "Buy shares"], a: 1, e: "You can't plan until you know where the money goes." },
    { s: 2, q: "In the 50/30/20 rule, what's the 20% for?", o: ["Rent", "Wants", "Savings and extra debt repayments", "Tax"], a: 2, e: "50 needs, 30 wants, 20 savings and debt." },
    { s: 3, q: "What does 'pay yourself first' mean?", o: ["Buy a treat on payday", "Move money to savings automatically before spending", "Pay bills late", "Ask for a raise"], a: 1, e: "Savings come out first, automatically." },
    { s: 4, q: "What's a typical emergency fund target?", o: ["One week of expenses", "3 to 6 months of essential expenses", "5 years of income", "$50"], a: 1, e: "Enough to ride out a job loss or big repair." },
    { s: 5, q: "Which debt payoff method saves the most interest?", o: ["Avalanche: highest rate first", "Snowball: smallest balance first", "Minimum payments only", "Newest debt first"], a: 0, e: "Tackling the highest rate first minimises interest." },
  ],
  related: ["superannuation", "negotiation"],
},
);
