/* WISEBYTE LESSONS · Life Skills (part 1) */
WB.LESSONS.push(
{
  id: "negotiation", audience: "adult", cat: "life", level: "intermediate",
  popularity: 84, added: "2026-09-16",
  title: "How to negotiate",
  hook: "Salaries, rent, car prices, bedtimes: life is full of negotiations. A few principles reliably change the outcome.",
  sections: [
    { h: "Everyone negotiates", key: "Negotiation is two sides working out an agreement; a few principles make a big difference.",
      b: "Negotiation is simply two or more sides working out an agreement. Whether it's a pay rise, a second-hand car, a phone bill or who does the dishes, you're negotiating. Many people avoid it because it feels awkward or confrontational, and they leave real money on the table. Studies of salary offers find that people who negotiate often get more, and employers generally expect it. A handful of principles, most from the Harvard Negotiation Project, make a big difference." },
    { h: "Prepare first", key: "Research the market, know what you want and plan your walk-away point before you start.",
      b: "Most negotiations are won before they start. Research the market: what do similar jobs pay, what have similar cars sold for, what are competitors offering? Websites, job ads and industry salary surveys help. Decide your target, the outcome you're aiming for, and your walk-away point, the worst deal you'll accept. Anticipate the other side's concerns and questions. Preparation gives you confidence and stops you making decisions on the spot under pressure." },
    { h: "Know your BATNA", key: "Your BATNA is your best alternative if no deal is reached; a strong one gives you power.",
      b: "Your BATNA is your 'best alternative to a negotiated agreement': what you'll do if this deal falls through. The term comes from the 1981 book Getting to Yes by Roger Fisher and William Ury. If you have another job offer, your BATNA is strong; if you'd be unemployed, it's weak. The stronger your alternative, the more confidently you can push, and the more clearly you'll know when to walk away. Improving your BATNA, for example by getting another quote, is often the smartest move." },
    { h: "Interests, not positions", key: "A position is what someone asks for; an interest is why. Find the interests.",
      b: "A position is what someone says they want. An interest is why they want it. The classic story: two sisters argue over one orange and finally cut it in half. One eats the fruit and throws away the peel; the other uses the peel for baking and throws away the fruit. If they'd asked why, both could have had all they needed. Asking 'What's most important to you here?' uncovers room for creative deals, like a later start date in exchange for a higher salary." },
    { h: "Anchor with reasons", key: "A well-researched first offer anchors the conversation; back it with a reason.",
      b: "The first number on the table tends to anchor the whole conversation. If you've done your research, it often pays to make the first offer, aiming ambitious but defensible, and to back it with a reason: 'Similar roles pay $95,000 to $105,000, and I bring X, so I'm looking for $102,000.' Reasons make numbers feel legitimate. If the other side anchors first with an unreasonable figure, don't argue about it; calmly re-anchor with your own researched number." },
    { h: "Listen, label and stay quiet", key: "Ask open questions, name the other side's feelings, and get comfortable with silence.",
      b: "Former FBI negotiator Chris Voss recommends 'labelling': naming the other side's feelings, like 'It sounds like budgets are tight this year.' It shows you're listening, builds trust and often draws out useful information. Ask open questions: 'How am I supposed to do that?' invites them to solve your problem. After making an offer, stop talking. Silence feels uncomfortable, and the other person will often fill it, sometimes with a better offer." },
    { h: "Trade, don't just concede", key: "Never give something for nothing; trade concessions and look beyond price.",
      b: "Avoid simply splitting the difference or giving ground for nothing. Every concession should buy something: 'I can do that price if you include delivery.' Look beyond the headline number. In a job negotiation, there's leave, flexibility, training, title and start date. When buying a car, there are accessories, servicing and warranty. Give ground on what's cheap for you but valuable to them, and ask for things that are cheap for them but valuable to you." },
    { h: "A deal both can live with", key: "Aim for agreements both sides can live with; resentful deals fall apart.",
      b: "If the other side feels cheated, they may not follow through, may resent you in a job you'll hold for years, or may never deal with you again. Most negotiations are with people we'll meet again, so relationships matter. Aim for an agreement both sides can live with, be firm on substance and friendly with people, and get the final deal in writing. And remember your walk-away point: sometimes the best negotiation is the one where you politely say no." },
  ],
  quiz: [
    { s: 2, q: "What is a BATNA?", o: ["Your best alternative if no deal is reached", "Your opening offer", "The other side's bottom line", "A legal contract"], a: 0, e: "It's your fallback and your source of leverage." },
    { s: 3, q: "What's the difference between a position and an interest?", o: ["No difference", "A position is what you ask for; an interest is why you want it", "Interests are always money", "Positions are secret"], a: 1, e: "Interests reveal creative solutions." },
    { s: 4, q: "Why can it help to make the first offer?", o: ["It anchors the negotiation", "It's polite", "It ends the negotiation", "It hides your BATNA"], a: 0, e: "First numbers pull later ones towards them." },
    { s: 5, q: "What should you usually do right after making an offer?", o: ["Keep talking to justify it", "Stay quiet and let them respond", "Lower it straight away", "Walk out"], a: 1, e: "Silence often works in your favour." },
    { s: 6, q: "What's the principle behind 'trade, don't just concede'?", o: ["Every concession should get something in return", "Always split the difference", "Never give anything", "Only talk about price"], a: 0, e: "Give ground on what's cheap for you and valuable to them." },
  ],
  related: ["persuasion", "communication"],
},
{
  id: "scams", audience: "adult", cat: "life", level: "beginner",
  trending: true, popularity: 94, added: "2026-09-24",
  title: "How scams work, and how to beat them",
  hook: "Australians lose billions to scams. Scammers aren't targeting the gullible; they're targeting everyone, using the same few tricks.",
  sections: [
    { h: "Anyone can be scammed", key: "Scams target everyone; they succeed through pressure and emotion, not stupidity.",
      b: "Australians reported losing about $2.18 billion to scams in 2025, and many losses go unreported. Scams aren't only aimed at the elderly or naive; young adults are frequently targeted, especially through social media and job and investment scams. Scammers are organised, professional and constantly adapting. They succeed not because victims are foolish but because they exploit universal emotions: fear, urgency, greed, love and the desire to help. Knowing the patterns is the best defence." },
    { h: "Impersonation", key: "Scammers pretend to be banks, government agencies, delivery firms or family members.",
      b: "Most scams start with impersonation. Scammers pretend to be your bank, the ATO, myGov, Australia Post, a toll company, a phone provider or the police. Until mid-2026, scam texts could even land in the same thread as genuine messages by spoofing sender names; since July 2026, texts using an unregistered sender name are marked 'Unverified', but scammers keep adapting, so don't rely on that alone. A notorious version is the 'Hi Mum' scam, where someone claims to be your child on a new number and urgently needs money. Always verify using contact details you find yourself, never the ones in the message." },
    { h: "The red flags", key: "Urgency, secrecy, unusual payment methods and requests for codes or passwords are red flags.",
      b: "Scams share tell-tale signs. You're rushed: act now or your account will be closed, you'll be arrested, the offer disappears. You're asked to keep it secret. You're asked to pay in unusual ways: gift cards, cryptocurrency, wire transfers or to a 'safe account'. You're asked for passwords, one-time codes or remote access to your computer. The deal seems too good to be true. Any one of these should make you stop. Genuine organisations won't pressure you this way." },
    { h: "Investment scams", key: "Investment scams promise high, guaranteed returns, often via social media, fake ads or 'mentors'.",
      b: "Investment scams cause the biggest losses. They often start with fake ads featuring celebrities or well-known Australians, or a friendly stranger on social media or a dating app who shares their 'success' trading crypto. Victims are shown professional-looking platforms with fake profits, encouraged to invest more, then find they can't withdraw. Warning signs: guaranteed high returns, pressure to invest quickly, and unlicensed operators. Check whether a company holds an Australian Financial Services licence on ASIC's professional register." },
    { h: "Romance and job scams", key: "Romance scammers build trust over weeks before asking for money; fake jobs demand upfront payments.",
      b: "Romance scammers build relationships online over weeks or months, often claiming to work overseas, in the military or on oil rigs. They avoid video calls, then eventually ask for money for an emergency, travel or an investment opportunity. Job scams offer easy money for simple online tasks like rating products, then ask you to deposit money to 'unlock' earnings. Rule of thumb: never send money to someone you've only met online, and a real job never asks you to pay to work." },
    { h: "Remote access and 'safe account' scams", key: "Never let a caller access your device, and banks never ask you to move money to a 'safe account'.",
      b: "In remote access scams, a caller claims to be from your telco, bank or a tech company, says your computer or account has been hacked, and asks you to install software so they can 'fix' it. Once in, they can access your banking. In 'safe account' scams, a fake bank officer says your money is at risk and must be moved to a new account, which they control. No genuine bank or tech company will ask you to do either. Hang up and call the organisation yourself." },
    { h: "Stop. Check. Protect.", key: "Stop and slow down, check independently, and protect yourself by acting fast if something's wrong.",
      b: "Australia's National Anti-Scam Centre recommends three steps. Stop: don't give money or information if you're unsure; scammers rely on rushing you. Check: ask yourself if the message could be fake, and contact the organisation using details from its official website or app, not the message. Talk to someone you trust; a second opinion breaks the spell. Protect: act quickly if something feels wrong. Use two-factor authentication and strong, unique passwords to reduce the damage if details leak." },
    { h: "If it happens to you", key: "Contact your bank immediately, then report to Scamwatch and ReportCyber; IDCARE can help.",
      b: "If you've been scammed, act fast and don't be embarrassed; it happens to smart people every day. Contact your bank or card provider immediately; they may be able to stop or recover payments. Change compromised passwords. Report it to Scamwatch (scamwatch.gov.au), and cybercrime to ReportCyber (cyber.gov.au). If your identity documents were exposed, contact IDCARE (1800 595 160), a free national support service. Beware of 'recovery' scammers who contact victims promising to get their money back for a fee." },
  ],
  quiz: [
    { s: 2, q: "Which of these is a classic scam red flag?", o: ["A request to pay by gift card or crypto", "An email with no links", "A letter by post", "A friend saying hello"], a: 0, e: "Unusual payment methods are a major warning sign." },
    { s: 1, q: "What's the 'Hi Mum' scam?", o: ["A scammer pretends to be your child on a new number", "A Mother's Day sale", "A fake charity", "A lottery win"], a: 0, e: "Always verify on a number you already know." },
    { s: 3, q: "Where can you check whether an investment company is licensed?", o: ["Social media reviews", "ASIC's professional register", "The company's own website", "A forum"], a: 1, e: "Legitimate advisers and dealers hold an AFS licence." },
    { s: 5, q: "Your 'bank' calls asking you to move money to a safe account. What should you do?", o: ["Move it quickly", "Hang up and call your bank on its official number", "Give them your password", "Install their software"], a: 1, e: "Banks never ask you to do this." },
    { s: 7, q: "What should you do first if you've been scammed?", o: ["Wait a week", "Contact your bank immediately", "Pay a recovery service", "Delete everything"], a: 1, e: "Speed can help stop or recover payments." },
  ],
  related: ["digital-security", "credit-scores"],
},
{
  id: "digital-security", audience: "adult", cat: "life", level: "beginner",
  popularity: 71, added: "2026-09-17",
  title: "Stay safe online",
  hook: "A few simple habits stop the vast majority of account takeovers, and most take only minutes to set up.",
  sections: [
    { h: "Why you're a target", key: "Attackers target everyone automatically; your accounts, data and identity all have value.",
      b: "Many people think, 'Why would a hacker want my stuff?' But most attacks aren't personal. Criminals use automated tools to try millions of stolen passwords, send millions of phishing messages and scan for unpatched devices. Your email account alone can be used to reset passwords for your bank, shopping and social media. Stolen identities are sold and used for fraud. Australia has seen major data breaches, like Optus and Medibank in 2022, exposing millions of people's details." },
    { h: "Passwords that work", key: "Use long passphrases and never reuse a password.",
      b: "Length beats complexity. A passphrase of four or more random words, like 'purple-kettle-marathon-cactus', is easier to remember and much harder to crack than a short jumble like P@ssw0rd1. The most important rule is never reuse passwords. When one website is breached, attackers automatically try the same email and password on banks, email and shopping sites, a technique called credential stuffing. Your email password is the most important of all; make it unique and strong." },
    { h: "Use a password manager", key: "A password manager creates and stores a unique strong password for every account.",
      b: "Nobody can remember 100 unique strong passwords. A password manager solves this: it generates a random password for each site, stores them securely, and fills them in for you. You only remember one strong master password. Good password managers are built into Apple and Google devices and browsers, and dedicated apps are also available. They also help protect against phishing, because they won't autofill your password on a fake website with the wrong address." },
    { h: "Turn on two-factor authentication", key: "Two-factor authentication adds a second login step, so a stolen password isn't enough.",
      b: "Two-factor (or multi-factor) authentication, often called 2FA or MFA, adds a second step when you log in, such as a code from an authenticator app, a text message code, a fingerprint or a security key. Even if someone steals your password, they can't get in without that second factor. Turn it on for your email, banking, myGov, social media and shopping accounts. Authenticator apps are more secure than text messages. And never share a code with anyone who asks for it." },
    { h: "Spot phishing", key: "Phishing uses urgency, threats and fake links; go to the official site or app directly.",
      b: "Phishing messages pretend to come from organisations you trust to trick you into clicking a link, opening an attachment or entering details. Warning signs include urgency or threats, generic greetings, odd sender addresses, spelling mistakes and links that don't match the real website. But modern phishing can look flawless. The safest habit: don't click links in unexpected messages. Instead, open the official app or type the website address yourself. myGov, for example, says it will never send you a link to sign in." },
    { h: "Update everything", key: "Automatic updates patch security holes attackers already know about.",
      b: "Software updates often patch security holes that attackers already know about and actively exploit. The Australian Signals Directorate lists patching applications and operating systems among its most important cyber security strategies. Turn on automatic updates for your phone, computer, browser and apps. Don't ignore update prompts for weeks. Old devices that no longer receive security updates, like very old phones and routers, are a risk and worth replacing when practical." },
    { h: "Back up and lock down", key: "Back up important files, lock your devices and be careful on public Wi-Fi.",
      b: "Ransomware and device failure can wipe out photos and documents. Back up important files regularly, ideally automatically to the cloud and to an external drive. Lock your phone and computer with a PIN, password or biometrics, and turn on 'find my device' so you can locate or wipe a lost one. Public Wi-Fi is less risky than it used to be, since most websites are encrypted, but avoid banking on unknown networks and use your mobile data when in doubt." },
    { h: "Share less", key: "Limit what you share publicly; details like birthdays and pet names help scammers.",
      b: "Scammers and identity thieves piece together information from social media: your birthday, hometown, school, pet's name and holiday dates. These are often the answers to security questions or useful for impersonation. Review your privacy settings, limit what's public and think before posting in real time that you're away from home. Be sceptical of quizzes asking for personal details. If an organisation you use suffers a data breach, change that password and watch for follow-up scams." },
  ],
  quiz: [
    { s: 1, q: "Which is the strongest password?", o: ["P@ssw0rd1", "Summer2024!", "A long passphrase of random words", "Your pet's name"], a: 2, e: "Length beats complexity." },
    { s: 1, q: "Why shouldn't you reuse passwords?", o: ["It's slower", "A breach at one site exposes other accounts", "Websites ban it", "It uses more storage"], a: 1, e: "Attackers try leaked logins everywhere (credential stuffing)." },
    { s: 3, q: "What does two-factor authentication add?", o: ["A second step, like an app code, when logging in", "A password hint", "A backup email", "Faster logins"], a: 0, e: "A stolen password alone isn't enough." },
    { s: 4, q: "What's the safest response to an unexpected message with a login link?", o: ["Click it quickly", "Open the official app or type the address yourself", "Reply with your details", "Forward it to friends"], a: 1, e: "Never log in through links in unexpected messages." },
    { s: 5, q: "Why install updates promptly?", o: ["They patch known security holes", "They save battery", "The law requires it", "They delete viruses"], a: 0, e: "Unpatched software is an easy target." },
  ],
  related: ["scams", "encryption"],
},
{
  id: "first-aid", audience: "adult", cat: "life", level: "beginner",
  popularity: 79, added: "2026-09-14",
  title: "First aid basics: DRSABCD",
  hook: "The seven steps that could help you save a life. An overview to build confidence, not a replacement for a proper course.",
  sections: [
    { h: "Why learn it", key: "Australian first aid follows DRSABCD; a hands-on course is the best way to learn.",
      b: "Knowing what to do in the first few minutes of an emergency can save a life. When someone's heart stops, every minute without CPR sharply reduces their chance of survival, and ambulances can take several minutes or more to arrive. In Australia, first aid follows an action plan called DRSABCD, from the Australian Resuscitation Council. This lesson is an overview only. A hands-on course, from organisations such as St John Ambulance or Australian Red Cross, is the best way to learn properly and practise on a manikin." },
    { h: "D: Danger", key: "Check for danger to yourself, bystanders and the casualty before approaching.",
      b: "Before rushing in, check for danger to yourself, bystanders and the injured person: traffic, fire, electricity, deep water, falling objects or aggressive people. You can't help anyone if you become a casualty yourself. If it's safe, approach. If not, and you can't make it safe, call for help and keep your distance. Wear gloves if available when dealing with blood or bodily fluids." },
    { h: "R: Response", key: "Check for a response by talking to the person and squeezing their shoulders.",
      b: "Check whether the person responds. Use the COWS approach: can you hear me, open your eyes, what's your name, squeeze my hand. Speak loudly and firmly squeeze their shoulders. If they respond, they're conscious: make them comfortable, check for injuries, call for help if needed and monitor them. If there's no response, move straight on to getting help and checking their airway and breathing." },
    { h: "S: Send for help", key: "Call Triple Zero (000); the operator will guide you. 112 also works from mobiles.",
      b: "If the person is unresponsive, call Triple Zero (000), or ask a bystander to call while you help. From a mobile, 112 also works. Ask for an ambulance and put the phone on speaker. The operator will ask questions and can guide you step by step through what to do, including CPR, so you're not alone. If there's an AED (defibrillator) nearby, send someone to get it immediately; many are listed on apps and at shopping centres, gyms and sporting clubs." },
    { h: "A: Airway", key: "Open the mouth, check for blockages and roll the person onto their side to clear them if needed.",
      b: "Open the person's mouth and look for anything blocking the airway, such as vomit, blood, food or loose teeth. If there's something there, roll them onto their side and clear it with your fingers. Then, with the person on their back, open the airway by gently tilting the head back and lifting the chin. For babies, keep the head in a neutral position rather than tilting it back." },
    { h: "B: Breathing", key: "Look, listen and feel for normal breathing for up to 10 seconds; if breathing, use the recovery position.",
      b: "Look for the chest rising and falling, listen for breathing and feel for breath on your cheek, for up to 10 seconds. Occasional gasping is not normal breathing and can happen in the first minutes after cardiac arrest. If the person is breathing normally, place them in the recovery position, on their side with the top leg bent, which keeps the airway clear, and keep watching them until help arrives. If they're not breathing normally, start CPR." },
    { h: "C: CPR", key: "If the person is unresponsive and not breathing normally, start CPR straight away.",
      b: "CPR, short for cardiopulmonary resuscitation, is the C in DRSABCD. It combines chest compressions with rescue breaths to keep some oxygen-carrying blood flowing to the brain and heart. CPR on its own rarely restarts a stopped heart, but it buys precious time until a defibrillator or paramedics arrive. Start as soon as you've found that the person is unresponsive and not breathing normally. Starting quickly matters more than perfect technique. The CPR lesson walks you through exactly how to do it, including rescue breaths and how to adjust for children and babies." },
    { h: "D: Defibrillation", key: "Attach an AED (defibrillator) as soon as one is available and follow its instructions.",
      b: "The final D is defibrillation: an electric shock that can reset a heart whose rhythm has become chaotic. An automated external defibrillator, or AED, is built for untrained bystanders. It analyses the heart rhythm itself and tells you what to do at every step. Attach it the moment it arrives, keeping CPR going while it's set up. It's worth noticing where AEDs are kept at your workplace, gym, sports club or local shops, usually marked by a green sign with a heart and lightning bolt. The CPR lesson covers using one step by step." },
  ],
  quiz: [
    { s: 1, q: "What does the first D in DRSABCD stand for?", o: ["Doctor", "Danger", "Defibrillation", "Diagnose"], a: 1, e: "Always check for danger first." },
    { s: 3, q: "What number do you call in an emergency in Australia?", o: ["911", "999", "000", "111"], a: 2, e: "Triple Zero (000). 112 also works from mobiles." },
    { s: 5, q: "Someone unresponsive is breathing normally. What should you do?", o: ["Start CPR", "Place them in the recovery position and monitor them", "Give them water", "Leave them"], a: 1, e: "The recovery position keeps the airway clear." },
    { s: 6, q: "What does CPR do for someone whose heart has stopped?", o: ["It always restarts the heart on its own", "It keeps some oxygen-carrying blood flowing until a defibrillator or paramedics arrive", "It clears the airway", "It replaces the need to call Triple Zero"], a: 1, e: "CPR buys time; defibrillation is usually what restarts the heart's rhythm." },
    { s: 7, q: "When should you attach an AED?", o: ["Only after 30 minutes of CPR", "Only if a doctor is present", "As soon as one is available, keeping CPR going while it's set up", "Never, unless you are trained"], a: 2, e: "AEDs are designed for bystanders and talk you through each step." },
  ],
  related: ["brain", "home-maintenance"],
},
);
