/* WISEBYTE LESSONS · food batch y */
WB.L("coffee-bean-to-cup", "food", "beginner", "Coffee: from goat legend to flat white", "Every morning, billions of people drink the roasted seeds of a cherry from the Ethiopian highlands. Here is how that seed conquered the world, and what actually happens between the farm and your cup.",
  [
    ["A story about dancing goats", "Coffee's origin legend is charming, but its real roots lie in Ethiopia and Yemen.", "The most famous coffee story tells of Kaldi, an Ethiopian goatherd who noticed his goats prancing about after nibbling red berries from a shrub. He tried them himself, felt wonderfully alert, and the rest is history. Sadly, the tale was first written down many centuries after it supposedly happened, so historians treat it as legend. What we do know is that the arabica coffee plant grows wild in the highland forests of Ethiopia. The first solid evidence of people drinking coffee comes from Yemen in the fifteenth century, where Sufi religious communities brewed it to stay awake during night-time prayers. From the Yemeni port of Mocha, whose name still lives on in cafe menus, coffee began its journey across the Islamic world."],
    ["Coffeehouses change society", "Coffeehouses became places where news, business and ideas were traded.", "By the sixteenth century, coffeehouses were thriving in cities such as Cairo and Istanbul, and some rulers tried to ban them, worried about the gossip and political talk they encouraged. Coffee reached Europe in the seventeenth century and the pattern repeated. In London, coffeehouses were nicknamed 'penny universities' because for the price of a cup you could sit for hours reading newspapers and arguing with strangers. Particular coffeehouses attracted particular crowds. Merchants and ship owners gathered at Edward Lloyd's coffeehouse to swap shipping news, and that meeting place grew into Lloyd's of London, the famous insurance market. Unlike beer and wine, the usual everyday drinks of the time, coffee sharpened people rather than dulling them, which may help explain why it became linked with commerce and debate."],
    ["Arabica and robusta", "Two species dominate the world's coffee, and they taste quite different.", "Almost all the coffee people drink comes from two species. Arabica is the prized one: it grows best at higher altitudes, produces sweeter, more complex flavours and makes up the larger share of world production. Robusta, as the name hints, is a tougher plant that tolerates heat and disease and grows at lower altitudes. Its beans contain roughly twice as much caffeine, which partly acts as a natural pesticide, and they taste more bitter and earthy. Robusta is common in instant coffee and in many espresso blends, where it adds body and a thick crema. Today Brazil is the world's biggest coffee producer by a wide margin, while Vietnam, a robusta powerhouse, is usually second. Climate change worries growers, because arabica in particular is fussy about temperature."],
    ["From cherry to green bean", "A coffee bean is the seed of a fruit, and how that fruit is processed shapes the flavour.", "On the plant, coffee grows as small cherries that ripen from green to deep red. Inside each cherry are usually two seeds, the beans. After picking, farmers must remove the fruit, and the method matters. In washed processing, the skin and most of the sticky flesh are stripped off and the beans are soaked so microbes break down the rest, giving clean, bright flavours. In natural processing, the whole cherry is dried in the sun before the fruit is removed, which can add fruity, wine-like notes. Either way, the result is a hard, pale green bean that smells grassy rather than anything like coffee. Green beans keep well for months, which is why coffee is shipped around the world in this state and roasted closer to where it is drunk."],
    ["The magic of roasting", "Roasting turns a grassy seed into something with hundreds of aroma compounds.", "Roasting is where coffee's flavour is created. Green beans are tumbled in hot air, usually reaching around 200 degrees Celsius. First they dry out and turn yellow, smelling a bit like bread. Then the browning reactions kick in: sugars caramelise, and amino acids react with sugars in the Maillard reaction, the same chemistry that browns toast and seared steak. Pressure builds inside the bean until it cracks audibly, rather like popcorn. Scientists have identified hundreds of aroma compounds in roasted coffee. Light roasts keep more of the bean's origin character, often tasting fruity or floral and more acidic. Dark roasts taste more of the roast itself: smoky, bitter and chocolatey. Once roasted, beans start to go stale within weeks as aromas escape, so freshness really does matter."],
    ["Brewing is extraction", "Making coffee is about dissolving the right amount of flavour out of the grounds.", "Whatever your method, brewing is extraction: water dissolves flavour compounds from ground coffee. The trick is getting the amount right. Acids dissolve first, then sweeter compounds, and bitter ones last. Pull too little and the coffee tastes sour and thin; pull too much and it turns harsh and bitter. Grind size, water temperature, contact time and the ratio of coffee to water are the levers. Espresso uses very fine grounds and forces hot water through them at high pressure, typically around nine bars, for roughly half a minute, producing a small, intense shot topped with crema, a foam of oils and gases. Plunger coffee uses coarse grounds steeped for several minutes. Cold brew steeps in cold water for many hours, giving a smoother, less acidic drink."],
    ["Australia's coffee culture", "Post-war migrants helped turn Australia into a nation of espresso lovers.", "For much of the twentieth century, Australia was a tea-drinking country, and coffee often meant a spoonful of instant. That changed after the Second World War, when Italian and Greek migrants opened cafes and brought espresso machines with them, especially in Melbourne and Sydney. Over the following decades, a distinctive cafe culture grew, built around milk-based espresso drinks and independent cafes rather than big chains. The flat white became an Australian favourite, although New Zealanders also claim to have invented it, and the argument shows no sign of ending. Caffeine works by blocking adenosine, a chemical that builds up in the brain and makes us feel sleepy. Most healthy adults can enjoy a few cups a day, but this is general information, so check healthdirect for guidance on caffeine limits."]
  ],
  [
    [0, "Where did people first clearly drink coffee as a beverage?", ["Brazil", "Yemen", "Italy", "Vietnam"], 1, "The earliest solid evidence of coffee drinking comes from fifteenth-century Yemen, where Sufi communities brewed it to stay awake."],
    [1, "Which famous institution grew out of a London coffeehouse?", ["The Bank of England", "The British Museum", "Lloyd's of London", "The Royal Mint"], 2, "Merchants met at Edward Lloyd's coffeehouse to share shipping news, and it grew into the Lloyd's insurance market."],
    [2, "How does robusta compare with arabica?", ["It has roughly twice the caffeine and tastes more bitter", "It grows only at very high altitudes", "It contains no caffeine at all", "It is the sweeter, more delicate species"], 0, "Robusta is hardier, contains around twice the caffeine and has a more bitter, earthy taste."],
    [4, "Which chemical reaction, also used to brown toast, helps create coffee's flavour during roasting?", ["Fermentation", "Oxidation of iron", "Photosynthesis", "The Maillard reaction"], 3, "The Maillard reaction between amino acids and sugars produces many of roasted coffee's flavours and aromas."],
    [5, "What usually causes a coffee to taste sour and thin?", ["Over-extraction", "Under-extraction", "Using filtered water", "Grinding too finely"], 1, "Acids dissolve first, so pulling too little from the grounds leaves coffee sour and thin."]
  ]);

WB.L("chocolate-cacao", "food", "beginner", "Chocolate: from bitter drink to sweet bar", "For thousands of years, chocolate was a frothy, bitter drink for rulers and gods. It became the solid, sweet bar we know only in the last two centuries.",
  [
    ["Food of the gods", "Cacao has been used in the Americas for more than 5,000 years.", "Chocolate begins with the cacao tree, whose scientific name, Theobroma cacao, means 'food of the gods'. The tree is native to the tropical Americas, and archaeologists have found traces of cacao on pottery in Ecuador more than 5,000 years old. Later, the Olmec, Maya and Aztec peoples of Mexico and Central America made it central to their cultures. They did not eat chocolate bars. Instead they ground roasted cacao beans into a paste, mixed it with water, and often added chilli, maize or flowers, then poured it from a height to create a prized layer of foam. The drink was bitter, not sweet. It featured in religious ceremonies, feasts and marriages, and the Aztecs valued the beans so highly they used them as a form of money."],
    ["Chocolate reaches Europe", "Europeans sweetened cacao with sugar and turned it into a fashionable luxury.", "Spanish invaders encountered cacao in the sixteenth century and brought it back to Spain. At first Europeans found the bitter drink strange, but once it was sweetened with sugar and flavoured with spices such as cinnamon and vanilla, it caught on. For a long time, drinking chocolate was an expensive luxury for royal courts and the wealthy, spreading from Spain to Italy, France and England. Chocolate houses opened in London alongside the coffeehouses. Because sugar and cacao both came from plantations in the colonies, the European taste for chocolate was tied to colonial trade and the forced labour of enslaved people. It is a reminder that many everyday foods we now take for granted have complicated and sometimes painful histories behind them."],
    ["The inventions that made the bar", "A handful of nineteenth-century inventions created modern chocolate.", "Chocolate as we know it is surprisingly recent. In 1828, the Dutch chemist Coenraad van Houten patented a press that squeezed much of the fat, called cocoa butter, out of ground cacao, leaving a powder that mixed easily into drinks. That cocoa butter turned out to be useful. In 1847, the English firm J. S. Fry and Sons combined cocoa powder, sugar and extra cocoa butter to make a mouldable paste, often credited as the first modern chocolate bar. In Switzerland, Daniel Peter used condensed milk developed by his neighbour Henri Nestle to create milk chocolate in the 1870s. Soon after, Rodolphe Lindt invented the conche, a machine that stirs chocolate for hours or days, making it far smoother than the gritty bars before it."],
    ["From pod to bean", "The flavour of chocolate starts with fermentation on the farm.", "Cacao trees grow large, rugby-ball-shaped pods directly from their trunks and thick branches. Inside each pod are dozens of beans surrounded by sweet, white pulp. After harvest, farmers scoop out the beans and pulp and pile them up, often covered with banana leaves, for several days. Yeasts and bacteria feast on the pulp, the pile heats up, and chemical changes inside the beans begin to develop chocolate flavour. Without fermentation, cacao would taste astringent and flat. The beans are then dried in the sun and shipped to chocolate makers. There, they are roasted, cracked and winnowed to remove the shells, leaving pieces called nibs. Grinding the nibs produces a thick liquid known as cocoa mass or cocoa liquor, though it contains no alcohol at all."],
    ["The secret of snap and shine", "Tempering controls how cocoa butter crystallises, giving chocolate its gloss and snap.", "Good chocolate breaks with a clean snap, shines like glass and melts smoothly on the tongue. The secret is cocoa butter, a fat that can solidify into several different crystal forms. Only one of them gives that perfect texture. Tempering is the process of heating, cooling and gently reheating chocolate so the right crystals form and spread. Chocolatiers do it by hand on marble slabs or with machines. If chocolate is poorly tempered, or if a bar gets warm and then cools again, you may see white or grey streaks on the surface. This is called bloom, and it is either cocoa butter or sugar that has moved to the surface. It looks unappealing and the texture suffers, but bloomed chocolate is still safe to eat."],
    ["Where cacao grows today", "Most of the world's cacao comes from small farms in West Africa.", "Cacao only thrives in a narrow band of hot, humid land near the equator. Although the tree comes from the Americas, today most of the world's cacao is grown in West Africa, with Cote d'Ivoire and Ghana together producing well over half of global supply. Much of it comes from millions of small family farms. Many cacao farmers earn very little, and investigations have repeatedly found child labour on farms in the region. Certification schemes and company programmes aim to improve conditions, with mixed results. Cacao is also vulnerable to plant diseases and changing weather. When harvests failed in West Africa in 2023 and 2024, cocoa prices shot to record highs, and shoppers around the world noticed chocolate becoming more expensive or bars getting smaller."],
    ["Chocolate, health and pets", "Dark chocolate contains interesting compounds, but it is still a treat.", "Cacao contains plant compounds called flavanols, which researchers have studied for possible benefits to blood vessels, and theobromine, a mild stimulant related to caffeine. These findings are often turned into headlines claiming chocolate is a health food. In reality, most chocolate is also high in sugar and fat, and processing can strip out many of the flavanols, so it is best enjoyed as a treat. This is general information, and healthdirect is a good place for advice about diet. One important warning concerns pets. Dogs break down theobromine far more slowly than people do, so chocolate can be poisonous to them, and dark chocolate and cooking chocolate are the most dangerous. If a dog eats chocolate, call a vet promptly, especially around Easter and Christmas."]
  ],
  [
    [0, "How did the Aztecs and Maya usually consume cacao?", ["As a solid sweet bar", "As a frothy, bitter drink", "As a baked biscuit", "Raw, straight from the pod"], 1, "In Mesoamerica cacao was ground and mixed with water, often with chilli or maize, and drunk as a foamy, bitter beverage."],
    [2, "What did Coenraad van Houten's 1828 press do?", ["Removed much of the cocoa butter to make cocoa powder", "Added milk to chocolate", "Froze chocolate into bars", "Fermented the beans faster"], 0, "His press squeezed out cocoa butter, leaving a powder that mixed easily into drinks."],
    [3, "Why are cacao beans fermented after harvest?", ["To make them alcoholic", "To remove all caffeine", "To develop chocolate flavour and reduce astringency", "To turn them white"], 2, "Fermentation by yeasts and bacteria triggers changes inside the beans that develop chocolate flavour."],
    [4, "What are the white streaks called bloom?", ["A sign of dangerous mould", "Added artificial colouring", "Milk powder clumping", "Cocoa butter or sugar that has moved to the surface"], 3, "Bloom is fat or sugar migrating to the surface; it affects texture but the chocolate is still safe."],
    [6, "Why is chocolate dangerous for dogs?", ["They process theobromine far more slowly than people", "They are allergic to sugar", "Cocoa butter blocks their stomach", "It contains alcohol"], 0, "Dogs break down theobromine slowly, so it can build up to toxic levels, especially from dark chocolate."]
  ]);

WB.L("tea-story", "food", "beginner", "Tea: one plant, a thousand cups", "Green, black, white and oolong tea all come from the same shrub. The differences lie in what happens to the leaves after picking, and the story of how tea spread reshaped empires.",
  [
    ["One plant, many teas", "All true tea comes from Camellia sinensis; processing creates the different types.", "It surprises many people that green tea, black tea, white tea and oolong all come from a single plant, an evergreen shrub called Camellia sinensis. The differences come from how the leaves are handled after picking. Drinks made from other plants, such as peppermint, chamomile or rooibos, are not technically tea at all. They are herbal infusions, sometimes called tisanes. There are two main varieties of the tea plant. The Chinese type has smaller leaves and copes with cooler mountain climates. The Assam type, found growing wild in north-east India, has bigger leaves and suits hot, wet lowlands, and it gives many strong black teas their malty character. Growing conditions, altitude, season and the skill of the tea maker all shape the final flavour in the cup."],
    ["Ancient beginnings in China", "Tea has been drunk in China for more than 2,000 years.", "Chinese legend credits the emperor Shennong with discovering tea when leaves blew into his pot of boiling water, but this is a myth. The hard evidence is still impressively old. Archaeologists found tea leaves buried in the tomb of a Han dynasty emperor who died in 141 BCE, showing tea was valued more than 2,000 years ago. At first it was often treated as a medicine. During the Tang dynasty, a writer named Lu Yu produced 'The Classic of Tea' in the eighth century, a detailed guide to growing, preparing and appreciating it, and tea became an art. Buddhist monks carried tea to Japan, where powdered green tea, now known as matcha, became the heart of the Japanese tea ceremony, with its careful, meditative rituals."],
    ["How Britain fell for tea", "Tea arrived in Europe in the 1600s and became a British obsession.", "Dutch traders brought tea to Europe in the early seventeenth century. In England it got a fashionable boost from Catherine of Braganza, the Portuguese princess who married King Charles II in 1662 and was already a tea drinker. At first tea was expensive and heavily taxed, so smuggling was widespread. As prices fell, tea spread from the upper classes to working people, and sugared tea became a staple of the British diet. Tea also carried politics. In 1773, protesters in Boston dumped a cargo of East India Company tea into the harbour in protest against British taxation, an event that fed into the American Revolution. Britain bought so much tea from China that it ran short of silver to pay for it, a problem that helped lead to the Opium Wars."],
    ["The great tea heist", "Britain broke China's control of tea by moving production to India.", "For centuries, China kept the secrets of growing and processing tea to itself, and Britain wanted its own supply. Two things changed the picture. In the 1820s and 1830s, the Assam variety of the tea plant was identified growing in north-east India, and the British began plantations there. Then, between 1848 and 1851, the Scottish botanist Robert Fortune travelled in China, sometimes in disguise, and smuggled out thousands of tea plants and seeds, along with knowledge of how tea was made and even skilled workers. Plantations spread across India and Ceylon, now Sri Lanka. They made tea cheap, but the plantation system relied on poorly paid labourers working in harsh conditions. Today India, Sri Lanka and Kenya are major exporters alongside China, which remains the biggest producer."],
    ["What oxidation does", "Black tea is oxidised, green tea is not, and oolong sits in between.", "Once tea leaves are picked, enzymes inside them start reacting with oxygen, much as a cut apple turns brown. This process is called oxidation, and controlling it is the key to tea making. For green tea, leaves are heated soon after picking, by steaming in Japan or pan-firing in China, which stops the enzymes and keeps the leaves green and grassy. For black tea, leaves are withered, then rolled or crushed to break their cells, and left to oxidise fully. Compounds called catechins turn into darker, richer molecules, giving black tea its colour, briskness and depth. Oolong is only partly oxidised, so it can range from flowery and light to toasty and dark. White tea is minimally processed, usually made from young buds and leaves that are simply withered and dried."],
    ["Brewing a better cup", "Water temperature and steeping time make a big difference.", "Because different teas are processed differently, they like to be brewed differently. Black tea generally suits water just off the boil and a steep of three to five minutes. Green tea is more delicate, and boiling water can scorch its flavour and pull out bitterness, so many people use water that has cooled to roughly 70 to 80 degrees Celsius and steep it for a shorter time. Oolongs often reward several short infusions from the same leaves. Tea contains caffeine, usually less per cup than coffee, along with an amino acid called L-theanine, which some research links to a calm, focused feeling. Tea bags spread widely in the twentieth century. A popular story says they began when a New York merchant sent samples in small silk bags, though the history is fuzzier."],
    ["Tea in Australia", "Tea was Australia's national drink long before the espresso arrived.", "For most of Australia's colonial and early national history, tea was the drink of choice. It travelled well, was easy to brew over a campfire, and the billy, a simple tin can for boiling water, became an icon of bush life, celebrated in songs and stories. Tea was included in rations for convicts, soldiers and workers, and for much of the twentieth century Australians drank far more tea than coffee. Although Australia imports most of its tea, small amounts are grown here, mainly in the wet tropics of far north Queensland. Tea drinking has since been overtaken by the cafe espresso, but it remains hugely popular, and a new wave of specialty tea shops, bubble tea bars and Chinese and Indian tea traditions has given it fresh life."]
  ],
  [
    [0, "Which of these is NOT made from the tea plant Camellia sinensis?", ["Oolong", "Green tea", "Peppermint tea", "White tea"], 2, "Peppermint is a herbal infusion; true teas all come from Camellia sinensis."],
    [1, "What is the oldest firm archaeological evidence of tea mentioned here?", ["Leaves in a Han dynasty emperor's tomb from about 141 BCE", "A Roman shipwreck cargo", "A painting in an Egyptian pyramid", "Seeds found in a Viking grave"], 0, "Tea leaves found in a Han emperor's tomb show tea was valued in China more than 2,000 years ago."],
    [3, "What did Robert Fortune do between 1848 and 1851?", ["Invented the tea bag", "Smuggled tea plants and know-how out of China", "Discovered tea growing in Kenya", "Founded the East India Company"], 1, "Fortune smuggled thousands of plants and seeds, plus processing knowledge, to help establish tea in India."],
    [4, "What mainly makes black tea different from green tea?", ["It comes from a different species", "It is grown in the dark", "It is always flavoured with bergamot", "Its leaves are allowed to oxidise fully"], 3, "Black tea leaves are oxidised fully, while green tea is heated early to stop oxidation."],
    [5, "Why do many people brew green tea with water below boiling?", ["Boiling water can scorch it and draw out bitterness", "Hot water removes all caffeine", "It makes the tea turn black", "Green tea will not dissolve in hot water"], 0, "Green tea is delicate, so slightly cooler water gives a smoother, less bitter cup."]
  ]);

WB.L("australian-bush-foods", "food", "beginner", "Bush foods: Australia's native pantry", "Long before supermarkets, this continent was a pantry of seeds, fruits, nuts and greens known intimately by First Nations peoples. Many are now finding their way onto restaurant menus.",
  [
    ["A continent of food knowledge", "First Nations peoples have used thousands of native foods over tens of thousands of years.", "When Europeans arrived in Australia, many assumed the land offered little to eat. They were badly mistaken. First Nations peoples had lived here for tens of thousands of years, and over that time they built up deep knowledge of thousands of plants and animals: which ones were edible, when they were ripe, how to prepare them and how to look after the places where they grew. That knowledge was passed down through generations and differed from Country to Country, from tropical rainforests to deserts and coasts. Food was tied to seasons, ceremony, law and trade. Today the term bush food, or bush tucker, covers native ingredients from this long tradition. Many are being rediscovered by chefs and home cooks, but they were never lost to the communities who knew them."],
    ["Grinding seeds into flour", "Grinding stones show Aboriginal people were processing seeds into flour very early.", "In dry inland Australia, seeds from native grasses, acacias and other plants were an important food. Collecting and processing them was skilled, laborious work. Seeds were winnowed, then ground between a large flat stone and a smaller hand stone, mixed with water and baked as cakes in hot ashes. Archaeologists have found grinding stones in Australia that are tens of thousands of years old, among the oldest evidence of seed grinding anywhere in the world. That suggests Aboriginal people were making a kind of bread long before farming began in the Middle East. Today, some growers and researchers are exploring native grains again because many of these grasses are perennial and adapted to Australian conditions, meaning they may need less water and fertiliser than imported crops."],
    ["Wattleseed and lemon myrtle", "Some native flavours are now used in kitchens around the world.", "Wattleseed comes from certain species of acacia, the wattles whose golden flowers are Australia's floral emblem. When roasted and ground, the seeds have a rich, nutty flavour often compared to coffee, chocolate and hazelnut, and they turn up in bread, ice cream and desserts. Only particular species are used for food, and some acacias are toxic, so this is not something to experiment with on your own. Lemon myrtle is a rainforest tree from Queensland whose leaves are packed with citral, the compound that makes lemons smell lemony. Many people find it more intensely lemony than lemon itself. It is used in teas, biscuits, marinades and cheesecakes. Pepperberry and pepperleaf from the Tasmanian mountain pepper add a hot, spicy bite that some cooks use instead of black pepper."],
    ["Fruits of the rainforest and desert", "Finger limes, quandongs and Kakadu plums are prized for flavour and nutrition.", "Australia has some remarkable native fruits. The finger lime grows wild in the rainforests near the border of New South Wales and Queensland. Slice one open and out tumble tiny pearls of juice, earning it the nickname 'citrus caviar', and chefs love it with seafood. The quandong, sometimes called the desert peach, grows in arid regions and has tart red flesh used in jams and pies, while its hard seed was used to make jewellery and games. The Kakadu plum, also known as gubinge, is a small green fruit from northern Australia that is famous for having one of the highest vitamin C contents of any fruit in the world. Aboriginal communities have harvested it for generations, and it is now sold in powders and skincare."],
    ["The macadamia's journey", "Australia's best-known native food crop was commercialised overseas first.", "The macadamia is the most commercially successful Australian native food. The trees come from the rainforests of south-east Queensland and northern New South Wales, where Aboriginal people had long eaten the nuts. Ironically, the first big macadamia industry grew in Hawaii in the twentieth century, using trees taken from Australia, and for decades many people assumed the nut was Hawaiian. Australia later built its own large industry and is now one of the world's leading producers. Genetic research suggests that most Hawaiian commercial trees may descend from a very small number of Queensland trees, possibly even a single one. That narrow genetic base makes the crop more vulnerable to disease, so scientists are working to protect the remaining wild macadamias, several species of which are now threatened."],
    ["Greens, nuts and gatherings", "Some bush foods were the centre of great seasonal gatherings.", "Warrigal greens, a native leafy plant also called New Zealand spinach, grow along coasts and were eaten by Captain Cook's crew to ward off scurvy. They contain oxalates, so they should be blanched briefly before eating, much like ordinary spinach is sometimes treated. In the Bunya Mountains of Queensland, huge bunya pines drop enormous cones packed with starchy nuts. In years of heavy crops, many Aboriginal groups travelled long distances to gather there for weeks of feasting, ceremony, trade, marriage arrangements and settling disputes. These bunya gatherings show how food could bring together people from across a vast region. Today bunya nuts are eaten boiled or roasted, and they have a texture somewhere between a chestnut and a potato, with a mild, earthy flavour."],
    ["Respect and opportunity", "Growing interest in bush foods raises questions about who benefits.", "The native food industry has grown quickly, but research has found that only a small share of it is owned or led by First Nations people, even though it rests on their knowledge. Many communities and organisations are working to change that, through Aboriginal-owned businesses, fair partnerships and protections for traditional knowledge. When buying bush foods, you can look for products that name the communities involved or come from Indigenous-owned enterprises. A word of caution: foraging for wild plants without expert knowledge is risky, because some native plants are toxic or need careful preparation. Buy from reputable suppliers, and learn from First Nations guides where possible. Try a pinch of wattleseed in pancakes or lemon myrtle in a cup of tea for an easy first taste."]
  ],
  [
    [1, "What do ancient grinding stones in Australia suggest?", ["Aboriginal people ground seeds into flour very early", "Wheat was grown in Australia 50,000 years ago", "Stones were only used for weapons", "Bread came to Australia with the First Fleet"], 0, "Grinding stones tens of thousands of years old are among the oldest evidence of seed grinding anywhere."],
    [2, "Which compound gives lemon myrtle its strong lemony scent?", ["Capsaicin", "Caffeine", "Citral", "Glutamate"], 2, "Lemon myrtle leaves are rich in citral, the compound responsible for lemon aroma."],
    [3, "Which native fruit is famous for an extremely high vitamin C content?", ["Finger lime", "Quandong", "Bunya nut", "Kakadu plum"], 3, "The Kakadu plum, or gubinge, has one of the highest vitamin C levels of any fruit."],
    [4, "Where did the first large commercial macadamia industry develop?", ["Hawaii", "Brazil", "South Africa", "New Zealand"], 0, "The industry first boomed in Hawaii using trees taken from Australia."],
    [6, "What is sensible advice for trying bush foods?", ["Forage any berry that looks ripe", "Buy from reputable suppliers rather than foraging unknown plants", "Avoid all native plants entirely", "Eat acacia seeds from any wattle tree"], 1, "Some native plants are toxic or need preparation, so buy from reputable sources or learn from experts."]
  ]);

WB.L("fermentation-microbes", "food", "intermediate", "Fermentation: cooking with microbes", "Bread, cheese, yoghurt, soy sauce, kimchi, vinegar and Vegemite all depend on tiny living helpers. Fermentation is one of humanity's oldest and cleverest food technologies.",
  [
    ["Controlled rotting", "Fermentation is microbes transforming food in ways we find useful.", "Leave a bowl of fruit on the bench and microbes will eventually spoil it. Fermentation is what happens when we steer that process instead. By controlling things like salt, temperature, moisture and oxygen, cooks encourage helpful microbes and keep harmful ones out. The helpful microbes eat sugars and other nutrients in food and produce by-products such as alcohol, carbon dioxide and acids. Those by-products change flavour and texture, and often make food last longer. People fermented food for thousands of years without knowing microbes existed. Chemical traces in pottery from Jiahu in China suggest people there brewed a drink from rice, honey and fruit about 9,000 years ago. In the 1850s and 1860s, Louis Pasteur showed that living microorganisms were responsible for fermentation, transforming our understanding of food and disease."],
    ["Yeast: bubbles and booze", "Yeasts turn sugar into alcohol and carbon dioxide.", "The best-known fermenting microbe is yeast, a single-celled fungus. When yeast feeds on sugar without much oxygen around, it produces two main by-products: alcohol and carbon dioxide gas. Brewers and winemakers want the alcohol. In wine, yeast ferments the sugars in grape juice. In beer, grains such as barley are first malted and mashed so their starches break down into sugars that yeast can use. Bakers want the gas. In bread dough, carbon dioxide bubbles get trapped in a stretchy network of gluten, making the loaf rise, and the small amount of alcohol produced bakes off in the oven. Sourdough uses a starter, a living culture of wild yeasts and bacteria, which gives a tangier flavour than bread made with commercial baker's yeast."],
    ["Lactic acid bacteria", "Bacteria that make lactic acid give us yoghurt, sauerkraut and kimchi.", "Lactic acid bacteria are the quiet workhorses of fermentation. They convert sugars into lactic acid, which makes food tangy and creates an acidic environment where many spoilage and disease-causing microbes struggle to survive. Yoghurt is made by adding specific bacteria to warm milk. As they produce acid, milk proteins tighten and the milk thickens into a soft gel. Sauerkraut and kimchi rely on bacteria that live naturally on vegetables. Cabbage is salted, which draws out water and favours salt-tolerant lactic acid bacteria over other microbes. Over days or weeks, the vegetables sour and soften. Kimchi in its familiar red form is a newer invention than many people assume, because chillies only reached Korea from the Americas a few centuries ago, after European traders spread them across Asia."],
    ["Moulds and koji", "Moulds such as koji are behind soy sauce, miso and sake.", "Not all fermenting microbes are yeasts or bacteria. Some are moulds. In East Asian cooking, the most important is koji, a mould with the scientific name Aspergillus oryzae. Grown on steamed rice, soybeans or barley, koji produces powerful enzymes that break starches into sugars and proteins into amino acids. That makes it the starting point for soy sauce, miso, mirin and sake. Soy sauce is traditionally made by mixing koji-covered soybeans and wheat with brine and leaving the mixture to ferment for months. The amino acids released, especially glutamate, give these foods their deep savoury taste, often called umami. In Europe, moulds also play a role: blue cheeses such as Roquefort get their veins from Penicillium moulds, and white rinds on brie and camembert come from moulds too."],
    ["Cheese and vinegar", "Cheese and vinegar show how fermentation can be layered in steps.", "Many fermented foods involve more than one step and more than one microbe. Cheese begins when milk is soured by bacteria and then curdled, usually with rennet, an enzyme that makes milk proteins clump into curds. The liquid whey is drained off, and the curds are salted, pressed and often aged. During ageing, bacteria and moulds slowly break down fats and proteins, creating the huge range of cheese flavours and textures. Vinegar is a two-stage fermentation. First, yeast turns sugars in fruit or grain into alcohol, making wine, cider or beer. Then acetic acid bacteria, which need oxygen, convert that alcohol into acetic acid. The word vinegar comes from the French for 'sour wine', which is a pretty accurate description of what it is."],
    ["Preservation and voyages", "Before refrigeration, fermentation helped food last through winters and voyages.", "Before refrigerators, fermentation was one of the most important ways to stop food from spoiling. Acid, alcohol and salt all make life difficult for harmful microbes, so fermented foods could be stored for months. Communities relied on them to get through winters and lean seasons, and sailors relied on them at sea. On his voyages in the eighteenth century, including the one that reached Australia's east coast in 1770, James Cook carried large quantities of sauerkraut, partly in the hope of preventing scurvy. Fermentation also turns waste into food. Vegemite, created in Melbourne in the early 1920s by the chemist Cyril Callister, is made from spent brewer's yeast left over from beer making, which is mixed with salt and vegetable extracts and turned into the famous dark spread."],
    ["Fermenting at home", "Home fermenting is rewarding, but safety depends on following tested methods.", "Fermenting at home has become popular, and sauerkraut, yoghurt, kombucha and sourdough are good places to start. The general principles are simple: use clean equipment, get the salt or acidity right, keep air out when the recipe says to, and trust your senses. Healthy ferments smell sour, yeasty or pleasantly funky. Fuzzy coloured mould, slime or a rotten smell are signs to throw a batch out. Low-acid foods stored without oxygen can carry a risk of botulism, a rare but dangerous illness, so follow reliable, tested recipes rather than improvising. Fermented foods are often promoted for gut health, and some contain live microbes, but the evidence for specific benefits is still developing. This is general information, so see Food Standards Australia New Zealand and healthdirect for more."]
  ],
  [
    [0, "Who showed in the mid-1800s that living microbes cause fermentation?", ["Isaac Newton", "Louis Pasteur", "Charles Darwin", "Marie Curie"], 1, "Pasteur's work in the 1850s and 1860s showed microorganisms were responsible for fermentation."],
    [1, "In bread making, which product of yeast fermentation makes the dough rise?", ["Lactic acid", "Acetic acid", "Glutamate", "Carbon dioxide"], 3, "Carbon dioxide bubbles get trapped in the gluten network and make the dough rise."],
    [2, "Why is salt added when making sauerkraut?", ["To favour salt-tolerant lactic acid bacteria", "To make it alcoholic", "To kill all bacteria", "To turn the cabbage red"], 0, "Salt draws out water and gives salt-tolerant lactic acid bacteria an advantage over other microbes."],
    [3, "Koji, used for soy sauce and miso, is what kind of organism?", ["A bacterium", "A yeast", "A mould", "A virus"], 2, "Koji is the mould Aspergillus oryzae, which produces enzymes that break down starches and proteins."],
    [5, "What is Vegemite made from?", ["Fermented soybeans", "Spent brewer's yeast", "Roasted wattleseed", "Aged cheese"], 1, "Vegemite was developed in the 1920s using spent yeast left over from brewing beer."]
  ]);

WB.L("spice-trade", "food", "intermediate", "The spice trade: flavours that built empires", "Pepper, cloves and nutmeg were once worth fighting and dying for. The hunt for spices sent ships around the world, made fortunes and caused terrible violence.",
  [
    ["Where the spices grew", "Many of the most valuable spices came from small parts of South and South-East Asia.", "Today you can buy a jar of nutmeg for a few dollars, but for most of history spices were luxury goods, partly because they grew in so few places. Black pepper came from the Malabar Coast of south-west India, in what is now Kerala. True cinnamon came from Sri Lanka. Cloves grew on a handful of islands in the northern Moluccas, now part of Indonesia, and nutmeg and its lacy covering, mace, came almost entirely from the tiny Banda Islands. These goods passed through many hands, carried by Indian, Arab, Malay, Chinese and other merchants over sea and land. Each trader added a markup, so by the time spices reached a European or Middle Eastern market they could be astonishingly expensive, and their origins were often shrouded in tall tales."],
    ["Rome's appetite for pepper", "The ancient Romans imported huge quantities of Indian pepper.", "The spice trade is ancient. Romans developed a serious taste for black pepper, and merchants learned to use the monsoon winds to sail between Egypt's Red Sea ports and India, crossing the Arabian Sea in weeks. Roman coins have been found in southern India, evidence of the trade's scale. Roman recipes from a cookbook attributed to Apicius use pepper constantly. According to ancient accounts, when the Gothic leader Alaric besieged Rome in 408, his demands included thousands of pounds of pepper along with gold and silver. A popular modern belief holds that medieval Europeans used spices to hide the taste of rotting meat. Most historians reject this, pointing out that spices often cost far more than fresh meat, and that they were prized for flavour, medicine and status."],
    ["The race for a sea route", "The desire to reach spice markets directly drove European voyages of exploration.", "In the medieval period, much of the spice trade into Europe flowed through Middle Eastern routes and then through Italian cities such as Venice, which grew rich as middlemen. Other European powers wanted to cut out those middlemen. Portugal pushed down the coast of Africa, and in 1498 Vasco da Gama rounded the Cape of Good Hope and reached Calicut in India by sea. Christopher Columbus, sponsored by Spain, sailed west in 1492 hoping to reach Asia. He reached the Caribbean instead, where he encountered chillies and allspice, and he called the chillies 'peppers', a name that has confused people ever since. Ferdinand Magellan's expedition, which completed the first circumnavigation of the globe in 1522, was also largely a search for a route to the spice islands."],
    ["Monopolies and massacres", "The Dutch East India Company used extreme violence to control nutmeg and cloves.", "In the seventeenth century, the Dutch East India Company, known by its initials VOC, set out to control the most valuable spices completely. Its methods were brutal. In 1621, forces under the governor-general Jan Pieterszoon Coen conquered the Banda Islands, the world's only real source of nutmeg. Most of the Bandanese population was killed, enslaved or driven away, and the islands were turned into plantations worked by enslaved people. The Dutch also restricted clove trees to particular islands and destroyed trees elsewhere to keep prices high. When England and the Netherlands made peace in 1667, the Dutch kept Run, a tiny nutmeg island the English had held, while England kept New Amsterdam, which it had seized and renamed New York. In hindsight, the deal looks rather different."],
    ["Smuggled seedlings break the monopoly", "Smuggled plants and changing tastes made spices cheap and ordinary.", "Monopolies over living plants are hard to keep forever. In the 1770s, a French official named Pierre Poivre organised expeditions that smuggled clove and nutmeg seedlings out of the Dutch-controlled islands and planted them on Mauritius and other French colonies. During the Napoleonic Wars, the British also took spice plants and spread them to places such as Ceylon and the Caribbean island of Grenada, which still features a nutmeg on its flag. Clove growing became a major industry on Zanzibar, worked by enslaved people. As spices were grown in more places, prices fell. At the same time, European tastes shifted towards sugar, coffee, tea and chocolate. Spices that had once been worth a fortune became ordinary kitchen staples, sold cheaply in jars all over the world."],
    ["Saffron and vanilla", "The priciest spices today are labour-intensive rather than rare.", "Some spices are still expensive, mostly because they take so much work. Saffron, usually the most expensive spice by weight, is made from the thread-like stigmas of a crocus flower. Each flower has only three, and they must be picked by hand, so a single kilogram requires well over a hundred thousand flowers. Iran grows most of the world's saffron, and small amounts are grown in Tasmania. Vanilla, the cured pods of a climbing orchid from Mexico, is another luxury. Outside Mexico, its natural pollinators are missing, so for a long time plants grown elsewhere produced few pods. In 1841, Edmond Albius, a twelve-year-old enslaved boy on the island of Reunion, worked out a quick method for hand-pollinating vanilla flowers, a technique still used on plantations today."],
    ["The legacy in your kitchen", "The spice trade reshaped cuisines and left a lasting, complicated legacy.", "The spice trade did more than move goods. It moved plants, people and ideas, and it reshaped cooking everywhere. Chillies from the Americas became central to Indian, Thai, Sichuan and Korean food within a few centuries. Black pepper became so common in Western kitchens that it sits beside salt on almost every table. Words travelled too: the word pepper ultimately traces back to a Sanskrit word for long pepper. The trade also left a darker legacy of colonial conquest, monopoly, slavery and environmental change in the places where spices grew. Next time you grind pepper over your dinner or sprinkle cinnamon on toast, it is worth remembering that these ordinary flavours once drove some of the biggest and most violent upheavals in world history."]
  ],
  [
    [0, "Where did nutmeg and mace come from almost exclusively?", ["The Banda Islands", "Sri Lanka", "Madagascar", "The Malabar Coast"], 0, "Nutmeg and mace came almost entirely from the tiny Banda Islands in present-day Indonesia."],
    [1, "Why do most historians reject the idea that spices hid rotten meat?", ["Spices were banned in medieval Europe", "Rotten meat was never eaten", "Spices often cost far more than fresh meat", "Spices were only used in drinks"], 2, "Spices were expensive status goods, so using them to rescue spoiled meat makes little sense."],
    [2, "What did Columbus call the chillies he found in the Caribbean?", ["Spices", "Peppers", "Cloves", "Nutmegs"], 1, "Columbus called chillies peppers, a name that has caused confusion ever since."],
    [3, "What happened in the Banda Islands in 1621?", ["The islands became independent", "Nutmeg trees were first planted there", "Portugal and Spain divided them by treaty", "Dutch forces conquered them and most of the population was killed, enslaved or driven away"], 3, "Under Jan Pieterszoon Coen, the VOC conquered Banda in a brutal campaign to control nutmeg."],
    [5, "What did Edmond Albius discover in 1841?", ["How to grow saffron in Tasmania", "A quick way to hand-pollinate vanilla flowers", "The source of cinnamon", "How to dry pepper berries"], 1, "Albius, an enslaved twelve-year-old on Reunion, devised the hand-pollination method still used for vanilla."]
  ]);

WB.L("umami-msg", "food", "intermediate", "Umami and the MSG story", "A Japanese chemist tasting his soup discovered a fifth basic taste. The seasoning he created went on to become one of the most misunderstood ingredients in the world.",
  [
    ["A chemist and his soup", "In 1908, Kikunae Ikeda identified the taste he called umami.", "In 1908, the Japanese chemist Kikunae Ikeda was enjoying a bowl of dashi, a broth made with kombu seaweed, when he wondered about its distinctive savoury taste. It was not sweet, sour, salty or bitter, the four tastes scientists recognised at the time. Ikeda set out to find what caused it. Working with large quantities of kombu, he isolated crystals of glutamic acid, an amino acid, and showed that its salts carried the savoury taste. He named the sensation umami, from a Japanese word for delicious, roughly meaning 'savoury deliciousness'. Ikeda then worked out how to produce a stable, easy-to-use seasoning based on his discovery: monosodium glutamate, or MSG. Together with a business partner, he launched it commercially in Japan in 1909 under the brand name Ajinomoto."],
    ["Glutamate is everywhere", "Glutamate occurs naturally in many foods, especially ripe, aged and fermented ones.", "MSG sounds like an industrial invention, but glutamate is one of the most common amino acids in nature. Our bodies make it, and it is found in many foods, including human breast milk. Usually glutamate is locked up in proteins, where we cannot taste it. When proteins break down, through ripening, ageing, drying, cooking or fermenting, free glutamate is released and umami appears. That explains why ripe tomatoes taste more savoury than green ones, why parmesan and other aged cheeses are so moreish, and why soy sauce, fish sauce, miso, mushrooms, anchovies and cured meats are prized for adding depth. Vegemite and Marmite, made from yeast extract, are also rich in glutamate. Cooks were using umami for thousands of years before anyone had a name for it."],
    ["The flavour boosters", "Certain compounds team up with glutamate to multiply umami.", "After Ikeda, other Japanese scientists found more umami substances. In 1913 his student Shintaro Kodama identified inosinate in dried bonito flakes, and in the 1950s Akira Kuninaka identified guanylate, which is abundant in dried shiitake mushrooms. These compounds, called nucleotides, have an extraordinary property. When combined with glutamate, they do not simply add to the umami taste, they multiply it, so the combination tastes far stronger than either alone. Traditional cooking had stumbled on this long before the chemistry was understood. Japanese dashi combines kombu, rich in glutamate, with bonito flakes, rich in inosinate. Western cooks do something similar when they pair tomatoes or parmesan with meat, or add anchovies to a beef stew. This synergy is one reason some dish combinations feel so deeply satisfying."],
    ["A fifth taste is confirmed", "Scientists eventually found taste receptors dedicated to umami.", "For decades, many Western scientists doubted that umami was a separate taste. They argued it was just a blend of other tastes or an effect of smell. The debate shifted in the early 2000s, when researchers identified taste receptors on the tongue that respond specifically to glutamate, giving umami a clear biological basis. Today it is widely accepted as the fifth basic taste alongside sweet, sour, salty and bitter. Why would we evolve to detect it? A common explanation is that umami signals protein. Since glutamate is released when protein-rich foods are cooked or aged, a taste that rewards it could steer us towards nourishing food. Sweetness, by comparison, signals energy from sugars, while bitterness may warn of toxins and sourness of unripe or spoiled food."],
    ["How a rumour began", "A 1968 letter sparked decades of fear about MSG.", "For its first half-century, MSG was used widely with few complaints. In 1968, a doctor wrote a letter to a prominent medical journal describing symptoms such as numbness and palpitations after eating at Chinese restaurants in the United States, wondering whether cooking wine, sodium or MSG might be to blame. The letter prompted a flood of responses and the term 'Chinese restaurant syndrome' spread through newspapers. MSG became a villain, and restaurants began displaying 'no MSG' signs. Many people now see this panic as tinged with prejudice, because ingredients such as parmesan, tomatoes and stock were rarely blamed, despite their natural glutamate. The idea stuck so firmly that many people still report avoiding MSG today, often without knowing that much of their favourite food is naturally rich in glutamate."],
    ["What the evidence says", "Food regulators consider MSG safe for the general population.", "Since the 1970s, researchers have run many studies on MSG, including double-blind trials in which neither participants nor researchers know who has eaten MSG and who has had a placebo. These studies have generally failed to find consistent reactions at the amounts used in normal food. Some people report mild, short-lived symptoms after large doses taken without food, but the evidence is weak. Food Standards Australia New Zealand considers MSG safe for the general population. In Australia, MSG appears on ingredient lists by name or as flavour enhancer 621. A product labelled 'no added MSG' may still contain plenty of natural glutamate from ingredients like yeast extract or tomato. This is general information, so anyone with concerns about reactions to food should speak with a doctor."],
    ["Using umami in your cooking", "A little umami can add depth and even help reduce salt.", "MSG today is mostly made by fermentation: bacteria feed on sugars from crops such as sugarcane, corn or cassava and produce glutamate, which is purified and crystallised. It looks like fine white salt and has a mild taste on its own, but it lifts savoury dishes such as soups, stir-fries, stews and dressings. MSG contains roughly a third as much sodium as table salt, so swapping some salt for a little MSG can reduce sodium in a dish without losing flavour. You do not need the crystals to cook with umami, though. A splash of soy or fish sauce, a spoonful of tomato paste, a grating of parmesan, a few dried mushrooms or a dab of Vegemite in gravy can all deepen flavour in exactly the same way."]
  ],
  [
    [0, "What was Kikunae Ikeda eating when he set out to identify umami?", ["Parmesan cheese", "Dashi broth made with kombu seaweed", "Tomato soup", "Grilled beef"], 1, "Ikeda investigated the savoury taste of kombu dashi and isolated glutamate from the seaweed."],
    [1, "Why do ripe tomatoes and aged cheeses taste strongly of umami?", ["They contain added MSG", "They are high in sugar", "Breaking down proteins releases free glutamate", "They contain capsaicin"], 2, "Ripening and ageing break down proteins, releasing free glutamate that we can taste."],
    [2, "What happens when glutamate is combined with nucleotides like inosinate?", ["The umami taste is multiplied", "The flavours cancel out", "The food becomes bitter", "The food turns sweet"], 0, "Glutamate and nucleotides work synergistically, making umami far stronger than either alone."],
    [3, "What firmly established umami as a basic taste in the early 2000s?", ["A new dictionary definition", "Surveys of chefs", "A Japanese government decree", "The discovery of taste receptors that respond to glutamate"], 3, "Identifying dedicated receptors gave umami a clear biological basis."],
    [6, "How does MSG's sodium content compare with table salt?", ["It has about three times as much", "It has roughly a third as much", "It has none at all", "It has exactly the same amount"], 1, "MSG contains roughly a third of the sodium of table salt, so it can help cut salt."]
  ]);

WB.L("chilli-heat", "food", "advanced", "Why chillies burn: the science of heat", "Chilli heat is not a taste at all. It is a clever chemical trick that fools your pain sensors, and the story of how it conquered the world's kitchens is just as surprising.",
  [
    ["From Mexico to the world", "Chillies are American plants that spread across the globe after 1492.", "It is hard to imagine Thai, Indian, Sichuan or Korean food without chillies, yet every one of these cuisines learned to use them only in the last five centuries. Chillies belong to the genus Capsicum and originated in the Americas. They were domesticated in Mexico thousands of years ago and were a central part of cooking across the region. After Columbus's voyages, Spanish and especially Portuguese traders carried chillies around the world. Unlike many crops, chillies were easy to grow from seed, thrived in warm climates and offered a cheap, intense flavour, so they spread with remarkable speed. Within about a century they were being grown in India, Africa and South-East Asia, and local cooks soon made them their own, often replacing or supplementing black pepper."],
    ["Capsaicin and the TRPV1 receptor", "Capsaicin triggers the same nerve receptor that detects painful heat.", "The burn of chilli comes mainly from a group of compounds called capsaicinoids, the most important being capsaicin. Capsaicin is not detected by taste buds. Instead it binds to a protein on pain-sensing nerve endings called TRPV1. This receptor's normal job is to detect dangerous heat, and it switches on at temperatures above roughly 43 degrees Celsius. When capsaicin latches on, it flips the same switch, so your brain receives the message that your mouth is being burned, even though the temperature has not changed. That is why chilli can make you sweat, flush and feel genuinely hot. Work on how TRPV1 and related receptors sense temperature and pain earned the American scientist David Julius a share of the 2021 Nobel Prize in Physiology or Medicine."],
    ["Why chillies make capsaicin", "Capsaicin seems to deter mammals and fungi while sparing seed-spreading birds.", "Why would a plant produce something that burns? One leading explanation is called directed deterrence. Mammals that chew chilli fruits tend to crush the seeds, while birds swallow them whole and spread them far and wide in their droppings. Crucially, birds' version of the TRPV1 receptor is insensitive to capsaicin, so they can eat the hottest chillies without discomfort. Capsaicin therefore discourages the animals that destroy seeds while allowing the ones that disperse them. There is also evidence that capsaicin protects fruits from fungi. Studies of wild chillies in Bolivia found that plants in wetter areas, where fungal attack was more common, tended to be hotter. As with many evolutionary explanations, scientists continue to debate the relative importance of these factors, and both may play a part."],
    ["Measuring heat", "The Scoville scale began with human tasters and now uses lab instruments.", "In 1912, the American pharmacist Wilbur Scoville devised a way to compare chilli heat. He dissolved an extract of dried chilli in alcohol, diluted it in sugar water and asked a panel of tasters to report when they could no longer detect any heat. The more dilution required, the hotter the chilli, and the result was expressed in what became known as Scoville heat units. A bell pepper scores zero, a jalapeno typically scores a few thousand, and the hottest varieties bred by enthusiasts now exceed two million. Because human tasters vary and tire quickly, modern labs instead use a technique called high-performance liquid chromatography to measure capsaicinoid concentrations directly. The results are then converted into Scoville units, so the familiar scale survives even though its original method has largely been retired."],
    ["Where the heat hides", "Capsaicin is concentrated in the pale pith, and it dissolves in fat, not water.", "Many people believe the seeds are the hottest part of a chilli. In fact, capsaicin is made mostly in the pale, spongy tissue called the placenta, the ribs inside the fruit to which the seeds are attached. Seeds can taste hot because they sit pressed against it. Removing the ribs and seeds therefore tames a chilli considerably. Chemistry also explains why water does little to cool a burning mouth. Capsaicin is an oily molecule that dissolves poorly in water but well in fats and alcohol. Gulping water mostly spreads it around. Dairy products such as milk and yoghurt help, probably because their fat and a protein called casein help carry capsaicin away. Starchy foods like rice or bread can also provide some relief by physically mopping up the oil."],
    ["Other kinds of fire", "Wasabi, mustard, black pepper and Sichuan pepper each trigger different sensations.", "Not every pungent spice works the way chilli does. Black pepper gets its bite from piperine, which also activates TRPV1, along with a related receptor, though its burn is milder. Wasabi, horseradish and mustard rely on compounds called isothiocyanates, which are volatile, so the heat rushes up the nose and fades quickly. They activate a different receptor, TRPA1, which responds to irritants such as the fumes from cut onions. Sichuan pepper, from the dried husks of a prickly ash shrub unrelated to chillies or black pepper, does something stranger still. A compound called hydroxy-alpha-sanshool produces a tingling, buzzing numbness that researchers have compared to a mild vibration on the lips. Sichuan cooking combines this numbing sensation with chilli heat in a famous pairing called mala, meaning numbing and spicy."],
    ["Why we love the pain", "Chilli lovers may enjoy a safe thrill, and tolerance builds with exposure.", "Humans are one of very few animals that seek out chilli's burn on purpose. One idea, developed by the psychologist Paul Rozin, is called benign masochism: we enjoy experiences that feel threatening while our brain knows we are actually safe, much like riding a roller coaster or watching a horror film. Pain may also trigger the release of endorphins, adding to the pleasure, although how much this contributes is uncertain. Tolerance is real. Repeated exposure to capsaicin makes the nerve endings less responsive for a while, which is why regular chilli eaters can handle more heat. Capsaicin is also the active ingredient in some pain-relief creams and in pepper spray. Handle very hot chillies with gloves, avoid touching your eyes, and take extreme chilli challenges cautiously."]
  ],
  [
    [0, "Where did chillies originally come from?", ["India", "Thailand", "The Americas", "China"], 2, "Chillies are native to the Americas and spread worldwide after Columbus's voyages."],
    [1, "Which receptor does capsaicin activate to create the sensation of heat?", ["TRPV1", "The sweet taste receptor", "TRPA1 only", "The umami receptor"], 0, "Capsaicin binds TRPV1, the receptor that normally detects painful heat above about 43 degrees Celsius."],
    [2, "Why can birds eat very hot chillies without discomfort?", ["They have no taste buds", "They only eat the seeds", "Their stomach acid destroys capsaicin instantly", "Their version of TRPV1 is insensitive to capsaicin"], 3, "Birds' TRPV1 does not respond to capsaicin, so they eat chillies and spread the seeds intact."],
    [4, "Why does milk soothe chilli burn better than water?", ["Milk is colder than water", "Capsaicin dissolves in fat and is carried away by milk's fat and casein", "Milk neutralises capsaicin chemically", "Water makes capsaicin stronger"], 1, "Capsaicin dissolves poorly in water but is helped away by fats and the protein casein in dairy."],
    [5, "Which compound produces the tingling numbness of Sichuan pepper?", ["Piperine", "Capsaicin", "Hydroxy-alpha-sanshool", "Isothiocyanate"], 2, "Hydroxy-alpha-sanshool causes the buzzing, numbing sensation unique to Sichuan pepper."]
  ]);
