/* WISEBYTE LESSONS · Planet Earth and Climate */
WB.L("earth-structure", "geography", "beginner", "Inside the Earth",
  "Nobody has ever drilled even halfway through the crust, yet we know the Earth has a solid metal heart as hot as the surface of the Sun. Here's how.",
  [
    ["A layered planet", "Earth is layered like a peach: a thin crust, a thick rocky mantle and a metal core.",
      "The Earth has a radius of about 6,371 kilometres, and it is built in layers. On the outside is the crust, a thin rocky skin. Below that is the mantle, a vast layer of hot rock that makes up roughly 84% of the planet's volume. At the centre is the core, made mostly of iron and nickel, split into a liquid outer core and a solid inner core. A useful picture is a peach: the skin is the crust, the flesh is the mantle and the stone is the core. The layers formed early in Earth's history, when heavy metals sank towards the centre and lighter rock floated to the top."],
    ["The crust", "Oceanic crust is thin and dense; continental crust is thicker, lighter and much older.",
      "There are two kinds of crust. Oceanic crust, under the sea floor, is usually only 5 to 10 kilometres thick and made of dense, dark basalt. It is constantly created at mid-ocean ridges and destroyed where it sinks back into the mantle, so almost none of it is older than about 200 million years. Continental crust is thicker, typically 30 to 50 kilometres and up to about 70 kilometres under big mountain ranges like the Himalayas. It is lighter, so it floats higher and rarely sinks. That is why continents hold the oldest rocks on Earth, including zircon crystals from the Jack Hills in Western Australia dated to about 4.4 billion years old."],
    ["The mantle", "The mantle is solid rock that flows very slowly, carrying heat up from the core.",
      "The mantle reaches down to about 2,900 kilometres. It is often drawn as a sea of molten lava, but it is almost entirely solid. Under enormous heat and pressure, though, this solid rock can creep and flow very slowly, a few centimetres a year, rather like a glacier or very stiff toffee. Hotter rock rises and cooler rock sinks in slow convection currents that carry heat out of the planet. The top of the mantle and the crust together form the rigid lithosphere, which is broken into tectonic plates. These plates ride on a softer layer beneath, called the asthenosphere, and the mantle's motion helps drive them."],
    ["The core", "The outer core is liquid iron and nickel; the inner core is solid, at around 5,000 to 6,000 degrees.",
      "The core begins about 2,900 kilometres down. The outer core, roughly 2,200 kilometres thick, is liquid metal, mostly iron with some nickel and lighter elements. The inner core is a solid ball about 1,220 kilometres in radius, roughly two-thirds the size of the Moon. Its temperature is estimated at around 5,000 to 6,000 degrees Celsius, similar to the surface of the Sun. It stays solid despite that heat because the pressure at the centre, millions of times the air pressure at the surface, squeezes the atoms together. The inner core is slowly growing as the planet cools and the liquid metal around it freezes onto it."],
    ["How we know: seismic waves", "Earthquake waves bend, speed up and vanish as they pass through different layers, revealing the interior.",
      "The deepest hole ever drilled, the Kola Superdeep Borehole in Russia, stopped at about 12 kilometres, a tiny scratch. Almost everything we know about the deep Earth comes from earthquakes. Quakes send seismic waves through the planet. P-waves are push-pull waves that travel through solids and liquids. S-waves are side-to-side waves that cannot pass through liquid. Seismometers around the world record when and where each type arrives. Waves speed up, slow down and bend at boundaries between layers. In 1909 Andrija Mohorovičić found the base of the crust, now called the Moho, and in the early 1900s others located the core and measured its depth."],
    ["The shadow zone and Inge Lehmann", "S-waves never cross the core, proving it is liquid; Inge Lehmann discovered the solid inner core in 1936.",
      "After a large earthquake, there is a broad region on the far side of the planet where S-waves never arrive, called the shadow zone. Since S-waves cannot travel through liquid, this showed that the outer core must be molten. But faint P-waves were turning up in places that a simple liquid core could not explain. In 1936 Danish seismologist Inge Lehmann studied these puzzling signals and proposed that a solid inner core was reflecting them. Her idea was confirmed as instruments improved. Other clues fit too: Earth's average density is about 5.5 times that of water, far denser than surface rocks, so heavy metal must lie deep inside."],
    ["The magnetic field", "Churning liquid iron in the outer core generates Earth's magnetic field, which shields us from the solar wind.",
      "The swirling liquid iron in the outer core acts like a giant dynamo. As the electrically conducting metal moves, driven by heat and Earth's rotation, it generates electric currents, which in turn produce a magnetic field. This field is why a compass points roughly north. It also extends far into space, deflecting most of the solar wind, a stream of charged particles from the Sun, so most of it never reaches the lower atmosphere. Some particles are funnelled towards the poles, where they make the upper atmosphere glow. In the south this is the aurora australis, sometimes visible from Tasmania and southern Victoria."],
    ["Wandering and flipping poles", "The magnetic poles drift constantly, and the whole field has reversed many times; the last full flip was about 780,000 years ago.",
      "Earth's magnetic field is not fixed. The magnetic poles wander, and the north magnetic pole has moved hundreds of kilometres over the past century, which is why navigation charts and phone compasses need regular updates. Over geological time, the whole field has flipped many times, so a compass would once have pointed south. We know because volcanic rock records the field's direction as it cools. The last full reversal happened about 780,000 years ago. Reversals are irregular and take thousands of years, and there is no good evidence they caused mass extinctions. Next time you use a compass, remember that it is responding to molten metal nearly 3,000 kilometres beneath your feet."]
  ],
  [
    [3, "Why does the inner core stay solid despite temperatures similar to the Sun's surface?", ["Immense pressure squeezes the atoms together", "It is made of rock, not metal", "It is cooled by the oceans", "The magnetic field freezes it"], 0, "The pressure at the centre is so great that the iron stays solid even at around 5,000 to 6,000 degrees."],
    [5, "What showed scientists that Earth's outer core is liquid?", ["Drilling samples from deep boreholes", "S-waves cannot pass through it, creating a shadow zone", "Volcanoes erupt liquid iron", "Satellites photographed it"], 1, "S-waves cannot travel through liquid, so the S-wave shadow zone revealed a molten outer core."],
    [1, "Why do continents hold the oldest rocks on Earth?", ["Continents formed before the oceans", "Continental crust is thinner", "Continental crust is lighter, so it rarely sinks back into the mantle", "Oceanic rocks dissolve in seawater"], 2, "Oceanic crust is recycled within about 200 million years, but buoyant continental crust survives for billions of years."],
    [6, "What generates Earth's magnetic field?", ["The solid inner core acting as a bar magnet", "Iron deposits in the crust", "The solar wind hitting the atmosphere", "Moving liquid iron in the outer core"], 3, "The churning, electrically conducting liquid iron of the outer core works like a dynamo."],
    [2, "Which best describes the mantle?", ["An ocean of molten lava", "Solid rock that flows very slowly", "A layer of liquid iron", "A thin skin of basalt"], 1, "The mantle is almost entirely solid, but under heat and pressure it creeps a few centimetres a year."]
  ],
  { popularity: 72, related: ["plate-tectonics", "volcanoes-earthquakes"] }
);

WB.L("volcanoes-earthquakes", "geography", "beginner", "Volcanoes, earthquakes and tsunamis",
  "Australia feels rock-solid, yet in 1989 an earthquake killed 13 people in Newcastle. Here's what makes the ground shake and mountains explode.",
  [
    ["Runny or sticky magma", "Runny magma makes gentle, flowing eruptions; thick, gassy magma makes explosive ones.",
      "Whether a volcano oozes or explodes depends mostly on its magma. Runny, low-silica basalt lets gas escape easily, so it tends to pour out as lava flows that build broad, gently sloping shield volcanoes, like those of Hawaii. Thicker, silica-rich magma traps gas like a shaken soft drink, until the pressure blasts it apart into ash and rock. That builds the steep, layered cones called stratovolcanoes, such as Mount Fuji and Indonesia's many peaks. Australia has volcanoes too. The Newer Volcanics Province of western Victoria and south-east South Australia includes Mount Gambier, whose crater holds the Blue Lake. It last erupted roughly 5,000 to 6,000 years ago and is thought to be dormant rather than extinct."],
    ["The Ring of Fire", "The Ring of Fire around the Pacific hosts most of the world's active volcanoes and big earthquakes.",
      "The Pacific Ocean is ringed by a horseshoe of subduction zones about 40,000 kilometres long, running from New Zealand up through Indonesia, the Philippines and Japan, across to Alaska, and down the Americas to Chile. This is the Ring of Fire. It contains roughly three-quarters of the world's active volcanoes and produces most of its earthquakes, including nearly all of the very largest. Our near neighbours sit right on it: Indonesia has more active volcanoes than any other country, and New Zealand, Papua New Guinea and Vanuatu all experience frequent earthquakes and eruptions. Australia, by contrast, sits near the middle of its plate, far from the edges."],
    ["Measuring earthquakes", "Each whole step on the magnitude scale means about 32 times more energy.",
      "In 1935 seismologist Charles Richter created a scale to compare earthquakes in California. Today scientists mainly use the moment magnitude scale, which works better for very large quakes, though news reports often still say 'Richter'. The scale is logarithmic: each whole number up means about ten times more ground shaking and roughly 32 times more energy released. So a magnitude 7 releases about 1,000 times the energy of a magnitude 5. Magnitude measures the size of the quake itself. Intensity is different: it describes how strongly shaking was felt in a particular place, which depends on distance, depth and local soil. A moderate quake directly under a city can do more damage than a huge one far offshore."],
    ["Famous eruptions", "Tambora in 1815 caused a 'year without a summer'; Krakatoa in 1883 was heard thousands of kilometres away.",
      "In 79 AD Mount Vesuvius buried the Roman towns of Pompeii and Herculaneum under ash and scorching gas flows, preserving a snapshot of daily life. In 1815 Mount Tambora in Indonesia produced the largest eruption in recorded history. Its ash and sulfur haze cooled global climate, and 1816 became known in Europe and North America as the 'year without a summer', with crop failures and famine. In 1883 Krakatoa, between Java and Sumatra, exploded with a sound heard across the Indian Ocean, including in parts of Western Australia. Its tsunamis killed tens of thousands of people, and fine dust in the upper atmosphere produced vivid red sunsets around the world."],
    ["The biggest earthquakes", "The largest earthquake recorded was magnitude 9.5 in Chile in 1960.",
      "The most powerful earthquake ever recorded struck Chile in 1960, at magnitude 9.5. The 2004 Indian Ocean earthquake off Sumatra, about magnitude 9.1, generated tsunamis that killed roughly 230,000 people in 14 countries, making it one of the deadliest natural disasters in modern history. In 2011 a magnitude 9.0 to 9.1 earthquake off north-east Japan triggered a tsunami that killed around 18,000 people and caused the Fukushima nuclear accident. All three struck at subduction zones, where huge areas of plate can lock together for centuries and then slip all at once. Despite decades of research, scientists still cannot predict the exact time and place of an earthquake, only estimate the long-term risk."],
    ["Australia's big quakes", "Australia's largest quakes struck the sparsely populated interior; the smaller 1989 Newcastle quake was deadlier because it hit a city.",
      "Australia is not immune. Stress transmitted through the plate still cracks its interior. On 14 October 1968, a quake of about magnitude 6.5 wrecked much of the Wheatbelt town of Meckering in Western Australia and ripped open a fault scarp tens of kilometres long. On 22 January 1988, three quakes, the largest about magnitude 6.6, struck near Tennant Creek in the Northern Territory within 12 hours, the biggest recorded on the mainland. Because both hit sparsely populated areas, no one died. The magnitude 5.6 Newcastle quake of 28 December 1989 was far smaller, yet it killed 13 people, nine of them in the collapse of the Newcastle Workers Club, because it struck a city partly built on soft ground. It led to tougher building standards."],
    ["How tsunamis work", "Tsunamis are fast, long waves set off when the sea floor moves; they grow as they reach shallow water.",
      "A tsunami is usually caused when an undersea earthquake suddenly lifts or drops the sea floor, moving the entire column of water above it. Landslides and volcanic eruptions can also cause them. In the deep ocean a tsunami can travel at around 800 kilometres an hour, as fast as a jet, yet be less than a metre high, so ships barely notice it. As it reaches shallow water it slows and piles up, sometimes into a wall of water many metres high. Unlike a normal wave, it can keep surging inland for many minutes. Often the first sign is the sea dramatically drawing back from the shore, exposing the sea floor."],
    ["Staying safe", "If you feel strong shaking: drop, cover and hold on. Near the coast, get to high ground if the sea suddenly retreats.",
      "In an earthquake, the standard advice is to drop to the ground, take cover under a sturdy table and hold on until the shaking stops. Most injuries come from falling objects and debris, not the ground itself, so stay away from windows and don't run outside past falling masonry. Near the coast, a strong or long earthquake, or the sea suddenly retreating, is a natural warning to move to high ground straight away without waiting for an official alert. Australia's Joint Australian Tsunami Warning Centre, run by the Bureau of Meteorology and Geoscience Australia, monitors the region around the clock. When travelling in Bali, Japan or New Zealand, check local warning signs and evacuation routes."]
  ],
  [
    [2, "Roughly how much more energy does a magnitude 7 earthquake release than a magnitude 6?", ["About 2 times", "About 10 times", "About 32 times", "About 1,000 times"], 2, "Each whole step on the magnitude scale means roughly 32 times more energy."],
    [1, "Roughly how long is the Pacific Ring of Fire?", ["About 400 kilometres", "About 4,000 kilometres", "About 40,000 kilometres", "About 400,000 kilometres"], 2, "The horseshoe of subduction zones runs about 40,000 kilometres around the Pacific."],
    [5, "Why did the 1989 Newcastle quake kill 13 people when larger Australian quakes at Meckering and Tennant Creek killed no one?", ["It struck close to a city", "It triggered a tsunami", "It was actually the largest", "It happened at night"], 0, "Meckering and Tennant Creek hit sparsely populated areas; Newcastle hit a city partly built on soft ground."],
    [6, "Why do ships in the deep ocean barely notice a passing tsunami?", ["Tsunamis only form near the coast", "In deep water it is less than a metre high, though very fast", "Tsunamis travel underwater", "Tsunamis are too slow to feel"], 1, "In deep water a tsunami is fast but low, only growing tall when it slows in shallow water."],
    [3, "Which eruption led to the 'year without a summer' in 1816?", ["Krakatoa", "Vesuvius", "Tambora", "Mount St Helens"], 2, "Tambora's 1815 eruption, the largest in recorded history, cooled the global climate the following year."]
  ],
  { popularity: 78, related: ["plate-tectonics", "earth-structure"] }
);

WB.L("weather", "geography", "beginner", "How weather works",
  "Every forecast you check is the result of sunlight, spinning air and some of the most powerful computers on the planet.",
  [
    ["It starts with the Sun", "Weather is driven by the Sun heating the Earth unevenly, and the atmosphere moving heat around.",
      "All weather begins with sunlight. The Sun heats the tropics far more strongly than the poles, because near the equator its rays hit the ground almost head-on, while at high latitudes the same energy is spread over a larger area. Land also heats and cools faster than water. The atmosphere and oceans are constantly trying to even out these differences, moving warm air towards the poles and cold air towards the equator. That restless movement of air, heat and moisture is what we call weather. Weather is the day-to-day state of the atmosphere; climate is the long-term average, usually measured over 30 years or more."],
    ["Air pressure: highs and lows", "High pressure usually brings settled, dry weather; low pressure brings cloud, wind and rain.",
      "Air has weight. At sea level it presses down with an average pressure of about 1013 hectopascals, the unit you see on weather maps. Where air is sinking, pressure rises, forming a high. Sinking air warms and dries, so highs usually bring clear skies, light winds and, in winter, cold frosty nights. Where air is rising, pressure falls, forming a low. Rising air cools, its moisture condenses into cloud, and lows bring wind and rain. Air flows from high to low pressure, but Earth's spin deflects it. In the Southern Hemisphere, winds circle anticlockwise around highs and clockwise around lows, the reverse of the north."],
    ["Fronts and cool changes", "A front is the boundary between air masses; cold fronts bring the southern 'cool change'.",
      "Large bodies of air, called air masses, take on the temperature and moisture of where they formed, such as the hot interior of Australia or the cold Southern Ocean. The boundary between two air masses is a front. In southern Australia, cold fronts sweep in from the west every few days, especially in winter. They are marked on weather maps as lines with triangles. Ahead of a front, hot, dry northerly winds can blow, raising fire danger in summer. When the front passes, the wind swings to the south-west, the temperature can drop ten degrees or more within an hour, and showers often follow. Melburnians know this well as the 'cool change'."],
    ["How clouds form", "Clouds form when rising air cools and its water vapour condenses onto tiny particles.",
      "Air always contains invisible water vapour. When air rises, it expands and cools, and cool air can hold less vapour. Eventually the vapour condenses into tiny droplets or ice crystals, each forming around a speck of dust, salt or smoke. Billions of these make a cloud. Air can be forced to rise by heating from the ground, by mountains, or by fronts. The main cloud families are named in Latin: cumulus (heap), puffy fair-weather clouds; stratus (layer), flat grey sheets; and cirrus (curl of hair), wispy high ice clouds. Cumulonimbus are towering storm clouds that can reach over 12 kilometres high and bring lightning, hail and heavy rain."],
    ["From droplets to rain", "Cloud droplets must grow roughly a million times in volume to fall as raindrops.",
      "Cloud droplets are so small that rising air easily holds them up. To fall as rain, they must grow enormously; a typical raindrop contains the water of around a million cloud droplets. In warm clouds, droplets collide and merge as they are tossed around. In colder clouds, ice crystals grow at the expense of nearby supercooled water droplets, then fall and melt into rain on the way down. Hail forms when strong updrafts in thunderstorms carry ice up and down repeatedly, adding layers like an onion. Despite cartoons, raindrops are not teardrop-shaped; small ones are nearly round, and larger ones flatten into something like a hamburger bun as they fall."],
    ["How forecasts are made", "Modern forecasts come from supercomputers solving the physics of the atmosphere, fed by millions of observations.",
      "Modern forecasting is called numerical weather prediction. Observations from weather stations, balloons, ships, aircraft, radar and satellites, including Japan's Himawari satellites that watch our region, are fed into supercomputers. These divide the atmosphere into a three-dimensional grid and use the laws of physics to calculate how it will change, step by step. Because tiny errors grow over time, forecasters run the model many times with slightly different starting conditions, called an ensemble, to estimate the range of possibilities. Forecasts have improved steadily, by roughly a day of useful accuracy per decade. Even so, the chaotic nature of the atmosphere means detailed forecasts beyond about 10 days remain unreliable."],
    ["Tropical cyclones", "Tropical cyclones form over seas warmer than about 26.5°C and, in the Southern Hemisphere, spin clockwise.",
      "Tropical cyclones, called hurricanes or typhoons elsewhere, form over tropical oceans where the water is warmer than about 26.5 degrees Celsius. Warm, moist air rises, its vapour condenses and releases heat, and that heat powers a spiralling storm that can be hundreds of kilometres across. Like other lows in the Southern Hemisphere, they spin clockwise. Australia's cyclone season runs from November to April, with around ten forming in our region in a typical season. The Bureau of Meteorology rates them from category 1 to 5; a category 5 brings gusts above 280 kilometres an hour. Storm surge and flooding rain often do more harm than wind. Cyclone Tracy flattened much of Darwin on Christmas Day 1974, leading to far stronger building codes across the north."],
    ["Reading a forecast well", "A 70% chance of rain means a 70% chance of at least 0.2 millimetres falling at that location.",
      "A few tips make forecasts more useful. In BOM forecasts, 'chance of rain' means the chance of at least 0.2 millimetres falling at that location during the period, not the share of the area or the day that will be wet. Check the expected rainfall amounts too: a 90% chance of 1 millimetre is very different from a 40% chance of 30 millimetres. Watch for fronts and wind changes on the synoptic chart if you're planning outdoor activities, especially on hot, windy days when fire danger is high. For severe weather, rely on official warnings from the BOM and your state emergency services, and check the radar before heading out."]
  ],
  [
    [1, "What kind of weather does a high-pressure system usually bring?", ["Settled, dry weather with light winds", "Heavy rain and thunderstorms", "Strong winds and cloud", "Tropical cyclones"], 0, "Sinking air in a high warms and dries, so highs usually bring clear, settled weather."],
    [2, "What typically happens when a cold front passes through southern Australia in summer?", ["The wind swings north and temperatures rise", "The wind swings south-west and temperatures drop sharply", "Humidity stays the same and skies clear", "A tropical cyclone forms"], 1, "After a cold front, winds turn south-westerly and temperatures can fall ten degrees or more: the 'cool change'."],
    [6, "Roughly how warm must the sea be for a tropical cyclone to form?", ["About 15°C", "About 20°C", "About 26.5°C", "About 35°C"], 2, "Warm seas supply the heat and moisture that power the storm."],
    [7, "In a BOM forecast, what does a 70% chance of rain mean?", ["It will rain on 70% of the area", "It will rain for 70% of the day", "70% of forecasters expect rain", "A 70% chance of at least 0.2 mm at that location"], 3, "BOM's chance of rain is the probability of at least 0.2 millimetres falling at the location."],
    [3, "What is the main reason clouds form?", ["Rising air cools and its water vapour condenses", "The Sun heats water droplets in the sky", "Wind blows sea spray upwards", "Cold air pushes moisture down"], 0, "As air rises it cools, and its vapour condenses onto tiny particles to form cloud droplets."]
  ],
  { popularity: 76, related: ["australia-climate", "climate-change"] }
);

WB.L("ice-ages", "geography", "intermediate", "Ice ages",
  "Twenty thousand years ago you could have walked from Melbourne to Hobart, and on to New Guinea. The reason lies in a slow wobble in Earth's orbit.",
  [
    ["We're still in an ice age", "Technically we live in an ice age, in a warm interglacial period that began about 11,700 years ago.",
      "To geologists, an ice age is any long period when large ice sheets exist on Earth. By that definition we are living in one right now, because Antarctica and Greenland are covered in ice. The current ice age began about 2.6 million years ago. Within it, the climate has swung back and forth between cold glacial periods, when ice sheets spread across North America and northern Europe, and shorter warm interglacial periods like today's. Our current interglacial, called the Holocene, began about 11,700 years ago. When people say 'the Ice Age', they usually mean the most recent glacial period, which peaked around 20,000 years ago."],
    ["Milankovitch cycles", "Slow, regular changes in Earth's orbit and tilt, called Milankovitch cycles, pace the ice ages.",
      "In the early 20th century, Serbian scientist Milutin Milanković calculated how small changes in Earth's orbit alter the sunlight reaching different latitudes. There are three main cycles. Eccentricity is the shape of Earth's orbit, which stretches from nearly circular to slightly oval over about 100,000 years. Obliquity is the tilt of Earth's axis, which varies between about 22 and 24.5 degrees over about 41,000 years. Precession is the slow wobble of the axis, like a spinning top, over roughly 23,000 years. Together they change how strong the seasons are, especially how much summer sunshine reaches the far north, where the great ice sheets grow and melt."],
    ["Proof from the sea floor", "Deep-sea sediments confirmed Milankovitch's theory in 1976; feedbacks like carbon dioxide amplify the small orbital nudge.",
      "Milanković's idea was debated for decades. In 1976 scientists James Hays, John Imbrie and Nicholas Shackleton analysed deep-sea sediment cores and found climate cycles matching his predicted rhythms, a landmark confirmation. But the orbital changes alone are fairly small nudges. They are amplified by feedbacks. As ice spreads, its bright white surface reflects more sunlight, cooling things further. Colder oceans absorb more carbon dioxide, lowering greenhouse warming. Antarctic ice cores, containing tiny bubbles of ancient air stretching back about 800,000 years, show carbon dioxide at roughly 180 parts per million in glacial periods and about 280 in warm periods, rising and falling closely with temperature."],
    ["The Last Glacial Maximum", "Around 20,000 years ago, ice sheets up to 3 kilometres thick covered much of North America and Europe.",
      "The coldest part of the last glacial period, called the Last Glacial Maximum, was roughly 26,000 to 19,000 years ago. Ice sheets up to about 3 kilometres thick covered Canada and the northern United States as far south as present-day New York and Chicago, and much of northern Europe, including most of Britain and Scandinavia. Estimates suggest global average temperatures were around 6 degrees Celsius colder than before the industrial era, though figures vary. The world was also drier and dustier. Woolly mammoths, woolly rhinoceroses and cave lions roamed the cold grassy steppes of Europe and Asia, and humans survived in the milder regions further south."],
    ["Australia in the cold", "Ice-age Australia was colder, drier and windier, with small glaciers in Tasmania and the Snowy Mountains.",
      "Australia was never covered by large ice sheets, but it was very different. Much of the continent was colder, drier and windier, and desert dune fields expanded. Glaciers carved the highlands of Tasmania, leaving features such as Cradle Mountain's lakes and valleys, and small glaciers formed around Mount Kosciuszko, where glacial lakes like Blue Lake remain today. Many inland lakes, such as those of the Willandra Lakes region including Lake Mungo, held water at various times and later dried out. Aboriginal people had already lived in Australia for tens of thousands of years, and they adapted to these harsh conditions and to the great changes that followed."],
    ["Lower seas, Sahul", "With so much water locked in ice, sea levels were about 120 metres lower, joining Australia, New Guinea and Tasmania.",
      "Ice sheets hold water that would otherwise be in the oceans. At the Last Glacial Maximum, so much water was locked up on land that global sea levels were roughly 120 metres lower than today. Coastlines moved far out, and shallow seas became dry plains. Australia, New Guinea and Tasmania formed a single landmass that scientists call Sahul. The Bass Strait region was a broad plain, dotted with lakes and low hills, that could be walked across. To the north, the land bridge across what is now Torres Strait and the Gulf of Carpentaria connected Cape York to New Guinea. Around Asia, a similar exposed landmass called Sunda joined many Indonesian islands to the mainland."],
    ["The seas return", "Rising seas cut off Tasmania roughly 12,000 years ago and New Guinea roughly 8,000 years ago.",
      "As the ice sheets melted, sea levels rose rapidly, at times by more than a metre per century. Rising water flooded the Bass Strait plain and cut Tasmania off from the mainland roughly 12,000 years ago, though estimates vary by a few thousand years. The land bridge to New Guinea was drowned later, around 8,000 years ago. Sea levels reached roughly their present height about 7,000 years ago. Communities living on these coasts would have watched the shoreline creep inland over generations. Some researchers suggest certain Aboriginal oral traditions may preserve memories of these rising seas, an idea that is taken seriously but still debated."],
    ["What it means for us", "Ice ages show how sensitive climate is: small nudges, amplified by feedbacks, changed sea levels by over 100 metres.",
      "Ice ages carry an important lesson. A modest change in sunlight, amplified by ice and carbon dioxide feedbacks, was enough to shift global temperatures by several degrees and sea levels by over 100 metres. Today, carbon dioxide has risen from about 280 parts per million before industry to well over 400, higher than at any time in the ice-core record, and far faster than natural glacial cycles. On orbital grounds alone, scientists expect the next glacial period is many tens of thousands of years away, and human emissions may delay it further. The coastlines we know, and the Aboriginal history written into them, are a reminder that the map is never permanent."]
  ],
  [
    [1, "What are Milankovitch cycles?", ["Changes in the Sun's brightness", "Slow changes in Earth's orbit, tilt and wobble", "Cycles of volcanic activity", "Shifts in ocean currents"], 1, "Milankovitch cycles are regular changes in eccentricity, axial tilt and precession that alter the sunlight Earth receives."],
    [5, "About how much lower were sea levels at the Last Glacial Maximum?", ["About 5 metres", "About 30 metres", "About 120 metres", "About 500 metres"], 2, "So much water was locked in ice sheets that seas were roughly 120 metres lower."],
    [5, "What was the ice-age landmass joining Australia, New Guinea and Tasmania called?", ["Sahul", "Sunda", "Gondwana", "Pangaea"], 0, "Sahul was the single landmass of Australia, New Guinea and Tasmania; Sunda was its Asian counterpart."],
    [0, "Why do geologists say we are still in an ice age?", ["Global temperatures are falling", "Glaciers are advancing worldwide", "The last glacial period never ended", "Large ice sheets still cover Antarctica and Greenland"], 3, "An ice age is any period with large ice sheets; we are in a warm interglacial within one."],
    [2, "How do feedbacks strengthen the effect of Milankovitch cycles?", ["Spreading ice reflects sunlight and colder oceans absorb carbon dioxide", "Volcanoes erupt more often during glacials", "The Moon moves closer to Earth", "Ocean salt levels rise"], 0, "Bright ice reflects sunlight and lower carbon dioxide reduces greenhouse warming, amplifying the orbital nudge."]
  ],
  { popularity: 70, related: ["climate-change", "australia-climate"] }
);

WB.L("renewable-energy", "science", "beginner", "Renewable energy",
  "Australia has more rooftop solar per person than almost anywhere on Earth. Here's how renewables work, and what makes the switch hard.",
  [
    ["Why renewables", "Renewable energy comes from sources that are naturally replenished, like sunlight, wind and flowing water.",
      "Renewable energy comes from sources that are constantly replenished: sunlight, wind, flowing water, and heat from the Earth. Fossil fuels like coal and gas release carbon dioxide stored over millions of years when burned, and electricity generation has long been one of Australia's largest sources of greenhouse emissions. Renewables produce almost no emissions while running, although making and installing them does have a footprint. Across their whole lifetime, solar, wind and hydro emit only a small fraction of the carbon of coal per unit of electricity. They also use free fuel, which is a big reason the cost of renewable electricity has fallen so sharply over the past two decades."],
    ["How solar panels work", "Solar panels turn sunlight directly into electricity using silicon cells, with key advances made in Australia.",
      "Solar photovoltaic panels, or PV, convert sunlight directly into electricity. Each panel contains cells made from specially treated silicon. When light hits the cell, it knocks electrons loose, and the cell's structure pushes them in one direction, creating a direct current. An inverter then converts this into the alternating current used in homes. Australian researchers have played a major role. A team at the University of New South Wales, led by Martin Green, developed the PERC cell design in the 1980s, which became the world's dominant solar cell technology for years. The price of solar panels fell by around 90% during the 2010s, as mass production scaled up, largely in China."],
    ["Rooftop solar in Australia", "Australia has one of the highest rates of rooftop solar in the world, with over a third of houses fitted.",
      "Australia has embraced rooftop solar like few other countries. Sunshine, government rebates and falling prices helped more than a third of Australian houses install panels, around four million systems by the mid-2020s, one of the highest rates per person in the world. On sunny days, rooftop panels can supply most of South Australia's electricity demand at times. This success brings new challenges. Around the middle of the day, so much solar floods the grid that demand from power stations drops very low, which can make the system harder to manage. Wholesale prices sometimes go negative. That is one reason for the growing interest in batteries and time-of-use tariffs."],
    ["Wind power", "Wind turbines turn moving air into electricity and complement solar because wind often blows at night.",
      "Wind turbines capture the energy of moving air. The wind turns large blades, which spin a generator, usually through a gearbox. Modern turbines are huge: towers can exceed 100 metres, with blades longer than an Olympic swimming pool. Because wind speeds increase with height and power rises steeply with wind speed, taller turbines produce much more electricity. Australia's best wind resources are along the southern coastline and in elevated areas, and South Australia has become a leader, getting well over half its electricity from wind and solar combined in recent years. Wind is a useful partner for solar because it often blows at night and in winter, when solar output is low."],
    ["Hydro and the Snowy", "Hydroelectricity uses falling water and can start quickly; Snowy 2.0 will store energy by pumping water uphill between reservoirs.",
      "Hydroelectric power uses water flowing downhill through turbines. It is Australia's oldest large-scale renewable energy source, and a hydro station can ramp up within minutes, which makes it a valuable backup when solar and wind dip. Tasmania gets most of its electricity from hydro, and the Snowy Mountains Scheme remains the mainland's biggest. The newer Snowy 2.0 project is pumped hydro: it links two existing reservoirs, Tantangara and Talbingo, through about 27 kilometres of tunnels, pumping water uphill when electricity is cheap and releasing it through turbines when needed, like a giant battery. Its estimated cost has blown out from about $2 billion when announced in 2017 to more than $12 billion, with full operation now expected around 2028."],
    ["Batteries and storage", "Batteries store surplus renewable energy and respond to grid problems in fractions of a second.",
      "The sun sets and the wind drops, so storage is essential. In 2017, after a statewide blackout in South Australia the previous year, the Hornsdale Power Reserve was built near Jamestown. At 100 megawatts, it was then the world's largest lithium-ion battery, and it was built in under 100 days. It proved especially good at stabilising the grid, responding to faults in fractions of a second, faster than traditional power stations, and it has since been expanded. Many large batteries have followed. At home, batteries let households store daytime solar for the evening. Pumped hydro, like Snowy 2.0, provides longer-duration storage, lasting days rather than hours."],
    ["The trade-offs", "Renewables need backup, storage, new transmission lines, land and mined minerals, and each raises hard questions.",
      "Renewables are not without costs. Solar and wind are variable, so the grid needs storage, backup generation such as gas, and smarter demand management to keep the lights on. Good renewable sites are often far from cities, so thousands of kilometres of new transmission lines are needed, which can face strong opposition from landholders and communities. Wind and solar farms use large areas of land, and turbines can affect birds and landscapes. Panels, turbines and batteries require mining of materials such as lithium, copper and rare earths, and recycling them at scale is still developing. Honest debate about renewables means weighing these trade-offs against the costs of continuing with fossil fuels."],
    ["Where Australia is heading", "Renewables supply a rising share of Australia's electricity, and a federal target aims for 82% by 2030.",
      "Australia's electricity system is changing quickly. In the main eastern and southern grid, renewables supplied roughly 40% of electricity by the mid-2020s, up from under 10% in the early 2000s, while ageing coal-fired power stations are scheduled to close over the coming decades. In 2022 the federal government set a target of 82% renewable electricity by 2030, though progress towards it is debated. For households, the practical questions are usually whether rooftop solar or a battery suits your roof, usage and budget. Get several quotes from accredited installers, check government rebates, and consider independent advice before committing to a large purchase."]
  ],
  [
    [1, "What does an inverter do in a solar system?", ["Stores electricity for night-time", "Cools the panels", "Converts direct current into alternating current", "Tracks the Sun across the sky"], 2, "Panels produce direct current; the inverter converts it to the alternating current used in homes."],
    [4, "What makes Snowy 2.0 different from a regular hydro power station?", ["It uses seawater", "It pumps water uphill to store energy for later", "It runs only in winter", "It burns gas when water is low"], 1, "Pumped hydro stores energy by pumping water uphill when power is cheap and releasing it when needed."],
    [5, "What was the Hornsdale Power Reserve especially good at?", ["Stabilising the grid by responding in fractions of a second", "Generating power from wind", "Replacing all coal power in South Australia", "Heating homes"], 0, "The battery responded to grid faults faster than traditional power stations."],
    [3, "Why is wind a useful partner for solar?", ["Wind turbines need sunlight", "Wind is completely constant", "Solar panels power wind turbines", "Wind often blows at night and in winter"], 3, "Wind often picks up when solar output is low, smoothing total renewable supply."],
    [6, "Which is a genuine challenge of expanding renewables?", ["They produce large emissions while running", "They need new transmission lines, storage and mined minerals", "Their fuel is expensive", "They cannot work in Australia's climate"], 1, "Renewables have free fuel and low emissions, but need transmission, storage, land and materials."]
  ],
  { popularity: 74, related: ["climate-change", "energy", "weather"] }
);
