/* WISEBYTE LESSONS · The Human Body: organs, systems and ageing */
WB.L("skin-largest-organ", "body", "beginner", "Your skin: the organ you wear", "It is waterproof, self-repairing, temperature-controlled and covered in sensors, and you are wearing it right now. Meet the most underrated organ you have.",
  [
    ["An organ, not a wrapper", "Skin is your largest organ, doing far more than simply holding you in.", "Picture unpacking an adult's skin and laying it flat. It would cover roughly two square metres, about the size of a single bed sheet, and weigh several kilograms. That makes it the largest organ in the body, even though we rarely think of it as an organ at all. Yet skin does an astonishing amount of work. It keeps water in and germs out, shields you from sunlight, helps control your temperature, makes vitamin D, and feeds your brain a constant stream of information about touch, pressure, heat and pain. It also heals itself after cuts and scrapes, usually without leaving much trace. Every square centimetre is a busy, living system, packed with blood vessels, nerves, glands and cells that are constantly being replaced."],
    ["Three layers, three jobs", "The epidermis protects, the dermis supports and senses, and the fat layer below cushions and insulates.", "Skin is built in layers, a bit like a well-made jacket. The outermost layer, the epidermis, is surprisingly thin, in most places thinner than a sheet of paper, but it is the part that faces the world. Its top is made of flattened dead cells packed with a tough protein called keratin, which forms a waterproof, germ-resistant barrier. Beneath it lies the dermis, a thicker layer woven from collagen and elastin fibres that give skin its strength and stretch. The dermis holds the blood vessels, nerve endings, hair roots and sweat glands. Below that is the subcutaneous layer, mostly fat, which cushions you against bumps, stores energy and helps hold in body heat. Thickness varies hugely: the skin on your eyelids is delicate, while the soles of your feet are thick and rugged."],
    ["A coat that renews itself", "You shed skin cells constantly and grow a fresh outer layer every few weeks.", "Deep at the base of the epidermis, cells are dividing all the time. As new cells form, older ones are pushed upwards towards the surface. On the way they fill with keratin, flatten out and die, so the surface you touch is essentially a layer of dead cells doing a protective job. Eventually they flake away, often too small to notice. This journey from bottom to top takes roughly a month, so in a sense you grow a new outer skin many times a year. You lose a huge number of skin cells every day. A popular claim says most household dust is dead skin, but research suggests a lot of indoor dust actually comes in from outside, so skin is only part of the story."],
    ["The colour of skin", "Skin colour comes mainly from melanin, a natural pigment that helps protect against ultraviolet light.", "Scattered through the bottom of the epidermis are cells called melanocytes, which make a pigment called melanin. People of all skin tones have broadly similar numbers of melanocytes. What differs is how much melanin they produce and what type. More melanin, especially the darker form, gives deeper skin tones and stronger natural protection against ultraviolet radiation. When skin is exposed to the sun, melanocytes ramp up production, which is what a tan is: a sign that skin has been damaged and is trying to defend itself. Scientists think human skin colour varies so much because our ancestors lived under very different levels of sunlight, balancing protection from UV against the need to make vitamin D. In a high-UV country like Australia, that protection matters for everyone."],
    ["Air conditioning and goosebumps", "Sweat cools you down, blood vessels redirect heat, and goosebumps are a leftover from furrier ancestors.", "Go for a brisk walk on a hot Brisbane afternoon and your skin becomes a cooling system. Millions of small sweat glands release watery sweat, and as it evaporates it carries heat away. Meanwhile, blood vessels near the surface widen, sending warm blood close to the skin so heat can escape, which is why your face flushes. In the cold, the reverse happens: those vessels narrow to keep warmth near your core. A second type of sweat gland, found mainly in the armpits and groin, releases a thicker sweat. It is odourless at first, and the smell comes from skin bacteria breaking it down. Goosebumps are made by tiny muscles that pull hairs upright. In furry animals this traps insulating air or makes them look bigger; in us, it is mostly a curious leftover."],
    ["A sensor-covered surface", "Skin contains several kinds of touch receptors, and your fingertips are among the most sensitive spots.", "Close your eyes and run a finger over a coin. You can feel the ridges, the edge and the coolness of the metal, all thanks to specialised nerve endings in your skin. Some respond to light touch, others to vibration, deep pressure, stretching, heat, cold or damage. They are not spread evenly. Your fingertips, lips and tongue are packed with receptors, while your back has far fewer, which is why it is hard to tell whether one or two pencil points are pressing on it. The ridges that make up your fingerprints form before birth and seem to help with grip and with sensing fine texture. Even identical twins, who share the same DNA, have different fingerprints, because small variations in the womb shape how the ridges form."],
    ["Looking after your skin", "Sun protection matters most, and the changes that come with age are mostly driven by collagen loss and UV exposure.", "As we age, skin makes less collagen and elastin, grows thinner, and holds less moisture, which is why wrinkles and sagging appear. But much of what people think of as ageing skin is actually sun damage. Compare the skin on someone's forearm with the skin on their inner upper arm and the difference can be striking. Australia has some of the highest rates of skin cancer in the world, so sun protection is the single most useful habit: shade, clothing, a broad-brimmed hat, sunglasses and sunscreen, especially when the UV index is 3 or above. Getting to know your own skin and checking for new or changing spots is also worthwhile. This is general information, not medical advice, so for any concern see a doctor or visit healthdirect."]
  ],
  [
    [0, "Roughly how much area would an adult's skin cover if laid flat?", ["About half a square metre", "About two square metres", "About ten square metres", "About fifty square metres"], 1, "An adult's skin covers roughly two square metres, making it the body's largest organ."],
    [1, "Which layer of skin contains collagen fibres, blood vessels and hair roots?", ["The dermis", "The epidermis", "The keratin layer", "The enamel"], 0, "The dermis is the thicker middle layer that holds structural fibres, vessels, nerves and glands."],
    [3, "What do people with different skin tones mainly differ in?", ["The number of skin layers", "The number of sweat glands", "The amount and type of melanin produced", "The thickness of their keratin"], 2, "People have broadly similar numbers of melanocytes; it is melanin production that varies."],
    [4, "Why does armpit sweat develop a smell?", ["It contains salt crystals", "It is made by the kidneys", "It is acidic when released", "Skin bacteria break it down"], 3, "This sweat is odourless at first; bacteria on the skin create the smell as they break it down."],
    [5, "Why do identical twins have different fingerprints?", ["Fingerprints change every few years", "Small variations in the womb shape the ridges", "Fingerprints come only from the father", "Twins are born without fingerprints"], 1, "Fingerprints form before birth and are shaped by tiny differences in the womb environment, not DNA alone."]
  ]);

WB.L("how-breathing-works", "body", "beginner", "How breathing works", "You will take more than 20,000 breaths today without thinking about any of them. Here is the clever machinery that keeps the air moving.",
  [
    ["The breath you never notice", "Breathing runs on autopilot, but you can take manual control whenever you like.", "Right now, while you read this, you are breathing roughly 12 to 20 times a minute. Over a day that adds up to tens of thousands of breaths, almost none of which you choose to take. Breathing is one of the few body functions that runs automatically yet can also be taken over by will. You can hold your breath, speed it up, sing a long note or blow out birthday candles. Then, the moment you stop paying attention, your brain quietly takes the controls back. That handover is managed by the brainstem, an ancient part of the brain at the top of the spinal cord. Every breath delivers oxygen your cells need to release energy from food, and carries away the carbon dioxide they produce as waste."],
    ["The diaphragm does the work", "Breathing in happens when the diaphragm and rib muscles enlarge the chest, letting air rush in.", "Lungs have no muscles of their own to pull in air. Instead, the work is done by the diaphragm, a dome-shaped sheet of muscle beneath the lungs. When it contracts, it flattens and moves downwards, while muscles between the ribs lift the ribcage up and out. The chest gets bigger, the pressure inside the lungs drops slightly below the pressure of the air outside, and air flows in to fill the space. Breathing out at rest is mostly passive: the diaphragm relaxes, the elastic lungs spring back, and air is pushed out. When you exercise hard, extra muscles in your neck, chest and belly join in to move air faster. Hiccups, by the way, are sudden involuntary spasms of the diaphragm, with a snap of the vocal cords closing."],
    ["A tree upside down", "Air travels through ever-smaller branching tubes to reach hundreds of millions of tiny air sacs.", "Air enters through your nose or mouth, passes the voice box and travels down the windpipe, or trachea. From there the airways split into two main branches, one for each lung, then keep dividing again and again, like an upside-down tree. The smallest twigs end in clusters of tiny balloon-like sacs called alveoli. There are hundreds of millions of them, and because they are so numerous and so small, their combined inner surface is enormous, often compared to around half a tennis court. The two lungs are not identical either. The right lung has three sections, called lobes, while the left has only two, leaving room for the heart. The nose matters too: it warms, moistens and filters air before it reaches these delicate surfaces."],
    ["Where the swap happens", "In the alveoli, oxygen passes into the blood and carbon dioxide passes out, across walls thinner than a hair.", "The real business of breathing happens in the alveoli. Each tiny sac is wrapped in a mesh of hair-thin blood vessels called capillaries, and the barrier between air and blood is astonishingly thin. Oxygen drifts across into the blood, where it latches onto haemoglobin, an iron-rich protein inside red blood cells. At the same time, carbon dioxide moves the other way, out of the blood and into the air sacs, ready to be breathed out. The air you breathe in is about 21 per cent oxygen, and the air you breathe out still contains roughly 16 per cent. Your body uses only a fraction on each breath. That leftover oxygen is one reason rescue breaths during CPR can still help someone who is not breathing."],
    ["The urge comes from carbon dioxide", "Your drive to breathe is triggered mainly by rising carbon dioxide, not falling oxygen.", "Hold your breath and after a while the urge to breathe becomes overwhelming. Surprisingly, that urge is not mainly caused by running low on oxygen. Sensors in the brainstem and in major arteries track the level of carbon dioxide in the blood, which also changes the blood's acidity. When carbon dioxide rises, these sensors push you hard to breathe. This has an important safety lesson. Some swimmers and divers hyperventilate before going underwater, breathing rapidly to blow off carbon dioxide so they can stay down longer. The urge to breathe is delayed, but oxygen keeps falling, and a person can black out without warning. This is a known cause of drowning, even among strong swimmers, so hyperventilating before breath-holding in the water is dangerous and should be avoided."],
    ["Built-in cleaning crew", "A layer of mucus and tiny beating hairs constantly sweeps dust and germs out of your airways.", "Every day you breathe in dust, pollen, smoke particles and microbes. To deal with them, your airways are lined with sticky mucus that traps particles, and with millions of microscopic hair-like structures called cilia. The cilia beat in coordinated waves, moving the mucus upwards towards the throat, where it is usually swallowed without you noticing. Scientists sometimes call this the mucociliary escalator. Coughing and sneezing are the emergency backups, blasting out irritants at high speed. Cigarette smoke damages and slows the cilia, which is one reason people who smoke often develop a persistent cough: the body has to cough up what the escalator can no longer clear. Bushfire smoke is also hard on airways, so on smoky days it makes sense to follow local health advice."],
    ["Breathing and how you feel", "Slow, steady breathing can help you feel calmer, and your lungs reward regular exercise.", "Breathing is closely tied to the nervous system. When you are anxious, breathing tends to become fast and shallow, and when you are relaxed it slows down. The link works in both directions, so deliberately slowing your breath, especially with a long, unhurried breath out, can help many people feel calmer. Exercise does not grow new lung tissue, but it trains the breathing muscles, the heart and the muscles that use oxygen, so everyday activity feels easier. Lung function naturally declines a little with age, and smoking speeds that decline sharply. Breathlessness that is new, sudden or worsening deserves attention. This lesson is general information rather than medical advice, so if you are worried about your breathing, talk to a doctor or check healthdirect, and in an emergency call triple zero."]
  ],
  [
    [1, "What happens when the diaphragm contracts?", ["It flattens and moves down, enlarging the chest", "It pushes up and squeezes the lungs", "It closes the windpipe", "It pumps blood into the lungs"], 0, "Contracting flattens the diaphragm, lowering pressure in the chest so air flows in."],
    [2, "Why does the left lung have fewer lobes than the right?", ["It is used only during exercise", "It leaves room for the heart", "It holds the voice box", "It is damaged at birth"], 1, "The left lung has two lobes rather than three, making space for the heart."],
    [3, "Roughly how much oxygen is in the air you breathe out?", ["None at all", "About 1 per cent", "About 16 per cent", "About 50 per cent"], 2, "Exhaled air still contains around 16 per cent oxygen, compared with about 21 per cent going in."],
    [4, "Why is hyperventilating before breath-hold swimming dangerous?", ["It fills the lungs with water", "It raises carbon dioxide too high", "It stops the heart", "It delays the urge to breathe while oxygen keeps falling"], 3, "Blowing off carbon dioxide postpones the warning signal, so a swimmer can black out without feeling the need to surface."],
    [5, "What job do the cilia in your airways do?", ["Sweep mucus and trapped particles up towards the throat", "Absorb oxygen into the blood", "Produce the sound of your voice", "Warm the air to body temperature"], 0, "Cilia beat in waves to move mucus and trapped particles out of the airways."]
  ]);

WB.L("hormones-messengers", "body", "beginner", "Hormones: the body's chemical messengers", "A tiny drop of the right chemical can make your heart race, your stomach growl or a child grow taller. Hormones are the body's slow but powerful postal service.",
  [
    ["Messages in the bloodstream", "Hormones are chemicals released into the blood that change how distant cells behave.", "Imagine you nearly step on a snake on a bush track. Within seconds your heart is pounding, your breathing is fast and your muscles feel ready to spring. Part of that response comes from nerves, which act almost instantly, but part comes from hormones. A hormone is a chemical messenger made in one place and carried in the blood to cells elsewhere, where it changes what those cells do. Only cells with the matching receptor respond, a bit like a letter that can only be opened by the right key. Nerves are like phone calls: fast, targeted and brief. Hormones are more like a broadcast: slower to arrive, but able to reach the whole body at once and to keep working for minutes, hours or even years."],
    ["The glands that make them", "Hormones come from endocrine glands, coordinated by the hypothalamus and pituitary in the brain.", "The organs that release hormones directly into the blood make up the endocrine system. Key players include the thyroid in your neck, the adrenal glands perched on top of the kidneys, the pancreas, and the ovaries or testes. Fat tissue, the gut, the heart and the kidneys release hormones too. Overseeing much of this is a partnership in the brain. The hypothalamus monitors the body's state and sends signals to the pituitary gland, a pea-sized structure just below it. The pituitary then releases hormones that instruct other glands to speed up or slow down. Because it directs so many other glands, the pituitary is often called the master gland, although it takes its own orders from the hypothalamus."],
    ["Thermostats and feedback loops", "Most hormone levels are held steady by negative feedback, much like a thermostat.", "Think of the thermostat on an air conditioner. When the room warms past the set point, the cooling switches on; once it is cool enough, the cooling switches off. Many hormones work the same way, through negative feedback. Take the thyroid. When thyroid hormone levels fall, the hypothalamus and pituitary sense it and send signals urging the thyroid to make more. When levels rise high enough, those signals are turned down. This keeps things within a healthy range. The thyroid needs iodine to make its hormones, and iodine deficiency was once a widespread problem in parts of Australia. Since 2009, iodised salt has been required in most commercial bread here, a simple measure designed to top up iodine levels across the population."],
    ["Fight, flight and cortisol", "Adrenaline gives an instant boost, while cortisol manages longer-term energy and follows a daily rhythm.", "When you get a fright, your adrenal glands release adrenaline, also called epinephrine. It quickens the heart, widens the airways, sends more blood to the muscles and releases stored fuel into the blood, preparing you to fight or flee. The adrenals also make cortisol, often labelled the stress hormone, though that undersells it. Cortisol helps regulate blood sugar, blood pressure, inflammation and the body's use of energy. It also follows a daily rhythm, typically rising in the early morning to help you wake and falling towards night. Short bursts of these hormones are useful and normal. Problems are more likely when stress is intense and long-lasting, which is one reason sleep, exercise and rest matter for the whole body, not just the mind."],
    ["Insulin, a story of hope", "Insulin controls blood sugar, and its discovery in Canada in the early 1920s transformed type 1 diabetes.", "After a meal, sugar from your food enters the blood. The pancreas responds by releasing insulin, which signals cells in the muscles, liver and fat to take that sugar in, bringing blood levels back down. Between meals, another hormone, glucagon, does the reverse. In type 1 diabetes, the body's immune system destroys the cells that make insulin. Before the 1920s, this meant a grim and usually short life. Then, in 1921, Frederick Banting and Charles Best, working at the University of Toronto with colleagues, managed to extract insulin. In early 1922 a teenage boy named Leonard Thompson became the first person to receive it as a treatment, and his condition improved. Within a few years insulin was being produced on a large scale, saving countless lives worldwide."],
    ["Hunger, sleep and love", "Hormones such as ghrelin, leptin, melatonin and oxytocin shape appetite, sleep and connection.", "Hormones influence everyday feelings more than many people realise. Ghrelin, made mainly in the stomach, tends to rise before meals and helps stir up hunger. Leptin, released by fat tissue, helps signal to the brain how much energy is stored. Melatonin, produced by the pineal gland deep in the brain, rises in the evening as light fades and helps signal that it is time for sleep, which is one reason bright screens late at night can make it harder to drift off. Oxytocin plays key roles in childbirth and breastfeeding, and it is involved in social bonding and trust. It is sometimes nicknamed the love hormone, but scientists caution that its effects are complex and depend heavily on context, so the nickname is a big oversimplification."],
    ["A word for 'set in motion'", "The term hormone dates from 1905, and hormones remain central to modern medicine.", "The idea of chemical messengers is surprisingly recent. In 1902 two physiologists in London, William Bayliss and Ernest Starling, discovered that a substance from the gut, which they called secretin, could trigger the pancreas through the blood rather than through nerves. In 1905 Starling popularised the word hormone, from a Greek word meaning to set in motion or to excite. Since then, hormones have become central to medicine, from treating thyroid conditions to fertility treatment and contraception. Because hormones affect so many systems, symptoms of hormone problems can be vague, such as tiredness, weight changes or feeling unusually hot or cold. This lesson is general information, not medical advice. If something feels off, a GP can arrange tests, and healthdirect is a reliable starting point."]
  ],
  [
    [0, "How do hormones mainly travel to their target cells?", ["Along nerve fibres", "Through the bloodstream", "Through the air we breathe", "Through the lymph nodes only"], 1, "Hormones are released into the blood and carried to cells with the matching receptors."],
    [1, "Which gland is often called the master gland?", ["The thyroid", "The pancreas", "The pituitary", "The adrenal gland"], 2, "The pituitary directs many other glands, although it takes its cues from the hypothalamus."],
    [2, "Why has iodised salt been required in most Australian bread since 2009?", ["To make bread last longer", "To lower blood pressure", "To improve the taste", "To help the thyroid by boosting iodine intake"], 3, "The thyroid needs iodine to make its hormones, and the measure aimed to reduce iodine deficiency."],
    [4, "What does insulin do after a meal?", ["Signals cells to take sugar from the blood", "Releases stored sugar into the blood", "Makes the stomach feel hungry", "Raises the heart rate"], 0, "Insulin helps cells absorb sugar, bringing blood sugar levels back down."],
    [5, "Which hormone rises in the evening as light fades and helps signal sleep?", ["Adrenaline", "Melatonin", "Ghrelin", "Glucagon"], 1, "Melatonin from the pineal gland rises in darkness and helps prepare the body for sleep."]
  ]);

WB.L("liver-chemical-factory", "body", "beginner", "The liver: your chemical factory", "Quietly tucked under your ribs is an organ that stores fuel, builds proteins, breaks down toxins and can even regrow itself. Meet the liver.",
  [
    ["A myth that knew something", "The liver is a remarkable regenerating organ, a fact that echoes an ancient Greek story.", "In Greek mythology, Prometheus stole fire from the gods and was punished by being chained to a rock. Each day an eagle ate his liver, and each night it grew back. Whether the ancient storytellers knew it or not, they picked exactly the right organ. The liver is famous among doctors for its ability to regenerate. If a large part is removed, the remaining tissue can grow and restore much of the organ's size and function within weeks to months. This is what makes living donor liver transplants possible: part of a healthy adult's liver can be given to someone else, and both pieces can grow. Few organs can do anything like it, and it is only one of the liver's many talents."],
    ["Big, busy and well supplied", "The liver is the largest internal organ and receives blood from two sources.", "Your liver sits in the upper right of your abdomen, mostly tucked behind the lower ribs. In an adult it weighs around one and a half kilograms, making it the largest solid organ inside the body. It is also unusually well supplied with blood. Like other organs, it receives oxygen-rich blood through an artery. But most of its blood arrives through a second route, the hepatic portal vein, which carries blood straight from the stomach and intestines. That means nearly everything you absorb from a meal, nutrients, alcohol, medicines and the odd unwanted chemical, passes through the liver before it reaches the rest of your body. The liver gets first look at it all, and gets to decide what to store, change, use or send on."],
    ["A pantry for energy", "The liver stores sugar as glycogen and releases it to keep blood sugar steady between meals.", "After a meal, your blood carries a flood of sugar. With help from insulin, the liver takes some of it in and links the sugar molecules together into a storage form called glycogen. Hours later, when you have not eaten and blood sugar starts to dip, the liver breaks glycogen back down and releases sugar into the blood. This keeps your brain, which relies heavily on sugar for fuel, running smoothly overnight and between meals. When glycogen runs low, during a long fast for example, the liver can make new sugar from other building blocks. It also handles fats, packaging them for transport around the body, and makes cholesterol, which the body uses to build cell membranes and some hormones. Think of the liver as both pantry and kitchen."],
    ["Builder of essential proteins", "The liver makes many vital blood proteins, including those that help your blood clot.", "Cut your finger and, within minutes, the bleeding slows and stops. That depends partly on clotting factors, proteins that work together to form a clot, and the liver makes most of them. It also produces albumin, the most abundant protein in blood plasma, which helps keep fluid inside blood vessels and carries hormones and medicines around the body. Many other transport proteins and parts of the immune system are made here too. Because of this, a liver that is not working well can cause problems that seem to have nothing to do with the liver, such as easy bruising or swelling in the legs. Doctors often check liver function with a blood test that measures some of these proteins along with enzymes that leak out when liver cells are damaged."],
    ["Bile and the colour of things", "The liver makes bile to help digest fat, and recycled red blood cells give bile its colour.", "Every day your liver produces bile, a greenish-yellow fluid that drains into the gallbladder for storage. When you eat a fatty meal, the gallbladder squeezes bile into the small intestine, where it breaks fat into tiny droplets, a bit like washing-up liquid on a greasy pan, so digestive enzymes can work on it. Bile is also a way of getting rid of waste. When old red blood cells are broken down, their haemoglobin is converted into a yellow substance called bilirubin. The liver processes it and sends it out in bile. Gut bacteria then change it further, and that is what gives poo its brown colour. If bilirubin builds up in the blood instead, the skin and the whites of the eyes can turn yellow, a sign called jaundice."],
    ["Clearing the chemical waste", "The liver changes harmful substances, including ammonia and alcohol, into forms the body can remove.", "Your cells constantly produce waste, and some of it is toxic. When proteins are broken down, they release ammonia, which is harmful to the brain at high levels. The liver converts it into urea, a much safer substance that the kidneys then flush out in urine. The liver also chemically alters many medicines, hormones and foreign substances, often making them easier to excrete. Alcohol is a major example. The liver breaks it down at a fairly fixed pace, often estimated at around one standard drink an hour, and nothing such as coffee or a cold shower speeds this up. This is also why so-called detox teas and cleanses are unnecessary for healthy people: the liver and kidneys already do this job continuously, and they do it well."],
    ["The silent organ", "Liver problems often cause no symptoms early on, so prevention and checks matter.", "The liver has few pain nerves inside it and a lot of spare capacity, so it can be quite damaged before a person feels unwell. One of the most common liver problems today is a build-up of fat in the liver, often linked with being overweight, type 2 diabetes and inactivity. It frequently causes no symptoms at first, and it can often improve with changes to diet, activity and weight. Heavy drinking and viral hepatitis are other major causes of liver damage. Australia offers vaccination against hepatitis B, and effective treatments now exist for hepatitis C. Remember that this is general information, not medical advice. If you have concerns about your liver, talk to your GP, who can arrange simple blood tests, and see healthdirect for reliable background."]
  ],
  [
    [0, "Why are living donor liver transplants possible?", ["The liver can regenerate after part is removed", "Humans have two livers", "The liver is not essential for life", "Liver tissue never gets rejected"], 0, "Part of a healthy liver can be donated and both portions can regrow."],
    [1, "What does the hepatic portal vein carry to the liver?", ["Blood from the lungs", "Blood straight from the stomach and intestines", "Bile from the gallbladder", "Urine from the kidneys"], 1, "Most of the liver's blood comes from the gut, so absorbed substances pass through the liver first."],
    [2, "In what form does the liver store sugar?", ["Albumin", "Bile", "Glycogen", "Urea"], 2, "The liver links sugar molecules into glycogen and breaks it down again when blood sugar drops."],
    [4, "What gives poo its typical brown colour?", ["Undigested fibre", "Stomach acid", "Iron from meat", "Bilirubin from old red blood cells, changed by gut bacteria"], 3, "Bilirubin from recycled red blood cells is sent out in bile and altered by gut bacteria."],
    [5, "What does the liver convert ammonia into?", ["Urea", "Glucose", "Cholesterol", "Melatonin"], 0, "Ammonia is turned into urea, which the kidneys then remove in urine."]
  ]);

WB.L("kidneys-filters", "body", "intermediate", "Your kidneys: the body's master filters", "Two fist-sized organs filter your entire blood supply many times a day, balancing water, salt and acid with exquisite precision.",
  [
    ["A surprising workload", "Your kidneys filter around 180 litres of fluid a day but make only about one and a half litres of urine.", "Each kidney is roughly the size of a fist and shaped, unsurprisingly, like a kidney bean. They sit against the back wall of the abdomen, partly protected by the lower ribs. Despite their modest size, they receive about a fifth of all the blood the heart pumps. Every day they filter something like 180 litres of fluid out of the blood, enough to fill a large bathtub. Yet a typical adult produces only around one and a half litres of urine. That means the kidneys reclaim about 99 per cent of what they filter, carefully choosing what to keep and what to throw away. The kidneys' real skill is not simply removing waste, but deciding, moment by moment, exactly how much of everything the body should hold onto."],
    ["The nephron", "Each kidney contains around a million tiny filtering units called nephrons.", "The working unit of the kidney is the nephron, and each kidney has roughly a million of them, though the number varies a lot between people. A nephron begins with a glomerulus, a tiny tangle of capillaries where blood pressure pushes water and small molecules through a fine filter, while blood cells and most proteins stay behind. The filtered fluid then flows into a long, twisting tube. Along its length, cells lining the tube pull back the useful things, such as sugar, salts, amino acids and most of the water, and return them to the blood. They also actively push some extra wastes and excess substances into the tube. What remains at the end becomes urine, which drains into collecting ducts and then out of the kidney towards the bladder."],
    ["Balancing water", "A hormone from the brain tells the kidneys how much water to save, which is why urine colour changes.", "Spend a long, hot day working outdoors in the Pilbara without drinking enough, and your urine becomes darker and smaller in volume. Drink a lot of water on a cool day, and it becomes pale and plentiful. The kidneys are responding to instructions. When your blood becomes too concentrated, sensors in the brain trigger the release of antidiuretic hormone, also called vasopressin, from the pituitary gland. This hormone makes the final parts of the nephron more permeable to water, so more is reabsorbed and urine becomes concentrated. Alcohol suppresses this hormone, which is partly why drinking makes people urinate more and can leave them dehydrated. Urine colour is a handy rough guide to hydration, though some vitamins, foods and medicines can change it too."],
    ["Salt, potassium and blood pressure", "By adjusting how much sodium and water they keep, the kidneys help set long-term blood pressure.", "Sodium and potassium are essential for nerves and muscles, including the heart, and their levels must be kept in a fairly narrow range. The kidneys fine-tune both. They are also central to blood pressure. When blood flow to the kidneys falls, they release an enzyme called renin, which starts a chain of reactions involving a hormone system that narrows blood vessels and signals the body to retain salt and water. More fluid in the circulation means higher pressure. This system is useful after blood loss, but it is also why several common blood pressure medicines work by acting on this pathway or on the kidneys' handling of salt. The link runs both ways too: long-term high blood pressure can damage the delicate filters inside the kidneys."],
    ["Acid, bones and blood", "The kidneys also manage the blood's acidity, activate vitamin D and signal the body to make red blood cells.", "Filtering is only part of the job. Your metabolism constantly produces acids, and the kidneys help keep the blood's acidity in a tight range by getting rid of acid and holding onto bicarbonate, a natural buffer. The kidneys also act as hormone factories. When oxygen levels in the kidney fall, as they do at high altitude or after significant blood loss, the kidneys release erythropoietin, often shortened to EPO, which tells the bone marrow to make more red blood cells. A synthetic version is a vital medicine for some patients, and it became notorious when misused as a doping drug in endurance sport. The kidneys also complete the activation of vitamin D, which the body needs to absorb calcium, so healthy kidneys matter for healthy bones."],
    ["Stones and other troubles", "Kidney stones form when minerals crystallise in urine, and dehydration is a common contributor.", "Kidney stones are hard deposits that form when minerals in urine, most often calcium combined with oxalate, become concentrated enough to crystallise. Small stones may pass unnoticed, but a stone moving down the narrow tube to the bladder can cause sudden, severe pain that people often rank among the worst they have experienced. Being dehydrated is a common contributor, which is relevant in hot parts of Australia. Kidneys can also be gradually harmed by long-term diabetes and high blood pressure, two of the leading causes of chronic kidney disease. Because the kidneys have so much reserve, chronic kidney disease often causes no symptoms until a lot of function has been lost. Simple blood and urine tests can pick it up early, when steps to protect the kidneys are most effective."],
    ["Living with one, or with none", "People can live well with one kidney, and dialysis or a transplant can replace failed kidneys.", "Because the kidneys have so much spare capacity, most people can live a normal life with just one, which is why living kidney donation is possible. The first successful kidney transplant took place in Boston in 1954, between identical twins, which avoided the problem of rejection. When both kidneys fail, a person needs either dialysis, where a machine or the lining of the abdomen is used to filter the blood, or a transplant. In Australia you can register your decision to be an organ and tissue donor through the Australian Organ Donor Register, which is run by Services Australia, and talking about your wishes with family is important too. This lesson is general information, not medical advice. For questions about kidney health, speak with your GP or visit healthdirect."]
  ],
  [
    [0, "About what proportion of the fluid they filter do the kidneys reclaim?", ["About 10 per cent", "About half", "About 75 per cent", "About 99 per cent"], 3, "Of roughly 180 litres filtered daily, only about one and a half litres leaves as urine."],
    [1, "What is the glomerulus?", ["A tangle of capillaries where blood is first filtered", "The tube that carries urine to the bladder", "A hormone that controls water", "A type of kidney stone"], 0, "The glomerulus is the filtering start of each nephron, where pressure pushes fluid out of the blood."],
    [2, "Why can alcohol leave people dehydrated?", ["It blocks the glomerulus", "It suppresses antidiuretic hormone, so less water is reabsorbed", "It stops the bladder emptying", "It makes the kidneys release EPO"], 1, "With less antidiuretic hormone, the kidneys save less water and more urine is produced."],
    [4, "What does erythropoietin (EPO) from the kidneys do?", ["Breaks down kidney stones", "Lowers blood pressure", "Tells bone marrow to make more red blood cells", "Activates insulin"], 2, "When oxygen in the kidney is low, EPO signals the bone marrow to boost red blood cell production."],
    [6, "Why was the first successful kidney transplant, in 1954, between identical twins?", ["Twins have larger kidneys", "It avoided the problem of rejection", "It was required by law", "Twins need only one kidney"], 1, "Identical twins are genetically matched, so the recipient's immune system did not reject the organ."]
  ]);

WB.L("gut-microbiome", "body", "intermediate", "Your microbiome: the trillions living inside you", "You are not just you. Your gut is home to a vast, bustling community of microbes that digest food you cannot, train your immune system and may even chat with your brain.",
  [
    ["An inner rainforest", "Your large intestine hosts a vast, diverse ecosystem of microbes, mostly bacteria.", "If you could shrink down and wander into your large intestine, you would find something like a rainforest: crowded, warm, dark and teeming with life. Living there are trillions of microorganisms, mostly bacteria, along with archaea, fungi and viruses. Together they are called the gut microbiota, and their combined genes are often called the microbiome. Hundreds of different species may live in one person's gut, and the mix is so individual that it is sometimes compared to a fingerprint. Most of these microbes are not germs in the frightening sense. They are long-term residents that have evolved alongside humans, and many of them are helpful or harmless. In total, the microbes in your gut weigh perhaps a couple of hundred grams, roughly the weight of a mango."],
    ["Are we really outnumbered?", "An old claim of ten microbes for every human cell has been revised to roughly one to one.", "For decades, textbooks and popular articles repeated a striking claim: microbial cells in the body outnumber human cells by about ten to one. It made a great headline, but it was based on a rough estimate from the 1970s. In 2016, researchers recalculated the numbers more carefully and concluded the ratio is closer to one to one, with tens of trillions of each. The exact figure shifts with every trip to the toilet, since faeces contain a large share of gut bacteria. The lesson here is a good one for any curious reader: catchy statistics sometimes survive long after the evidence for them has been questioned. Even at one to one, though, the microbes in and on your body form an enormous and important community."],
    ["Eating what you cannot", "Gut microbes ferment fibre that human enzymes cannot digest, producing useful short-chain fatty acids.", "Humans make enzymes that digest sugars, starches, proteins and fats, but we lack the enzymes to break down many types of dietary fibre, such as those in legumes, oats, wholegrains, vegetables and fruit. That fibre travels largely intact to the large intestine, where gut microbes take over. They ferment it, producing gases, which explains why a big serve of baked beans can have noisy consequences, and also substances called short-chain fatty acids. One of these, butyrate, is a key fuel for the cells lining the colon. Short-chain fatty acids also appear to influence inflammation and metabolism elsewhere in the body. Gut bacteria help make some vitamins too, including vitamin K. In a real sense, eating fibre is a way of feeding the microbes that help feed you."],
    ["Training the immune system", "Gut microbes help educate the immune system and crowd out harmful invaders.", "Much of the body's immune tissue sits along the gut, where it faces a tricky task: attacking dangerous germs while tolerating food and friendly microbes. Studies, particularly in laboratory animals raised completely free of germs, show that the immune system develops abnormally without a microbiome, which suggests these microbes help train it. A healthy, diverse community also provides colonisation resistance, which simply means it takes up space and resources, making it harder for harmful bacteria to gain a foothold. This is one reason a course of broad-spectrum antibiotics, which can kill helpful bacteria along with harmful ones, sometimes leads to diarrhoea. Antibiotics are essential, life-saving medicines when they are needed, but this side effect is a reminder that they are not harmless and should be used only when appropriate."],
    ["A first gift at birth", "The microbiome begins forming at birth and changes through life, shaped by diet, environment and medicines.", "A baby's gut is thought to be largely free of microbes before birth. The colonisation begins during and after delivery, as the baby picks up microbes from the mother, the environment and early feeding. Babies born vaginally and by caesarean section tend to start with somewhat different microbial communities, although those differences seem to narrow over the first months and years. Breast milk contains special sugars that the baby cannot digest but certain beneficial bacteria can, a striking example of feeding microbes. Over the first few years the microbiome becomes more diverse and more adult-like. After that, it is relatively stable, but it continues to respond to diet, illness, travel, medicines and age. Older adults often show changes in their microbiome, though researchers are still working out what that means."],
    ["Faecal transplants and the gut-brain link", "Faecal transplants can cure one stubborn infection, while gut-brain research is promising but early.", "One of the most dramatic proofs that gut microbes matter comes from faecal microbiota transplantation. It sounds unappealing, but for people with recurring infections of a bacterium called Clostridioides difficile, often triggered by antibiotics, transferring screened stool from a healthy donor can restore a healthy community and has proved remarkably effective. Researchers are also exploring the gut-brain axis, the network of nerves, hormones and immune signals linking the gut and the brain. Animal studies suggest microbes can influence behaviour and mood, and human studies have found associations with various conditions. But association is not the same as cause, and much of this work is still early. Be wary of headlines claiming that a particular bacterium causes or cures complex conditions in people. The science is fascinating, but still unfolding."],
    ["Caring for your microbes", "A varied diet rich in plant fibre is the best-supported way to support a diverse microbiome.", "So what can an ordinary person do? The best-supported advice is not exotic. Eating a wide variety of plant foods, such as vegetables, fruit, legumes, wholegrains, nuts and seeds, provides the range of fibres that different microbes thrive on. Fermented foods such as yoghurt, kefir and kimchi contain live microbes, and some studies suggest they may increase microbial diversity, though more research is needed. Probiotic supplements are widely sold, but evidence for them varies greatly depending on the strain and the condition, and many claims run ahead of the science. Using antibiotics only when they are genuinely needed also helps protect your microbes. This lesson is general information, not medical advice, so talk with your GP or an accredited practising dietitian if you have specific gut concerns."]
  ],
  [
    [1, "What did a 2016 recalculation suggest about the ratio of microbial to human cells?", ["About one hundred to one", "About ten to one", "Roughly one to one", "About one to ten"], 2, "The famous ten to one figure was revised to roughly one to one, with tens of trillions of each."],
    [2, "What do gut microbes produce when they ferment dietary fibre?", ["Short-chain fatty acids such as butyrate", "Insulin", "Bile", "Haemoglobin"], 0, "Fermenting fibre yields short-chain fatty acids, including butyrate, a key fuel for colon cells."],
    [3, "What does colonisation resistance mean?", ["Microbes resisting antibiotics", "The immune system rejecting food", "The colon refusing to absorb water", "Friendly microbes making it harder for harmful bacteria to settle in"], 3, "A healthy microbial community occupies space and resources, crowding out invaders."],
    [4, "Why does breast milk contain sugars babies cannot digest?", ["They pass straight through as waste", "They feed certain beneficial gut bacteria", "They protect the baby's teeth", "They are needed for bone growth"], 1, "These special sugars nourish helpful bacteria in the baby's developing gut."],
    [5, "For which problem have faecal microbiota transplants proved remarkably effective?", ["Recurring Clostridioides difficile infections", "Broken bones", "Short-sightedness", "Seasonal hay fever"], 0, "Transplanting screened donor stool can restore a healthy gut community and clear recurring C. difficile."]
  ]);

WB.L("why-we-age", "body", "advanced", "Why we age: the biology of growing old", "Some tortoises seem barely to age, while mice are old at three. What is actually happening inside our cells as the years go by, and why did evolution let it happen at all?",
  [
    ["Ageing is not wear and tear", "Ageing is a gradual build-up of damage and declining repair, not simply parts wearing out like a machine.", "It is tempting to think of the body like a car that slowly wears out. But that picture misses something important: unlike a car, the body constantly repairs itself. Cells are replaced, proteins are recycled and damaged DNA is fixed, often thousands of times a day in a single cell. Ageing seems to happen as damage gradually accumulates faster than these repair systems can keep up, and as the repair systems themselves become less effective. The result is a slow decline in how well tissues work and how well the body bounces back from stress, illness or injury. Ageing is also the biggest single risk factor for many major diseases, including heart disease, many cancers and dementia, which is why scientists study it so intensely."],
    ["Why evolution allowed it", "Natural selection weakens with age, so genes with late harmful effects are not strongly weeded out.", "If ageing is harmful, why has evolution not eliminated it? A key insight came from biologists in the mid twentieth century, including Peter Medawar and George Williams. In the wild, most animals die young from predators, accidents, disease or starvation, long before old age could matter. Natural selection is therefore powerful in youth, when survival and reproduction are at stake, but weak in later life. A gene that causes harm only in old age may barely be selected against. Worse, a gene that helps an animal grow fast and breed early might be favoured even if it causes damage decades later. This idea, sometimes called antagonistic pleiotropy, suggests that ageing is partly the price of traits that served our ancestors well when they were young."],
    ["The shrinking telomere", "Telomeres, the protective caps on chromosomes, tend to shorten as cells divide.", "At the ends of each chromosome sit telomeres, repeating stretches of DNA that protect the genetic material, often compared to the plastic tips on shoelaces. Every time most cells divide, the telomeres get a little shorter, because the copying machinery cannot fully copy the very ends. When telomeres become too short, the cell typically stops dividing or dies. In the 1960s, Leonard Hayflick showed that normal human cells grown in the laboratory can divide only a limited number of times, a ceiling now called the Hayflick limit. An enzyme called telomerase can rebuild telomeres and is active in some cells, such as certain stem cells. Many cancer cells switch it on, which helps them divide indefinitely. That link shows why simply boosting telomerase is not a safe anti-ageing shortcut."],
    ["Zombie cells", "Senescent cells stop dividing but linger, releasing inflammatory signals that can harm nearby tissue.", "When cells are damaged or their telomeres run short, some enter a state called senescence. They stop dividing, which is useful because it helps prevent damaged cells turning cancerous. But senescent cells do not always die. They can linger and pump out a mixture of inflammatory chemicals that disturb surrounding tissue. Scientists have nicknamed them zombie cells. Normally the immune system clears them, but with age they seem to build up in many tissues. The low-grade, chronic inflammation that tends to rise with age, sometimes called inflammaging, may be partly driven by these cells. In experiments on mice, clearing senescent cells has improved some measures of health. Drugs designed to do this, called senolytics, are being tested in people, but it is too soon to know whether they will be safe and useful."],
    ["Hallmarks of ageing", "Researchers group the causes of ageing into a set of interconnected hallmarks.", "In 2013, a group of scientists proposed a now widely cited framework that described nine hallmarks of ageing, later expanded in an updated version. The list includes damage to DNA, shortening telomeres, changes in how genes are switched on and off, a breakdown in keeping proteins correctly folded, faltering mitochondria, the cells' energy producers, senescent cells, exhausted stem cells, altered communication between cells, and chronic inflammation. Crucially, these processes are interlinked. Damaged mitochondria can produce harmful molecules that damage DNA, which can push cells into senescence, which drives inflammation, which harms stem cells. Rather than a single cause, ageing looks more like a web of problems that feed into one another. That complexity is one reason no single pill or treatment has been shown to halt human ageing."],
    ["Lessons from long-lived creatures", "Some animals live remarkably long lives, and lab studies show ageing can be slowed in some species.", "Nature offers striking variety. The naked mole-rat, a small burrowing rodent, can live for over 30 years, many times longer than a mouse of similar size, and seems to show unusually few signs of ageing for most of its life. Greenland sharks are estimated to live for several centuries, and some tortoises have lived well beyond a hundred years. In the laboratory, researchers have extended the lifespan of worms, flies and mice using genetic changes, certain drugs and reducing calorie intake without causing malnutrition. These findings show that ageing is not fixed and can be modified, at least in some animals. Translating this to humans is far harder. People live a long time, so trials take decades, and results in mice often fail to carry over to us."],
    ["What you can actually do", "No proven anti-ageing pill exists, but well-established habits support healthier ageing.", "The anti-ageing industry sells many supplements and treatments, but none has been proven to slow human ageing itself. What the evidence does support is less glamorous and more reliable. Regular physical activity, including strength training, is strongly linked with healthier ageing and helps preserve muscle, bone and balance. Not smoking, limiting alcohol, eating a mostly plant-rich diet, getting enough sleep, protecting your skin from the sun and staying socially connected all appear to help. Managing blood pressure and blood sugar protects the heart, brain and kidneys. Genes matter too, but lifestyle and environment usually play a larger role in how people age. This lesson is general information, not medical advice. Your GP is the best person to talk to about health checks as you get older."]
  ],
  [
    [1, "According to evolutionary theory, why has ageing not been eliminated?", ["Ageing helps species evolve faster", "Natural selection is weak on harms that appear only in later life", "Old animals are needed to teach the young", "Evolution has not had enough time"], 1, "Because most wild animals die young, genes with late harmful effects are poorly weeded out."],
    [2, "What is the Hayflick limit?", ["The maximum human lifespan", "The size limit of a chromosome", "The limited number of times normal cells can divide in the lab", "The point at which telomerase switches on"], 2, "Hayflick showed normal human cells stop dividing after a limited number of divisions."],
    [3, "Why are senescent cells nicknamed zombie cells?", ["They stop dividing but linger and release harmful inflammatory signals", "They come back to life after dying", "They attack the brain", "They only appear after death"], 0, "Senescent cells stop dividing yet persist, disturbing surrounding tissue with inflammatory chemicals."],
    [4, "What is the key idea behind the hallmarks of ageing?", ["Ageing has one single cause", "Ageing affects only the skin", "Ageing can be stopped with one drug", "Several interlinked processes feed into each other"], 3, "The hallmarks are interconnected, making ageing a web of problems rather than a single cause."],
    [5, "Why is it hard to test anti-ageing treatments in humans?", ["Humans do not age", "People live a long time, so trials take decades", "There are no long-lived animals to compare", "Ageing cannot be measured at all"], 1, "Long human lifespans make trials slow, and mouse results often fail to translate."]
  ]);

WB.L("science-of-pain", "body", "advanced", "The science of pain", "Pain feels like a simple signal from an injury, but it is really the brain's best guess about danger. That surprising idea changes how we understand hurt.",
  [
    ["A nail through the boot", "Pain is produced by the brain and does not always match the amount of tissue damage.", "A famous case reported in the British Medical Journal in 1995 describes a builder who jumped onto a 15 centimetre nail. It went straight through his boot, and he was in agony. Even small movements hurt, and he was given strong pain relief. When doctors carefully removed the boot, they found the nail had passed between his toes without touching his foot at all. On the other side of the coin, people sometimes suffer serious injuries in emergencies or sport and feel little at first. These stories reveal something profound. Pain is not a direct readout of damage. It is something the brain produces, based on all the information it has, to protect you from what it judges to be a threat."],
    ["Nociception: the danger signal", "Special nerve endings called nociceptors detect potential harm and send warning signals to the spinal cord.", "Throughout your skin, muscles, joints and organs are nerve endings called nociceptors. They respond to things that could cause harm, such as intense pressure, extreme heat or cold, and certain chemicals released by damaged tissue. When triggered, they send signals along nerve fibres to the spinal cord and up to the brain. Scientists call this process nociception, which simply means the detection of danger. Nociception is not the same as pain. Signals can arrive without pain being felt, and pain can occur without them. Different nerve fibres also carry signals at different speeds. Stub your toe and you often feel a sharp first jolt, followed a moment later by a duller, throbbing ache, as faster and slower fibres deliver their messages one after the other."],
    ["Pain without injury, injury without pain", "The brain weighs context, attention, expectations and emotions when deciding how much something hurts.", "Once warning signals reach the brain, they do not simply switch pain on. Many brain regions get involved, weighing the signal against context, memories, attention, mood and expectations. That is why the same injury can feel very different in different situations. A paper cut during a stressful day may sting far more than a scrape during an exciting footy match. Anxiety and fear tend to amplify pain, while distraction and feeling safe can reduce it. An extreme example is phantom limb pain, where people feel pain in a limb that has been amputated. There is no tissue left to be damaged, yet the pain is real, because the brain's map of the body still includes the missing limb. All pain is real, whatever its source."],
    ["The pain gate", "Signals in the spinal cord can be turned up or down, which is why rubbing a bump helps.", "Bang your elbow and you will probably rub it without thinking. That instinct has a scientific explanation. In 1965, Ronald Melzack and Patrick Wall proposed the gate control theory of pain. They suggested that nerve circuits in the spinal cord act like a gate, letting more or fewer pain-related signals through to the brain. Signals from touch and pressure, carried by other nerve fibres, can partly close the gate, which is why rubbing a bruise can bring some relief. The brain can also send signals down the spinal cord to turn pain up or down. Details of the original theory have since been revised, but its central idea, that the nervous system actively modulates pain rather than passively transmitting it, transformed pain science and remains influential."],
    ["The body's own painkillers", "The brain makes natural opioid-like chemicals, which help explain stress-induced pain relief and placebo effects.", "In the 1970s scientists discovered that the brain has receptors that respond to opium-derived drugs such as morphine. That raised an obvious question: why would the brain have receptors for a plant chemical? The answer was that the body makes its own similar substances, including endorphins. The name comes from a combination of endogenous, meaning made within, and morphine. These natural painkillers help dampen pain during intense stress, injury and exercise. They also appear to play a role in some placebo effects, where expecting pain relief can genuinely reduce pain. Medicines that act on these same receptors, opioids, are powerful painkillers but can cause dependence and dangerous side effects, which is why in Australia they are tightly regulated and are prescribed with caution."],
    ["When pain outstays its welcome", "Chronic pain can persist after healing as the nervous system becomes more sensitive.", "Acute pain is the short-term pain of an injury, and it usually fades as the tissue heals. Chronic pain is usually defined as pain that lasts longer than about three months, and it is very common. Australian health organisations estimate that around one in five adults lives with chronic pain. In many cases, the nervous system itself has changed, becoming more sensitive so that it produces pain more easily, a process called central sensitisation. In effect, the alarm system has become overprotective, sounding the alarm even when the danger is small or gone. This does not mean the pain is imagined. It means that treating chronic pain often requires more than looking for ongoing damage, and may need to address the nervous system's sensitivity as well."],
    ["New approaches to living with pain", "Modern pain care often combines movement, education, sleep and psychological strategies with medicines.", "Understanding pain as a protective output of the brain has changed how many people are treated. For persistent pain, approaches often combine several elements: graded physical activity that gradually builds confidence and capacity, good sleep, stress management, and pain education that explains how the nervous system works. Psychological therapies can help people reduce fear and get back to activities they value. Medicines still have a place, but for many types of chronic pain, relying on them alone tends to work less well than a combined approach. Australian researchers have been prominent in this field of pain education. This lesson is general information and is not medical advice. If you are living with pain, talk to your GP, and healthdirect and Painaustralia offer helpful starting points."]
  ],
  [
    [0, "What did the case of the builder and the nail reveal?", ["Nails cannot pierce boots", "Severe pain can occur without any tissue damage", "Pain relief does not work on builders", "Feet have no pain receptors"], 1, "The nail missed his foot entirely, yet he felt intense pain, showing pain is produced by the brain."],
    [1, "What is nociception?", ["The feeling of pain itself", "A type of painkiller", "The detection of potentially harmful stimuli by nerve endings", "The healing of tissue"], 2, "Nociception is danger detection, which is not the same as the experience of pain."],
    [3, "According to gate control theory, why does rubbing a bumped elbow help?", ["Touch signals can partly close a gate in the spinal cord", "Rubbing removes the bruise", "It speeds up tissue healing instantly", "It numbs the skin with heat"], 0, "Touch and pressure signals can reduce pain-related signals passing through the spinal cord."],
    [4, "Where does the word endorphin come from?", ["A Greek word for joy", "The name of its discoverer", "A type of plant", "Endogenous plus morphine"], 3, "Endorphin combines endogenous, meaning made within, and morphine."],
    [5, "What is central sensitisation?", ["The nervous system becoming more sensitive, producing pain more easily", "A loss of all feeling", "Pain caused only by infection", "Healing of nerves after injury"], 0, "In central sensitisation the nervous system's alarm becomes overprotective, a common feature of chronic pain."]
  ]);
