/* WISEBYTE LESSONS · Music */
WB.L("how-music-works", "arts", "beginner", "How music works",
  "Every song you love is just air, pushed back and forth in careful patterns. Here is how those patterns become music.",
  [
    ["Sound is a wave", "Sound is a pressure wave travelling through air at about 343 metres per second.",
      "When a guitar string vibrates, it pushes the air molecules beside it, squeezing them together and then letting them spread apart. That pattern of squeezes and stretches travels outwards as a pressure wave, at about 343 metres per second in air at room temperature, roughly a kilometre every three seconds. When the wave reaches you, it nudges your eardrum back and forth in the same pattern. Tiny bones pass the movement to the cochlea, a fluid-filled spiral in your inner ear, where hair cells turn it into nerve signals. Music, at its most basic, is organised vibration."],
    ["Pitch and frequency", "Pitch is how we hear frequency: faster vibrations sound higher.",
      "How high or low a note sounds depends on its frequency, the number of vibrations per second, measured in hertz (Hz). A healthy young ear hears roughly 20 Hz to 20,000 Hz, and the upper limit falls steadily with age. The A above middle C, which orchestras tune to, is usually set at 440 Hz. Double any frequency and you get the same note an octave higher, so the next A up is 880 Hz. That doubling is why notes an octave apart sound so alike that men and women singing the 'same' tune together are often an octave apart without noticing."],
    ["Why instruments sound different", "Timbre, the colour of a sound, comes from the mix of overtones above the main note.",
      "A piano and a violin can play exactly the same pitch and still sound completely different. The reason is timbre, sometimes called tone colour. Almost no instrument produces a single pure frequency. Alongside the main note, called the fundamental, it produces fainter overtones at higher frequencies, often simple multiples of the fundamental. Each instrument has its own recipe of overtones, plus its own way of starting and fading a note: the sharp strike of a piano hammer, the smooth swell of a bowed string. Your brain reads that recipe instantly, which is how you can recognise a familiar voice from a single word."],
    ["Rhythm and beat", "Rhythm is the pattern of sounds in time; the beat is the steady pulse underneath.",
      "The beat is the steady pulse you tap your foot to, and tempo is its speed, measured in beats per minute. A slow ballad might sit around 60 to 80 beats per minute, while much dance music runs at about 120 to 130. Beats are grouped into bars, most commonly four beats to a bar, though waltzes use three. Rhythm is the pattern of long and short sounds laid over that pulse. Humans are unusually good at locking onto a beat; very few other animals do it naturally, though some parrots have been filmed bobbing in time to music."],
    ["Melody", "A melody is a sequence of pitches in rhythm that the mind hears as a single shape.",
      "A melody is a line of notes, one after another, that your brain groups into a single shape, the part you hum in the shower. Good melodies usually balance repetition and surprise: they repeat short ideas, called motifs, so you can follow them, then vary them just enough to stay interesting. Most move in small steps between neighbouring notes, with occasional leaps for drama. Melodies also tend to rise and fall like a sentence, building to a high point and settling back home. That feeling of returning 'home' at the end is one of the strongest pulls in music."],
    ["Scales", "A scale is the set of notes a piece draws on; Western music divides the octave into 12 semitones.",
      "Most Western music divides each octave into 12 equally spaced steps called semitones, the white and black keys on a piano. A scale is a chosen subset of those notes. The familiar major scale uses seven, the do-re-mi you may have learned at school. The pentatonic scale uses just five and turns up in folk music across the world, from Scotland to China to West Africa, which is one reason simple tunes can feel universal. Other traditions divide the octave differently: Indian classical music and Arabic music use pitches that fall between the keys of a piano."],
    ["Harmony", "Harmony is notes sounding together; simple frequency ratios tend to sound smooth or 'consonant'.",
      "Harmony is what happens when notes sound at the same time. A chord is three or more notes played together, usually built by stacking notes from a scale. Some combinations sound smooth and stable, called consonant; others sound tense and restless, called dissonant. Consonant intervals tend to have simple frequency ratios: an octave is 2 to 1, and a perfect fifth, the interval at the start of many fanfares, is 3 to 2. Their sound waves line up neatly. Much of music's drama comes from building tension with dissonance and then releasing it by resolving to a consonant chord."],
    ["Happy chords, sad chords", "Major chords tend to sound bright and minor chords darker, partly from acoustics and partly from learning.",
      "Listeners raised on Western music usually hear major chords as bright or happy and minor chords as darker or sad. The difference is small: in a minor chord, the middle note is one semitone lower. Why it matters so much is still debated. Some researchers point to acoustics, and to similarities with the way sad speech is lower and flatter. Others stress learning, since the association varies between cultures and eras. Context counts too: a minor key at a fast tempo can sound energetic rather than sad. Next time a song moves you, listen for where the key or tempo changes."]
  ],
  [
    [1, "If a note vibrates at 440 Hz, what frequency is the same note one octave higher?", ["220 Hz", "660 Hz", "880 Hz", "4,400 Hz"], 2, "Going up an octave doubles the frequency, so 440 Hz becomes 880 Hz."],
    [2, "Why does a violin sound different from a piano playing the same note?", ["They play at different speeds of sound", "Each has a different mix of overtones, called timbre", "The violin's note is always louder", "Pianos can only play pure frequencies"], 1, "Timbre comes from each instrument's particular recipe of overtones and the way notes start and fade."],
    [5, "How many semitones divide the octave in most Western music?", ["5", "7", "8", "12"], 3, "The octave is split into 12 semitones, the white and black keys of a piano."],
    [6, "What is the frequency ratio of a perfect fifth?", ["3 to 2", "2 to 1", "5 to 4", "9 to 8"], 0, "A perfect fifth has a 3 to 2 ratio; 2 to 1 is an octave."],
    [7, "Why do minor chords tend to sound sad to many listeners?", ["They are always played more slowly", "Scientists have proven it is purely acoustic", "It seems to be a mix of acoustics and cultural learning, and is still debated", "Minor chords contain no consonant intervals"], 2, "The link is real for many listeners, but its cause is debated: acoustics and learned association both seem to play a part."]
  ],
  { popularity: 78, related: ["instruments", "music-brain", "senses"] }
);

WB.L("instruments", "arts", "beginner", "The world of instruments",
  "Blow, bow, pluck, strike or switch it on: every instrument ever made uses one of a handful of tricks to shake the air.",
  [
    ["Five ways to make a sound", "Instruments are classified by what vibrates: a solid body, a skin, a string, air, or electricity.",
      "In 1914, the musicologists Erich von Hornbostel and Curt Sachs published a system for sorting instruments by what actually vibrates. Idiophones vibrate their whole body, like bells, rattles and xylophones. Membranophones use a stretched skin, like most drums. Chordophones use strings, from the harp to the guitar. Aerophones vibrate a column of air, like flutes, trumpets and the didgeridoo. A fifth group, electrophones, was added later for instruments that make sound electronically. Museums still use this system, because it works for instruments from any culture, not just the European orchestra."],
    ["Strings", "Stringed instruments vibrate a string and use a hollow body to make the sound louder.",
      "A vibrating string on its own is surprisingly quiet, because it moves very little air. Stringed instruments solve this with a hollow wooden body that resonates and amplifies the sound. Players change pitch in three ways: string length (pressing a finger on the neck shortens it), tension (tuning pegs tighten or loosen it) and thickness (heavier strings sound lower). Violins, violas, cellos and double basses are usually bowed, and the bow's horsehair is coated in rosin so it grips the string. Guitars, harps and lutes are plucked, and the piano, surprisingly, is a stringed instrument whose strings are struck."],
    ["Wind and brass", "Woodwinds use a reed or an edge to start the air vibrating; brass players buzz their lips.",
      "Wind instruments set a column of air vibrating inside a tube, and the tube's length sets the pitch. Woodwinds start the vibration in two main ways. A flute player blows across an edge, like blowing over a bottle. Clarinets and saxophones use a single cane reed, and oboes and bassoons use a double reed. Covering holes changes the tube's effective length. Brass players buzz their lips into a cup-shaped mouthpiece, and valves or a slide add extra tubing to lower the pitch. The family is defined by the lips, not the metal: the saxophone is brass-coloured, but it is a woodwind."],
    ["Percussion", "Percussion covers anything struck, shaken or scraped, and is the oldest family of all.",
      "Percussion instruments are struck, shaken or scraped, and they are almost certainly the oldest instruments, since clapping hands and hitting sticks require no technology at all. Some percussion is untuned, like snare drums, cymbals and shakers, adding rhythm and texture. Others are tuned to definite pitches, like the timpani, xylophone, glockenspiel and the steel pans of Trinidad and Tobago, invented in the twentieth century from oil drums. The Indonesian gamelan orchestra is built largely around tuned gongs and metal bars. Percussionists in an orchestra often play a dozen different instruments in a single concert."],
    ["The yidaki", "The yidaki, widely known as the didgeridoo, comes from the Yolŋu people of north-east Arnhem Land.",
      "The instrument most Australians call the didgeridoo is known to the Yolŋu people of north-east Arnhem Land as the yidaki, and it has other names in other languages. Traditionally it is made from a eucalyptus branch hollowed out by termites. Players buzz their lips to create a deep drone and use circular breathing, breathing in through the nose while pushing air out from the cheeks, to keep the sound going without a break. Rock art suggests it has been played in northern Australia for at least a thousand years. The word 'didgeridoo' itself is not from an Aboriginal language and is probably imitative of the sound."],
    ["Respecting the yidaki", "The yidaki has ceremonial significance, and cultural protocols guide how and by whom it is played.",
      "For Yolŋu and other Aboriginal communities, the yidaki is not just an instrument. It accompanies songs and dances in ceremony, and its sounds and rhythms can be connected with particular clans, places and stories. Cultural protocols guide how it is made, played and shared, and these differ between communities. In some, playing it is traditionally a men's role, and some Aboriginal people ask that women not play it, while views vary elsewhere. If you want to buy or learn the yidaki, a respectful approach is to buy from Aboriginal-owned makers and art centres and to learn about the protocols from Aboriginal teachers."],
    ["The piano", "The piano was invented by Bartolomeo Cristofori in Florence around 1700.",
      "Before the piano, the main keyboard instrument was the harpsichord, which plucks its strings and plays at much the same volume however hard you press. Around 1700 in Florence, the instrument maker Bartolomeo Cristofori built a keyboard whose keys threw small leather-covered hammers at the strings, then let them bounce away. For the first time, pressing harder made a louder note. Its full name, pianoforte, means 'soft-loud' in Italian. Over the next two centuries it grew heavier and louder, gaining an iron frame and today's standard 88 keys. One of Cristofori's pianos, from 1720, survives in New York's Metropolitan Museum of Art."],
    ["Electronic instruments", "Electronic instruments, from the theremin to the synthesiser, make sound from electrical signals.",
      "The theremin, invented by the Russian scientist Leon Theremin around 1920, is played without being touched: moving your hands near two antennas changes its pitch and volume, giving the eerie sound of old science fiction films. In the 1960s, Robert Moog's synthesisers let musicians shape electronic sounds with knobs and patch cables. Australia has its own claim here: CSIRAC, one of the world's first stored-program computers, played music in the early 1950s. Since 1983, a standard called MIDI has let keyboards, drum machines and computers talk to each other, which is why a laptop can now stand in for a whole studio."]
  ],
  [
    [0, "In the Hornbostel-Sachs system, what is a drum with a stretched skin?", ["An idiophone", "A membranophone", "A chordophone", "An aerophone"], 1, "Membranophones make sound with a stretched membrane, like a drum skin."],
    [2, "Which family does the saxophone belong to, and why?", ["Brass, because it is made of metal", "Percussion, because its keys click", "Woodwind, because it uses a reed rather than buzzing lips", "Strings, because it has a vibrating reed"], 2, "Families are defined by how sound is started. The saxophone uses a single reed, so it is a woodwind."],
    [4, "What technique lets a yidaki player sustain an unbroken drone?", ["Circular breathing", "Vibrato", "Double tonguing", "Bowing"], 0, "Players breathe in through the nose while pushing air out from the cheeks, so the sound never stops."],
    [6, "What did Cristofori's piano offer that the harpsichord did not?", ["Plucked strings", "More than one keyboard", "An electric amplifier", "Louder or softer notes depending on how hard you press"], 3, "Its hammers let the player control volume by touch, hence the name pianoforte, 'soft-loud'."],
    [7, "What was unusual about CSIRAC?", ["It was the first synthesiser sold in shops", "It was an early Australian computer that played music in the early 1950s", "It was the first electric guitar", "It invented the MIDI standard"], 1, "CSIRAC, one of the first stored-program computers, played music in the early 1950s."]
  ],
  { popularity: 72, related: ["how-music-works", "first-australians", "classical-music"] }
);

WB.L("classical-music", "arts", "beginner", "A guide to classical music",
  "Three centuries, three giants and a lot of music that still turns up in films, ads and ringtones. Here is how to find your way in.",
  [
    ["What 'classical' means", "'Classical music' usually means the Western art music tradition, grouped into broad periods.",
      "In everyday speech, 'classical music' means the tradition of Western art music written for orchestras, choirs, soloists and small ensembles over roughly the last four centuries. Historians divide it into periods: the Baroque, about 1600 to 1750; the Classical period, about 1750 to 1820, which confusingly gives the whole tradition its name; and the Romantic period, about 1820 to 1900. Then came a burst of twentieth-century experiment. The dates are rough, since composers did not wake up one morning in a new era. Knowing the periods helps you hear why a piece sounds the way it does."],
    ["The Baroque", "Baroque music (about 1600–1750) is ornate and energetic, built on interweaving lines and a steady bass.",
      "Baroque music tends to be busy, decorated and driven by a steady rhythmic pulse. Underneath most pieces runs a continuous bass line, often played by a cello and a harpsichord filling in chords. Opera was born in Italy around 1600, and instrumental forms like the concerto flourished, pitting a soloist or small group against the orchestra. Antonio Vivaldi's The Four Seasons, published in 1725, is a set of four violin concertos that paint spring birdsong, summer storms and winter ice. George Frideric Handel's oratorio Messiah, first performed in Dublin in 1742, is still sung by choirs across Australia every Christmas."],
    ["Johann Sebastian Bach", "Bach (1685–1750) was the great master of counterpoint, weaving several independent melodies together.",
      "Johann Sebastian Bach spent his working life in Germany as a church musician and court composer, and was better known in his day as an organist than a composer. He wrote more than a thousand works, including the Brandenburg Concertos, the Mass in B minor and hundreds of church cantatas. His great skill was counterpoint: several independent melodies played at once that fit together perfectly, as in a fugue, where one theme enters again and again in different voices. After his death his music fell out of fashion, until Felix Mendelssohn revived his St Matthew Passion in 1829. Many musicians now consider him the greatest composer of all."],
    ["The Classical period", "The Classical period (about 1750–1820) prized clarity, balance and memorable tunes.",
      "After the dense layers of the Baroque, composers turned towards clarity: a clear melody on top, simpler accompaniment underneath, and balanced phrases like a question and answer. The harpsichord gave way to the new piano. This was the age of the symphony, a large orchestral work usually in four movements, and of the string quartet. Joseph Haydn wrote more than 100 symphonies and is often called the father of both forms. Composers also developed sonata form, a way of presenting two contrasting themes, developing them, and bringing them back, which shaped instrumental music for the next 150 years."],
    ["Wolfgang Amadeus Mozart", "Mozart (1756–1791) wrote over 600 works in a life of just 35 years.",
      "Mozart was born in Salzburg in 1756 and was touring Europe as a child prodigy by the age of six, performing for royalty alongside his sister Nannerl. In a life of only 35 years, he wrote more than 600 works, including 41 numbered symphonies, over 20 piano concertos and operas such as The Marriage of Figaro, Don Giovanni and The Magic Flute. His music can sound effortless, but it is full of subtle drama and wit. He died in Vienna in 1791 while working on his Requiem. Popular stories of a murderous rivalry with the composer Salieri, spread by the film Amadeus, are not supported by historians."],
    ["Ludwig van Beethoven", "Beethoven (1770–1827) kept composing as he went deaf and pushed music into the Romantic era.",
      "Beethoven was born in Bonn in 1770 and moved to Vienna, where he took lessons for a time from Haydn. In his late twenties he began to lose his hearing, and by his final years he was almost completely deaf. In 1802 he wrote a despairing letter to his brothers, now called the Heiligenstadt Testament, yet he kept composing. His Fifth Symphony opens with perhaps the most famous four notes in music, and his Ninth Symphony of 1824 broke convention by adding singers in its finale. His music is more personal and dramatic than earlier composers', and it opened the door to Romanticism."],
    ["The Romantic era", "Romantic composers (about 1820–1900) used bigger orchestras to express intense emotion and national identity.",
      "Romantic composers valued personal feeling, drama and imagination over balance. Orchestras grew larger, pieces grew longer, and music was often linked to stories, landscapes or poems. Frédéric Chopin wrote intimate piano music; Pyotr Ilyich Tchaikovsky wrote the ballets Swan Lake and The Nutcracker; Richard Wagner wrote operas lasting four or five hours; Johannes Brahms carried on Beethoven's symphonic tradition. Many composers drew on folk music to express national identity, such as Antonín Dvořák in Czech lands and Edvard Grieg in Norway. Much of today's film music, with its sweeping strings and big brass, grows directly out of this era."],
    ["How to start listening", "Start with short, famous pieces, listen actively, and try hearing an orchestra live.",
      "You don't need any training to enjoy classical music. Start with short, well-known pieces: a movement of Vivaldi's The Four Seasons, Mozart's Eine kleine Nachtmusik, the opening of Beethoven's Fifth, or Tchaikovsky's Nutcracker suite. Many are free on streaming services and on radio such as ABC Classic. Listen actively the first time, with no phone, and notice what repeats and what changes. If a piece grabs you, explore more by the same composer. Then try it live: the Sydney, Melbourne and other state symphony orchestras run affordable concerts, and hearing a full orchestra in person is a different experience from headphones."]
  ],
  [
    [0, "Roughly when was the Baroque period?", ["About 1600–1750", "About 1750–1820", "About 1820–1900", "About 1900–1950"], 0, "The Baroque ran from about 1600 to 1750, ending around the time of Bach's death."],
    [2, "What is counterpoint, the technique Bach mastered?", ["Playing one melody very fast", "Several independent melodies played at once that fit together", "Using only percussion instruments", "Singing without any accompaniment"], 1, "Counterpoint weaves independent melodic lines together, as in a fugue."],
    [3, "Which composer is often called the father of the symphony?", ["Vivaldi", "Chopin", "Haydn", "Wagner"], 2, "Joseph Haydn wrote more than 100 symphonies and shaped the form."],
    [4, "What do historians say about the story that Salieri murdered Mozart?", ["It is confirmed by Salieri's letters", "It was proven in a Viennese court", "Mozart himself predicted it", "It is not supported by historical evidence"], 3, "The rivalry story was popularised by fiction, including the film Amadeus, but historians don't support it."],
    [5, "What was groundbreaking about Beethoven's Ninth Symphony?", ["It was the first symphony ever written", "It added singers in the finale", "It was written for harpsichord alone", "It had no melody"], 1, "Beethoven broke convention by bringing a choir and vocal soloists into the final movement."]
  ],
  { popularity: 70, related: ["how-music-works", "instruments", "renaissance"] }
);

WB.L("popular-music", "arts", "intermediate", "From blues to hip hop",
  "Almost every song on your playlist can trace its family tree back to the blues, and to a few machines that changed how music was heard.",
  [
    ["The blues", "The blues grew from African American communities in the US South around the turn of the twentieth century.",
      "The blues emerged in African American communities in the southern United States around the late 1800s and early 1900s, drawing on work songs, field hollers and spirituals rooted in the experience of slavery and its aftermath. Its most famous structure, the 12-bar blues, repeats a pattern of three chords over twelve bars, and its 'blue notes' bend slightly below the standard pitches of a Western scale. Musicians such as W.C. Handy, Bessie Smith and Robert Johnson helped spread it. The blues shaped jazz, rhythm and blues, rock and roll, soul and much of the popular music that followed."],
    ["The recording revolution", "Recording turned music from a live-only event into something anyone could own and replay.",
      "For most of history, you could only hear music when someone played it in front of you. That changed in 1877, when Thomas Edison demonstrated the phonograph, recording sound as grooves on a tin foil cylinder. Flat gramophone discs followed, then radio in the 1920s, which brought music into millions of homes for free. For the first time, a singer in one city could be heard across the world, and styles spread and mixed faster than ever. Records also fixed a performance permanently, so one particular recording, rather than the written song, became the version people knew and loved."],
    ["Rock and roll", "Rock and roll combined blues, country and gospel in the 1950s and made the electric guitar central.",
      "In the 1950s, rock and roll fused rhythm and blues with country music and gospel, driven by a strong backbeat on beats two and four. Black musicians such as Chuck Berry, Little Richard and Sister Rosetta Tharpe were central to its sound, and Elvis Presley became its biggest star. The electric guitar, amplified so it could compete with drums, became its signature instrument. Rock and roll was also a social shift: it was marketed directly to teenagers, who now had money to spend. In the 1960s, British bands such as the Beatles and the Rolling Stones sent it back across the Atlantic, reshaped."],
    ["Tape, LPs and the studio", "Magnetic tape, multitrack recording and the LP turned the studio into an instrument.",
      "After the Second World War, magnetic tape made recordings far easier to edit, and multitrack recorders let musicians record parts separately and layer them. The long-playing record, introduced in 1948, held around twenty minutes a side, encouraging artists to think in whole albums. By the late 1960s, the studio itself had become an instrument, with bands creating sounds that were difficult to play live. Portable cassettes arrived in the 1960s and the Walkman in 1979, making music personal and mobile. Compact discs followed in the early 1980s, then MP3 files, file sharing and, from the late 2000s, streaming services."],
    ["Hip hop", "Hip hop began at block parties in the Bronx, New York, in the 1970s.",
      "Hip hop grew out of block parties in the Bronx, New York, in the 1970s, largely among African American and Caribbean-born young people. A 1973 party where DJ Kool Herc played is often cited as its starting point. DJs extended the drum breaks of funk records by switching between two turntables, and MCs rhymed over the top. The culture is often described as having four elements: DJing, MCing, breakdancing and graffiti. Sampling, reusing fragments of existing recordings, became central to its sound. From a local scene it grew into one of the world's best-selling genres, including a strong Australian hip hop scene."],
    ["Electronic and dance music", "Electronic dance music grew from disco, with house in Chicago and techno in Detroit in the 1980s.",
      "Disco in the 1970s built music for the dance floor around a steady four-on-the-floor kick drum. When disco faded in the United States, DJs and producers in Black and gay club scenes kept experimenting. In the mid-1980s, Chicago gave rise to house music and Detroit to techno, both built on affordable drum machines and synthesisers such as the Roland TR-808 and TB-303. The sound spread to Europe, fuelling the rave scene of the late 1980s and 1990s. Today electronic production techniques are everywhere, and many pop hits are made largely on a computer rather than with a live band."],
    ["Australian milestones", "Australian music milestones include Johnny O'Keefe, AC/DC, Kylie Minogue and Yothu Yindi.",
      "Johnny O'Keefe's Wild One, in 1958, was one of the first Australian rock and roll hits. AC/DC, formed in Sydney in 1973 by brothers Malcolm and Angus Young, became one of the biggest rock bands in the world; their 1980 album Back in Black is among the best-selling albums ever. Kylie Minogue moved from the TV soap Neighbours to international pop stardom with The Loco-Motion in 1987. Yothu Yindi's Treaty, released in 1991 and sung partly in the Yolŋu language Gumatj, became a national hit, and singer Mandawuy Yunupingu was named Australian of the Year for 1992. The ABC's Countdown and triple j helped launch countless careers."],
    ["How to listen more deeply", "Trace the family tree of the music you love to discover more of it.",
      "Almost every genre borrows from the ones before it, so following the family tree is a great way to find new music. If you like a modern artist, look up who they say influenced them, then listen to those artists. Liner notes and credits on streaming services show who wrote, produced and sampled each track. Many hip hop songs are built on samples of soul, funk and jazz records, which are worth hearing in full. Support local music too: live venues, community radio and triple j Unearthed are where many Australian artists get their start."]
  ],
  [
    [0, "What is the 12-bar blues?", ["A song that must last exactly 12 minutes", "A repeating pattern of three chords over twelve bars", "A scale with twelve notes", "A style played only on twelve-string guitar"], 1, "The 12-bar blues repeats a set pattern of three chords over twelve bars."],
    [1, "Who demonstrated the phonograph in 1877?", ["Thomas Edison", "Alexander Graham Bell", "Robert Moog", "Guglielmo Marconi"], 0, "Edison's phonograph recorded sound as grooves on a tin foil cylinder."],
    [4, "Where did hip hop begin?", ["London in the 1960s", "Chicago in the 1980s", "Sydney in the 1990s", "The Bronx, New York, in the 1970s"], 3, "Hip hop grew from Bronx block parties in the 1970s."],
    [5, "Which city is credited with house music in the mid-1980s?", ["Detroit", "Berlin", "Chicago", "Manchester"], 2, "House music came from Chicago; techno from Detroit."],
    [6, "What was notable about Yothu Yindi's Treaty?", ["It was the first Australian song played on radio", "It was sung partly in the Yolŋu language Gumatj and became a national hit", "It was AC/DC's debut single", "It was recorded entirely on a synthesiser"], 1, "Treaty (1991) brought Yolŋu language and Aboriginal perspectives into the national charts."]
  ],
  { popularity: 76, related: ["how-music-works", "music-brain", "civil-rights"] }
);

WB.L("music-brain", "arts", "intermediate", "Music and the brain",
  "Music gives you no food, shelter or money, yet it can make your skin tingle and bring back memories you thought were lost. Why?",
  [
    ["A whole-brain workout", "Listening to music engages many brain areas at once, from hearing to movement to emotion.",
      "There is no single music centre in the brain. When you listen to a song, areas that process sound decode pitch and timbre, while regions involved in movement track the beat, which is why it's hard not to tap your foot. Memory areas recognise familiar tunes, and emotional and reward systems respond to how the music makes you feel. Playing an instrument adds fine motor control, reading and planning on top. This is one reason neuroscientists find music so useful to study: it connects perception, prediction, movement and feeling in a single everyday activity."],
    ["Music and emotion", "Music stirs emotions partly by mimicking the voice and body, and partly by playing with our expectations.",
      "Music can make us feel sad, joyful, calm or pumped up, often within seconds. One explanation is that it borrows the cues of emotional speech and movement: happy music tends to be faster, higher and brighter, like excited speech, while sad music is slower, lower and softer. Another is expectation. Your brain constantly predicts what comes next, and composers delay, confirm or surprise those predictions to create tension and release. Culture matters too, but some features travel well: research comparing songs from many societies suggests people can often tell a lullaby from a dance song even in an unfamiliar musical tradition."],
    ["Chills", "Musical 'chills', or frisson, are tingling sensations many people feel at powerful moments in music.",
      "Many people know the feeling: a shiver down the spine or goosebumps at a key moment in a piece of music. Researchers call it frisson, or simply chills. It often arrives with something unexpected, like a sudden change in volume, a new voice entering, or a surprising chord, especially after a long build-up. Not everyone gets chills from music, and some studies suggest people who score high on openness to experience report them more often. Chills are a useful research tool, because they give scientists a clear, measurable moment of intense musical pleasure to study."],
    ["Dopamine and reward", "Pleasurable music triggers dopamine release in the brain's reward system, even in anticipation of the peak.",
      "A 2011 study at McGill University in Montreal used brain scans to watch people listening to music that gave them chills. At the moment of peak pleasure, their brains released dopamine in the striatum, part of the reward system that also responds to food and other rewards. Interestingly, dopamine was also released in a different part of the striatum in the seconds before the peak, as listeners anticipated it. That helps explain why a favourite song's build-up can feel almost as good as the moment itself. Music is abstract, yet it taps into some of the brain's oldest reward machinery."],
    ["Music and memory", "Music is strongly tied to memory, especially music heard in our teens and early twenties.",
      "A few notes of an old song can transport you instantly to a particular summer, car trip or school dance. Music is closely bound up with autobiographical memory, and it tends to be tied to emotion, which helps memories stick. Studies consistently find that people remember and feel most strongly about music from their teens and early twenties, part of a wider pattern psychologists call the reminiscence bump. That's one reason many adults feel the best music was made when they were young. Songs also make words easier to remember, which is why children learn the alphabet with a tune."],
    ["Music and dementia", "Musical memory is often relatively preserved in dementia, and personal music can improve mood and connection.",
      "Carers and researchers have long noticed that people with dementia, including some who struggle to recognise family members, can still sing along to songs from their youth. Musical memory seems to rely partly on brain areas that are affected relatively late in some forms of dementia such as Alzheimer's disease. Music does not cure dementia or reverse its progress. But there is reasonable evidence that personally meaningful music can lift mood, reduce agitation and help people connect with those around them. Many Australian aged-care homes now use personalised playlists, and registered music therapists work in hospitals and care settings."],
    ["The Mozart effect myth", "Listening to Mozart does not make you smarter; the famous 1993 finding was small, brief and hard to repeat.",
      "In 1993, a short paper in the journal Nature reported that university students who listened to ten minutes of a Mozart sonata did slightly better on a spatial reasoning task for about the next 10 to 15 minutes. The media turned this into 'Mozart makes babies smarter', and in 1998 the governor of the US state of Georgia proposed giving every newborn a classical music CD. Later studies struggled to repeat the result, and reviews found any effect was small and short-lived. The best explanation is simply that enjoyable music can briefly lift mood and alertness, and Mozart has no special power."],
    ["Does learning an instrument make you smarter?", "Learning an instrument builds musical skills, but evidence it boosts general intelligence is mixed.",
      "Children who learn instruments often do better at school, but that doesn't prove the lessons caused it; families who pay for music lessons differ in many other ways. Studies that randomly assign children to music training have produced mixed results, and several reviews have found little evidence of broad gains in intelligence or grades. What is clear is that practice improves musical skills themselves, such as listening, timing and coordination, and that playing brings enjoyment, discipline and social connection at any age. So learn an instrument because you want to play music, and treat any other benefits as a bonus."]
  ],
  [
    [1, "Which features tend to make music sound happy?", ["Slower, lower and softer", "Faster, higher and brighter", "No beat at all", "Only minor chords"], 1, "Happy-sounding music tends to share cues with excited speech: faster, higher and brighter."],
    [2, "What often triggers musical chills?", ["Constant, unchanging volume", "Silence throughout", "Something unexpected, like a sudden change or new voice", "Only very quiet music"], 2, "Chills often come with surprise, such as a sudden change after a build-up."],
    [3, "What did the 2011 McGill study find about dopamine and music?", ["It was released at peak pleasure and also in anticipation of it", "Music blocks dopamine release", "Dopamine was released only while sleeping", "Only classical music triggered any release"], 0, "Dopamine was released both at the peak and in the build-up before it."],
    [4, "Music from which part of life do people tend to remember most strongly?", ["Early childhood, before age five", "Middle age", "The last year", "The teens and early twenties"], 3, "This is part of the reminiscence bump, when memories are especially vivid and lasting."],
    [6, "What is the best explanation for the original 'Mozart effect' result?", ["Mozart's music rewires the brain permanently", "Enjoyable music briefly lifted mood and alertness", "The students were all trained musicians", "It only worked on babies"], 1, "The small, brief effect is best explained by improved mood and arousal, not anything special about Mozart."]
  ],
  { popularity: 82, related: ["how-music-works", "brain-chemicals", "false-memories"] }
);
