/* WISEBYTE LESSONS · Maths batch Y */
WB.L("power-of-doubling", "maths", "beginner", "The power of doubling", "Fold a sheet of paper 42 times and, in theory, it would reach past the Moon. Doubling is the simplest pattern in maths, and the one our brains are worst at imagining.",
  [
    ["The king and the chessboard", "Doubling a single grain of wheat across 64 squares produces more wheat than the world could grow in centuries.", "An old legend, told in many versions, says the inventor of chess was offered any reward he liked by a delighted ruler. He asked for something that sounded modest: one grain of wheat on the first square of the board, two on the second, four on the third, and so on, doubling each time across all 64 squares. The ruler laughed and agreed. He should not have. By square 11 the pile holds 1,024 grains, still only a handful. By square 21 it passes a million. The final square alone would need about 9.2 quintillion grains, and the whole board adds up to 18,446,744,073,709,551,615 grains, which is 2 multiplied by itself 64 times, minus one. The world would need many centuries of harvests to grow that much."],
    ["Folding paper to the Moon", "Each fold doubles the thickness, so 42 folds of ordinary paper would stretch beyond the Moon.", "Take a sheet of printer paper about 0.1 millimetres thick and fold it in half. It is now 0.2 millimetres thick. Fold again and it is 0.4. After 10 folds it would be about 10 centimetres thick, roughly the height of a coffee mug. After 20 folds, if that were possible, it would be about 105 metres tall, around the height of a 30 storey building. After 30 folds it would be over 100 kilometres, reaching the edge of space. After 42 folds the stack would be about 440,000 kilometres high, further than the average distance to the Moon, which is about 384,000 kilometres. In reality each fold needs far more paper than the last. In 2002 an American student, Britney Gallivan, set a record by folding a very long strip of paper 12 times."],
    ["Why our brains think in straight lines", "We instinctively imagine steady, step by step growth, so doubling takes us by surprise.", "Imagine 30 ordinary steps and you picture walking about 30 metres. Now imagine 30 steps where each one is double the length of the one before, starting at one metre. The last step alone would be more than 500,000 kilometres long, and the whole walk would add up to more than a million kilometres, enough to go around the Earth nearly 27 times. Our intuition is built for adding, not multiplying. In daily life most things change steadily. Researchers call our tendency to underestimate this kind of growth 'exponential growth bias'. The word exponential simply means growth driven by repeated multiplication, and it shows up in debts, savings and outbreaks of disease."],
    ["The lily pond riddle", "With doubling, most of the change happens right at the end, so warnings arrive late.", "A classic puzzle: a patch of lily pads on a pond doubles in area every day. If it covers the whole pond on day 48, on what day does it cover half the pond? Many people say day 24, but the answer is day 47. Just one doubling before the end, half the pond is still clear water. Four days before the end, the lilies cover only about 6 per cent. This is why doubling is so hard to manage in real life. Early on, the numbers look tiny. By the time the problem is obvious, there are only a few doublings to go. Public health experts stress this point: early in an outbreak, acting a few days sooner can make a very large difference."],
    ["The rule of 72", "Divide 72 by a yearly growth rate to estimate how many years something takes to double.", "To estimate how long something growing by a steady percentage each year takes to double, divide 72 by that percentage. At 6 per cent a year, an amount would double in about 12 years. At 9 per cent, in about 8 years. At 3 per cent, in about 24. The rule is not exact, but it is close for everyday rates: at 8 per cent the true doubling time is just over 9 years, and the rule says 9. It works for costs too. Prices rising 3 per cent a year roughly double in 24 years. Credit card debt charging 20 per cent a year would double in under four years if left unpaid. This is general information, not financial advice; moneysmart.gov.au has free calculators."],
    ["Halving: doubling in reverse", "Repeated halving shrinks things just as dramatically, which is how scientists date ancient remains.", "Doubling has a mirror image: repeated halving. Radioactive carbon-14 has a half-life of about 5,730 years: in that time, half of any sample decays into nitrogen. After another 5,730 years, half of what is left has gone, leaving a quarter. After ten half-lives, about 57,000 years, less than a thousandth of the original remains. Living things constantly take in carbon, so the level of carbon-14 in their bodies stays steady while they are alive. When they die the clock starts ticking, and by measuring how much is left, scientists can date bones, wood and charcoal back to roughly 50,000 years. Halving also explains why the amount of a medicine in your blood fades in steps rather than all at once."],
    ["Nothing doubles forever", "Real-world doubling always hits limits, bending into an S-shaped curve.", "If a single bacterium dividing every 20 minutes kept going unchecked, its descendants would outweigh the entire Earth in about two days. That never happens, because food runs out, waste builds up and space fills. Real growth usually follows an S-shaped curve: slow at first, then explosive, then levelling off as it hits its limits. Mathematicians call this logistic growth. Technology shows the same pattern. In 1965 the engineer Gordon Moore noticed that the number of components on a computer chip was doubling regularly, and in 1975 he revised his estimate to roughly every two years. 'Moore's law' held for decades and powered the computer revolution, though progress has slowed as the parts approach the size of atoms. The lesson is to spot doubling early, and to ask what limit will eventually stop it."]
  ],
  [
    [0, "Roughly how many grains would the final square of the chessboard need?", ["About 64,000", "About 18 million", "About 9.2 quintillion", "About 1 billion"], 2, "Each square doubles the last, so square 64 needs 2 multiplied by itself 63 times, about 9.2 quintillion grains."],
    [1, "About how thick would ordinary paper be after 10 folds?", ["About 1 millimetre", "About 10 centimetres", "About 10 metres", "About 1 kilometre"], 1, "0.1 millimetres doubled 10 times is 0.1 times 1,024, about 102 millimetres."],
    [3, "If the lilies cover the whole pond on day 48, when do they cover half of it?", ["Day 24", "Day 36", "Day 46", "Day 47"], 3, "They double daily, so they are at half just one day before the end."],
    [4, "Using the rule of 72, roughly how long does something growing 6 per cent a year take to double?", ["About 12 years", "About 6 years", "About 36 years", "About 72 years"], 0, "72 divided by 6 is 12, so it doubles in about 12 years."],
    [6, "Why does real-world growth usually follow an S-shaped curve?", ["Doubling only works with even numbers", "Limits such as food and space slow it down", "Growth always speeds up forever", "Scientists round off the numbers"], 1, "Growth that starts out doubling levels off once it runs into limits, which is called logistic growth."]
  ]);

WB.L("monty-hall-problem", "maths", "beginner", "The Monty Hall problem: the puzzle that fools almost everyone", "Three doors, one car, two goats. Should you switch? The right answer is simple to state, hard to believe, and once had people with maths doctorates writing angry letters.",
  [
    ["Three doors and two goats", "The puzzle comes from a US game show and has a deceptively simple setup.", "Imagine you are a contestant on a game show. In front of you are three closed doors. Behind one is a new car; behind the other two are goats. You pick a door, say door 1, but it stays shut. The host, who knows exactly where the car is, always opens one of the other doors to reveal a goat, and always offers you a choice. Say he opens door 3. Do you stick with door 1, or switch to door 2? The puzzle is named after Monty Hall, the long-running host of the American show Let's Make a Deal, and the statistician Steve Selvin posed it in a journal letter in 1975. Most people's instinct is that two doors remain, so it must be 50 to 50."],
    ["Why switching wins two thirds of the time", "Your first pick is right only a third of the time, and switching wins in every other case.", "When you pick a door, you have a one in three chance of choosing the car and a two in three chance of choosing a goat. Now follow each case. If you picked the car, the host opens either goat door, and switching loses. That happens one time in three. If you picked a goat, the host cannot open your door and cannot reveal the car, so he is forced to open the only other goat door. The remaining closed door must hide the car, and switching wins. That happens two times in three. So sticking wins one third of the time and switching wins two thirds. Opening a door did not change the odds on your pick; it concentrated the other two thirds onto the one door left."],
    ["The letters that poured in", "When the puzzle appeared in a popular magazine column, thousands of readers, including academics, insisted the answer was wrong.", "In 1990 a reader sent the puzzle to Marilyn vos Savant, who wrote the 'Ask Marilyn' column in Parade, a US magazine read by millions. She replied that you should switch, because switching wins two thirds of the time. The reaction was extraordinary. She received thousands of letters, many from people with doctorates, many telling her she had made an embarrassing mistake. She was right. The puzzle even troubled Paul Erdős, one of the most prolific mathematicians of the twentieth century. According to a well-known account, he refused to accept the answer until he was shown a computer simulation of the game played many times over. Expertise does not protect anyone from a strong but faulty intuition."],
    ["Imagine a hundred doors", "Scaling the puzzle up makes the right answer feel obvious.", "If the answer still feels wrong, imagine 100 doors, with a car behind one and goats behind the other 99. You pick door 37. Your chance of being right is just 1 in 100. Now the host, who knows where the car is, opens 98 of the other doors, every one revealing a goat, and leaves just one other door closed: door 74. Would you stick with door 37 or switch to door 74? Almost everyone now feels the pull to switch, and they are right. Your door still has its original 1 in 100 chance. The host has carefully avoided the car while opening 98 doors, so door 74 carries all the remaining 99 in 100. The three door game works the same way, just with smaller numbers."],
    ["It all depends on the host", "Switching only helps because the host knows where the car is and never reveals it.", "There is a subtle condition hidden in the puzzle. The host knows where the car is, always opens a goat door and always offers the swap. Change those rules and the answer changes. Suppose instead the host has no idea where the car is and opens one of the other two doors at random. Sometimes he will reveal the car and spoil the game. But in the games where he happens to reveal a goat, your chances really are 50 to 50, and switching makes no difference. The difference is information. A knowing host's choice is limited by where the car is, so his action tells you something useful. A random host's choice tells you nothing extra. Many heated arguments about the puzzle are really about which rules apply."],
    ["Bertrand's box", "An older puzzle with three boxes shows the same trap: treating outcomes as equally likely when they are not.", "More than 70 years before the game show, the French mathematician Joseph Bertrand described a similar trap in an 1889 book on probability. Picture three boxes: one holds two gold coins, one holds two silver coins and one holds one of each. You pick a box at random, reach in without looking and pull out a gold coin. What is the chance that the other coin in that box is also gold? Most people say one half. But the answer is two thirds. There are three equally likely gold coins you could have drawn. Two of them sit in the gold box, and only one sits in the mixed box. So two times out of three, the coin left behind is gold as well."],
    ["Taming your intuition", "List every equally likely outcome, or simply play the game many times, and the truth appears.", "Our intuition tends to count the options left in front of us, such as two doors or two boxes, and assume each one is equally likely. Often they are not. A reliable fix is to list every equally likely starting situation and follow each one through to the end, as we did with the doors and the coins. Another is to experiment. You can play Monty Hall at home with three cups, a coin and a friend acting as a host who knows where the coin is hidden. Play 30 rounds always sticking and 30 rounds always switching, and record the wins. The switching column will usually come out well ahead. Watching results pile up is often more persuasive than any explanation."]
  ],
  [
    [1, "In the standard puzzle, how often does switching win?", ["One third of the time", "Half the time", "Two thirds of the time", "Every time"], 2, "Your first pick is wrong two times in three, and in each of those cases switching wins."],
    [2, "Who answered the puzzle in a 1990 magazine column and received thousands of letters saying she was wrong?", ["Marilyn vos Savant", "Ada Lovelace", "Emmy Noether", "Florence Nightingale"], 0, "Marilyn vos Savant said to switch in her Parade column, and she was right."],
    [3, "With 100 doors, after the host opens 98 goat doors, what is the chance the other closed door hides the car?", ["1 in 100", "1 in 2", "1 in 98", "99 in 100"], 3, "Your door keeps its 1 in 100 chance, so the remaining door carries the other 99 in 100."],
    [4, "If the host opens a door at random and happens to show a goat, what is the chance that switching wins?", ["One third", "One half", "Two thirds", "Zero"], 1, "A random host gives you no extra information, so the two closed doors are equally likely."],
    [5, "In Bertrand's box puzzle, after drawing a gold coin, what is the chance the other coin is gold?", ["One half", "Two thirds", "One third", "Three quarters"], 1, "Two of the three equally likely gold coins sit in the box with two gold coins."]
  ]);

WB.L("fractals-coastlines", "maths", "intermediate", "Fractals: the infinite detail of coastlines, ferns and clouds", "How long is a coastline? The honest answer is 'it depends on your ruler', and that puzzle opened the door to a whole new kind of geometry.",
  [
    ["The coastline that keeps growing", "The more finely you measure a jagged coastline, the longer it gets.", "Try measuring a rocky coastline on a map with a pair of dividers set to 100 kilometres. You will cut straight across bays and headlands and get one number. Set the dividers to 10 kilometres and you follow more of the wiggles, so the total grows. Walk the shore with a one metre ruler, tracing around every rock, and it grows again. In the mid twentieth century the English scientist Lewis Fry Richardson noticed this effect when comparing published lengths of coasts and borders, which often disagreed. In 1967 Benoit Mandelbrot built on this in a famous paper titled 'How Long Is the Coast of Britain?'. His point was that for shapes like coastlines, length is not a fixed property. It depends on the scale you choose to measure at."],
    ["Shapes that repeat as you zoom", "Fractals are shapes whose rough detail keeps reappearing at smaller and smaller scales.", "Look closely at a fern frond. It is made of smaller leaflets, each shaped much like the whole frond, and each of those has its own smaller lobes. Or break a floret off a head of romanesco broccoli: it looks like a miniature copy of the whole head, built from even smaller spiralling cones. This property is called self-similarity, and shapes that show rough detail across many scales are called fractals. Mandelbrot coined the word in 1975, from the Latin fractus, broken. In nature the repetition is never perfect and only lasts across a limited range of sizes, but it is everywhere: in river networks seen from the air, in the branching of trees, in lightning bolts, clouds and mountain ranges. Classical geometry, built on smooth lines and circles, struggles to describe any of them."],
    ["The snowflake with an infinite edge", "The Koch snowflake has a boundary of infinite length wrapped around a finite area.", "In 1904 the Swedish mathematician Helge von Koch described a shape that startled many of his peers. Start with an equilateral triangle. On the middle third of each side, add a smaller triangle pointing outwards, turning each straight side into four shorter pieces. Now do the same to every one of those pieces, and keep going forever. Each round multiplies the length of the outline by four thirds. Repeat that endlessly and the perimeter grows without limit, so the finished snowflake has an infinitely long edge. Yet the shape never spreads far beyond the original triangle, and its area settles at exactly eight fifths of the area of the starting triangle. A finite area wrapped in an infinite boundary sounds like a contradiction, but it is a perfectly sound piece of mathematics."],
    ["Dimensions between the whole numbers", "Fractals can have a dimension like 1.26, which measures how quickly their detail fills space.", "A line is one dimensional and a square is two dimensional, but mathematicians have a way of measuring dimension that also works for fractals. Scale a line up by three times and you get three copies of the original. Scale a square up by three and you get nine copies, which is three squared, so its dimension is two. Now take one side of the Koch snowflake. Scale it up by three and you get four copies of the original. Its dimension is the power you must raise three to in order to get four, which works out to about 1.26. It is more than a line but less than a surface. Mandelbrot estimated a dimension of about 1.25 for the rugged west coast of Britain, while smoother coastlines came out much closer to 1."],
    ["The Mandelbrot set", "A one line rule, repeated by a computer, produces a shape of endless complexity.", "The most famous fractal comes from a very short rule. Start with zero. Square it and add a fixed number, called c. Then take the result, square it and add c again, over and over. For some values of c the numbers stay small forever. For others they rush off towards infinity. The numbers involved are complex numbers, which can be plotted as points on a flat plane. Colour every point that stays small in black, and you get the Mandelbrot set, named after Benoit Mandelbrot, who studied it using computers at IBM around 1980. Its boundary is endlessly intricate. Zoom in anywhere along the edge and you find spirals, seahorse shapes and tiny copies of the whole set, with new detail appearing no matter how far you magnify it."],
    ["Why nature loves fractals", "Branching fractal shapes pack an enormous surface or reach into a small space.", "Fractal shapes are not just pretty; they solve practical problems. Your windpipe splits into two airways, which split again and again, through around 20 or more rounds of branching, ending in hundreds of millions of tiny air sacs. That repeated branching folds a huge surface for absorbing oxygen into your chest, estimated at tens of square metres, many times the area of your skin. Blood vessels branch in a similar way, so that almost every cell in your body sits close to a tiny capillary. Trees use branching to spread their leaves towards sunlight and their roots through the soil. Rivers drain whole landscapes through networks of tributaries that look similar at many scales. In each case, a simple rule of repeated splitting builds a structure that reaches almost everywhere it needs to."],
    ["Fractals at work", "Fractal ideas now help design antennas, create film landscapes and describe rough real-world surfaces.", "Engineers and artists have put fractals to work. Computer graphics pioneers realised that repeatedly adding smaller and smaller random bumps to a shape produces convincing mountains, coastlines and clouds, and fractal techniques helped create a computer-generated planet surface for the 1982 film Star Trek II: The Wrath of Khan. Similar ideas still help build landscapes in films and video games. Some antennas in mobile phones and other devices use fractal-like shapes, which let a compact antenna work across a wide range of frequencies. Scientists use fractal dimension to describe the roughness of surfaces, the branching of blood vessels in medical scans and the sprawl of growing cities. Mandelbrot himself applied fractal thinking to financial markets, arguing that prices are wilder and more prone to sudden jumps than standard models assume."]
  ],
  [
    [0, "What happens to a coastline's measured length as you use a shorter ruler?", ["It stays the same", "It gets shorter", "It gets longer", "It drops to zero"], 2, "A shorter ruler follows more of the bays and wiggles, so the total length grows."],
    [1, "Where does the word 'fractal' come from?", ["Latin for broken", "Greek for snowflake", "French for coastline", "German for branch"], 0, "Mandelbrot coined it in 1975 from the Latin fractus, meaning broken."],
    [2, "Each round of building the Koch snowflake multiplies the perimeter by what?", ["Two", "Four thirds", "Three quarters", "Three"], 1, "Each side becomes four pieces, each a third as long, so the length is multiplied by four thirds."],
    [3, "Roughly what is the fractal dimension of the Koch curve?", ["0.5", "1", "2", "1.26"], 3, "Scaling by three gives four copies, and three raised to about 1.26 equals four."],
    [5, "Why is fractal branching useful in the lungs?", ["It makes breathing silent", "It stops the lungs growing", "It packs a huge surface area into a small space", "It stores extra blood"], 2, "Repeated branching folds tens of square metres of surface for absorbing oxygen into the chest."]
  ]);

WB.L("seven-bridges-networks", "maths", "intermediate", "The seven bridges puzzle and the maths of networks", "In the 1700s, people in a Prussian city wondered whether they could stroll across all seven of its bridges exactly once. The answer started a branch of maths that now guides your phone's maps.",
  [
    ["A stroll in Königsberg", "Locals wondered whether a walk could cross each of seven bridges exactly once.", "The city of Königsberg, in what was then Prussia, sat on the River Pregel. The river split around two islands, and seven bridges linked the islands to each other and to the two riverbanks. Residents enjoyed a puzzle: could you take a walk through the city that crossed every bridge exactly once? You could start and finish anywhere, but no swimming, no boats and no turning back halfway across a bridge. Nobody could find a route, but nobody could prove that one did not exist either. In 1736 the Swiss mathematician Leonhard Euler, then working in St Petersburg, took up the problem. His answer to this small local puzzle launched a whole new field. Königsberg is now Kaliningrad, part of Russia."],
    ["Dots and lines", "Euler realised that only the connections mattered, not distances or shapes.", "Euler's breakthrough was to throw away almost everything about the map. The length of the bridges, the shape of the islands and the layout of the streets made no difference. All that mattered was which pieces of land were connected to which, and by how many bridges. So he effectively shrank each of the four land areas to a single point and treated each bridge as a line joining two points. Today we call such a diagram a graph, though it has nothing to do with the bar charts of school. The points are called nodes or vertices and the lines are called edges. This way of thinking, focusing on connections rather than measurements, grew into graph theory, and it also helped inspire topology, the study of properties that survive stretching and bending."],
    ["The odd and even rule", "A walk using every line once is possible only if no more than two points have an odd number of lines.", "Euler then counted the bridges touching each piece of land. Think about passing through a place in the middle of a walk: you arrive on one bridge and leave on another, so bridges get used up in pairs. That means every place you pass through needs an even number of bridges. Only the start and end of the walk can have an odd number. In a connected network, a route that uses every line exactly once can exist only if there are either zero or two points with an odd number of lines. In Königsberg, one island had five bridges and the other three land areas had three each. Four odd points meant the walk was impossible, and no amount of trying would ever find one."],
    ["Drawing without lifting your pen", "The same rule solves children's puzzles and even tells you where to start.", "Try drawing a house shape, a square with both diagonals and a triangular roof on top, without lifting your pen or going over a line twice. Count the lines meeting at each corner. The two top corners of the square have four each and the roof peak has two, all even numbers. The two bottom corners have three each. Exactly two odd points means it can be done, but only if you start at one bottom corner, and you will finish at the other. Start anywhere else and you will get stuck. Much of old Königsberg was destroyed in the Second World War, and several bridges were lost or replaced. With the bridges that stand today, only two land areas have an odd number, so a walk crossing each one exactly once is now possible."],
    ["From bridges to sat navs", "Graph theory now finds fast routes, links websites and keeps networks running.", "Euler's dots and lines turn out to describe much of the modern world. A road map is a graph, with intersections as points and roads as lines, each labelled with a distance or travel time. When your phone suggests the fastest way across town, it is running a route-finding method on a vast graph. One classic method was devised by the Dutch computer scientist Edsger Dijkstra in 1956, by his own account in about 20 minutes while sitting at a café with his fiancée. Airline routes, electricity grids, the links between web pages and the connections between computers on the internet are all graphs. Delivery companies use graph methods to plan their vans' routes."],
    ["Six degrees of separation", "In social networks, most people are linked by a surprisingly short chain of acquaintances.", "Social networks are graphs too, with people as points and friendships as lines. In the 1960s the American psychologist Stanley Milgram asked volunteers in the Midwest to pass a letter, through people they knew on a first name basis, towards a target person in the Boston area. The letters that arrived took around six steps on average, though many never arrived at all. The phrase 'six degrees of separation' later became popular through a 1990 play of that name. In 1998 the researchers Duncan Watts and Steven Strogatz showed why such 'small worlds' are common: a network of mostly local friendships needs only a few long-range links to bring everyone surprisingly close together. A 2016 analysis by Facebook found its users were separated by an average of about three and a half people in between."],
    ["Four colours are enough", "Any map can be coloured with four colours so that no neighbours match, a fact first proved with a computer.", "In 1852 a young British graduate, Francis Guthrie, was colouring a map of the counties of England and noticed he never needed more than four colours to keep neighbouring counties different. Could any map, however complicated, be coloured with just four? Turn the map into a graph, with regions as points and shared borders as lines, and it becomes a question about networks. The problem resisted proof for over a century. In 1976 Kenneth Appel and Wolfgang Haken at the University of Illinois finally proved it, but only by having a computer check nearly two thousand special cases, a job far too long for any person to do by hand. Some mathematicians were uneasy about a proof no human could fully check. Today the theorem is accepted, and computer-assisted proofs are a normal tool."]
  ],
  [
    [0, "How many bridges were in the famous Königsberg puzzle?", ["Four", "Five", "Six", "Seven"], 3, "Seven bridges joined two islands and two riverbanks."],
    [2, "Why was the Königsberg walk impossible?", ["The bridges were too far apart", "All four land areas had an odd number of bridges", "The river was too wide", "There were too many islands"], 1, "A walk using every bridge once allows at most two places with an odd number of bridges, and Königsberg had four."],
    [3, "Where must you start to draw the house shape in one continuous line?", ["At one of the two bottom corners", "At the roof peak", "At a top corner of the square", "Anywhere at all"], 0, "The bottom corners are the only two points with an odd number of lines, so the drawing must start at one and end at the other."],
    [5, "What did Watts and Strogatz show about 'small world' networks?", ["Everyone must know everyone else", "Social networks are completely random", "A few long-range links make everyone surprisingly close", "Letters rarely reach their target"], 2, "Adding just a few long-range links to a mostly local network sharply shortens the chains between people."],
    [6, "How was the four colour theorem first proved in 1976?", ["With a single elegant diagram", "With a computer checking many special cases", "By Euler in St Petersburg", "By colouring every map in the world"], 1, "Appel and Haken used a computer to check nearly two thousand configurations."]
  ]);

WB.L("check-digits", "maths", "intermediate", "Check digits: the hidden maths that catches typos", "Mistype one digit of a card number online and the website often knows instantly, before it has contacted any bank. The secret is a single extra digit doing some clever arithmetic.",
  [
    ["The trouble with typing numbers", "People most often get one digit wrong or swap two neighbouring digits.", "Every day, millions of long numbers are typed, read aloud, copied and scanned: card numbers, barcodes, account numbers and book codes. People make mistakes, and the mistakes are predictable. Studies of real errors, including a well-known analysis by the Dutch mathematician Jacobus Verhoeff in 1969, found that the most common slip by far is getting a single digit wrong, such as typing 7 instead of 1. The next most common is swapping two neighbouring digits, so that 58 becomes 85. A single wrong digit in a payment could send money to the wrong place or charge the wrong customer. The solution most systems use is wonderfully cheap: add one extra digit whose only job is to check the others."],
    ["How a check digit works", "The last digit is calculated from the others, so a mistake usually breaks the arithmetic.", "A check digit is worked out by running the other digits through a fixed recipe. Here is the simplest version. Suppose a shop's item codes are four digits long, and we add a fifth digit so that all five add up to a multiple of 10. For the code 2 4 7 3, the digits sum to 16, so the check digit is 4, making 24734, which adds up to 20. If someone later types 24834, the computer adds the digits, gets 21, and knows something is wrong. This simple version catches any single wrong digit, because changing one digit always changes the total by something other than a multiple of 10. But it has a weakness: swap two digits, as in 27434, and the total is unchanged, so the error sails straight through."],
    ["The barcode on your groceries", "Supermarket barcodes weight alternate digits by 1 and 3, which also catches most swapped digits.", "Look at the barcode on a packet in your pantry. The 13 digit number beneath it, known as an EAN-13, ends in a check digit. The recipe multiplies the first 12 digits alternately by 1 and 3, adds up the results, and picks the final digit that brings the total up to a multiple of 10. Because neighbouring digits get different weights, swapping them usually changes the total, and the system spots it. The one blind spot is swapping two neighbouring digits that differ by exactly 5, such as 1 and 6. Many Australian products have barcodes starting with 93, a prefix assigned to Australia by the barcode organisation GS1, though it shows where a company registered, not where a product was made."],
    ["Books and the number 11", "The old 10 digit ISBN used division by 11 to catch every single wrong digit and every neighbouring swap.", "Books have ISBNs. The older 10 digit version used a clever recipe. Multiply the first digit by 10, the second by 9, and so on down to the last digit, the check digit, which is multiplied by 1. The total must divide exactly by 11. Take the ISBN 0-306-40615-2. The first nine digits give 0 plus 27 plus 0 plus 42 plus 24 plus 0 plus 24 plus 3 plus 10, which is 130. Adding the check digit 2 gives 132, which is 12 times 11. Because 11 is a prime number, this system catches every single wrong digit and every swap of neighbouring digits. Sometimes the check digit needs to be 10, which is written as an X. Since 2007, books have used 13 digit ISBNs that follow the barcode recipe."],
    ["Card numbers and the Luhn check", "Card numbers use the Luhn formula, which catches typos but offers no protection against fraud.", "Credit and debit card numbers end in a check digit worked out with the Luhn formula, created by the IBM engineer Hans Peter Luhn, who patented it in 1960. Starting from the right and moving left, you double every second digit, beginning with the one next to the check digit. If doubling gives a two digit number, add those two digits together, so 8 doubled is 16, which becomes 7. Then add everything up, including the digits you did not double. For a valid number, the total is a multiple of 10. That is how a payment page can flag a mistyped card number instantly. But the check is public and easy to satisfy, so it only catches accidents. It says nothing about whether a card is real, active or actually yours."],
    ["Check digits in Australian life", "Australian identifiers such as ABNs have built-in checks, as do many account and ID numbers around the world.", "The Australian Business Number, or ABN, has 11 digits and a built-in check. The Australian Business Register publishes the method: after a small adjustment to the first digit, each digit is multiplied by a set weight, the results are added, and the total must divide evenly by 89. If it doesn't, the ABN cannot be valid, which helps accounting software catch typos on invoices. Tax file numbers are widely reported to include a similar check. Overseas, international bank account numbers, known as IBANs, carry two check digits based on division by 97. Australia does not use IBANs, relying instead on BSB and account numbers. In every case the logic is the same: a little arithmetic catches a lot of human error at almost no cost."],
    ["Beyond spotting errors: fixing them", "Error-correcting codes go further, repairing damaged data so that QR codes still scan when scratched.", "A check digit can tell you something is wrong, but not what. Error-correcting codes go a step further by adding enough carefully designed extra information to repair mistakes. In the late 1940s the American mathematician Richard Hamming, frustrated that his weekend computer jobs kept failing because of errors, devised codes that could find and fix a flipped digit automatically. Later codes, such as Reed-Solomon codes from 1960, protect data on CDs, in deep space communications and in QR codes. A QR code can be printed with different levels of protection, and at the highest level it can still be read even if around 30 per cent of it is damaged or covered. Behind everyday convenience sits some elegant mathematics."]
  ],
  [
    [0, "What is the most common kind of mistake when people copy long numbers?", ["Adding an extra digit", "Getting a single digit wrong", "Writing the number backwards", "Leaving out half the number"], 1, "Studies of real errors found single wrong digits are by far the most common, followed by swapped neighbours."],
    [2, "In supermarket barcodes, the first 12 digits are multiplied alternately by which numbers?", ["1 and 2", "2 and 5", "1 and 3", "10 and 1"], 2, "Alternating weights of 1 and 3 mean most swaps of neighbouring digits change the total."],
    [3, "In an old 10 digit ISBN, what does a check digit of X mean?", ["The check digit is 10", "The book is out of print", "The number is invalid", "The book was printed overseas"], 0, "Because the recipe works with division by 11, the check digit can be 10, which is written as X."],
    [4, "What can the Luhn check on a card number tell a website?", ["Whether the card has enough money", "Whether the card is stolen", "Who owns the card", "Whether the number has probably been mistyped"], 3, "The Luhn check only catches typing mistakes; it says nothing about whether a card is genuine or yours."],
    [6, "What can error-correcting codes do that a simple check digit cannot?", ["Make numbers shorter", "Repair some damaged data automatically", "Hide data from hackers", "Speed up typing"], 1, "They add enough extra information to fix errors, which is why a damaged QR code can still scan."]
  ]);

WB.L("benfords-law", "maths", "advanced", "Benford's law: why so many numbers start with 1", "In many tables of real-world numbers, from river areas to company accounts, almost a third begin with the digit 1. The pattern is real, it can be explained, and it has helped auditors spot cooked books.",
  [
    ["The grubby pages", "Two scientists, decades apart, noticed that numbers starting with 1 are surprisingly common.", "Before calculators, scientists looked up logarithms in thick books of tables. In 1881 the Canadian-American astronomer Simon Newcomb noticed something odd: the early pages, covering numbers starting with 1, were far more worn than the later ones. People seemed to be looking up numbers beginning with 1 much more often than numbers beginning with 9. His short note on the pattern was largely forgotten. In 1938 the American physicist Frank Benford, working at General Electric, noticed the same thing independently. He went further, collecting more than 20,000 numbers from around 20 very different sources, including the areas of rivers, city populations, physical constants and figures printed in magazines. The same lopsided pattern appeared again and again, and it now carries his name."],
    ["The pattern itself", "About 30 per cent of leading digits are 1, falling to under 5 per cent for 9.", "Benford's law describes how often each digit appears first in many collections of real numbers. You might expect each of the nine possible leading digits, 1 to 9, to turn up about 11 per cent of the time. Instead, in data that follow the law, about 30.1 per cent of numbers start with 1. Around 17.6 per cent start with 2, 12.5 per cent with 3 and 9.7 per cent with 4. The share keeps falling: 7.9 per cent for 5, 6.7 for 6, 5.8 for 7 and 5.1 for 8, down to just 4.6 per cent starting with 9. The formula behind these figures uses logarithms: the chance of a leading digit d is the base 10 logarithm of one plus one divided by d."],
    ["Why growth favours the digit 1", "Things that grow by percentages spend longer with a leading 1 than with any other digit.", "Imagine a town of 100 people that grows by 10 per cent a year. To go from 100 to 200 it has to double, which takes a little over seven years. During all that time its population starts with a 1. To go from 200 to 300 it only needs to grow by half, which takes a little over four years. And to go from 900 to 1,000, a rise of just 11 per cent, takes only about a year. Then it reaches 1,000 and must double again to escape the 1s. Anything that grows by multiplying rather than adding, like populations, prices, investments and company revenues, spends the most time starting with 1 and the least starting with 9. Snapshots of many such numbers inherit the same pattern."],
    ["The same in any units", "Benford's law survives a change of units, a sign that it reflects something deep about scale.", "There is another clue that the pattern is no accident. Suppose you take a list of company revenues in Australian dollars that follows Benford's law and convert them all into US dollars, yen or euros. Or take river lengths in kilometres and convert them into miles. Most individual leading digits will change, yet the overall pattern stays the same. Mathematicians call this scale invariance. In 1961 the mathematician Roger Pinkham showed that if a universal law of leading digits existed, one that did not depend on the choice of units, it would have to be Benford's law. This helps explain why the law shows up in such a wild mix of data. Numbers that span several orders of magnitude, and are not tied to any particular unit, tend to settle into this shape."],
    ["When the law does not apply", "Numbers confined to a narrow range, or assigned by people, do not follow Benford's law.", "Benford's law is not a law of nature that every list must obey. It works best for numbers that spread across several orders of magnitude, say from tens to tens of thousands, and that arise from natural processes or from combining other numbers. It fails for data stuck in a narrow range. Adult heights in centimetres almost all start with 1, because nearly everyone is between 100 and 199 centimetres tall, and adult body temperatures cluster around 37 degrees. It also fails for numbers that people assign, such as phone numbers, postcodes and lottery numbers, and for prices deliberately set at points like $9.99 or $49. Before applying the law to any data set, you need to ask whether there is a good reason to expect it to fit at all."],
    ["Catching cooked books", "Made-up numbers often break the pattern, so auditors use Benford's law as a red flag.", "When people invent numbers, they tend to spread first digits fairly evenly, or favour middle digits, because that feels random. Real financial data, such as invoice amounts or expense claims, often follow Benford's law closely. That gap makes the law a useful screening tool. In the 1990s the accounting researcher Mark Nigrini helped popularise its use in auditing, and tax agencies and forensic accountants in many countries have since used it. An auditor might run thousands of transactions through a quick test and find far too many amounts starting with 7 or 8, or an odd cluster just below an approval limit. That does not prove fraud. It flags where to look more closely, and many unusual patterns turn out to have innocent explanations, such as a business that charges many identical fees."],
    ["Using it wisely", "Benford's law is a clue, not proof, and it has been misused to make false claims.", "Because Benford's law sounds mysterious, it is easy to misuse. After the 2020 US presidential election, posts online claimed that vote counts in some cities broke Benford's law and therefore proved fraud. Statisticians pointed out the flaw: voting precincts are often drawn to be of broadly similar size, so their vote totals cluster in a narrow range and there is no reason to expect them to follow the law in the first place. The deeper lesson applies to any statistical tool. Before reading meaning into a deviation, ask whether the data should fit the pattern at all, and what else could explain the gap. Used carefully, Benford's law is a clever first check. Used carelessly, it becomes a way to dress up a hunch in the clothes of mathematics."]
  ],
  [
    [0, "What did Simon Newcomb notice in 1881?", ["Calculators gave wrong answers", "The early pages of logarithm books were more worn", "River lengths were often wrong", "Most numbers end in zero"], 1, "The pages for numbers starting with 1 were far grubbier, suggesting those numbers were looked up more often."],
    [1, "Roughly what share of numbers start with 1 under Benford's law?", ["About 11 per cent", "About 50 per cent", "About 30 per cent", "About 5 per cent"], 2, "About 30.1 per cent of leading digits are 1, compared with 4.6 per cent for 9."],
    [2, "A town grows 10 per cent a year. Which step takes the longest?", ["Growing from 900 to 1,000", "Growing from 500 to 600", "Growing from 200 to 300", "Growing from 100 to 200"], 3, "Going from 100 to 200 means doubling, which takes a little over seven years at 10 per cent."],
    [4, "Which data set would you not expect to follow Benford's law?", ["Adult heights in centimetres", "Populations of the world's towns", "Company revenues", "Areas of rivers"], 0, "Adult heights sit in a narrow range, so almost all of them start with 1."],
    [5, "What does a Benford's law mismatch tell an auditor?", ["Fraud has definitely occurred", "The data are perfectly accurate", "Where it may be worth looking more closely", "That the accounts use the wrong currency"], 2, "A mismatch is a red flag for further checking, not proof of wrongdoing."]
  ]);

WB.L("geometry-in-nature", "maths", "beginner", "Nature's geometry: hexagons, spirals and bubbles", "Bees build hexagons, sunflowers count in Fibonacci numbers and soap bubbles solve maths problems in an instant. Nature is full of geometry, and there are good reasons why.",
  [
    ["The bee's hexagon", "Hexagons tile a surface with no gaps while using the least wall for the space enclosed.", "Look at a slab of honeycomb and you see rows of near-perfect hexagons. Why that shape? Only three regular shapes fit together on a flat surface with no gaps: triangles, squares and hexagons. Of these, hexagons enclose a given area with the shortest total wall. For cells of the same area, a square needs about 7.5 per cent more perimeter than a hexagon, and a triangle about 22 per cent more. Bees must eat honey to make wax, so saving wax saves energy. Around 300 CE Pappus of Alexandria praised bees for their geometric wisdom. The stronger claim, that hexagons beat every possible way of dividing a flat surface into equal areas, was only proved in 1999, by the American mathematician Thomas Hales. It is known as the honeycomb conjecture."],
    ["Sunflower spirals", "Sunflower seeds sit in spirals whose counts are often neighbouring Fibonacci numbers.", "Look closely at the centre of a large sunflower and you will see seeds arranged in two sets of spirals, one curving clockwise and the other anticlockwise. Count them and you often get neighbouring numbers from the Fibonacci sequence, such as 34 and 55, or 55 and 89. Pinecones, pineapples and the centres of daisies show the same thing with smaller numbers, like 8 and 13. Fibonacci patterns are common rather than universal, though. A large citizen science project published in 2016, inspired by the code breaker Alan Turing's interest in sunflowers, counted the spirals on hundreds of seed heads and found that a sizeable minority did not fit simple Fibonacci patterns. Nature leans strongly towards these numbers, but it is a tendency rather than an unbreakable rule."],
    ["The golden angle", "Placing each new seed about 137.5 degrees round from the last packs seeds with no wasted space.", "A sunflower head grows from the centre, adding new seeds one at a time, and each new seed appears at a fixed angle around from the one before. If that angle were a simple fraction of a full turn, such as a quarter, the seeds would line up in four straight spokes with big gaps between them. The angle that best avoids lining up is about 137.5 degrees, called the golden angle. It is linked to the golden ratio, the number that resists being approximated by simple fractions more than any other. Using it, seeds fill the head evenly, packing in as many as possible. The spirals we see, and their Fibonacci counts, are a side effect of that efficient packing, and computer models reproduce them from this one rule."],
    ["Bubbles that solve problems", "Soap films automatically find the smallest surface, and always meet in threes at 120 degrees.", "Blow a single soap bubble and it becomes a sphere. That is no coincidence: for any amount of air, a sphere is the shape with the smallest possible surface, and surface tension pulls the soap film as tight as it can go. When bubbles cluster in a foam, they follow rules set out by the Belgian physicist Joseph Plateau in 1873. Soap films always meet in threes, at equal angles of 120 degrees, and the edges where films meet always come together in fours, at about 109.5 degrees. Dip a wire frame into soapy water and the film often forms the smallest surface spanning it, instantly solving a problem that can take pages of calculation. The architect Frei Otto used soap film models to design light, curving roofs."],
    ["Spirals that keep their shape", "Many shells grow as logarithmic spirals, getting bigger without changing shape.", "A snail or nautilus has a problem: the animal inside keeps growing, but it cannot remodel the shell it has already built. The solution is to keep adding material at the open end, so each new turn is a scaled-up copy of the last. The result is close to a logarithmic spiral, a curve that keeps the same shape whether you zoom in or out. The Swiss mathematician Jacob Bernoulli was so taken with this curve that he called it the 'marvellous spiral' and asked for it to be carved on his gravestone. The stonemason carved the wrong kind of spiral, one whose turns are evenly spaced. Rough versions appear in spiral galaxies and tropical cyclones. Popular claims that the nautilus follows the golden ratio, though, do not survive careful measurement."],
    ["Why there are no giant ants", "When something doubles in size, its strength grows four times but its weight grows eight times.", "Science fiction loves giant insects, but geometry is against them. Imagine making an ant twice as long, twice as wide and twice as tall. The cross section of its legs, which sets their strength, grows four times. Its volume, and so its weight, grows eight times. Each leg now has to carry twice as much weight for every unit of strength. Scale it up ten times and its weight rises a thousand times while its leg strength rises only a hundred times. Galileo described this square-cube law in 1638. It also helps explain why an elephant has such stout legs, why a mouse can survive falls that would injure a person, and why small animals such as shrews must eat almost constantly to replace the heat they lose."],
    ["Columns of stone", "Cooling lava can crack into columns that are often six sided, as you can see near Melbourne.", "Sometimes rock itself turns geometric. When a thick flow of lava cools slowly, it shrinks, and the strain opens cracks that spread through the rock. The cracks tend to meet at angles close to 120 degrees, forming long columns, many of them six sided, though five and seven sided columns are common too. The most famous example is the Giant's Causeway in Northern Ireland, with tens of thousands of interlocking basalt columns. Australia has fine examples as well, including Organ Pipes National Park on the north-western edge of Melbourne, where basalt columns rise above a creek. The same 120 degree meeting rule shows up in bubbles, honeycomb and mud that has dried and cracked many times over. Different materials and different forces keep arriving at the same efficient answers that geometry predicts."]
  ],
  [
    [0, "Of the regular shapes that tile a surface with no gaps, which uses the least wall for a given area?", ["Triangle", "Square", "Hexagon", "Octagon"], 2, "Hexagons enclose a given area with less perimeter than squares or triangles, saving the bees wax."],
    [2, "About how far round does each new sunflower seed sit from the one before?", ["90 degrees", "137.5 degrees", "120 degrees", "180 degrees"], 1, "The golden angle of about 137.5 degrees stops the seeds lining up in spokes, so they pack evenly."],
    [3, "At what angle do soap films meet when three of them join?", ["120 degrees", "90 degrees", "60 degrees", "137.5 degrees"], 0, "Plateau's rules say soap films always meet in threes at equal angles of 120 degrees."],
    [4, "What is special about a logarithmic spiral?", ["Its turns are evenly spaced", "It always has eight turns", "It only appears in galaxies", "It keeps the same shape as it grows"], 3, "Each turn is a scaled-up copy of the last, so a shell can grow without changing shape."],
    [5, "If an animal doubles in every dimension, how much does its weight increase?", ["Two times", "Eight times", "Four times", "Six times"], 1, "Volume, and so weight, grows by 2 times 2 times 2, which is eight, while leg strength grows only four times."]
  ]);

WB.L("history-of-counting", "maths", "beginner", "Why an hour has 60 minutes: a history of counting", "We count in tens, tell the time in sixties and buy eggs by the dozen. Each habit is a fossil from a different civilisation's way of counting, and together they tell a story more than 40,000 years long.",
  [
    ["Notches in bone", "The oldest possible counting records are notched bones tens of thousands of years old.", "Long before writing, people may have kept count by cutting marks into bone. The Lebombo bone, a baboon leg bone found in a cave in the mountains between South Africa and Eswatini, carries 29 notches and is more than 40,000 years old. The Ishango bone, found in what is now the Democratic Republic of the Congo and thought to be around 20,000 years old, bears groups of notches that some researchers read as deliberate number patterns. Nobody can be sure what these marks meant. But tally marks are the most natural counting system there is, with one mark for each thing. People still use them today, often grouping strokes in fives, to keep score in games or count votes by hand."],
    ["Ten fingers, ten digits", "Most number systems use base 10 because we have ten fingers, and some used fingers and toes to count in twenties.", "Most of the world counts in tens, and the reason is probably at the end of your arms. The word digit comes from the Latin digitus, meaning finger or toe. Counting in tens means that once you reach ten, you start a new group. Not every culture stopped at the fingers. Counting fingers and toes gives base 20, which the Maya used. Traces of counting in twenties survive in modern languages: French says quatre-vingts, literally 'four twenties', for 80, and English speakers once commonly used 'score' for 20, as in Abraham Lincoln's 'four score and seven years ago'. Some communities in Papua New Guinea traditionally counted by pointing to a sequence of body parts, running up one arm, across the head and down the other."],
    ["The Babylonian sixty", "Our 60 minutes and 360 degrees come from Mesopotamian counting in base 60.", "About 4,000 years ago, scribes in Mesopotamia, in what is now Iraq, did their sums in base 60. Sixty is a wonderfully convenient number because it divides evenly by 1, 2, 3, 4, 5, 6, 10, 12, 15, 20 and 30, which makes fractions like thirds and quarters easy to handle. Babylonian astronomers used it to track the heavens, and Greek astronomers later borrowed it. That is why we still divide an hour into 60 minutes and a minute into 60 seconds, and why a circle has 360 degrees, each split into 60 minutes of arc. One Babylonian clay tablet shows the square root of 2 written in base 60 and accurate to about six decimal places, a remarkable result from more than 3,500 years ago."],
    ["The usefulness of a dozen", "Twelve divides neatly in many ways, which may be why it survives in hours, eggs and inches.", "Twelve has a special place in counting too. The ancient Egyptians divided daytime and night-time into 12 hours each, which is the root of our 24 hour day. We still buy eggs by the dozen, and a dozen dozen, 144, is called a gross. Feet were divided into 12 inches, and before 1966 Australians used pounds, shillings and pence, with 12 pence in a shilling and 20 shillings in a pound. Twelve divides evenly by 2, 3, 4 and 6, which is handy when sharing things out. One popular theory for its origin is finger counting: use your thumb to touch the three segments of each of the other four fingers on one hand, and you can count to 12."],
    ["Roman numerals", "Roman numerals were good for recording numbers but clumsy for calculating.", "The Romans wrote numbers with letters: I for 1, V for 5, X for 10, L for 50, C for 100, D for 500 and M for 1,000. Symbols are added together, so 27 is XXVII, and a smaller symbol placed before a larger one is usually subtracted, so 4 is IV and 90 is XC. You still see Roman numerals on clock faces, at the end of film credits and in the names of monarchs and Super Bowls. Many clocks show 4 as IIII rather than IV. The system worked well for recording, but it is awkward for arithmetic. Try multiplying XLVIII by XIV. Romans calculated on counting boards, moving small stones. The Latin word for a pebble, calculus, gives us the word calculate."],
    ["The great import from India", "Place value with a zero, developed in India, made written arithmetic fast and reliable.", "The numerals you use today, 0 to 9, grew out of a system developed in India, where by around the sixth century CE mathematicians were writing numbers with just ten symbols, including zero, and a digit's value depended on its place. In 347, the 3 means three hundreds, while in 734 it means three tens. This made written arithmetic fast and reliable. Scholars in the Islamic world adopted and spread the system. The Persian mathematician Muhammad ibn Musa al-Khwarizmi wrote about it in the ninth century, and his name gives us the word algorithm. In 1202 Leonardo of Pisa, better known as Fibonacci, championed the numerals in Europe in his book Liber Abaci, showing merchants how much easier their bookkeeping could become. Even so, they took centuries to win out."],
    ["Ones and zeros", "Computers count in base 2, while attempts to make time decimal have failed.", "The simplest place value system of all uses just two digits, 0 and 1. In binary, each place is worth double the one to its right: 1, 2, 4, 8, 16 and so on. So 13 is written 1101, meaning one 8, one 4, no 2s and one 1. The German philosopher and mathematician Gottfried Leibniz published an account of binary in 1703. Centuries later it became the language of computers, because an electronic switch has two natural states, off and on. Meanwhile, the old base 60 has proved remarkably stubborn. During the French Revolution, France introduced decimal time, with 10 hours in a day and 100 minutes in each hour. People never warmed to it, and its compulsory use was suspended in 1795, after less than two years."]
  ],
  [
    [0, "What is the Lebombo bone thought to be?", ["A Roman counting board", "One of the oldest possible counting records", "A Babylonian clay tablet", "An early Egyptian calendar"], 1, "Its 29 notches, made more than 40,000 years ago, may be among the earliest records of counting."],
    [2, "Why is 60 such a handy base for working with fractions?", ["It is a prime number", "It is the number of fingers and toes", "It divides evenly by many numbers", "It was easy to write"], 2, "Sixty divides evenly by 1, 2, 3, 4, 5, 6, 10, 12, 15, 20 and 30, so thirds and quarters are simple."],
    [4, "Where does the word 'calculate' come from?", ["The Latin word for pebble", "The Greek word for count", "The name of a Roman emperor", "The Arabic word for number"], 0, "Romans calculated by moving small stones, and calculus is Latin for pebble."],
    [5, "What made the numerals developed in India so powerful?", ["They used letters for numbers", "They had a symbol for every number up to 100", "They were carved in stone", "A digit's value depends on its place, with zero as a placeholder"], 3, "Place value with zero lets just ten symbols write any number and makes written arithmetic easy."],
    [6, "How is 13 written in binary?", ["1011", "1101", "1110", "1001"], 1, "13 is one 8, one 4, no 2s and one 1, so it is written 1101."]
  ]);
