/* WISEBYTE LESSONS · Nature and Culture */
WB.LESSONS.push(
{
  id: "octopus-mind", audience: "adult", cat: "nature", level: "beginner",
  popularity: 83, added: "2026-06-30",
  title: "The alien intelligence of octopuses",
  hook: "An animal that thinks with its arms, tastes with its suckers, changes colour while colour-blind and escapes from aquariums.",
  sections: [
    { h: "A different path to intelligence", key: "Octopuses evolved intelligence completely separately from vertebrates like us.",
      b: "Octopuses are molluscs, related to snails and clams. Our last common ancestor with them was probably a small worm-like creature that lived over 500 million years ago. That means octopus intelligence evolved completely independently of ours. Philosopher Peter Godfrey-Smith, who spent years diving with octopuses off Sydney, describes them as the closest thing we'll meet to an intelligent alien. Studying them helps scientists understand what minds are, and the different ways they can be built." },
    { h: "Brains in the arms", key: "Octopuses have ~500 million neurons, about two thirds of them in their arms.",
      b: "An octopus has around 500 million neurons, similar to a dog. But about two thirds of them are in its eight arms, not its central brain. Each arm has its own cluster of neurons that can process information and control movement semi-independently. An arm can explore a crevice, taste what it finds and decide to grab something, while the central brain focuses elsewhere. Even an arm that has been severed can react to touch and grasp food for a while." },
    { h: "Tasting with suckers", key: "Octopus suckers can taste and smell by touch.",
      b: "Each of an octopus's suckers, up to around 2,000 on a common octopus, is packed with chemical receptors. So octopuses 'taste' what they touch. In 2020, researchers discovered special receptors in the suckers that let them detect chemicals on surfaces and identify prey hidden in cracks without seeing it. Imagine reaching into a dark cupboard and tasting everything your fingertips brushed against." },
    { h: "Three hearts, blue blood", key: "Octopuses have three hearts and blue, copper-based blood.",
      b: "Octopuses have three hearts. Two pump blood through the gills to pick up oxygen; the third pumps it around the rest of the body. That third heart stops beating when the octopus swims, which is partly why they tire quickly and prefer crawling. Their blood uses a copper-based protein called haemocyanin to carry oxygen, which makes it blue. Haemocyanin works well in cold, low-oxygen water." },
    { h: "Masters of disguise", key: "Octopuses change colour and texture using chromatophores, despite appearing to be colour-blind.",
      b: "Octopuses can change colour, pattern and even skin texture in a fraction of a second. Thousands of pigment cells called chromatophores, each controlled by tiny muscles and nerves, expand or shrink to show colour. Other cells reflect light to create shimmering or white effects, and muscles raise bumps and spikes to mimic rocks or seaweed. Remarkably, octopuses appear to be colour-blind, having only one type of light receptor. Scientists are still working out how they match colours so well." },
    { h: "Escape artists", key: "With no bones, an octopus can squeeze through any gap bigger than its beak.",
      b: "An octopus has no bones; its only hard part is its parrot-like beak. So it can squeeze through any gap larger than the beak, sometimes just a couple of centimetres. Aquarium keepers know them as escape artists. In 2016, an octopus named Inky escaped from New Zealand's National Aquarium by slipping out of a gap in his tank, crossing the floor and sliding down a drainpipe into the sea. Others have been caught sneaking into neighbouring tanks for a snack." },
    { h: "Problem solvers and tool users", key: "Octopuses unscrew jars, solve mazes and carry coconut shells as portable shelters.",
      b: "Octopuses can learn to unscrew jar lids, even from the inside, navigate mazes and recognise individual humans, sometimes squirting water at people they dislike. In Indonesia, veined octopuses have been filmed collecting discarded coconut shell halves, carrying them awkwardly across the sea floor, and assembling them into portable shelters, one of the few known examples of tool use by an invertebrate. Off the New South Wales coast, researchers have found gloomy octopuses living in small communities nicknamed Octopolis and Octlantis." },
    { h: "Short, intense lives", key: "Most octopuses live only one to two years and die soon after breeding.",
      b: "Despite their intelligence, most octopuses live only one to two years. Many species breed once and then die. A female guards her eggs, sometimes for months, without eating, and dies soon after they hatch. One deep-sea octopus was observed brooding her eggs for four and a half years, the longest known of any animal. Their short lives puzzle scientists: why evolve a big, costly brain if you won't live long enough to learn much? It's one of the many mysteries these creatures still hold." },
  ],
  quiz: [
    { s: 1, q: "Where are most of an octopus's neurons?", o: ["In its central brain", "In its arms", "In its hearts", "In its eyes"], a: 1, e: "About two thirds are in the arms." },
    { s: 2, q: "What can octopus suckers do?", o: ["Taste what they touch", "See light", "Hear sounds", "Nothing special"], a: 0, e: "They're packed with chemical receptors." },
    { s: 3, q: "Why is octopus blood blue?", o: ["It contains copper-based haemocyanin", "It's cold", "It contains ink", "It lacks oxygen"], a: 0, e: "Our blood uses iron-based haemoglobin." },
    { s: 5, q: "What limits the size of gap an octopus can squeeze through?", o: ["Its head", "Its beak", "Its hearts", "Its eyes"], a: 1, e: "The beak is its only hard part." },
    { s: 7, q: "How long do most octopuses live?", o: ["1 to 2 years", "10 years", "25 years", "Over 50 years"], a: 0, e: "Many die soon after breeding." },
  ],
  related: ["evolution", "wildlife"],
},
{
  id: "bees", audience: "adult", cat: "nature", level: "beginner",
  popularity: 72, added: "2026-09-24",
  title: "Why bees matter",
  hook: "About a third of what we eat depends on pollinators. Australia has around 2,000 native bee species most people have never noticed.",
  sections: [
    { h: "Pollination", key: "Pollinators carry pollen between flowers, letting many plants produce fruit and seeds.",
      b: "Many flowering plants can't make fruit or seeds unless pollen moves from one flower to another. Wind does the job for some, like wheat and rice, but many others rely on animals, mostly insects, that visit flowers for nectar and pollen and carry pollen with them. Bees are the most important pollinators. The UN Food and Agriculture Organization estimates that about three quarters of the world's leading food crops benefit at least partly from animal pollination." },
    { h: "What's on the line", key: "Crops like almonds, apples, berries and avocados depend heavily on pollinating insects.",
      b: "Without pollinators, supermarket shelves would look very different. Almonds depend almost entirely on bees; Australia's almond industry hires hundreds of thousands of beehives each winter to pollinate its orchards. Apples, cherries, blueberries, avocados, melons, pumpkins and many vegetable seeds also rely heavily on them. Staple grains like wheat, rice and corn don't, so we wouldn't starve, but our diets would be far less varied and nutritious, and many foods would become much more expensive." },
    { h: "Honey bees", key: "European honey bees were introduced to Australia in 1822 and live in large, organised colonies.",
      b: "The honey bee most people know isn't native to Australia. European honey bees were introduced in 1822. A hive can hold tens of thousands of bees: one queen who lays eggs, a few hundred male drones, and thousands of female workers who build comb, feed young, guard the hive and forage. To make about half a kilogram of honey, bees may visit around two million flowers. Honey bees are vital for commercial pollination, and there are also large feral populations in the bush." },
    { h: "The waggle dance", key: "Honey bees communicate the direction and distance of food using the waggle dance.",
      b: "When a forager finds a good patch of flowers, she returns to the hive and performs a 'waggle dance' on the honeycomb. The angle of her waggle run relative to vertical shows the direction of the food relative to the Sun, and the length of the waggle indicates distance. Other bees follow her movements and fly straight to the flowers. Austrian scientist Karl von Frisch decoded the dance and shared the 1973 Nobel Prize in Physiology or Medicine." },
    { h: "Australia's native bees", key: "Australia has around 2,000 native bee species, most of them solitary.",
      b: "Australia has around 2,000 native bee species, many still not formally described. Most are solitary: each female builds her own nest in the ground, in wood or in plant stems, and doesn't live in a hive. They come in striking forms, like the blue-banded bee, which pollinates tomatoes by 'buzz pollination', vibrating flowers to shake pollen loose, something honey bees can't do. About a dozen species are social stingless bees, found mainly in warmer areas, which make small amounts of tangy 'sugarbag' honey that Aboriginal people have long harvested." },
    { h: "Threats to bees", key: "Bees face habitat loss, pesticides, disease, parasites like varroa and climate change.",
      b: "Bees face many pressures: loss of flowering habitat, some pesticides, diseases and parasites, and climate change shifting when flowers bloom. The varroa mite, a parasite that has devastated honey bee colonies worldwide, was detected in Newcastle, NSW, in 2022. After a major effort, authorities concluded in 2023 that eradication was no longer feasible, and the focus shifted to managing it. Australia had been the last inhabited continent free of varroa. Native bees aren't affected by varroa but face their own habitat pressures." },
    { h: "Other pollinators", key: "Flies, beetles, moths, butterflies, birds, bats and even possums also pollinate.",
      b: "Bees aren't the only pollinators. Hoverflies, beetles, moths and butterflies all move pollen. In Australia, birds such as honeyeaters and lorikeets pollinate many native plants like banksias, grevilleas and eucalypts. Flying foxes pollinate eucalypts as they travel long distances at night, spreading pollen across the landscape. Even small marsupials like the honey possum, which feeds almost entirely on nectar and pollen, act as pollinators." },
    { h: "Helping bees at home", key: "Plant diverse flowers, avoid unnecessary pesticides and provide water and nesting spots.",
      b: "You can help pollinators even in a small backyard or on a balcony. Plant a variety of flowering plants, especially native ones, so something is blooming across the seasons. Herbs like lavender, basil and rosemary are popular with bees when they flower. Avoid spraying pesticides, especially on flowering plants. Leave a shallow dish of water with pebbles for landing. Leave some bare ground, or build a simple 'bee hotel' from drilled wood blocks, for native solitary bees to nest in." },
  ],
  quiz: [
    { s: 0, q: "About what share of the world's leading food crops benefit from animal pollination?", o: ["About 5%", "About three quarters", "All of them", "None"], a: 1, e: "According to the UN FAO." },
    { s: 2, q: "When were European honey bees introduced to Australia?", o: ["1788", "1822", "1901", "They're native"], a: 1, e: "They're not native to Australia." },
    { s: 3, q: "What does the honey bee waggle dance communicate?", o: ["Danger", "Direction and distance to food", "The queen's health", "The weather"], a: 1, e: "Decoded by Karl von Frisch." },
    { s: 4, q: "What can blue-banded bees do that honey bees can't?", o: ["Make large amounts of honey", "Buzz pollinate flowers such as tomatoes", "Perform the waggle dance", "Live in hives of tens of thousands"], a: 1, e: "They vibrate flowers to shake the pollen loose." },
    { s: 5, q: "What parasite of honey bees was detected in NSW in 2022?", o: ["Varroa mite", "Fire ant", "Cane toad", "Locust"], a: 0, e: "Eradication was later judged no longer feasible." },
  ],
  related: ["octopus-mind", "wildlife"],
},
{
  id: "wildlife", audience: "adult", cat: "nature", level: "beginner",
  popularity: 85, added: "2026-09-24",
  title: "Australia's 'deadly' animals, in perspective",
  hook: "Snakes, spiders, sharks and crocs get the headlines. The numbers tell a very different, and reassuring, story.",
  sections: [
    { h: "The reputation", key: "Australia is famous for dangerous animals, but deaths from them are rare.",
      b: "Australia has a fearsome reputation: venomous snakes, deadly spiders, box jellyfish, crocodiles and sharks. It's true that many of the world's most venomous snakes live here. But the chance of being killed by any wild animal in Australia is extremely low. A study of hospital and coronial data from 2000 to 2013 found that about 20 to 30 people died from animal-related causes in Australia each year, and most of those deaths weren't from the animals you'd expect." },
    { h: "The real killers", key: "Horses and cattle cause more deaths than venomous snakes or spiders.",
      b: "That same study found that horses and cattle were responsible for more deaths than any wild animal, through falls, kicks and crushing. Bees and wasps, through severe allergic reactions called anaphylaxis, caused about as many deaths as snakes. The lesson: familiar animals cause far more harm than the exotic ones we fear, simply because we're around them so much more." },
    { h: "Snakes", key: "Australia averages around 2 snakebite deaths a year; the pressure immobilisation bandage saves lives.",
      b: "Australia has some of the most venomous snakes in the world, including the inland taipan and the eastern brown snake. Yet on average only about two people die from snakebite each year, thanks to antivenom, fast emergency care and good first aid. Australian researchers developed the pressure immobilisation technique: call 000, keep the person still, and wrap a firm bandage over the bite and up the whole limb, then splint it. Don't wash the bite, cut it or apply a tourniquet. Most bites happen when people try to catch or kill snakes." },
    { h: "Spiders", key: "No one has died from a confirmed spider bite in Australia since antivenoms became available.",
      b: "Sydney funnel-web and redback spiders can be dangerous, but no one has died from a confirmed spider bite in Australia since the funnel-web antivenom was introduced in 1981; redback antivenom has been available since the 1950s. The funnel-web antivenom is made using venom 'milked' from spiders, some collected by members of the public and handed in to the Australian Reptile Park. For a suspected funnel-web bite, use pressure immobilisation and call 000." },
    { h: "Sharks and crocodiles", key: "Fatal shark and crocodile attacks are rare, averaging a few a year combined.",
      b: "Shark attacks get enormous media attention, but fatal attacks in Australia average only a few a year, while millions of people swim and surf. Drowning kills far more beachgoers: around 300 people drown in Australia each year across all waterways. Saltwater crocodiles in northern Australia are genuinely dangerous and cause roughly one or two deaths a year, usually when people ignore warning signs. In croc country, stay well back from the water's edge and never swim where crocodiles may be present." },
    { h: "In the water", key: "Box jellyfish and irukandji are a risk in tropical waters in summer; swim at patrolled beaches.",
      b: "In tropical northern waters, box jellyfish and tiny irukandji jellyfish are a serious risk during the warmer months, roughly October to May. Box jellyfish stings can be fatal. Swim at patrolled beaches, inside stinger nets where provided, and wear a full-body stinger suit. For a box jellyfish sting, call 000 and pour vinegar over the sting for at least 30 seconds; vinegar is not recommended for bluebottle stings, which are best treated with hot water. Always swim between the flags." },
    { h: "Swooping magpies", key: "Magpies swoop in spring to protect their nests; walk away calmly and protect your head.",
      b: "Every spring, some Australian magpies swoop people who come near their nests. It's the male bird protecting his chicks, usually for about six weeks. Most swoops are warnings, but they can cause eye injuries. Avoid known swooping areas if you can, walk rather than run, wear a hat and sunglasses, and cyclists should dismount and walk through. Interestingly, research shows magpies can recognise individual human faces and are less likely to swoop people who've been kind to them." },
    { h: "Keeping it in perspective", key: "The biggest outdoor dangers are drowning, heat, sun and roads, not wildlife.",
      b: "Australia's genuinely big outdoor killers are far less exotic: drowning, road crashes, extreme heat and, over the long run, skin cancer from UV. Heatwaves kill more Australians than any other natural hazard. So by all means respect the wildlife, learn basic snakebite first aid and heed croc and stinger warnings. But the most life-saving habits are swimming between the flags, being sun smart, staying hydrated in heatwaves and driving safely." },
  ],
  quiz: [
    { s: 1, q: "Which animals caused more deaths in Australia than venomous snakes in the 2000–2013 study?", o: ["Horses and cattle", "Koalas", "Kangaroos only", "Spiders"], a: 0, e: "Familiar animals cause most harm." },
    { s: 2, q: "On average, about how many people die from snakebite in Australia each year?", o: ["About 2", "About 20", "About 200", "About 2,000"], a: 0, e: "Antivenom, fast emergency care and good first aid save nearly everyone." },
    { s: 3, q: "Since when has no one died from a confirmed spider bite in Australia?", o: ["1981, when funnel-web antivenom arrived", "2020", "Nobody ever has", "1901"], a: 0, e: "Redback antivenom dates from the 1950s." },
    { s: 4, q: "What kills far more Australian beachgoers than sharks?", o: ["Crocodiles", "Stingrays", "Drowning", "Box jellyfish"], a: 2, e: "Around 300 people drown in Australia each year." },
    { s: 7, q: "Which natural hazard kills the most Australians?", o: ["Sharks", "Heatwaves", "Snakes", "Earthquakes"], a: 1, e: "Heat is the deadliest natural hazard." },
  ],
  related: ["first-aid", "sun-safety"],
},
{
  id: "english-language", audience: "adult", cat: "arts", level: "beginner",
  popularity: 77, added: "2026-09-24",
  title: "The strange story of English",
  hook: "Why is English spelling so chaotic? Why do we eat 'beef' from a 'cow'? Blame invaders, printers and a mysterious vowel shift.",
  sections: [
    { h: "Anglo-Saxon roots", key: "English began with Germanic tribes settling Britain in the 5th century.",
      b: "English began in the 5th century, when Germanic tribes, the Angles, Saxons and Jutes, crossed the North Sea and settled in Britain. Their language, Old English, would be unreadable to most of us today; the epic poem Beowulf looks almost like a foreign language. But many of our most basic, everyday words come from it: house, water, bread, eat, sleep, mother, love, and the word 'English' itself, from the Angles." },
    { h: "The Vikings leave their mark", key: "Viking settlers added Norse words like sky, egg, knife and even 'they'.",
      b: "From the late 700s, Viking raiders and then settlers from Scandinavia arrived in England. Old Norse was related to Old English, so the two mixed easily. English borrowed hundreds of everyday words from Norse, including sky, egg, knife, window, skin, skull, husband, law and even the pronouns they, them and their. Words starting with 'sk', like skirt and sky, often have Norse origins, while their older English equivalents, like shirt, survived alongside them with different meanings." },
    { h: "1066: the French arrive", key: "After the Norman Conquest, French flooded English, especially in law, government and food.",
      b: "In 1066, William of Normandy conquered England, and for around 300 years the ruling class spoke Norman French. English survived among ordinary people, but it absorbed around 10,000 French words, especially related to power: government, parliament, court, judge, jury, crime, army and nobility. This created a class divide that still shows in food: the animals, tended by English-speaking peasants, kept English names like cow, pig and sheep, while the meat served to French-speaking nobles took French names: beef, pork and mutton." },
    { h: "Why spelling is so weird", key: "The Great Vowel Shift changed pronunciation after spelling had started to settle, leaving mismatches.",
      b: "Between roughly 1400 and 1700, English went through the Great Vowel Shift, a major change in how long vowels were pronounced. 'Bite' had sounded like 'beet' and 'house' like 'hoose'. But spelling, influenced by the arrival of printing in England in 1476, was starting to settle during this time, so many words kept spellings that matched old pronunciations. Printers, some of them Dutch, added quirks too. Words like 'knight', where the k and gh were once pronounced, are fossils of older English." },
    { h: "Shakespeare and friends", key: "Shakespeare's works include the first recorded uses of many words and phrases still in use.",
      b: "William Shakespeare's works contain the first recorded uses of many words and phrases that are still common, though some were probably already in speech. Phrases include 'the be-all and end-all', 'wild-goose chase', 'heart of gold', 'in a pickle' and 'wear my heart upon my sleeve'. The 1611 King James Bible also shaped the language with phrases like 'the salt of the earth' and 'a drop in the bucket'. Samuel Johnson's influential dictionary of 1755 helped standardise meanings and spellings." },
    { h: "A borrowing language", key: "English has borrowed words from hundreds of languages around the world.",
      b: "English is a magpie language, borrowing freely from others. From Latin and Greek came thousands of scientific and academic words. Trade and empire brought words from around the world: shampoo, bungalow and pyjamas from Indian languages; tea and ketchup from Chinese; algebra and coffee via Arabic; tsunami and emoji from Japanese; chocolate and tomato from Nahuatl, the language of the Aztecs. This is one reason English has such a huge vocabulary, often with several words for similar ideas." },
    { h: "Australian English", key: "Australian English has its own accent, slang and words borrowed from Aboriginal languages.",
      b: "Australian English developed from the mix of accents brought by convicts and settlers, mainly from southern England and Ireland, and soon had a distinct accent. It borrowed around 400 words from Aboriginal languages, including kangaroo, koala, wombat, dingo, billabong, yakka and boomerang. It's famous for shortening words: arvo, brekkie, servo, barbie and ambo. Australian spelling mostly follows British conventions, with some exceptions. The Macquarie Dictionary, first published in 1981, records Australian English." },
    { h: "A global language", key: "English is spoken by about 1.5 billion people, most of them as a second language.",
      b: "Today, around 1.5 billion people speak English, but only about 380 million as a first language. It's the dominant language of international business, science, aviation and the internet, a result of British colonial history and later American economic and cultural influence. As it spreads, English keeps changing, with new varieties, slang and words emerging all the time. Dictionaries now add hundreds of new words each year. Language is always a work in progress." },
  ],
  quiz: [
    { s: 0, q: "Which groups brought the earliest form of English to Britain?", o: ["The Romans", "The Angles, Saxons and Jutes", "The Normans", "The Vikings"], a: 1, e: "Germanic tribes in the 5th century." },
    { s: 1, q: "Which everyday pronoun did English borrow from Old Norse?", o: ["I", "They", "You", "We"], a: 1, e: "Along with them and their." },
    { s: 2, q: "Why do we call cow meat 'beef'?", o: ["It's an Australian word", "French-speaking nobles ate it after 1066, and 'beef' comes from French", "It's short for 'beefy'", "It's from Latin"], a: 1, e: "The animal kept its English name; the meat took the French one." },
    { s: 3, q: "What was the Great Vowel Shift?", o: ["A change in vowel pronunciation from about 1400–1700", "A spelling reform", "The loss of vowels", "A French invasion"], a: 0, e: "Spelling didn't keep up with the new sounds." },
    { s: 6, q: "Which of these words comes from an Aboriginal language?", o: ["Kangaroo", "Beef", "Sky", "Parliament"], a: 0, e: "Along with koala, wombat and billabong." },
  ],
  related: ["renaissance", "printing-press"],
},
);
