/* WISEBYTE LESSONS · Science (part 1) */
WB.LESSONS.push(
{
  id: "evolution", audience: "adult", cat: "science", level: "beginner",
  popularity: 80, added: "2026-06-25",
  title: "How evolution works",
  hook: "No designer, no plan, just time, variation and small differences adding up over millions of years.",
  sections: [
    { h: "Darwin's big idea", key: "Darwin (and Wallace) proposed that species change over generations through natural selection.",
      b: "In 1859, Charles Darwin published On the Origin of Species. Drawing on years of observation, including his voyage on HMS Beagle, which stopped in Sydney and Hobart in 1836, he argued that living things change over many generations through a process he called natural selection. Alfred Russel Wallace, working in South-East Asia, reached the same idea independently, and their work was presented together in 1858. It has since become the foundation of modern biology." },
    { h: "Variation", key: "Individuals vary, and much of that variation comes from genes passed to offspring.",
      b: "No two individuals are exactly alike. Some giraffes have slightly longer necks; some moths are slightly darker; some bacteria are slightly more resistant to a drug. Much of this variation comes from differences in genes, which are passed from parents to offspring. New variation arises from mutations, small random changes in DNA, and from the reshuffling of genes that happens with sexual reproduction. Most mutations are neutral or harmful, but occasionally one is helpful." },
    { h: "Survival and reproduction", key: "Individuals with traits that suit their environment leave more offspring, so those traits spread.",
      b: "Every species produces more offspring than can survive. A cod can release millions of eggs, and even slow-breeding elephants would overrun the planet if every calf survived. So there's competition for food, mates and safety. Individuals whose traits suit their environment are slightly more likely to survive and have young, passing those traits on. Over many generations, helpful traits become more common and unhelpful ones less so. That's natural selection: simple, relentless and unguided." },
    { h: "A real example", key: "Dark peppered moths spread when soot blackened trees, because birds spotted pale moths more easily.",
      b: "Peppered moths in England were mostly pale, speckled like the lichen on tree bark. During the Industrial Revolution, soot killed the lichen and blackened the trees. Within decades, dark moths became far more common around industrial cities, because birds spotted and ate pale moths more easily. When clean-air laws reduced pollution in the late 20th century, pale moths bounced back. Scientists have since tracked the gene responsible, making it one of the best-documented examples of evolution in action." },
    { h: "Evolution you can watch", key: "Antibiotic resistance is evolution happening fast, right now.",
      b: "Evolution isn't only ancient history. Bacteria reproduce so quickly, sometimes every 20 minutes, that they can evolve within weeks. When antibiotics kill most bacteria in an infection, any with a lucky mutation that helps them survive are left to multiply. Repeat that often enough and you get resistant 'superbugs'. It's also why doctors say to take antibiotics exactly as prescribed and not to use them for viral infections like colds. Insects evolving resistance to pesticides works the same way." },
    { h: "Not 'survival of the strongest'", key: "'Fittest' means best suited to an environment, not strongest; evolution has no goal.",
      b: "'Survival of the fittest' is a phrase coined by philosopher Herbert Spencer, and it's often misunderstood. It doesn't mean the strongest survive. It means those best suited to a particular environment leave the most offspring. Sometimes that's the fastest, but it might be the best camouflaged, the most cooperative or the one that needs the least food. A trait that helps in one place can hurt in another. And evolution has no goal or direction; it simply keeps whatever works well enough, right now." },
    { h: "The evidence", key: "Fossils, DNA, anatomy and observed change all independently support evolution.",
      b: "Evolution is supported by several independent lines of evidence. Fossils show changing life forms through time, including transitional species like early whales with legs. DNA comparisons show how closely species are related; humans and chimpanzees share about 98.8% of their DNA. Anatomy reveals shared designs, like the same bones in a human arm, a bat wing and a whale flipper. And we observe evolution directly in bacteria, insects and even Darwin's finches in the Galápagos." },
    { h: "Deep time and us", key: "Earth is about 4.5 billion years old; humans share common ancestors with all life.",
      b: "Earth is about 4.5 billion years old, and life appeared at least 3.5 billion years ago. That's enough time for small changes to add up to the enormous variety of life today. Humans didn't evolve from modern chimpanzees; we share a common ancestor that lived roughly 6 to 7 million years ago. Our own species, Homo sapiens, appeared in Africa around 300,000 years ago. Go back far enough and every living thing, from koalas to mushrooms, shares a common ancestor." },
  ],
  quiz: [
    { s: 0, q: "Who published On the Origin of Species in 1859?", o: ["Isaac Newton", "Charles Darwin", "Gregor Mendel", "Albert Einstein"], a: 1, e: "Charles Darwin published it in 1859." },
    { s: 2, q: "In natural selection, which individuals pass on their traits most?", o: ["The largest ones", "Those best suited to their environment", "The oldest ones", "Those that try hardest"], a: 1, e: "Better-suited individuals survive and reproduce more." },
    { s: 4, q: "Why is antibiotic resistance an example of evolution?", o: ["Antibiotics create new bacteria", "Bacteria that survive the drug multiply and pass on resistance", "Bacteria learn from humans", "It isn't evolution"], a: 1, e: "The drug selects for resistant survivors." },
    { s: 5, q: "What does 'fittest' mean in evolution?", o: ["Physically strongest", "Fastest", "Best suited to the environment", "Most intelligent"], a: 2, e: "Fitness means how well suited an organism is to its environment." },
    { s: 7, q: "What is the relationship between humans and chimpanzees?", o: ["Humans evolved from chimpanzees", "We share a common ancestor from millions of years ago", "We're not related", "Chimps evolved from humans"], a: 1, e: "Our lineages split roughly 6 to 7 million years ago." },
  ],
  related: ["dna", "antibiotics"],
},
{
  id: "water", audience: "adult", cat: "science", level: "intermediate",
  popularity: 58, added: "2026-09-18",
  title: "Water is weird",
  hook: "The most ordinary liquid on Earth breaks almost every rule in chemistry, and life depends on it.",
  sections: [
    { h: "A bent molecule", key: "Water (H₂O) is a bent, polar molecule: one oxygen and two hydrogens.",
      b: "A water molecule is one oxygen atom bonded to two hydrogen atoms, in a bent shape like a wide 'V', with an angle of about 104.5 degrees. Oxygen pulls the shared electrons towards itself, making the oxygen end slightly negative and the hydrogen ends slightly positive. That uneven charge makes water polar, a bit like a tiny magnet. Almost everything strange about water follows from this one simple fact." },
    { h: "Hydrogen bonds", key: "Hydrogen bonds are weak attractions between water molecules that explain most of its oddness.",
      b: "The positive hydrogen end of one water molecule is attracted to the negative oxygen end of its neighbour. These weak links are called hydrogen bonds. In liquid water they constantly form and break, trillions of times a second. They make water molecules cling to each other far more than you'd expect for such small molecules. Without hydrogen bonds, water would boil at around minus 80°C, and Earth would have no liquid oceans at all." },
    { h: "Ice floats", key: "Ice floats because freezing locks molecules into an open lattice about 9% less dense than liquid water.",
      b: "Most substances are densest as solids: solid wax sinks in melted wax. Water does the opposite. When it freezes, hydrogen bonds lock the molecules into an open, hexagonal lattice, which takes up more space. Ice is about 9% less dense than liquid water, so it floats. That's why pipes burst in freezing weather and why icebergs show only about a tenth of their bulk above the surface. Water is actually densest at about 4°C." },
    { h: "Why floating ice matters", key: "Because ice floats, lakes freeze from the top, insulating life beneath.",
      b: "If ice sank, lakes and seas in cold regions would freeze from the bottom up, and many would freeze solid every winter, killing most life in them. Instead, floating ice forms an insulating lid on top. The water beneath stays liquid, often at around 4°C, and fish, plants and other creatures survive the winter underneath. This quirk of chemistry has helped life on Earth persist through ice ages." },
    { h: "It stores heat", key: "Water's high heat capacity keeps coastal climates mild and body temperature stable.",
      b: "Water has a very high heat capacity: it takes a lot of energy to warm it up, and it releases that energy slowly as it cools. That's why the sea is still cold in early summer and still warm in autumn, and why coastal cities like Sydney have milder temperatures than inland towns like Dubbo. The oceans absorb enormous amounts of heat, moderating global climate. Your body, which is around 60% water, uses the same property to hold a steady temperature." },
    { h: "Sweat and evaporation", key: "Evaporating water carries away lots of heat, which is how sweating cools you.",
      b: "Turning liquid water into vapour also takes a lot of energy, because hydrogen bonds must be broken. When sweat evaporates from your skin, it carries that heat away, cooling you down. That's why a breeze feels so good on a hot day, and why humid days feel worse: when the air is already full of moisture, sweat evaporates more slowly. Evaporative coolers, common in drier parts of Australia, work on the same principle." },
    { h: "Surface tension", key: "Hydrogen bonds give water strong surface tension, letting insects walk on it.",
      b: "At the surface of water, molecules are pulled inwards by their neighbours below, creating a kind of elastic skin called surface tension. It's strong enough for insects like water striders to walk on ponds and for a carefully placed paper clip to float. Surface tension also helps water climb up narrow tubes, called capillary action, which is part of how plants draw water from their roots up to their leaves." },
    { h: "The universal solvent", key: "Because it's polar, water dissolves more substances than almost any other liquid.",
      b: "Because it's polar, water pulls apart and surrounds many other charged or polar molecules, dissolving them. It dissolves more substances than almost any other liquid, which is why it's called the universal solvent. It carries nutrients in your blood, minerals from rocks into rivers, and salt into the sea. It's also why water is so hard to keep pure. Every chemical reaction that keeps you alive happens in water, which is why scientists searching for life elsewhere start by looking for it." },
  ],
  quiz: [
    { s: 0, q: "What is a water molecule made of?", o: ["Two oxygen atoms and one hydrogen", "One oxygen atom and two hydrogens", "One carbon and two oxygens", "Hydrogen only"], a: 1, e: "H₂O: two hydrogens and one oxygen." },
    { s: 1, q: "What are hydrogen bonds?", o: ["Weak attractions between water molecules", "Strong bonds inside an atom", "Bonds between salt and water only", "A type of ice"], a: 0, e: "They're weak attractions between charged ends of neighbouring molecules." },
    { s: 2, q: "Why does ice float?", o: ["It contains trapped air", "Its molecules lock into an open, less dense pattern", "Cold things always float", "Freezing removes mass"], a: 1, e: "The open lattice makes ice about 9% less dense." },
    { s: 4, q: "Why do coastal cities have milder temperatures than inland ones?", o: ["Water has a high heat capacity", "Salt reflects heat", "Waves create wind", "Sand is cooler"], a: 0, e: "The sea absorbs and releases heat slowly." },
    { s: 5, q: "Why do humid days feel hotter?", o: ["Humid air is hotter", "Sweat evaporates more slowly, so it cools you less", "Humidity stops breathing", "Water blocks sunlight"], a: 1, e: "Evaporation is what carries heat away." },
  ],
  related: ["climate-change", "evolution"],
},
{
  id: "quantum", audience: "adult", cat: "science", level: "advanced",
  trending: true, popularity: 89, added: "2026-09-22",
  title: "Quantum mechanics, simply",
  hook: "The physics of the very small breaks every everyday rule. Yet it's the most tested theory in science, and it runs your phone.",
  sections: [
    { h: "The physics of the very small", key: "Quantum mechanics describes how atoms and particles behave; it's behind lasers, chips and MRI.",
      b: "Quantum mechanics describes how things behave at the scale of atoms and subatomic particles, like electrons and photons. At that size, the everyday rules of cause and effect you're used to stop working the way you'd expect. It sounds like science fiction, yet it's one of the most precisely tested theories in science, with predictions confirmed to many decimal places. It's also practical: without it, we'd have no transistors, computer chips, lasers, LEDs, solar panels or MRI machines." },
    { h: "Energy comes in packets", key: "Energy comes in fixed packets called quanta; packets of light are photons.",
      b: "In 1900, German physicist Max Planck was trying to explain the colours of light given off by hot objects. He found the maths only worked if energy was given off in tiny fixed amounts, which he called quanta. In 1905, Albert Einstein showed that light itself comes in packets, now called photons, to explain how light knocks electrons out of metal. That discovery, not relativity, won him his Nobel Prize. 'Quantum' simply means a fixed amount." },
    { h: "Quantum leaps", key: "Electrons in atoms can only have certain energy levels and jump between them.",
      b: "In 1913, Niels Bohr proposed that electrons in an atom can only have certain fixed energy levels, like steps on a ladder rather than a ramp. They jump between levels, absorbing or giving off exactly the right amount of energy as light. That's why each element glows with its own unique set of colours, which astronomers use to work out what distant stars are made of. Ironically, a 'quantum leap' in physics is incredibly tiny, not huge." },
    { h: "Waves and particles", key: "Particles like electrons behave as both waves and particles (the double-slit experiment).",
      b: "Light and matter behave like particles in some experiments and like waves in others. In the famous double-slit experiment, electrons are fired one at a time at a barrier with two narrow slits. Each electron lands as a single dot on the screen behind, like a particle. But over time, the dots build up a striped interference pattern, which only waves make, as if each electron passed through both slits at once. Try to detect which slit each electron goes through, and the pattern disappears." },
    { h: "Probabilities, not certainties", key: "Quantum theory predicts probabilities; before measurement a particle can be in a superposition.",
      b: "Quantum mechanics doesn't tell you exactly where a particle is or what it will do. It gives probabilities. Before it's measured, a particle can be in a 'superposition' of several possible states at once. Measuring it produces one definite result, with odds the theory predicts precisely. Erwin Schrödinger's famous thought experiment, a cat that is somehow both alive and dead until the box is opened, was meant to show how strange this seems when scaled up." },
    { h: "The uncertainty principle", key: "You can't know a particle's exact position and momentum at the same time.",
      b: "In 1927, Werner Heisenberg showed that you can't know both a particle's exact position and its exact momentum at the same time. The more precisely you pin down one, the fuzzier the other becomes. This isn't a flaw in our instruments; it's built into nature. It's also why atoms don't collapse: an electron squeezed into the tiny nucleus would have enormous uncertainty in its momentum, so it spreads out in a cloud around it instead." },
    { h: "Entanglement and tunnelling", key: "Entangled particles have linked measurements; tunnelling lets particles pass through barriers.",
      b: "Two particles can become entangled, so that measuring one instantly tells you about the other, however far apart they are. Einstein called it 'spooky action at a distance' and doubted it, but experiments have confirmed it repeatedly, and that work won the 2022 Nobel Prize in Physics. Another quantum effect, tunnelling, lets particles pass through barriers they classically shouldn't be able to cross. Tunnelling helps power the Sun's nuclear fusion and is used in some computer memory." },
    { h: "Quantum technology", key: "Quantum physics powers today's electronics; quantum computers use superposition for certain problems.",
      b: "The first quantum revolution gave us transistors, lasers and much of modern electronics. A second is under way. Quantum computers use qubits, which can be in superpositions of 0 and 1, to tackle certain problems, such as simulating molecules for new medicines, that would take ordinary computers far too long. They're still experimental and error-prone. Australia is a notable player in the field, with major research groups at universities in Sydney, Melbourne and Brisbane." },
  ],
  quiz: [
    { s: 1, q: "What is a photon?", o: ["A packet of light", "A type of atom", "A heavy particle in the nucleus", "A magnetic field"], a: 0, e: "Light comes in packets called photons." },
    { s: 2, q: "In physics, how big is a 'quantum leap'?", o: ["Enormous", "Incredibly tiny", "About a metre", "The size of a planet"], a: 1, e: "It's an electron jumping between energy levels in an atom." },
    { s: 3, q: "In the double-slit experiment, what do single electrons build up over time?", o: ["Two neat stripes", "A wave-like interference pattern", "Nothing at all", "A single dot"], a: 1, e: "The interference pattern reveals their wave-like behaviour." },
    { s: 5, q: "What does the uncertainty principle say?", o: ["You can't know exact position and momentum at the same time", "Scientists are unsure about everything", "Particles don't exist", "Measurement never changes anything"], a: 0, e: "Pinning down one makes the other less certain." },
    { s: 6, q: "What did Einstein call entanglement?", o: ["The theory of everything", "Spooky action at a distance", "A quantum leap", "General relativity"], a: 1, e: "He was sceptical, but experiments proved it real." },
  ],
  related: ["black-holes", "stars"],
},
);
