/* WISEBYTE LESSONS · Money (part 2): Australian personal finance. General information only; rules and rates change, so check ato.gov.au and moneysmart.gov.au. */
WB.LESSONS.push(
{
  id: "superannuation", audience: "adult", cat: "money", level: "beginner",
  trending: true, popularity: 93, added: "2026-09-24",
  title: "Superannuation explained",
  hook: "It's probably your second-biggest asset after a home, and most people barely look at it. Ten minutes here could be worth tens of thousands.",
  sections: [
    { h: "What super is", key: "Super is money set aside during your working life, invested to fund your retirement.",
      b: "Superannuation, or super, is money set aside from your pay during your working life and invested to support you in retirement. It became compulsory for most employees in 1992, and Australia's super system now holds more than $4 trillion, one of the largest retirement savings pools in the world. The idea is simple: small amounts invested over 40-odd years, compounding the whole time, grow into a large sum. Because it's locked away, it's protected from being spent early." },
    { h: "Your employer pays it", key: "Employers must pay super on top of wages; the rate is 12% from July 2025.",
      b: "If you're an employee, your employer must pay a percentage of your ordinary earnings into your super fund, on top of your wages. This is called the Super Guarantee, and it rose to 12% on 1 July 2025. So on a $70,000 salary, your employer adds $8,400 a year. Check your payslips and your fund account to make sure it's actually being paid; unpaid super can be reported to the ATO. Self-employed people aren't covered, so they need to make their own contributions." },
    { h: "Why it grows so much", key: "Super is invested, mostly in shares and property, and compounds over decades.",
      b: "Your super isn't sitting in a bank account. Your fund invests it in a mix of Australian and international shares, property, infrastructure, bonds and cash. Most people are in their fund's default 'balanced' or 'growth' option, often a MySuper product. Because it's invested for 40 years or more, compounding does enormous work: much of your final balance will come from investment returns, not contributions. Balances will fall in some years when markets drop, but it's a very long game." },
    { h: "Fees matter enormously", key: "Small differences in fees compound into large differences at retirement.",
      b: "Fees are charged as a dollar amount, a percentage of your balance, or both. A difference of just 0.5% or 1% a year sounds tiny, but over a working lifetime it can mean tens of thousands of dollars less in retirement. The ATO's free YourSuper comparison tool lets you compare MySuper products by fees and past returns. The regulator, APRA, also tests these products each year, and funds that fail the performance test must tell their members." },
    { h: "One fund, not five", key: "Consolidate multiple super accounts to avoid paying fees and insurance premiums several times.",
      b: "Many people have several super accounts from different jobs, each charging fees and often insurance premiums. Since 2021, your existing fund is generally 'stapled' to you and follows you to new jobs, which helps. You can find all your accounts, including lost super, by linking the ATO to your myGov account, and consolidate them online in minutes. Before closing an account, check whether it holds insurance you want to keep, as that cover ends when the account closes." },
    { h: "Insurance inside super", key: "Most funds include default life, TPD and sometimes income protection insurance.",
      b: "Most super funds automatically include insurance: life cover (paid to your beneficiaries if you die), total and permanent disability (TPD) cover and sometimes income protection. Premiums come out of your balance. It can be good value and is often the only life insurance people have. But check whether the amount suits your situation, and make sure you've nominated who should receive your super if you die. A binding nomination gives you more certainty." },
    { h: "Tax perks and topping up", key: "Super is taxed at a low rate, and extra contributions can reduce tax, within yearly caps.",
      b: "Super is taxed lightly to encourage saving. Contributions from your employer are generally taxed at 15%, which is lower than most people's income tax rate, and investment earnings are generally taxed at no more than 15%, though extra tax applies from July 2026 on earnings for balances above $3 million. You can add extra through salary sacrifice or personal contributions you claim as a tax deduction, up to the concessional cap, $32,500 a year from July 2026, including employer contributions. Lower-income earners may qualify for government co-contributions. Rules have limits and exceptions, so check the ATO website." },
    { h: "When can you use it?", key: "You generally access super after reaching preservation age (60) and retiring, or at 65.",
      b: "Super is locked away until you meet a 'condition of release'. For anyone born on or after 1 July 1964, the preservation age is 60: you can generally access your super once you're 60 and retire, or at 65 even if you keep working. Early access is only allowed in narrow situations, such as severe financial hardship or certain medical conditions. Be wary of anyone offering to help you access super early; illegal early release schemes can bring heavy penalties." },
  ],
  quiz: [
    { s: 1, q: "What is the Super Guarantee rate from 1 July 2025?", o: ["9.5%", "10%", "12%", "15%"], a: 2, e: "Employers must pay 12% of ordinary earnings." },
    { s: 3, q: "Why do small differences in super fees matter so much?", o: ["They compound over decades", "Fees are paid only once", "They're tax deductible", "They don't matter"], a: 0, e: "0.5–1% a year can cost tens of thousands by retirement." },
    { s: 4, q: "How can you find lost or multiple super accounts?", o: ["Call every fund", "Through the ATO via myGov", "Ask your bank", "You can't"], a: 1, e: "Link the ATO to myGov to see all your accounts." },
    { s: 6, q: "What is the concessional contributions cap?", o: ["$10,000 a year", "$32,500 a year", "$130,000 a year", "There is no cap"], a: 1, e: "From 1 July 2026. It includes employer contributions." },
    { s: 7, q: "What is the preservation age for people born on or after 1 July 1964?", o: ["55", "60", "67", "70"], a: 1, e: "Generally you can access super at 60 once retired, or at 65." },
  ],
  related: ["compound-interest", "tax-basics"],
},
{
  id: "tax-basics", audience: "adult", cat: "money", level: "beginner",
  popularity: 89, added: "2026-09-24",
  title: "How tax works in Australia",
  hook: "The pay rise that 'pushes you into a higher bracket' won't leave you worse off. Here's how income tax actually works.",
  sections: [
    { h: "Where tax goes", key: "Income tax funds services like health, education, welfare and defence.",
      b: "Income tax is the Australian Government's biggest source of revenue. It funds services like Medicare and hospitals, schools and universities, the pension and other welfare payments, defence, roads and much more. Other taxes include the 10% GST on most goods and services, company tax and excise on fuel, alcohol and tobacco. The financial year runs from 1 July to 30 June, and the Australian Taxation Office, the ATO, collects the money." },
    { h: "Tax brackets", key: "Australia uses progressive tax brackets: higher rates apply only to income above each threshold.",
      b: "Australia has a progressive income tax system: the more you earn, the higher the rate on the extra dollars. For Australian residents in 2026–27, the first $18,200 is tax-free. Income from $18,201 to $45,000 is taxed at 15%, from $45,001 to $135,000 at 30%, from $135,001 to $190,000 at 37%, and above $190,000 at 45%. The 15% rate is legislated to fall to 14% from July 2027. Most people also pay a 2% Medicare levy." },
    { h: "The bracket myth", key: "A pay rise never reduces your take-home pay; only the extra dollars are taxed at the higher rate.",
      b: "A common myth says a pay rise can 'push you into a higher tax bracket' and leave you worse off. It can't. Each rate applies only to the income within that bracket. If you earn $136,000, only the $1,000 above $135,000 is taxed at 37%; the rest is taxed exactly as before. So a pay rise always increases your take-home pay. Your marginal rate is the rate on your next dollar; your average rate, the share of your total income paid in tax, is always lower." },
    { h: "PAYG: tax as you go", key: "Employers withhold tax from each pay; your return settles the difference.",
      b: "If you're an employee, your employer withholds tax from each pay under the Pay As You Go (PAYG) system and sends it to the ATO. They use your tax file number and whether you claim the tax-free threshold, which you should normally only claim from one job at a time. At the end of the financial year, your tax return works out exactly what you owed. If too much was withheld, you get a refund; if too little, you pay the difference." },
    { h: "Your tax return", key: "Lodge by 31 October if doing it yourself; much of it is pre-filled via myGov.",
      b: "If you lodge your own tax return, it's due by 31 October. Registered tax agents can often lodge later for their clients. Most people lodge online through myTax in myGov, where much of the information, like your income, bank interest and private health insurance details, is pre-filled from late July. It's worth waiting until early August for the pre-filling to be complete. Double-check everything; you're responsible for what you lodge, even if it's pre-filled." },
    { h: "Deductions", key: "You can claim work-related expenses you paid, that relate to earning income, with records.",
      b: "Deductions reduce your taxable income. You can generally claim expenses directly related to earning your income, such as work tools, uniforms with a logo, professional memberships and some work-from-home costs. The ATO's three golden rules: you must have spent the money yourself and not been reimbursed; it must directly relate to earning your income; and you need a record, like a receipt. A $100 deduction doesn't save you $100; it saves you $100 multiplied by your marginal tax rate." },
    { h: "Other taxes you pay", key: "GST (10%), capital gains tax and HECS-HELP repayments also affect many people.",
      b: "GST, a 10% tax on most goods and services, is built into prices, though basic food, most health care and education are exempt. If you sell an investment such as shares or an investment property for a profit, capital gains tax applies, with a 50% discount if you held the asset for more than a year. Your main home is generally exempt. If you have a HECS-HELP student debt, compulsory repayments are collected through the tax system once your income passes a threshold." },
    { h: "Staying on the right side", key: "Keep records, use official sources and beware of tax scams impersonating the ATO.",
      b: "Keep receipts and records for five years, since the ATO can review your return. Use official sources like ato.gov.au for rates and rules, which change regularly. Be very wary of scams: fake ATO texts, emails and calls threatening arrest or demanding payment in gift cards or cryptocurrency are common. The ATO won't threaten you with immediate arrest or ask for payment that way. If unsure, contact the ATO directly using the number on its official website. This is general information only." },
  ],
  quiz: [
    { s: 1, q: "How much income is tax-free for Australian residents?", o: ["The first $10,000", "The first $18,200", "The first $45,000", "None"], a: 1, e: "The tax-free threshold is $18,200." },
    { s: 2, q: "You earn $136,000. How much is taxed at the 37% rate?", o: ["All of it", "Only the $1,000 above $135,000", "Nothing", "Half of it"], a: 1, e: "Each rate applies only to income within its bracket." },
    { s: 2, q: "Can a pay rise leave you with less take-home pay because of tax brackets?", o: ["Yes, often", "No, only the extra dollars are taxed at the higher rate", "Only above $190,000", "Only in July"], a: 1, e: "The bracket myth is false." },
    { s: 4, q: "When is your tax return due if you lodge it yourself?", o: ["30 June", "31 July", "31 October", "25 December"], a: 2, e: "Tax agents can often lodge later." },
    { s: 5, q: "Which is one of the ATO's golden rules for deductions?", o: ["You must have a record, like a receipt", "Any purchase counts", "Only amounts over $1,000", "Your employer must approve"], a: 0, e: "You also must have paid it and it must relate to earning income." },
  ],
  related: ["superannuation", "budgeting"],
},
{
  id: "credit-scores", audience: "adult", cat: "money", level: "beginner",
  popularity: 75, added: "2026-09-24",
  title: "How credit scores work",
  hook: "A three- or four-digit number can decide whether you get a loan, and at what rate. Here's how to see yours for free.",
  sections: [
    { h: "What a credit score is", key: "A credit score summarises how reliably you've handled credit, to help lenders assess risk.",
      b: "When you apply for a loan, credit card, phone plan or sometimes even a utility account, the provider checks your credit history to judge how likely you are to repay. A credit score boils that history down to a single number. A higher score suggests lower risk, which can mean easier approval and sometimes better interest rates. A low score doesn't mean you'll be rejected everywhere, but it can limit your options." },
    { h: "Who keeps the records", key: "In Australia, Equifax, Experian and illion are the main credit reporting bodies.",
      b: "In Australia, credit reports are kept by credit reporting bodies, mainly Equifax, Experian and illion. Each may hold slightly different information and calculates its own score on its own scale: Equifax uses 0 to 1,200, while Experian and illion use 0 to 1,000. So your score can differ between them. Lenders may check one or more of these bureaus when you apply." },
    { h: "What's in your report", key: "Reports include your credit accounts, enquiries, 24 months of repayment history and defaults.",
      b: "Your credit report includes personal details, the credit accounts you hold and their limits, and every time you've applied for credit, called an enquiry. Since comprehensive credit reporting began in 2014, reports also include up to 24 months of repayment history, showing whether you paid on time each month. Defaults (overdue debts of $150 or more that a lender has reported), court judgments and bankruptcies can also appear, and generally stay for years." },
    { h: "What helps your score", key: "Paying on time, keeping limits sensible and applying for credit rarely all help.",
      b: "The single biggest factor is paying bills and loan repayments on time, every time. Setting up direct debits for at least the minimum payment helps avoid accidental misses. Keeping credit card limits no higher than you need can help, since lenders consider your total available credit, not just what you've used. A long, steady history of well-managed accounts also works in your favour." },
    { h: "What hurts your score", key: "Late payments, defaults and many credit applications in a short time lower your score.",
      b: "Missing repayments, especially by more than 14 days, can show up in your repayment history. Defaults are more serious and can remain on your report for five years even after you pay them. Applying for lots of credit in a short period can also lower your score, because it can look like financial stress. Buy now, pay later services became regulated as credit in 2025, so providers may now check and report to credit bureaus." },
    { h: "Check yours for free", key: "You're entitled to a free credit report from each bureau every three months.",
      b: "You have the right to get your credit report free from each credit reporting body every three months, and also if you've been refused credit recently. Request it directly from Equifax, Experian and illion; look for the free option, as some services try to sell paid subscriptions. Checking your own report doesn't hurt your score. It's worth doing once a year, and before applying for a big loan like a mortgage." },
    { h: "Fixing errors", key: "Incorrect information can be corrected free of charge through the bureau or lender.",
      b: "Credit reports sometimes contain mistakes, such as a debt that isn't yours, a default already paid or a sign of identity fraud. You can ask the credit reporting body or the lender to correct it, free of charge. If they don't resolve it, you can complain to the Australian Financial Complaints Authority (AFCA). Be wary of 'credit repair' companies that charge large fees for things you can do yourself for free. Legitimate negative information can't simply be removed." },
    { h: "Protect your identity", key: "Unexpected enquiries may signal identity theft; you can request a ban on your credit file.",
      b: "Identity thieves sometimes use stolen details to apply for credit in your name, which damages your report. Warning signs include enquiries you didn't make or accounts you don't recognise. If you think your identity has been stolen, you can ask the credit reporting bodies to place a ban on your credit file, stopping anyone accessing it for 21 days (extendable). IDCARE, a free national service, can help you respond. Guard your licence, passport and Medicare details carefully." },
  ],
  quiz: [
    { s: 1, q: "Which of these is an Australian credit reporting body?", o: ["ASIC", "Equifax", "The ATO", "Centrelink"], a: 1, e: "Equifax, Experian and illion are the main ones." },
    { s: 2, q: "How many months of repayment history can appear on your report?", o: ["3", "12", "24", "120"], a: 2, e: "Comprehensive credit reporting includes up to 24 months." },
    { s: 3, q: "What's the biggest thing you can do to help your score?", o: ["Apply for lots of cards", "Pay bills and repayments on time", "Close all accounts", "Never check your report"], a: 1, e: "On-time repayments matter most." },
    { s: 5, q: "How often can you get a free credit report from each bureau?", o: ["Never", "Every three months", "Once in your life", "Every ten years"], a: 1, e: "And checking it doesn't hurt your score." },
    { s: 7, q: "What can you request if you suspect identity theft?", o: ["A ban on your credit file", "A new tax file number", "A bigger credit limit", "Nothing"], a: 0, e: "It stops anyone accessing your credit file for a period." },
  ],
  related: ["home-loans", "scams"],
},
{
  id: "home-loans", audience: "adult", cat: "money", level: "intermediate",
  popularity: 86, added: "2026-09-24",
  title: "How home loans work",
  hook: "Most people pay more in interest than the house itself cost. Understanding a few features can save you tens of thousands.",
  sections: [
    { h: "The basics", key: "A home loan is borrowed money secured against the property, repaid with interest over decades.",
      b: "A home loan, or mortgage, is money borrowed from a lender to buy a property, which serves as security: if you can't repay, the lender can sell it to recover the debt. Most Australian home loans run for 25 to 30 years. You repay the amount borrowed, called the principal, plus interest. Because the sums are so large and the timeframes so long, small differences in interest rates and features make an enormous difference." },
    { h: "Where the money goes", key: "Early repayments are mostly interest; the interest bill over 30 years can exceed the loan itself.",
      b: "Take a $500,000 loan at 6% interest over 30 years. The monthly repayment is about $3,000. Over the life of the loan, you'd repay around $1.08 million, meaning roughly $580,000 in interest, more than the amount borrowed. Early on, most of each repayment goes on interest; only a small slice reduces the principal. As the balance falls, that balance shifts. This is why extra repayments in the early years are so powerful." },
    { h: "Deposit, LVR and LMI", key: "Borrowing more than 80% of the property's value usually means paying lenders mortgage insurance.",
      b: "Your deposit is the share of the price you pay yourself. Lenders look at the loan-to-value ratio (LVR): a $600,000 loan on a $750,000 home is an 80% LVR. If you borrow more than 80%, lenders usually charge lenders mortgage insurance (LMI), which can cost thousands or tens of thousands of dollars. Note that LMI protects the lender, not you. Government schemes such as the Home Guarantee Scheme can let eligible first-home buyers purchase with a smaller deposit without paying LMI." },
    { h: "Variable or fixed?", key: "Variable rates move with the market; fixed rates lock in certainty but reduce flexibility.",
      b: "A variable rate moves up or down over time, usually following the Reserve Bank's cash rate. A fixed rate stays the same for a set period, often one to five years, giving certainty about repayments. Fixed loans often limit extra repayments and can charge break fees if you exit early. Many people split their loan, part fixed and part variable, to balance certainty and flexibility. When a fixed period ends, the loan usually rolls onto a variable rate, often not the lender's best one." },
    { h: "Offset and redraw", key: "An offset account reduces the balance you pay interest on; every dollar in it saves interest at your loan rate.",
      b: "An offset account is a transaction or savings account linked to your loan. The balance in it is subtracted from your loan balance when interest is calculated. With $30,000 in offset against a $500,000 loan, you pay interest on only $470,000. Every dollar in offset effectively 'earns' your mortgage rate, tax-free. A redraw facility lets you take back extra repayments you've made. Both reward keeping spare cash working against your loan." },
    { h: "Small extras, big savings", key: "Extra repayments, especially early, can cut years and tens of thousands off a loan.",
      b: "Because interest is calculated on the outstanding balance, every extra dollar you repay reduces all the interest that dollar would have attracted for the rest of the loan. On the $500,000 example, paying an extra $200 a month from the start would cut about four and a half years off the loan and save roughly $100,000 in interest. Switching from monthly to fortnightly repayments of half the monthly amount also helps, because it adds up to one extra monthly payment each year." },
    { h: "Comparing loans", key: "Compare using the comparison rate, and check features and fees, not just the headline rate.",
      b: "Advertised rates can hide fees, so Australian lenders must also show a comparison rate, which combines the interest rate with most fees into a single figure. Compare features too: offset, redraw, extra repayments and fees. Mortgage brokers can compare many lenders for you; they're usually paid by the lender, and must act in your best interests by law. Also check how much you can comfortably afford, not just how much a lender will offer, since lenders test whether you could cope if rates rose." },
    { h: "Don't pay the loyalty tax", key: "Existing customers are often charged more than new ones; ask for a better rate or refinance.",
      b: "Banks often offer their best rates to new customers while existing customers drift onto higher ones, sometimes called the loyalty tax. Every year or two, check what rate new customers are being offered. Call your lender and ask for a better rate; many will match competitors to keep you. If not, consider refinancing to another lender, weighing up any switching costs. Even a 0.3% cut on a $500,000 loan saves about $1,500 a year. This is general information only." },
  ],
  quiz: [
    { s: 1, q: "Early in a home loan, where does most of each repayment go?", o: ["Paying down the principal", "Interest", "Fees", "Insurance"], a: 1, e: "Most early repayments cover interest." },
    { s: 2, q: "Above what LVR do lenders usually charge LMI?", o: ["50%", "70%", "80%", "95%"], a: 2, e: "Borrowing more than 80% usually triggers LMI." },
    { s: 2, q: "Who does lenders mortgage insurance protect?", o: ["You", "The lender", "The real estate agent", "The government"], a: 1, e: "Despite you paying for it." },
    { s: 4, q: "What does an offset account do?", o: ["Reduces the balance you're charged interest on", "Pays your rates", "Fixes your interest rate", "Lowers your deposit"], a: 0, e: "Money in offset saves interest at your loan rate." },
    { s: 6, q: "What does the comparison rate include?", o: ["Only the interest rate", "The interest rate plus most fees", "The property price", "Stamp duty"], a: 1, e: "It helps compare loans with different fees." },
  ],
  related: ["credit-scores", "compound-interest"],
},
{
  id: "index-funds", audience: "adult", cat: "money", level: "intermediate",
  popularity: 84, added: "2026-09-24",
  title: "Index funds and ETFs",
  hook: "The boring, low-cost way to invest that beats most professional fund managers over time.",
  sections: [
    { h: "Owning the whole market", key: "An index fund buys every company in an index, instead of trying to pick winners.",
      b: "Most investment funds are actively managed: professionals try to pick shares that will beat the market. An index fund does something simpler. It buys every company in a market index, like the ASX 200 or the S&P 500, in proportion to its size, and just holds them. You don't try to beat the market; you are the market. The first index fund for ordinary investors was launched in 1976 by John Bogle, founder of Vanguard. Critics called it 'Bogle's folly'. It turned out to change investing." },
    { h: "Why passive often wins", key: "Most active funds underperform their index over the long run after fees.",
      b: "It seems obvious that experts should beat a fund that simply buys everything. But year after year, studies such as S&P's SPIVA reports find that most actively managed funds underperform their benchmark index over 10 to 15 years, once fees are counted. Part of the reason is simple maths: before costs, the average investor earns the market return, so after higher costs, the average active investor must do worse. It's also very hard to identify in advance which managers will be the lucky few who win." },
    { h: "Fees compound", key: "Low fees are one of the few things investors control, and they compound over decades.",
      b: "Index funds are cheap because they don't pay teams of analysts to pick stocks. Broad index funds and ETFs often charge between about 0.03% and 0.3% a year, while active funds commonly charge 1% or more. On a $100,000 investment over 30 years, earning 6% a year after fees instead of 7% leaves you with about $187,000 less. You can't control market returns, but you can control costs." },
    { h: "What's an ETF?", key: "An ETF is a fund that trades on the stock exchange like a share; many track indexes.",
      b: "An exchange-traded fund, or ETF, is a fund that's bought and sold on the stock exchange like a share. Many ETFs track an index, so buying one unit gives you a slice of hundreds or thousands of companies. You can buy them through any online broker, often with small amounts. There are ETFs for Australian shares, global shares, bonds, property and more. Some ETFs are narrow or complex, like those focused on a single theme or using leverage; broad, simple ones suit most long-term investors." },
    { h: "The famous bet", key: "Warren Buffett's 10-year bet showed an S&P 500 index fund beating a set of hedge funds.",
      b: "In 2007, Warren Buffett, one of history's most successful investors, bet $1 million that a simple S&P 500 index fund would beat a selection of hedge funds chosen by professionals over the following 10 years. A fund firm took the bet. By the end of 2017, the index fund had returned about 7% a year on average, while the hedge funds' average was about 2%. Buffett has said most people would be best served by low-cost index funds." },
    { h: "Diversify across the world", key: "Australian shares are a small slice of global markets; global funds add diversification.",
      b: "Australian shares make up only about 2% of the world's share markets, and the ASX is dominated by banks and miners. Many Australians have a 'home bias', holding mostly local shares. A diversified portfolio often includes international shares too, giving exposure to industries like technology and healthcare that are smaller here. Some diversified ETFs hold a mix of Australian and global shares and bonds in a single fund, rebalancing automatically." },
    { h: "Time in the market", key: "Regular investing and staying invested beat trying to time the market.",
      b: "Nobody reliably predicts short-term market moves, and some of the best days often come shortly after the worst ones, so jumping in and out can mean missing the recovery. Many investors use dollar-cost averaging: investing a fixed amount regularly, such as monthly, which means buying more units when prices are low and fewer when they're high. It also removes the stress of deciding when to invest. The old saying holds: time in the market beats timing the market." },
    { h: "Is it for you?", key: "Index investing suits long-term money; short-term savings belong somewhere safer.",
      b: "Index funds invested in shares suit money you won't need for at least five to seven years, because markets can fall sharply in the short term. Before investing, it's wise to have an emergency fund and clear high-interest debt. Remember that your super is probably already invested in shares, possibly including index funds. This is general information, not personal advice; ASIC's Moneysmart website has free, independent guides, and a licensed financial adviser can help with your circumstances." },
  ],
  quiz: [
    { s: 0, q: "What does an index fund do?", o: ["Picks a few winning stocks", "Buys every company in an index", "Only buys property", "Trades daily for profit"], a: 1, e: "It aims to match the market, not beat it." },
    { s: 1, q: "Over 10–15 years, how do most active funds perform against their index after fees?", o: ["Most beat it", "Most underperform it", "Exactly equal", "No one knows"], a: 1, e: "SPIVA reports consistently find this." },
    { s: 3, q: "What is an ETF?", o: ["A bank account", "A fund traded on the stock exchange like a share", "A government bond", "A type of super"], a: 1, e: "Exchange-traded fund." },
    { s: 4, q: "What did Warren Buffett's famous bet show?", o: ["Hedge funds always win", "An S&P 500 index fund beat a set of hedge funds", "Gold beats shares", "Timing the market works"], a: 1, e: "About 7% a year versus about 2%." },
    { s: 6, q: "What is dollar-cost averaging?", o: ["Investing a fixed amount at regular intervals", "Waiting for the perfect moment", "Converting dollars to euros", "Averaging your debts"], a: 0, e: "It removes the stress of timing the market." },
  ],
  related: ["stock-market", "superannuation"],
},
);
