/* WISEBYTE LESSONS · Technology (part 1) */
WB.LESSONS.push(
{
  id: "internet", audience: "adult", cat: "technology", level: "intermediate",
  popularity: 75, added: "2026-08-25",
  title: "How the internet works",
  hook: "What actually happens in the second between tapping a link and seeing a page.",
  sections: [
    { h: "A network of networks", key: "The internet is a global network of networks that grew from ARPANET (1969).",
      b: "The internet is a global network of networks: billions of computers, phones and servers owned by millions of different organisations, linked by cables, fibre optics, radio and satellites. Nobody owns it as a whole. It grew from ARPANET, a US research network that sent its first message in October 1969; the system crashed after two letters, so the first message was 'lo'. Australia's first international internet connection came in 1989, linking the University of Melbourne to Hawaii." },
    { h: "Packets", key: "Data is split into packets that travel separately and are reassembled at the destination.",
      b: "When you send a photo, email or video call, the data is chopped into small chunks called packets, typically around 1,500 bytes each. Each packet carries addressing information, like an envelope, and travels independently, possibly by different routes. At the destination they're reassembled in the right order. If a packet goes missing, only that piece needs resending. This design, called packet switching, makes the network resilient: if one route fails, packets simply take another." },
    { h: "IP addresses", key: "An IP address tells routers where to deliver packets, like a street address.",
      b: "Every device on the internet needs an address so packets can find it. That's its IP address, for Internet Protocol. The older IPv4 system uses addresses like 203.0.113.42, allowing about 4.3 billion combinations, which ran out as the internet grew. The newer IPv6 allows an almost unimaginable number. Routers, specialised computers across the network, read each packet's destination address and pass it one step closer, hop by hop, often across a dozen or more routers." },
    { h: "DNS: the internet's phone book", key: "DNS translates names like wikipedia.org into IP addresses.",
      b: "People remember names like abc.net.au, but computers need numbers. The Domain Name System, or DNS, translates names into IP addresses. When you type a web address, your device asks a DNS server, which looks it up, sometimes asking other servers in a chain, and returns the address, usually in a fraction of a second. If DNS fails, websites seem to vanish even though they're still running, which is behind some major outages." },
    { h: "TCP and the rules of the road", key: "Protocols like TCP/IP set the rules; TCP checks that everything arrives correctly.",
      b: "The internet works because everyone follows shared rules, called protocols. The two most important were designed in the 1970s by Vint Cerf and Bob Kahn: IP handles addressing and routing, and TCP makes sure data arrives completely and in order, requesting resends of anything lost. Together, TCP/IP was adopted across ARPANET on 1 January 1983, often called the internet's birthday. Other protocols sit on top, like HTTP for web pages and SMTP for email." },
    { h: "Under the sea", key: "Most data between continents travels through undersea fibre-optic cables.",
      b: "It's easy to imagine data flying through space, but around 99% of international internet traffic travels through undersea fibre-optic cables. Hundreds of these cables criss-cross the ocean floors, many only about as thick as a garden hose, carrying data as pulses of light. Australia is connected by cables landing mainly in Sydney and Perth, linking to Asia, the US and New Zealand. Occasionally cables are damaged by ship anchors, earthquakes and even sharks biting them." },
    { h: "The last mile", key: "Your connection to the network (NBN, 5G, satellite) is often the slowest link.",
      b: "The part of the network connecting your home to the wider internet is called the last mile, and it's often the slowest link. In Australia, most homes connect through the NBN using fibre to the premises, fibre to the node with copper for the last stretch, cable or fixed wireless. Mobile networks like 4G and 5G carry data by radio to nearby towers. Remote areas increasingly use satellites, including low-Earth-orbit satellites that orbit much closer than older ones, reducing delay." },
    { h: "The web isn't the internet", key: "The World Wide Web (1989, Tim Berners-Lee) is one service that runs on the internet.",
      b: "The internet and the web aren't the same thing. The internet is the network. The World Wide Web, proposed by Tim Berners-Lee at the physics lab CERN in 1989, is one service running on it, made of web pages linked together and viewed in a browser. Email, video calls, online games and streaming are other services using the same network. Berners-Lee chose not to patent the web, making it free for anyone to use, which helped it spread worldwide." },
  ],
  quiz: [
    { s: 1, q: "What happens to data when it's sent over the internet?", o: ["It travels as one big file", "It's split into packets", "It's converted to sound", "It's printed and scanned"], a: 1, e: "Packets travel independently and are reassembled." },
    { s: 2, q: "What is an IP address for?", o: ["Identifying where to deliver data", "Encrypting passwords", "Speeding up downloads", "Naming websites"], a: 0, e: "It works like a street address." },
    { s: 3, q: "What does DNS do?", o: ["Translates website names into IP addresses", "Blocks viruses", "Stores your photos", "Creates Wi-Fi signals"], a: 0, e: "DNS is the internet's phone book." },
    { s: 5, q: "How does most data travel between continents?", o: ["Satellites", "Undersea fibre-optic cables", "Radio towers", "Planes"], a: 1, e: "Around 99% of international traffic." },
    { s: 7, q: "Who invented the World Wide Web?", o: ["Bill Gates", "Tim Berners-Lee", "Steve Jobs", "Vint Cerf"], a: 1, e: "At CERN in 1989. Vint Cerf co-designed TCP/IP." },
  ],
  related: ["encryption", "gps"],
},
{
  id: "encryption", audience: "adult", cat: "technology", level: "advanced",
  popularity: 62, added: "2026-09-20",
  title: "How encryption keeps secrets",
  hook: "The maths behind the padlock in your browser, and why it protects nearly everything you do online.",
  sections: [
    { h: "Scrambling secrets", key: "Encryption uses a key to turn readable plaintext into scrambled ciphertext.",
      b: "Encryption turns readable information, called plaintext, into scrambled data, called ciphertext, using a key. Only someone with the right key can turn it back. It protects your messages, passwords, banking, medical records and card payments every day, usually without you noticing. Without encryption, anyone able to intercept internet traffic, such as someone on the same public Wi-Fi, could read what you send." },
    { h: "An ancient idea", key: "The Caesar cipher shifted each letter along the alphabet and is easy to crack.",
      b: "Secret codes are ancient. Julius Caesar is said to have shifted each letter three places along the alphabet, so A became D and B became E. Simple substitution ciphers like this are easy to crack by frequency analysis: in English, E is the most common letter, so the most common symbol in a long message probably stands for E. The Arab scholar al-Kindi described this technique in the 9th century." },
    { h: "Enigma and the codebreakers", key: "Breaking Germany's Enigma cipher in WWII shortened the war and helped launch computing.",
      b: "In World War II, Germany used the Enigma machine, whose rotating wheels scrambled each letter differently, creating an astronomical number of possible settings. Building on earlier work by Polish mathematicians, British codebreakers at Bletchley Park, including Alan Turing, built machines to find the daily settings. The intelligence helped the Allies win the Battle of the Atlantic and is thought to have shortened the war. The effort also helped lay foundations for modern computing." },
    { h: "Symmetric encryption", key: "Symmetric encryption uses one shared key; it's fast, but sharing the key safely is hard.",
      b: "In symmetric encryption, the same key locks and unlocks the data. Modern symmetric ciphers, like the widely used AES standard, are fast and extremely secure. They're used to encrypt files, phones and most internet traffic. The problem is the key itself: how do you share it with someone far away without anyone else intercepting it? For centuries, keys had to be delivered physically, by couriers or in person." },
    { h: "Public-key encryption", key: "Public-key encryption uses a shareable public key to lock and a secret private key to unlock.",
      b: "In 1976, Whitfield Diffie and Martin Hellman published a revolutionary idea, and in 1977 Rivest, Shamir and Adleman created the RSA system. Public-key encryption uses two mathematically linked keys. Your public key can be shared with anyone and used to lock messages to you. Only your matching private key can unlock them. Think of a padlock anyone can snap shut, but only you have the key to open. It solved the key-sharing problem and made secure online shopping possible." },
    { h: "The padlock in your browser", key: "HTTPS uses public-key encryption to agree on a key, then fast symmetric encryption.",
      b: "When you see HTTPS and a padlock in your browser, a protocol called TLS is protecting the connection. Your browser checks the website's digital certificate, issued by a trusted authority, to confirm you're talking to the real site. Then the two use public-key techniques to agree on a shared secret key, and switch to fast symmetric encryption for the rest of the session. Note that the padlock means the connection is encrypted, not that the website is trustworthy; scam sites can have padlocks too." },
    { h: "Why it's hard to break", key: "Modern encryption relies on maths that's easy one way and extremely hard to reverse.",
      b: "Modern encryption relies on maths problems that are easy to do one way and extremely hard to reverse. Multiplying two huge prime numbers is easy for a computer; working out which two primes produced the result is enormously hard. Guessing a 256-bit symmetric key by brute force would take longer than the age of the universe with today's computers. In practice, attackers rarely break the maths; they steal passwords, trick people or exploit software bugs instead." },
    { h: "Encryption in everyday life", key: "End-to-end encryption means only sender and recipient can read messages; quantum computing is prompting new standards.",
      b: "Messaging apps like Signal, WhatsApp and iMessage use end-to-end encryption, meaning only the sender and recipient can read messages, not even the company running the service. Phones encrypt their storage, protecting data if the device is lost. Governments periodically debate whether police should have special access, while security experts warn any 'back door' could be exploited by criminals. Future quantum computers could break some of today's public-key systems, so new 'post-quantum' standards were published in 2024." },
  ],
  quiz: [
    { s: 0, q: "What is ciphertext?", o: ["Readable text", "Scrambled, encrypted data", "A type of password", "A computer virus"], a: 1, e: "Ciphertext is encryption's scrambled output." },
    { s: 1, q: "How can simple substitution ciphers be cracked?", o: ["Frequency analysis of common letters", "They can't", "Using a password manager", "By guessing the author"], a: 0, e: "E is the most common letter in English." },
    { s: 2, q: "Where did Alan Turing and colleagues break Enigma?", o: ["Bletchley Park", "Los Alamos", "CERN", "Canberra"], a: 0, e: "The work helped shorten World War II." },
    { s: 4, q: "In public-key encryption, what unlocks a message sent to you?", o: ["Your public key", "Your private key", "Anyone's key", "The website name"], a: 1, e: "Only your private key can decrypt it." },
    { s: 5, q: "What does the padlock in your browser tell you?", o: ["The website is trustworthy", "The connection is encrypted", "The site is government-approved", "The site has no ads"], a: 1, e: "Scam sites can have padlocks too." },
  ],
  related: ["digital-security", "internet"],
},
{
  id: "gps", audience: "adult", cat: "technology", level: "intermediate",
  popularity: 73, added: "2026-09-24",
  title: "How GPS knows where you are",
  hook: "Your phone finds you to within a few metres by listening to ultra-precise clocks orbiting high above the Earth.",
  sections: [
    { h: "Satellites and timing", key: "GPS works by measuring how long signals take to arrive from multiple satellites.",
      b: "The Global Positioning System is run by the US and uses a constellation of around 31 satellites orbiting about 20,200 kilometres above Earth. Each satellite constantly broadcasts a signal saying, in effect, 'I'm this satellite, here's my position, and this is the exact time.' Your phone doesn't send anything back. It just listens. By measuring how long each signal took to arrive, it can work out how far away each satellite is." },
    { h: "Trilateration", key: "Knowing distances to four or more satellites pins down your position and the time.",
      b: "If you know you're exactly 20,500 km from one satellite, you could be anywhere on a giant sphere around it. A second satellite narrows it to a circle where two spheres meet; a third narrows it to two points, one of which is usually far off in space. A fourth satellite is needed to correct for the fact that your phone's clock isn't perfectly accurate. This process is called trilateration. Your device usually uses signals from many more satellites for better accuracy." },
    { h: "Why clocks matter so much", key: "Signals travel at light speed, so tiny timing errors mean big position errors.",
      b: "GPS signals travel at the speed of light, about 300,000 kilometres per second. That means a timing error of just one millionth of a second would put your position out by about 300 metres. So each GPS satellite carries extremely precise atomic clocks, accurate to billionths of a second. The whole system is really a way of distributing precise time from space, which is why it's also used to synchronise phone networks, power grids and financial transactions." },
    { h: "Deliberately blurred", key: "Until May 2000 the US deliberately degraded civilian GPS accuracy; switching this off made positions about ten times more precise.",
      b: "GPS began as a US military project. The first satellite was launched in 1978, and the full system was declared operational in 1995. For years the military deliberately added errors to the civilian signal, a feature called Selective Availability, so ordinary receivers were only accurate to around 100 metres while military users got precise positions. In May 2000, on the orders of President Bill Clinton, it was switched off, and civilian accuracy improved roughly tenfold overnight. That single change helped spark the boom in car navigation, fitness trackers and eventually smartphone maps. The US later announced that newer GPS satellites would be built without the ability to degrade the signal at all." },
    { h: "Other systems", key: "Phones use several satellite systems (GPS, GLONASS, Galileo, BeiDou), known together as GNSS.",
      b: "GPS isn't the only satellite navigation system. Russia runs GLONASS, the European Union runs Galileo, and China runs BeiDou. Together they're called GNSS, global navigation satellite systems. Most modern phones use several at once, seeing more satellites and getting faster, more accurate fixes. Australia is building SouthPAN, a system that improves positioning accuracy across Australia and New Zealand, useful for farming, mining, aviation and emergency services." },
    { h: "Why your phone is faster", key: "Phones also use Wi-Fi, mobile towers and downloaded data to find you quickly.",
      b: "A standalone GPS receiver can take a while to lock on, because it has to download satellite position data slowly from space. Your phone cheats a little: it downloads that data over the internet, and it also estimates your location from nearby mobile towers and Wi-Fi networks, whose locations are stored in huge databases. That's why your phone can find you almost instantly, and even indoors where satellite signals are weak." },
    { h: "Limits and errors", key: "Tall buildings, tunnels and dense trees can reflect or block signals, reducing accuracy.",
      b: "GPS signals are weak by the time they reach Earth and can't pass through buildings or ground. In city centres, signals bounce off tall buildings, confusing receivers and making your blue dot jump around; this is called the urban canyon effect. Tunnels and dense forest can block signals entirely. Ordinary phones are typically accurate to within about five metres in open sky. Specialised equipment used in surveying and farming can reach centimetre accuracy." },
    { h: "More than maps", key: "GPS underpins navigation, aviation, farming, emergency services and precise timing everywhere.",
      b: "Beyond getting you to a café, GPS guides planes and ships, helps emergency services find people, tracks deliveries and lets tractors drive themselves in straight lines to save fuel and fertiliser. Its timing signals keep mobile networks, power grids and stock exchanges in sync. The US opened GPS to civilian use after a Korean Air Lines passenger plane strayed into Soviet airspace and was shot down in 1983. Today it's so embedded in daily life that an outage would disrupt far more than maps." },
  ],
  quiz: [
    { s: 0, q: "Does your phone send signals to GPS satellites?", o: ["Yes, constantly", "No, it only listens", "Only when navigating", "Only in cities"], a: 1, e: "It calculates position from signals it receives." },
    { s: 1, q: "Why is a fourth satellite needed?", o: ["To correct for errors in your phone's clock", "Just for backup", "To make calls", "To measure altitude only"], a: 0, e: "Time is one of the unknowns being solved." },
    { s: 2, q: "About how far off would a one-millionth-of-a-second timing error put you?", o: ["3 cm", "3 metres", "300 metres", "300 km"], a: 2, e: "Light travels about 300 metres in a microsecond." },
    { s: 3, q: "What was GPS 'Selective Availability'?", o: ["A deliberate degrading of civilian GPS accuracy, switched off in 2000", "A way for phones to choose the nearest satellites", "A paid premium GPS service", "A backup system for power blackouts"], a: 0, e: "Turning it off made civilian positions roughly ten times more precise." },
    { s: 4, q: "What is the European Union's satellite navigation system called?", o: ["GLONASS", "BeiDou", "Galileo", "SouthPAN"], a: 2, e: "GNSS is the umbrella term for all of them." },
  ],
  related: ["internet", "black-holes"],
},
);
