/* WISEBYTE LESSONS · Human Body (part 1) */
WB.LESSONS.push(
{
  id: "brain", audience: "adult", cat: "body", level: "beginner",
  trending: true, popularity: 90, added: "2026-08-15",
  title: "The human brain",
  hook: "A 1.4-kilogram organ with 86 billion nerve cells, running on about the power of a dim light bulb.",
  sections: [
    { h: "An energy-hungry organ", key: "The brain is about 2% of body weight but uses about 20% of its energy.",
      b: "The adult human brain weighs about 1.3 to 1.4 kilograms, around 2% of your body weight, yet it uses about 20% of your body's energy, even at rest. That's roughly 20 watts, about the power of a dim light bulb, which is remarkably efficient compared with computers doing far less. It's about 75% water, with the consistency of soft tofu, which is why it floats in protective fluid inside the skull. It has no pain receptors of its own, which is why some brain surgery can be done while the patient is awake." },
    { h: "Neurons and synapses", key: "About 86 billion neurons communicate across synapses, forming trillions of connections.",
      b: "The brain contains roughly 86 billion nerve cells called neurons, and a similar number of supporting glial cells. Neurons communicate using electrical signals that travel along their length, and chemical messengers called neurotransmitters, such as dopamine and serotonin, that cross tiny gaps between cells called synapses. Each neuron can connect with thousands of others, creating an estimated 100 trillion or more connections. Thoughts, memories and feelings are patterns of activity across these networks." },
    { h: "The main regions", key: "Cerebrum: thinking and movement. Cerebellum: coordination. Brainstem: breathing and heart rate.",
      b: "The cerebrum, the large wrinkled outer part, handles thinking, language, memory, senses and voluntary movement. Its wrinkles pack more surface area into the skull. The cerebellum, tucked at the back underneath, fine-tunes balance, coordination and learned movements like riding a bike. The brainstem, connecting the brain to the spinal cord, controls automatic functions you don't think about, like breathing, heart rate, swallowing and sleep cycles." },
    { h: "Four lobes", key: "Frontal (planning, self-control), parietal (touch, space), temporal (hearing, memory), occipital (vision).",
      b: "Each side of the cerebrum has four lobes. The frontal lobes, behind your forehead, handle planning, decision-making, self-control and personality; they're the last part to fully mature, in the mid-20s. The parietal lobes process touch and help you sense where things are in space. The temporal lobes, near your ears, handle hearing, language and memory, and contain the hippocampus, vital for forming new memories. The occipital lobes, at the back, process vision." },
    { h: "Left brain, right brain?", key: "Each hemisphere controls the opposite side of the body; 'left-brained' personalities are a myth.",
      b: "The brain has two hemispheres connected by a thick bundle of fibres. Each side mostly controls the opposite side of the body. Some functions lean to one side; in most people, language is mainly processed on the left. But the popular idea that people are 'left-brained' (logical) or 'right-brained' (creative) is a myth. A large 2013 study scanning over 1,000 people found no evidence that individuals use one side more overall. Both sides work together constantly." },
    { h: "The 10% myth", key: "We use virtually all of our brain, not just 10%.",
      b: "You've probably heard that we only use 10% of our brains. It's false. Brain scans show activity across nearly every region over the course of a day, even during sleep. Damage to almost any area, from a stroke or injury, causes noticeable problems. And it would make no evolutionary sense to maintain such an energy-hungry organ if 90% of it did nothing. The myth probably came from misquoted early psychology and has been kept alive by movies and self-help marketing." },
    { h: "It rewires itself", key: "Neuroplasticity is the brain's ability to change with experience, throughout life.",
      b: "Your brain physically changes with experience, a property called neuroplasticity. Every time you learn something, connections between neurons strengthen or form. Scientists once thought the adult brain was fixed, but we now know it keeps changing throughout life. In a well-known study, London taxi drivers who spent years memorising the city's 25,000 streets had a larger rear hippocampus than bus drivers who followed set routes. After strokes, other areas can sometimes take over lost functions with rehabilitation." },
    { h: "Looking after your brain", key: "Exercise, sleep, social connection, learning and heart health all support brain health.",
      b: "Brain health is closely tied to overall health. Regular physical exercise increases blood flow to the brain and is one of the best-supported ways to protect thinking skills as we age. Sleep clears waste and consolidates memories. Social connection and continuing to learn new things are linked to lower dementia risk. Protecting your heart, by managing blood pressure, not smoking and limiting alcohol, protects your brain too. Wearing a helmet when cycling protects it more directly." },
  ],
  quiz: [
    { s: 0, q: "Roughly what share of the body's energy does the brain use?", o: ["2%", "10%", "20%", "50%"], a: 2, e: "About 20%, despite being about 2% of body weight." },
    { s: 1, q: "What are synapses?", o: ["Junctions where neurons pass signals", "Parts of the skull", "Blood cells", "Areas for vision"], a: 0, e: "Neurotransmitters cross these gaps." },
    { s: 2, q: "Which part of the brain controls breathing and heart rate?", o: ["The cerebrum", "The cerebellum", "The brainstem", "The frontal lobe"], a: 2, e: "The brainstem runs automatic functions." },
    { s: 3, q: "Which lobe handles planning and self-control, and matures last?", o: ["Frontal", "Occipital", "Temporal", "Parietal"], a: 0, e: "The frontal lobes mature in the mid-20s." },
    { s: 6, q: "What is neuroplasticity?", o: ["The brain's ability to change with experience", "A brain disease", "The brain's outer layer", "A type of neuron"], a: 0, e: "Learning physically reshapes the brain." },
  ],
  related: ["sleep", "memory-palace"],
},
{
  id: "sleep", audience: "adult", cat: "body", level: "intermediate",
  popularity: 85, added: "2026-09-12",
  title: "Why we sleep",
  hook: "You'll spend about a third of your life asleep. Here's what your brain is doing, and how to sleep better.",
  sections: [
    { h: "A third of your life", key: "Sleep is active maintenance for body and brain, not wasted time.",
      b: "You'll spend roughly a third of your life asleep, around 25 years for most people. Far from being wasted time, sleep is when your body and brain do essential maintenance: repairing tissue, consolidating memories, regulating hormones and supporting the immune system. Every animal studied so far sleeps in some form, even fruit flies and jellyfish, which suggests it serves fundamental purposes. Going without it quickly affects mood, attention and judgement." },
    { h: "Sleep cycles", key: "Sleep runs in ~90-minute cycles of light, deep and REM sleep.",
      b: "Each night you move through cycles of roughly 90 minutes. Each cycle includes light sleep, deep sleep (also called slow-wave sleep) and REM, or rapid eye movement, sleep. Deep sleep dominates the first half of the night and is important for physical recovery. REM sleep, when most vivid dreaming happens, becomes longer towards morning. During REM, your brain is highly active but most of your muscles are temporarily paralysed, which stops you acting out your dreams." },
    { h: "Memory and learning", key: "Sleep strengthens the day's memories and moves them into long-term storage.",
      b: "During sleep, the brain replays and strengthens memories from the day, helping move them into long-term storage. Studies show people remember new facts and skills better after sleeping on them than after the same time awake. Both deep sleep and REM seem to contribute in different ways. Sleep also helps with creative problem-solving: people are more likely to spot hidden patterns after a night's sleep. It's one more reason spaced learning beats an all-night cram." },
    { h: "Taking out the trash", key: "Research in mice suggests the brain clears waste more actively during sleep.",
      b: "In 2013, researchers studying mice found that the brain's 'glymphatic' system, which flushes fluid through brain tissue, becomes much more active during sleep, clearing waste products including proteins linked to Alzheimer's disease. Scientists are still working out exactly how this applies to humans, but it may be one reason chronic poor sleep is associated with a higher risk of cognitive decline. It's a vivid reminder that sleep is active work, not just switching off." },
    { h: "Your body clock", key: "The circadian rhythm is a ~24-hour body clock set by light; melatonin rises in the evening.",
      b: "A master clock in the brain, in a region called the suprachiasmatic nucleus, runs your circadian rhythm, a roughly 24-hour cycle controlling sleepiness, body temperature and hormones. Light is its main timekeeper. Morning daylight tells it the day has begun; as evening falls, the hormone melatonin rises to prepare you for sleep. Bright light, including from screens, late at night can delay that signal. Jet lag and shift work are hard because they force you out of sync with your clock." },
    { h: "Sleep pressure and caffeine", key: "Adenosine builds sleep pressure during the day; caffeine blocks it for hours.",
      b: "While you're awake, a chemical called adenosine builds up in the brain, creating 'sleep pressure' that makes you drowsy. Sleep clears it. Caffeine works by blocking adenosine receptors, masking tiredness. But it lingers: caffeine has a half-life of about five hours in most adults, so half the caffeine from a 3 pm coffee may still be in your system at 8 pm. Even if you can fall asleep, it can reduce deep sleep. Many sleep experts suggest avoiding caffeine for 8 hours or more before bed." },
    { h: "How much you need", key: "Most adults need 7–9 hours; regular short sleep has real costs.",
      b: "Most adults need 7 to 9 hours of sleep a night; teenagers need more, around 8 to 10. Very few people genuinely thrive on less than 6. Regularly getting too little is linked to poorer concentration, mood and immune function, weight gain and higher risks of heart disease and diabetes. Tiredness is also dangerous on the roads: being awake for 17 hours affects driving roughly as much as a blood alcohol concentration of 0.05. Surveys suggest many Australians regularly don't get enough sleep." },
    { h: "Sleeping better", key: "Keep a consistent schedule, get morning light, and keep the bedroom cool, dark and quiet.",
      b: "The most effective habit is consistency: going to bed and getting up at similar times every day, including weekends. Get daylight in the morning. Keep your bedroom cool, dark and quiet, and use the bed mainly for sleep. Wind down with a routine and dim lights in the hour before bed. Limit caffeine later in the day and alcohol at night; alcohol may help you nod off but fragments sleep later. If you regularly struggle with sleep or snore heavily, talk to a doctor, as conditions like sleep apnoea are common and treatable." },
  ],
  quiz: [
    { s: 1, q: "About how long is one sleep cycle?", o: ["30 minutes", "90 minutes", "3 hours", "8 hours"], a: 1, e: "Cycles last about 90 minutes." },
    { s: 1, q: "When does most vivid dreaming happen?", o: ["Deep sleep", "Light sleep", "REM sleep", "Only before waking"], a: 2, e: "REM sleep increases towards morning." },
    { s: 4, q: "Which hormone rises in the evening to prepare you for sleep?", o: ["Adrenaline", "Melatonin", "Insulin", "Cortisol"], a: 1, e: "Melatonin rises as it gets dark." },
    { s: 5, q: "How does caffeine keep you awake?", o: ["It adds energy", "It blocks adenosine, the sleep-pressure chemical", "It raises melatonin", "It cools the brain"], a: 1, e: "It masks tiredness rather than removing it." },
    { s: 6, q: "Being awake for 17 hours affects driving about as much as what?", o: ["A blood alcohol level of 0.05", "One coffee", "Nothing", "A short nap"], a: 0, e: "Fatigue is a serious road safety risk." },
  ],
  related: ["brain", "stress"],
},
{
  id: "immune-system", audience: "adult", cat: "body", level: "intermediate",
  popularity: 78, added: "2026-09-24",
  title: "How your immune system works",
  hook: "Right now, an army of cells is patrolling your body, learning, remembering and fighting invaders you'll never notice.",
  sections: [
    { h: "Your defence force", key: "The immune system defends against pathogens using barriers, fast general defences and targeted responses.",
      b: "Every day your body encounters bacteria, viruses, fungi and parasites, called pathogens. Most never make you sick, thanks to your immune system: a network of cells, tissues and organs spread throughout your body, including the bone marrow, thymus, spleen, lymph nodes and tonsils. It works in layers: physical barriers keep most invaders out, fast general defences attack anything suspicious, and a slower, targeted system learns to recognise specific threats and remembers them." },
    { h: "The first barriers", key: "Skin, mucus, stomach acid and friendly bacteria stop most pathogens getting in.",
      b: "The first line of defence is simply keeping invaders out. Your skin is a tough physical barrier. Mucus in your nose and airways traps particles, and tiny hairs called cilia sweep it out. Tears and saliva contain enzymes that break down bacteria. Stomach acid kills many microbes you swallow. And the trillions of friendly bacteria living on your skin and in your gut take up space and resources that harmful microbes would otherwise use." },
    { h: "The rapid response", key: "The innate immune system responds fast to any invader, causing inflammation and fever.",
      b: "When something gets past the barriers, the innate immune system responds within minutes to hours. White blood cells such as neutrophils and macrophages rush to the site and engulf invaders. They release chemical signals that cause inflammation, the redness, heat, swelling and pain around a cut, which brings more blood and immune cells to the area. Fever is also part of the response; a higher body temperature makes it harder for many pathogens to multiply and speeds up immune reactions." },
    { h: "The specialists", key: "The adaptive immune system uses B cells (antibodies) and T cells to target specific invaders.",
      b: "The adaptive immune system is slower, taking days, but highly targeted. It relies on two types of white blood cells called lymphocytes. B cells make antibodies, Y-shaped proteins that lock onto a specific pathogen, neutralising it or flagging it for destruction. T cells come in different kinds: some coordinate the immune response, while killer T cells destroy infected cells directly. Your body can produce a vast variety of antibodies, enough to recognise almost any invader it might meet." },
    { h: "Immune memory", key: "After an infection, memory cells let the body respond faster and stronger next time.",
      b: "After fighting off an infection, some B and T cells become long-lived memory cells. If the same pathogen returns, they recognise it and mount a faster, stronger response, often clearing it before you feel sick. That's why you usually only get diseases like chickenpox once. Some viruses, like flu and the common cold, keep changing their outer proteins or come in many varieties, so your memory cells don't recognise the new versions, and you can catch them again." },
    { h: "How vaccines work", key: "Vaccines train immune memory safely, without you having to get sick first.",
      b: "Vaccines give your immune system a safe preview of a pathogen, using a weakened or inactivated form, a piece of it, or instructions for making a piece, as mRNA vaccines do. Your body builds memory cells without you having to suffer the disease. Vaccines have been extraordinarily successful: smallpox, which killed hundreds of millions of people, was declared eradicated in 1980. When enough people are immune, disease struggles to spread, protecting those who can't be vaccinated, an effect called herd immunity." },
    { h: "When it goes wrong", key: "Allergies are overreactions to harmless things; autoimmune diseases attack the body itself.",
      b: "The immune system isn't perfect. In allergies, it overreacts to harmless substances like pollen, dust mites or certain foods. Australia has one of the highest rates of food allergy in the world, especially among children. In autoimmune diseases, such as type 1 diabetes, rheumatoid arthritis and coeliac disease, the immune system mistakenly attacks the body's own tissues. Scientists are still unravelling why, but genetics and environment both play roles." },
    { h: "Supporting your immunity", key: "Sleep, exercise, a balanced diet, vaccination and hygiene support immunity; 'boosting' products mostly don't.",
      b: "You can't 'boost' a healthy immune system into overdrive, and you wouldn't want to, since an overactive immune system causes problems. But you can support it. Regular sleep, physical activity, a balanced diet with plenty of vegetables and fruit, not smoking and moderating alcohol all help it work well. Staying up to date with vaccinations and washing your hands prevent infections in the first place. Be sceptical of supplements and products that promise to 'boost immunity'; for most people, the evidence is weak." },
  ],
  quiz: [
    { s: 1, q: "Which of these is part of the body's first line of defence?", o: ["Antibodies", "Skin and mucus", "Memory cells", "Vaccines"], a: 1, e: "Barriers keep most invaders out." },
    { s: 2, q: "Why does inflammation happen around a cut?", o: ["To bring more blood and immune cells to the area", "Because the skin is dying", "It's a sign of infection only", "It has no purpose"], a: 0, e: "Redness and swelling are part of the rapid response." },
    { s: 3, q: "What do B cells make?", o: ["Antibodies", "Red blood cells", "Insulin", "Mucus"], a: 0, e: "Antibodies lock onto specific pathogens." },
    { s: 5, q: "How do vaccines protect you?", o: ["They kill all germs", "They train immune memory without you getting sick", "They replace white blood cells", "They lower your temperature"], a: 1, e: "Your body builds memory cells safely." },
    { s: 6, q: "What happens in an autoimmune disease?", o: ["The immune system attacks the body's own tissues", "The immune system stops working", "You catch more colds", "Vaccines stop working"], a: 0, e: "Examples include type 1 diabetes and coeliac disease." },
  ],
  related: ["antibiotics", "sleep"],
},
);
