/* WISEBYTE LESSONS · Space */
WB.LESSONS.push(
{
  id: "black-holes", audience: "adult", cat: "space", level: "advanced",
  trending: true, popularity: 97, added: "2026-08-28",
  title: "How black holes work",
  hook: "Places where gravity wins completely, time slows down and even light can't escape.",
  sections: [
    { h: "Gravity that won't let go", key: "A black hole is a region where gravity is so strong that not even light can escape.",
      b: "A black hole is a region of space where gravity is so strong that nothing, not even light, can escape. It forms when a huge amount of mass is squeezed into a tiny space. Every object has an 'escape velocity', the speed you need to break free of its gravity: about 11 kilometres per second for Earth. For a black hole, the escape velocity is greater than the speed of light, about 300,000 kilometres per second, and since nothing can travel faster than light, nothing gets out." },
    { h: "An old idea proven", key: "Black holes were predicted by Einstein's general relativity and were once thought purely theoretical.",
      b: "In 1783, English clergyman John Michell imagined 'dark stars' so massive that light couldn't escape. The modern idea came from Albert Einstein's general theory of relativity (1915), which describes gravity as the bending of space and time by mass. Within months, Karl Schwarzschild found that Einstein's equations allowed for regions from which nothing could escape. For decades many physicists, including Einstein, doubted they really existed. The name 'black hole' was popularised in the late 1960s." },
    { h: "How they form", key: "Stellar black holes form when the core of a very massive star collapses.",
      b: "Stellar black holes form when a very massive star, typically at least about 20 times the mass of our Sun, runs out of fuel. Without the outward push of nuclear fusion, the core collapses under its own gravity in a fraction of a second, often triggering a supernova explosion that blasts away the outer layers. What remains is crushed into a black hole. Our Milky Way probably contains tens of millions of these stellar-mass black holes, most of them invisible." },
    { h: "The event horizon", key: "The event horizon is the boundary beyond which nothing can escape.",
      b: "The boundary around a black hole is called the event horizon. Outside it, a powerful enough rocket could still escape. Once inside, escape is impossible, because every possible path leads further in. A black hole with the mass of our Sun would have an event horizon only about 6 kilometres across. If Earth were somehow squeezed into a black hole, it would be about the size of a marble. At the centre, general relativity predicts a 'singularity', where our current physics breaks down." },
    { h: "Spaghettification", key: "Near a small black hole, uneven gravity would stretch you like spaghetti.",
      b: "Gravity gets stronger the closer you are to a mass. Near a small black hole, the pull on your feet would be enormously stronger than on your head, stretching you out like a noodle while squeezing you from the sides. Scientists really do call this spaghettification. Strangely, near a supermassive black hole the stretching at the event horizon is gentler, so you could cross it without noticing, though you'd still never come back out." },
    { h: "Time slows down", key: "General relativity says time passes more slowly in strong gravity.",
      b: "Einstein's general relativity predicts that time passes more slowly in stronger gravity. It's not just theory: clocks on GPS satellites, in weaker gravity high above Earth, tick slightly faster than clocks on the ground, and the system must correct for it. Near a black hole the effect becomes extreme. To a distant observer, a clock falling towards a black hole would appear to tick slower and slower as it approached the event horizon, its light growing dimmer and redder." },
    { h: "Monsters at galaxy centres", key: "Supermassive black holes, millions to billions of Suns in mass, sit at the centres of most large galaxies.",
      b: "Most large galaxies have a supermassive black hole at their centre, weighing millions to billions of times as much as the Sun. Ours is Sagittarius A*, about 4 million times the Sun's mass, around 26,000 light-years away. Astronomers proved it was there by tracking stars whipping around an invisible object at enormous speeds, work that won the 2020 Nobel Prize in Physics. Gas falling into supermassive black holes can heat up and shine brighter than whole galaxies, creating quasars." },
    { h: "Seeing the invisible", key: "The Event Horizon Telescope imaged M87's black hole (2019) and Sagittarius A* (2022); LIGO detected black hole collisions (2015).",
      b: "Black holes can't be seen directly, but their surroundings can. In 2015, the LIGO detectors in the US picked up gravitational waves, tiny ripples in space itself, from two black holes colliding over a billion light-years away. In 2019, the Event Horizon Telescope, a network of radio telescopes working as one Earth-sized dish, released the first image of a black hole's shadow, in the galaxy M87. In 2022 it imaged Sagittarius A*, at the heart of our own galaxy." },
  ],
  quiz: [
    { s: 0, q: "What makes a black hole 'black'?", o: ["It's made of dark matter", "Not even light can escape its gravity", "It's too far away to see", "It absorbs only visible light"], a: 1, e: "Its escape velocity exceeds the speed of light." },
    { s: 2, q: "How do stellar black holes usually form?", o: ["Two planets collide", "A massive star's core collapses", "A galaxy runs out of gas", "Dark energy condenses"], a: 1, e: "When a massive star runs out of fuel, its core collapses." },
    { s: 3, q: "What is the event horizon?", o: ["The centre of a black hole", "The boundary beyond which nothing can escape", "The glowing disc of gas", "A jet of particles"], a: 1, e: "Past it, escape would require going faster than light." },
    { s: 5, q: "How do GPS satellites show that gravity affects time?", o: ["Their clocks tick slightly faster than ground clocks", "Their clocks stop", "They don't use clocks", "They run backwards"], a: 0, e: "Weaker gravity up there means time runs slightly faster." },
    { s: 6, q: "What sits at the centre of the Milky Way?", o: ["A neutron star", "A supermassive black hole called Sagittarius A*", "A white dwarf", "Empty space"], a: 1, e: "About 4 million times the Sun's mass." },
  ],
  related: ["stars", "big-bang"],
},
{
  id: "stars", audience: "adult", cat: "space", level: "intermediate",
  popularity: 70, added: "2026-09-05",
  title: "The life and death of stars",
  hook: "How stars are born, why their mass decides their fate, and why many of them don't shine alone.",
  sections: [
    { h: "Born in clouds", key: "Stars form in nebulae when gravity pulls gas together until it ignites.",
      b: "Stars form inside giant, cold clouds of gas and dust called nebulae, made mostly of hydrogen. Something, perhaps a nearby supernova or a collision between clouds, disturbs the gas. Gravity pulls denser clumps together, and as they shrink they heat up. When the core reaches about 10 million degrees, nuclear fusion ignites and a star is born. The Orion Nebula, visible to the naked eye as a fuzzy patch in Orion's 'sword' (the handle of the Saucepan in Australian skies), is a stellar nursery." },
    { h: "Nuclear fusion", key: "Stars shine by fusing hydrogen into helium, which balances gravity pulling inwards.",
      b: "In a star's core, hydrogen nuclei are squeezed together so hard that they fuse into helium, converting a tiny amount of mass into a huge amount of energy, as described by Einstein's E = mc². The Sun converts about 4 million tonnes of matter into energy every second. That energy pushes outwards, balancing gravity pulling inwards. For most of a star's life, these two forces are locked in a stable balance." },
    { h: "Our Sun", key: "The Sun is an ordinary middle-aged star about 4.6 billion years old.",
      b: "The Sun is a fairly ordinary star, about 1.4 million kilometres across and 4.6 billion years old, roughly halfway through its life. Its surface is about 5,500°C and its core about 15 million °C. Energy released in the core can take tens of thousands of years or more to work its way out through the Sun's dense interior, but once it leaves the surface, the light reaches Earth in about eight minutes." },
    { h: "Mass decides fate", key: "Small stars live longest; massive stars burn out in millions of years.",
      b: "A star's mass decides almost everything about it: its colour, brightness and lifespan. Small, cool red dwarfs use fuel so slowly they can shine for trillions of years, far longer than the universe has existed. Massive blue stars burn hot and fast, lasting only a few million years. It seems backwards, but more fuel means a shorter life, because heavier stars burn it at a vastly faster rate. Most stars in the galaxy are red dwarfs, too faint to see with the naked eye." },
    { h: "The death of a Sun-like star", key: "The Sun will become a red giant, then a white dwarf, in about 5 billion years.",
      b: "In about 5 billion years, when the Sun runs low on hydrogen in its core, it will swell into a red giant, perhaps large enough to engulf Mercury, Venus and possibly Earth. Well before then, in about a billion years, its growing brightness will have boiled away Earth's oceans. Eventually the Sun will puff off its outer layers into a glowing shell called a planetary nebula. What's left will be a white dwarf: a dense, Earth-sized ember that slowly cools over trillions of years." },
    { h: "The death of a giant", key: "Massive stars explode as supernovae, leaving neutron stars or black holes.",
      b: "Massive stars end far more violently. They fuse heavier and heavier elements in their cores, up to iron. Fusing iron doesn't release energy, so the core collapses in less than a second, rebounding in a supernova, an explosion that can briefly outshine an entire galaxy of billions of stars. The collapsed core becomes a neutron star, so dense that a teaspoon would weigh billions of tonnes, or, if massive enough, a black hole." },
    { h: "Stars in pairs", key: "Close to half of Sun-like stars have a companion, and an exploding white dwarf in a pair makes a useful cosmic measuring stick.",
      b: "Our solitary Sun is a little unusual: close to half of Sun-like stars have at least one companion. Some pairs give themselves away by eclipses. Algol, in the constellation Perseus, noticeably dims every 2.9 days as a fainter partner passes in front of the brighter star. Sirius is circled by a small, faint companion, Sirius B, a white dwarf. Pairs can also be destructive. When a white dwarf pulls enough gas from a close partner, or merges with another white dwarf, it can blow apart in a type Ia supernova. These reach a predictable peak brightness, so astronomers use them to measure distances across the universe, work that earned ANU astronomer Brian Schmidt a share of the 2011 Nobel Prize in Physics." },
    { h: "Look up tonight", key: "A star's colour reveals its temperature, and starlight is a view into the past.",
      b: "Next time you're somewhere dark, look for colours. Reddish stars like Antares, in Scorpius, are cooler; blue-white stars like Rigel, in Orion, are hotter. Remember that starlight is old: light from the brightest star in the night sky, Sirius, left it about 8.6 years ago. Australia's dark outback skies are among the best in the world, and in 2016 Warrumbungle National Park in NSW became Australia's first Dark Sky Park." },
  ],
  quiz: [
    { s: 0, q: "Where are stars born?", o: ["Inside black holes", "In clouds of gas and dust called nebulae", "On planets", "Inside comets"], a: 1, e: "Gravity collapses clumps of gas inside nebulae." },
    { s: 1, q: "What powers a star?", o: ["Burning like coal", "Nuclear fusion of hydrogen into helium", "Electricity", "Friction"], a: 1, e: "Fusion converts mass into energy." },
    { s: 3, q: "Which stars live the longest?", o: ["Massive blue stars", "Small red dwarfs", "Red giants", "Supernovae"], a: 1, e: "They burn fuel so slowly they can last trillions of years." },
    { s: 4, q: "What will the Sun eventually become?", o: ["A black hole", "A neutron star", "A white dwarf", "A supernova"], a: 2, e: "It's not massive enough to explode." },
    { s: 6, q: "What can happen to a white dwarf in a close pair of stars?", o: ["It turns back into a Sun-like star", "It can explode as a type Ia supernova", "It becomes a planet", "It swells into a red giant again"], a: 1, e: "These explosions reach a predictable brightness, making them useful distance markers." },
  ],
  related: ["black-holes", "big-bang"],
},
{
  id: "big-bang", audience: "adult", cat: "space", level: "intermediate",
  popularity: 82, added: "2026-09-24",
  title: "The Big Bang",
  hook: "13.8 billion years ago, everything you can see was packed into a space smaller than an atom. How do we know?",
  sections: [
    { h: "Not an explosion", key: "The Big Bang was the rapid expansion of space itself, not an explosion into existing space.",
      b: "The Big Bang theory describes how the universe expanded from an extremely hot, dense state about 13.8 billion years ago. The name is misleading. It wasn't an explosion in a particular place, flinging matter outwards into empty space. It was the expansion of space itself, happening everywhere at once. There's no centre and no edge to point to. The name was coined, somewhat mockingly, by astronomer Fred Hoyle in a 1949 radio broadcast; he preferred a rival theory." },
    { h: "The expanding universe", key: "In 1929, Edwin Hubble showed galaxies are moving away from us, faster the further they are.",
      b: "In the 1920s, astronomers were still arguing about whether other galaxies even existed. Edwin Hubble settled that and then, in 1929, showed something astonishing: nearly all galaxies are moving away from us, and the further away they are, the faster they recede. That's exactly what you'd expect if space itself is stretching. Picture raisins in rising bread dough: every raisin moves away from every other, and distant ones separate faster. Run the film backwards and everything converges." },
    { h: "An echo of creation", key: "The cosmic microwave background, discovered in 1965, is leftover heat from the early universe.",
      b: "If the universe began hot and dense, some of that heat should still be around, stretched into faint microwaves by billions of years of expansion. In 1965, Arno Penzias and Robert Wilson, working at Bell Labs, found a mysterious hiss in their radio antenna coming from every direction. At first they suspected pigeon droppings. It turned out to be the cosmic microwave background: light released about 380,000 years after the Big Bang. It won them a Nobel Prize and is some of the strongest evidence for the theory." },
    { h: "The first minutes", key: "In the first few minutes, the universe made hydrogen, helium and a little lithium.",
      b: "In the first fraction of a second, the universe was far too hot for atoms to exist. As it expanded and cooled, basic particles formed, and within about three minutes, protons and neutrons fused into the nuclei of the lightest elements. The theory predicts the universe should have started out about three-quarters hydrogen and a quarter helium by mass, with a trace of lithium. That's almost exactly what astronomers observe in the oldest stars and gas clouds." },
    { h: "The first light and stars", key: "After about 380,000 years atoms formed and light travelled freely; the first stars formed within a few hundred million years.",
      b: "For its first 380,000 years, the universe was a glowing fog of charged particles that scattered light. When it cooled enough for electrons to join nuclei and form atoms, the fog cleared and light could travel freely. That's the light we see as the cosmic microwave background. Then came a long 'dark age' until gravity pulled gas into the first stars and galaxies, within a few hundred million years. The James Webb Space Telescope, launched in 2021, is now spotting galaxies from this early era." },
    { h: "Dark matter and dark energy", key: "Ordinary matter is only about 5% of the universe; dark matter and dark energy make up the rest.",
      b: "Everything we can see, stars, planets, gas and people, makes up only about 5% of the universe's contents. About 27% is dark matter, invisible material we detect only through its gravity, which holds galaxies together. The remaining 68% or so is dark energy, a mysterious effect causing the expansion of the universe to speed up, discovered in 1998. We don't yet know what either of them actually is. They're among the biggest open questions in science." },
    { h: "Before the Big Bang?", key: "What came 'before', and why, are open questions; the theory describes what happened after.",
      b: "The Big Bang theory describes how the universe evolved from an early hot, dense state. It doesn't explain what caused that state or whether anything came 'before'. Time itself may have begun with the Big Bang, making 'before' meaningless, much like asking what's north of the North Pole. Some physicists explore ideas such as cosmic inflation, a brief burst of extreme expansion in the first instant, or even multiple universes. These are active areas of research, not settled science." },
    { h: "How big is it?", key: "The observable universe is about 93 billion light-years across and holds hundreds of billions of galaxies, perhaps more.",
      b: "Because space has expanded while light travelled, the observable universe is about 93 billion light-years across, even though it's 13.8 billion years old. It may contain hundreds of billions of galaxies, perhaps as many as two trillion, each with billions of stars. The universe beyond what we can observe may be much larger, possibly infinite. On a clear night away from city lights, the faint smudge of the Large Magellanic Cloud, visible from Australia, is another galaxy whose light left it around 160,000 years ago." },
  ],
  quiz: [
    { s: 0, q: "How old is the universe, according to the Big Bang theory?", o: ["About 4.5 billion years", "About 13.8 billion years", "About 6,000 years", "It has always existed"], a: 1, e: "About 13.8 billion years." },
    { s: 1, q: "What did Edwin Hubble discover in 1929?", o: ["Black holes", "Galaxies are moving away from us, faster the further they are", "The Moon is moving away", "Dark energy"], a: 1, e: "That's the signature of an expanding universe." },
    { s: 2, q: "What is the cosmic microwave background?", o: ["Leftover heat from the early universe", "Radiation from mobile phones", "Light from the Sun", "Noise from black holes"], a: 0, e: "Light released about 380,000 years after the Big Bang." },
    { s: 5, q: "Roughly what share of the universe is ordinary matter?", o: ["About 5%", "About 50%", "About 95%", "100%"], a: 0, e: "Dark matter and dark energy make up the rest." },
    { s: 6, q: "Does the Big Bang theory explain what caused the Big Bang?", o: ["Yes, completely", "No, it describes what happened after", "It says aliens did it", "It says it never happened"], a: 1, e: "What came before, if anything, is still an open question." },
  ],
  related: ["stars", "black-holes"],
},
{
  id: "moon", audience: "adult", cat: "space", level: "beginner",
  popularity: 74, added: "2026-09-24",
  title: "The Moon: our strange companion",
  hook: "It was born in a collision, it's slowly drifting away, and it controls the tides at your local beach.",
  sections: [
    { h: "Born from a collision", key: "The Moon most likely formed when a Mars-sized body hit the young Earth.",
      b: "The leading explanation for the Moon's origin is the giant-impact hypothesis. About 4.5 billion years ago, when Earth was young, a Mars-sized body, sometimes called Theia, smashed into it. The collision flung molten rock into orbit, which gradually clumped together to form the Moon. Evidence includes the Moon's small iron core and the remarkable similarity between Moon rocks brought back by Apollo astronauts and rocks on Earth." },
    { h: "Why we see one face", key: "The Moon is tidally locked, so the same side always faces Earth.",
      b: "The Moon spins once on its axis in exactly the time it takes to orbit Earth, about 27 days. So the same side always faces us. This isn't a coincidence: Earth's gravity gradually slowed the Moon's spin until it locked into step, a process called tidal locking. The far side isn't permanently dark; it gets just as much sunlight. We simply never see it from Earth. Humans first saw it in 1959, in photos from a Soviet probe." },
    { h: "Phases", key: "Moon phases come from seeing different amounts of its sunlit half as it orbits.",
      b: "The Moon makes no light of its own; it reflects sunlight. Half of it is always lit by the Sun. As it orbits Earth, we see different amounts of that lit half, producing the phases: new moon, crescent, first quarter, gibbous and full, then back again, in a cycle of about 29.5 days. The word 'month' comes from 'moon'. From Australia, the Moon appears 'upside down' compared with northern hemisphere pictures, so a waxing crescent is lit on the left rather than the right." },
    { h: "Tides", key: "The Moon's gravity creates two tidal bulges, giving most coasts two high tides a day.",
      b: "The Moon's gravity pulls on Earth's oceans. It pulls hardest on the side facing it, creating a bulge of water, and least on the far side, where another bulge forms because the water is effectively left behind. As Earth rotates through the two bulges, most coasts get two high tides and two low tides each day. The Sun helps too: when Sun and Moon line up at full and new moon, we get extra-large spring tides. Australia's north-west has some of the largest tides in the world, over 10 metres." },
    { h: "Eclipses", key: "A solar eclipse happens when the Moon blocks the Sun; a lunar eclipse when Earth's shadow falls on the Moon.",
      b: "By a remarkable coincidence, the Sun is about 400 times wider than the Moon and about 400 times further away, so they look almost exactly the same size in our sky. When the Moon passes directly in front of the Sun, it can block it completely in a total solar eclipse. When Earth passes between the Sun and Moon, its shadow falls on the Moon, often turning it red, in a lunar eclipse. Eclipses don't happen every month because the Moon's orbit is tilted slightly." },
    { h: "Drifting away", key: "The Moon is moving away from Earth at about 3.8 cm a year.",
      b: "Apollo astronauts left mirrors on the Moon. Scientists fire lasers at them and time the reflection, measuring the distance to within millimetres. They've found the Moon is drifting away by about 3.8 centimetres a year, roughly the rate your fingernails grow. Tidal forces are also slowly lengthening Earth's day: hundreds of millions of years ago, a day was only around 22 hours long. Far in the future, total solar eclipses will no longer be possible, because the Moon will look too small to cover the Sun." },
    { h: "Seas without water", key: "The Moon's dark patches, called maria or 'seas', are plains of ancient solidified lava.",
      b: "The dark patches you can see with the naked eye are called maria, Latin for 'seas', because early astronomers thought they might be oceans. They are actually vast plains of solidified lava that flooded huge impact basins roughly 3 to 3.9 billion years ago. The brighter highlands are older, made of paler rock and packed with craters. Almost all the maria are on the near side, which is one reason the far side looks so different in photos. With no wind, rain or moving plates to wear them away, craters last billions of years. At full moon, binoculars show bright rays of debris spreading from young craters like Tycho." },
    { h: "Who owns the Moon?", key: "Under the 1967 Outer Space Treaty no country can claim the Moon, but plans to mine it raise new questions.",
      b: "Officially, nobody owns the Moon. The 1967 Outer Space Treaty, joined by Australia and more than 100 other countries, says no nation can claim the Moon or any other celestial body, and that space should be used for peaceful purposes. But plans to mine lunar water ice raise a new question: can a company own what it digs up? In 2020 Australia was one of eight founding signatories of the Artemis Accords, US-led principles that support using space resources and call for protecting historic sites such as the Apollo landing areas. Dozens more countries have since signed, while China and Russia are planning their own lunar research station instead." },
  ],
  quiz: [
    { s: 0, q: "How did the Moon most likely form?", o: ["It was captured passing by", "A Mars-sized body collided with Earth", "It split off Earth's spin", "It formed from a comet"], a: 1, e: "The giant-impact hypothesis." },
    { s: 1, q: "Why do we always see the same side of the Moon?", o: ["It doesn't spin", "It's tidally locked", "The far side is always dark", "Earth blocks the view"], a: 1, e: "Its spin matches its orbit." },
    { s: 3, q: "What causes ocean tides?", o: ["Wind", "Mainly the Moon's gravity", "Earthquakes", "Rivers"], a: 1, e: "The Sun contributes too." },
    { s: 5, q: "How fast is the Moon drifting away from Earth?", o: ["It isn't", "About 3.8 cm a year", "About 1 km a year", "About 1 metre a year"], a: 1, e: "Measured by bouncing lasers off Apollo mirrors." },
    { s: 6, q: "What are the Moon's dark 'seas', or maria?", o: ["Dried-up oceans of water", "Plains of ancient solidified lava", "Shadows cast by mountains", "Dust blown by lunar winds"], a: 1, e: "Lava flooded huge impact basins roughly 3 to 3.9 billion years ago." },
  ],
  related: ["big-bang", "gps"],
},
);
