/* WISEBYTE LESSONS · arts batch y */
WB.L("sydney-opera-house-story", "arts", "beginner", "The Sydney Opera House: a building that almost wasn't", "It is the most recognisable building in Australia, yet it cost about fourteen times its first estimate, lost its architect halfway through and took fourteen years to build. Here is the remarkable story behind the sails.",
  [
    ["A sketch that won the world", "An unknown Danish architect's daring sketch won an international competition in 1957.", "In 1955 the New South Wales government launched an international competition to design an opera house on Bennelong Point, a rocky spit of land jutting into Sydney Harbour that had previously held a tram depot. More than two hundred entries arrived from around the world. The winner, announced in January 1957, was Jorn Utzon, a 38-year-old Danish architect who had built very little. His entry was hardly more than a set of loose, beautiful sketches showing a cluster of white curved shells rising from a massive stone platform. A popular story says the American architect Eero Saarinen, a judge, rescued it from a pile of rejects. Whether or not that is true, the jury saw something nobody else had imagined: a building meant to be seen from every angle, including from above."],
    ["Named for a man, not just a place", "Bennelong Point honours a Wangal man who lived through the first years of colonial Sydney.", "The site carries the name of Woollarawarre Bennelong, a Wangal man of the Eora nation who was captured in 1789 on the orders of Governor Arthur Phillip, who hoped to learn about the local people through him. Bennelong learned English, became a go-between for the colonists and the Eora, and later travelled to England, one of the first Aboriginal people known to have done so. A small brick hut was built for him on the point that now bears his name. Long before any of this, the harbour foreshore was a meeting and gathering place for its traditional custodians. Today the Opera House acknowledges that history, and the building often hosts First Nations performances and projections on its sails, linking one of the world's newest landmarks to one of its oldest living cultures."],
    ["The shells nobody could build", "The sails looked simple on paper but were a giant engineering puzzle.", "Utzon's sketch had a problem: nobody knew how to build it. The free-flowing curves had no fixed geometry, which meant every piece would have to be unique and the shells might not stand up. Construction began in 1959 under political pressure to get started, even though the design was unresolved, a decision that caused enormous trouble later. Utzon and the engineering firm Ove Arup and Partners spent years testing shapes, using some of the earliest computers employed on a building project. The breakthrough, around 1961 to 1962, is usually credited to Utzon: every shell would be cut from the surface of the same imaginary sphere. Because the curves now matched, the ribs could be made from repeating precast concrete segments, mass produced on site and lifted into place by cranes."],
    ["A million tiles and a lottery", "The roof is covered in over a million Swedish tiles, and much of the cost was paid by gamblers.", "Look closely at the sails and you will see they are not plain white. They are covered in more than a million ceramic tiles made in Sweden, a mix of glossy white and matte cream arranged in chevron patterns. The glossy tiles catch the sun while the matte ones soften the glare, so the roof seems to change colour through the day, from bright white at noon to pink and gold at dusk. Utzon reportedly drew inspiration for the surface from Japanese ceramics. Paying for all this was another challenge. Rather than rely only on taxes, the state government ran the Opera House Lottery, which raised much of the money. Thousands of Australians bought tickets for a chance at a prize, and in doing so helped build a landmark."],
    ["The architect who walked away", "Utzon resigned in 1966 after a bitter dispute and never saw the finished building.", "By the mid 1960s the project was years late and costs were soaring. After a change of government in 1965, the new Minister for Public Works, Davis Hughes, clashed with Utzon over money, design changes and control of the project, and payments to the architect were held back. In February 1966 Utzon resigned. There were street protests in Sydney calling for his return, but he left Australia with his family and never came back. The interiors were finished by a team of Australian architects led by Peter Hall, who made major changes. Most notably, the larger hall, meant for opera, became a concert hall, and opera moved to the smaller theatre, which is one reason opera lovers have long complained about the cramped stage and orchestra pit."],
    ["Opening night and the bill", "The Queen opened the building in 1973, and the final cost was about fourteen times the first estimate.", "Queen Elizabeth II officially opened the Sydney Opera House on 20 October 1973, fourteen years after construction began and sixteen years after the competition. The early cost estimate had been around seven million dollars. The final bill came to about one hundred and two million, a figure often quoted as a warning about big public projects. Yet critics soon fell quiet. The building became the symbol of Sydney and of Australia, appearing on stamps, postcards and every New Year's Eve broadcast. It hosts well over a thousand performances a year, from symphonies and opera to comedy and children's shows, and millions of people visit annually just to walk around it. Few buildings anywhere have done more to put a city on the world map."],
    ["Reconciliation and recognition", "Late in life Utzon was brought back to guide changes, and the building became World Heritage.", "In the late 1990s the Opera House trust reached out to Utzon, then in his eighties, and asked him to set out design principles for the building's future. He agreed, working with his son Jan and the Australian architect Richard Johnson, although he still did not travel to Sydney. A reception room was redesigned to his plans and renamed the Utzon Room, the only interior fully true to his vision. In 2003 he received the Pritzker Prize, architecture's highest honour. In 2007 the Opera House was added to the UNESCO World Heritage List, one of the youngest buildings ever to receive that status, and its architect was still alive to see it. Utzon died in 2008, having never seen his masterpiece in person after leaving."]
  ],
  [
    [0, "What was Jorn Utzon's situation when he won the competition in 1957?", ["He was a famous architect with many large buildings", "He was a young Danish architect who had built very little", "He was an Australian government engineer", "He was a British architect working in Sydney"], 1, "Utzon was 38 and largely unknown, and his entry was mostly a set of sketches."],
    [2, "What idea finally made the shells buildable?", ["Making them out of steel and glass", "Cutting every shell from the surface of the same imaginary sphere", "Building each shell from timber first", "Making the shells smaller and flatter"], 1, "A shared spherical geometry meant the ribs could be made from repeating precast segments."],
    [3, "How was much of the Opera House paid for?", ["A special tax on concert tickets", "Donations from European royalty", "The Opera House Lottery", "A loan from the federal government"], 2, "The state government ran a lottery that raised much of the money."],
    [4, "What happened in 1966?", ["The building opened to the public", "Utzon resigned after a dispute with the new government", "The roof tiles were installed", "The site was moved to Circular Quay"], 1, "Utzon resigned after clashing with the Minister for Public Works, Davis Hughes, and never returned."],
    [6, "What recognition did the building receive in 2007?", ["It was added to the UNESCO World Heritage List", "It was named the world's best concert hall", "It was rebuilt to Utzon's original plans", "It won the Pritzker Prize"], 0, "It became one of the youngest buildings ever placed on the World Heritage List."]
  ]);

WB.L("gothic-cathedrals", "arts", "intermediate", "Gothic cathedrals: how medieval builders made stone fly", "Without calculators or engineering degrees, medieval masons raised stone ceilings dozens of metres into the air and filled walls with glowing glass. Here is how they pulled it off.",
  [
    ["An abbot who wanted light", "Gothic architecture began around the 1140s with Abbot Suger's rebuilding of Saint-Denis near Paris.", "In the 1140s Suger, the abbot of Saint-Denis just north of Paris, set out to rebuild the choir of his abbey church, the burial place of French kings. Suger was influenced by the idea that God could be experienced as light, and he wanted a church that glowed. His builders combined existing techniques, the pointed arch, ribbed vaults and large windows, in a new way, and the result, consecrated in 1144, felt astonishingly open and bright compared with the thick-walled, shadowy Romanesque churches before it. Historians usually treat it as the birth of Gothic architecture. Within decades the style spread across northern France, then to England, Germany, Spain and beyond, carried by travelling master masons and by bishops who wanted their own cathedral to outshine their neighbours'."],
    ["The pointed arch", "Pointed arches push weight downwards more steeply and are more flexible to design with.", "Hold a rounded Roman arch in your mind, then imagine pinching its top into a point. That small change mattered enormously. Any arch pushes outwards as well as down, and a pointed arch directs more of its load downwards, so it pushes sideways less than a semicircular arch of the same width. It is also far more adaptable. A round arch's height is fixed by its width, so arches of different widths end up at different heights, which makes vaulting awkward. A pointed arch can be made steeper or flatter, letting builders bring narrow and wide arches to the same height. Combined with ribbed vaults, a skeleton of stone ribs carrying the ceiling, this gave masons a flexible kit for covering complicated spaces with high stone roofs."],
    ["Flying buttresses", "External props carried the outward push of the vaults, freeing the walls for windows.", "A stone vault high above the floor is heavy, and it constantly tries to push the tops of the walls outwards. Romanesque builders countered that with thick walls and small windows. Gothic builders moved the support outside. A flying buttress is a half arch that leaps from the upper wall across the side aisle to a massive stone pier standing apart from the building. It catches the outward thrust of the vault and channels it down to the ground. Heavy stone pinnacles on top of the piers add weight that helps keep the forces flowing downwards. With the load handled outside, the walls between the supports no longer had to hold much up, so they could be opened into enormous windows. From outside, the buttresses give cathedrals their bristling, ribbed silhouette."],
    ["Walls of coloured light", "Stained glass turned the walls into glowing picture books.", "Step inside Chartres Cathedral on a sunny day and the walls seem to dissolve into deep blues and reds. Medieval stained glass was made by adding metal oxides to molten glass: cobalt for blue, copper for red and green. Glaziers cut the coloured pieces, painted details such as faces and folds in a dark enamel fired onto the surface, and joined everything with strips of lead. Iron frames held the panels in place. The windows told Bible stories and saints' lives, and they often showed the trades who paid for them, such as bakers or shoemakers. Circular rose windows, divided like the petals of a flower, became a signature of the style. The famous deep blue of Chartres has been admired for centuries and is still hard to reproduce exactly."],
    ["Building without equations", "Master masons relied on geometry, experience and rules of thumb rather than structural maths.", "Medieval builders had no theory of forces in the modern sense. Instead, master masons worked with geometry, using compasses, set squares and string to lay out proportions, and they guarded rules of thumb passed down through apprenticeships and workshops. Designs were drawn full size on plaster floors called tracing floors, from which templates for each stone were cut. Builders learned what worked by trial and, sometimes, disaster. At Beauvais in northern France, where the builders attempted the tallest Gothic choir of all, with a vault reaching about forty-eight metres, part of the vault collapsed in 1284 and had to be rebuilt with extra supports. The work was also slow. Cologne Cathedral was begun in 1248 and not finished until 1880, after centuries of interruption."],
    ["A name meant as an insult", "The label 'Gothic' was coined later by critics who thought the style barbaric.", "The people who built these cathedrals did not call them Gothic. They might simply have called the style French work. The word came later, from Renaissance Italian writers who admired the round arches and classical columns of ancient Rome. To them, the pointed medieval style looked crude, and they blamed it on the Goths, the Germanic peoples associated with the fall of Rome, even though the Goths had nothing to do with it. The insult stuck, but its meaning softened over time. By the eighteenth and nineteenth centuries, writers and artists had begun to find Gothic buildings romantic and mysterious, and the word also lent its name to a genre of spooky novels set in crumbling castles and abbeys. Today it is simply a neutral description."],
    ["Gothic comes to Australia", "The nineteenth century Gothic Revival left cathedrals, universities and parliaments across the world, including in Australia.", "In the 1800s Gothic made a spectacular comeback. Architects in Britain saw it as a deeply Christian and national style, and the rebuilt Houses of Parliament in London became its most famous example. The Gothic Revival travelled with the British Empire, and Australia is full of it. The architect William Wardell designed both St Mary's Cathedral in Sydney and St Patrick's Cathedral in Melbourne, which use pointed arches, rib vaults and stained glass in direct homage to medieval models. Universities adopted it too, and the main quadrangle at the University of Sydney is a well-known example. The original medieval buildings still matter deeply. When fire tore through the roof of Notre-Dame in Paris in 2019, people around the world watched in grief, and its reopening in December 2024 was celebrated globally."]
  ],
  [
    [0, "Which building is usually considered the birthplace of Gothic architecture?", ["Notre-Dame de Paris", "Cologne Cathedral", "The abbey church of Saint-Denis", "Westminster Abbey"], 2, "Abbot Suger's rebuilt choir at Saint-Denis, consecrated in 1144, is usually treated as the first Gothic building."],
    [1, "What is one advantage of a pointed arch over a round one?", ["It uses no mortar", "Arches of different widths can reach the same height", "It needs no foundations", "It can only be built from timber"], 1, "A pointed arch can be made steeper or flatter, so narrow and wide arches can line up at the same height."],
    [2, "What job does a flying buttress do?", ["It carries rainwater off the roof", "It holds up the bell tower", "It supports the stained glass from inside", "It catches the outward push of the vault and carries it to the ground"], 3, "By taking the vault's outward thrust outside the building, buttresses freed the walls for windows."],
    [4, "What happened at Beauvais Cathedral in 1284?", ["Part of its record-breaking vault collapsed", "It became the first Gothic building", "It was struck by lightning and burned down", "It was finished after six hundred years"], 0, "Builders pushed the vault to about forty-eight metres, and part of it fell in 1284."],
    [5, "Where did the name 'Gothic' come from?", ["The builders named it after their guild", "Renaissance critics used it as an insult linking the style to the Goths", "It came from a town called Goth in France", "Abbot Suger invented the word"], 1, "Italian writers who preferred classical styles blamed the pointed style on the 'barbarian' Goths."]
  ]);

WB.L("film-editing-invisible-art", "arts", "beginner", "Film editing: the invisible art", "The best editing is the kind you never notice. Yet every cut in a film is a decision that shapes what you feel, what you understand and even what you think an actor is doing.",
  [
    ["A face that changed meaning", "The Kuleshov effect suggests viewers read emotion into a face based on what it is cut with.", "In Russia around the time of the 1917 revolution, a young filmmaker named Lev Kuleshov tried an experiment. According to the usual account, he took a single shot of an actor with a neutral expression and cut it together with different images: a bowl of soup, a child in a coffin, a woman lounging on a sofa. Audiences reportedly praised the actor's subtle performance, seeing hunger, grief or desire, even though his face was identical each time. The original footage has been lost, and modern attempts to repeat the test have given mixed results, so the story is probably tidier than the reality. Still, the core idea is widely accepted by filmmakers: the meaning of a shot depends heavily on what comes before and after it. That is the editor's power."],
    ["Scissors and glue", "For most of film history, editing meant physically cutting and joining strips of film.", "For most of the twentieth century, editors worked with their hands. They watched footage on machines such as the upright Moviola or the flatbed Steenbeck, marked the frames they wanted, then literally cut the film with a splicer and joined pieces with tape or cement. Unused shots hung in long strips from bins. Because every change meant physically cutting, it took skill and patience to try alternatives. Beginning in the late 1980s and 1990s, digital non-linear editing systems such as Avid, and later software such as Final Cut and Premiere, changed everything. Footage could be rearranged instantly and every version saved. Editors still talk about 'cuts', 'trims' and 'bins', words that come straight from the days of scissors, and many say the craft itself, deciding what to show and when, has not changed."],
    ["Rules that hide the joins", "Continuity editing uses a set of conventions so cuts feel seamless.", "Hollywood developed a set of conventions known as continuity editing, designed so viewers follow the story without noticing the cuts. One is the 180-degree rule: imagine a line running between two people in conversation and keep the camera on one side of it, so each character consistently faces the same direction on screen. Another is the shot and reverse shot, cutting back and forth between speakers. Editors also cut on action. If a character starts to sit in a wide shot, the cut to a closer shot happens mid-movement, and the eye follows the motion across the join. An eyeline match shows someone looking off screen, then cuts to what they see. Together these tricks build a sense of a continuous space that, in reality, may have been filmed over several days."],
    ["Collision and montage", "Soviet filmmakers argued that clashing shots could create new ideas in the viewer's mind.", "In the 1920s Soviet filmmakers took Kuleshov's ideas in a bolder direction. Sergei Eisenstein believed that cutting two contrasting shots together could produce a third idea that existed in neither, a kind of collision of images. His film Battleship Potemkin, released in 1925, contains the famous Odessa Steps sequence, in which soldiers march down a great stairway firing on civilians. Eisenstein builds terror through rapid cuts between boots, faces, a mother and a runaway pram, stretching a moment far beyond real time. The sequence has been studied, copied and parodied ever since. Later filmmakers used the match cut to leap across vast distances. In Stanley Kubrick's 2001: A Space Odyssey, a bone thrown into the air by an early human cuts to a spacecraft, spanning millions of years in a single edit."],
    ["Breaking the rules on purpose", "Jump cuts and other deliberate jolts became a style of their own.", "Once audiences learned the rules, filmmakers began to break them for effect. In 1960 the French director Jean-Luc Godard released Breathless, which used jump cuts: abrupt jumps forward within the same shot, so a character seems to skip through time. To audiences used to smooth Hollywood continuity, it felt raw and restless, and it helped define the French New Wave. Jump cuts are now everywhere, from music videos to online videos where creators trim pauses from their speech. Other deliberate jolts include smash cuts, which jump suddenly from a quiet moment to something loud or shocking, and crosscutting, which moves back and forth between two events happening at the same time, ramping up suspense as they appear to converge. Breaking a rule only works because the audience knows it."],
    ["Rhythm and emotion", "Editors shape a film's pace, and many put emotion ahead of strict continuity.", "Walter Murch, the editor and sound designer behind films such as Apocalypse Now, wrote a much loved book about editing called In the Blink of an Eye. He suggested that a cut can feel natural because it works a bit like a blink, which tends to happen as we shift from one thought to the next. Murch also ranked the things a good cut should achieve, and he put emotion first, above advancing the story, rhythm and even keeping continuity perfect. In other words, if a cut makes you feel the right thing, a small mismatch in a glass of water will not matter. Studies of shot lengths also suggest that the average shot in Hollywood films has become much shorter over the decades, so modern films tend to cut faster than older ones."],
    ["An Australian in the edit suite", "Australian editor Margaret Sixel won an Academy Award for Mad Max: Fury Road.", "Mad Max: Fury Road, directed by George Miller and released in 2015, is often held up as a masterclass in action editing. It was cut by Margaret Sixel, an editor born in South Africa who built her career in Australia, from a huge quantity of footage. Sixel kept the most important action in the centre of the frame from shot to shot, so even when cuts come quickly, your eyes know exactly where to look and the chaos stays readable. She won the Academy Award for Best Film Editing for the film. Her work is a good reminder of the editor's paradox. When everything goes right, nobody notices you at all. Next time you watch a film, try counting the cuts in a single scene, and see how many slip by unseen."]
  ],
  [
    [0, "What does the Kuleshov effect suggest?", ["Actors should always show strong emotion", "Viewers read different emotions into the same face depending on surrounding shots", "Colour film is more emotional than black and white", "Audiences prefer long, uncut takes"], 1, "The same neutral face seemed to show hunger, grief or desire depending on what it was cut with."],
    [1, "How did film editors traditionally edit before digital systems?", ["By drawing on the film with pens", "By re-filming each scene in order", "By physically cutting film and joining pieces with tape or cement", "By using a typewriter to list shots"], 2, "Editors cut strips of film on machines such as the Moviola and Steenbeck and spliced them together."],
    [2, "What does the 180-degree rule help with?", ["Keeping characters facing consistent directions on screen", "Making scenes exactly 180 seconds long", "Rotating the camera during a shot", "Choosing the right lens"], 0, "Keeping the camera on one side of an imaginary line stops characters appearing to swap sides."],
    [4, "Which film helped popularise the jump cut in 1960?", ["Battleship Potemkin", "2001: A Space Odyssey", "Apocalypse Now", "Breathless"], 3, "Jean-Luc Godard's Breathless used abrupt jump cuts that defined the French New Wave."],
    [6, "What did Margaret Sixel win an Academy Award for?", ["Directing Mad Max: Fury Road", "Editing Mad Max: Fury Road", "Writing the music for Apocalypse Now", "Inventing digital editing"], 1, "She won Best Film Editing for her work on George Miller's film."]
  ]);

WB.L("story-of-pigments", "arts", "beginner", "The colourful history of paint", "Some colours were once worth more than gold. Others were made from snails, insects or even Egyptian mummies. The story of pigments is a story of trade, chemistry, danger and luck.",
  [
    ["Earth in the palm of your hand", "Ochre, a coloured earth, is one of humanity's oldest pigments.", "Pick up a lump of red or yellow earth, grind it to powder, mix it with water or fat, and you have paint. Ochre, a clay coloured by iron oxides, is among the oldest pigments people ever used. Humans were collecting and processing it tens of thousands of years ago, and it appears in ancient rock art around the world. In Australia, ochre has been used by Aboriginal and Torres Strait Islander peoples for a very long time, for painting rock surfaces, bark and bodies, and in ceremony. Some ochre sources were highly valued and traded across long distances. Heating yellow ochre turns it red, a trick that early people seem to have discovered. Earth colours remain on every artist's palette today, under names such as raw sienna and burnt umber."],
    ["Bluer than gold", "Ultramarine, made from lapis lazuli mined in Afghanistan, was once among the most expensive materials an artist could buy.", "For medieval and Renaissance painters, the finest blue came from a single remote place: the mines of Badakhshan in what is now Afghanistan, where the deep blue stone lapis lazuli was dug from the mountains. Turning the stone into paint was laborious, because simply grinding it produced a dull greyish powder. Craftspeople developed a method of kneading the ground stone in a dough of wax and resin, then washing out the pure blue particles. The result, called ultramarine, meaning 'from beyond the sea', could cost more than gold by weight. Patrons sometimes wrote into contracts how much ultramarine a painter had to use. Because of its value and beauty, it was often reserved for the most important figure in a painting, especially the robes of the Virgin Mary."],
    ["Purple from sea snails", "Tyrian purple was made from huge numbers of sea snails and became a symbol of power.", "The ancient city of Tyre, in today's Lebanon, became famous for a dye extracted from sea snails called murex. Each snail produces only a tiny amount of a gland secretion that turns purple when exposed to air and light, so making the dye required vast numbers of snails and produced an infamous stench. The colour was costly and slow to fade, which made it a natural badge of status. In ancient Rome, a purple stripe on a toga marked senators, and at times laws restricted who could wear the colour at all. Emperors claimed the deepest purple for themselves, and the Byzantine phrase 'born in the purple' referred to children born to a reigning emperor. Purple stayed a royal and religious colour in Europe for centuries."],
    ["Beautiful and deadly", "Some of history's loveliest colours were poisonous.", "Many old pigments were dangerous. Lead white, the main white paint for centuries, was toxic, and painters who handled it often were at risk of lead poisoning. In 1775 the Swedish chemist Carl Wilhelm Scheele created a vivid green from copper and arsenic. Scheele's green, and the related emerald green, became fashionable in the nineteenth century for wallpapers, clothing and even sweets, and they released arsenic as they aged or got damp, harming the people who lived with them. Then there was mummy brown, a rich brown paint made, quite literally, from ground-up Egyptian mummies, and sold by colourmakers until the twentieth century. Some artists were horrified when they learned what it contained. Modern artists' paints are far safer, and labels warn about the few hazardous pigments still sold."],
    ["A lucky accident in a laboratory", "Chemistry began producing new colours, sometimes by accident.", "Around 1706 in Berlin, a colourmaker trying to make a red pigment ended up with a deep blue instead, apparently because one of his ingredients was contaminated. Prussian blue became one of the first modern synthetic pigments, cheaper than ultramarine and widely used in painting, printing and later the blueprints used by engineers and architects. An even bigger accident came in 1856. William Henry Perkin, an eighteen-year-old chemistry student in London, was trying to make quinine, a malaria treatment, from coal tar. He failed, but he noticed a purple residue that dyed silk beautifully. He called it mauveine and started a business making it. Mauve became a fashion craze, and Perkin's discovery helped launch the synthetic dye industry, which went on to produce thousands of new colours."],
    ["Paint in a tube", "The collapsible paint tube let artists paint outdoors, with big consequences.", "For centuries, painters or their assistants ground pigments by hand and mixed them with oil in the studio, storing small amounts in pig bladders tied with string. It was messy and the paint did not travel well. In 1841 an American portrait painter living in London, John Goffe Rand, patented a collapsible metal tube with a screw cap. Suddenly paint was portable and kept fresh for longer. Combined with the bright new synthetic colours of the age, this made it far easier to paint outdoors in front of the subject, working quickly to capture changing light. That practice was central to the Impressionists in France, who often painted outside in the open air. It is a nice example of how a humble bit of technology can help change the course of art."],
    ["Colours still being invented", "New pigments continue to appear, and some spark arguments.", "The search for new colours has not ended. In 2009 a team led by the chemist Mas Subramanian at Oregon State University was experimenting with materials for electronics when a sample came out of the furnace a brilliant blue. Named YInMn blue after its ingredients, yttrium, indium and manganese, it was the first new inorganic blue pigment in about two centuries, and it is very stable. In 2014 a British company announced Vantablack, a coating of tiny carbon tubes that absorbs almost all visible light, making objects look like holes in space. When the sculptor Anish Kapoor obtained exclusive rights to use it in art, other artists protested, and the artist Stuart Semple responded by releasing his own pink paint that anyone could buy except Kapoor."]
  ],
  [
    [1, "Where did the lapis lazuli for ultramarine traditionally come from?", ["Egypt", "Afghanistan", "Spain", "China"], 1, "The mines of Badakhshan in Afghanistan supplied the stone for centuries."],
    [2, "What was Tyrian purple made from?", ["Sea snails", "Crushed beetles", "Purple flowers", "Iron-rich clay"], 0, "The dye came from murex sea snails, so huge numbers were needed."],
    [3, "What made Scheele's green dangerous?", ["It contained lead", "It was radioactive", "It contained arsenic", "It caught fire easily"], 2, "Scheele's green was made from copper and arsenic and released arsenic as it aged."],
    [4, "What was William Henry Perkin trying to make when he discovered mauveine?", ["A blue paint", "A cheaper gunpowder", "A new perfume", "Quinine, a malaria treatment"], 3, "He failed to make quinine from coal tar but noticed a purple residue that dyed silk."],
    [5, "Why did the collapsible paint tube matter?", ["It made paint portable, helping artists paint outdoors", "It made paint cheaper than water", "It allowed paint to glow in the dark", "It replaced brushes"], 0, "Portable paint made it easier to work in the open air, a practice central to the Impressionists."]
  ]);

WB.L("ukiyo-e-great-wave", "arts", "intermediate", "The Great Wave and the floating world", "A giant wave curls like a claw over three tiny boats while Mount Fuji sits calmly in the distance. This Japanese print is one of the most famous images on Earth. Here is the world that made it.",
  [
    ["Pictures of the floating world", "Ukiyo-e were popular Japanese prints celebrating urban pleasures in the Edo period.", "During the Edo period, from 1603 to 1868, Japan was largely closed to the outside world and ruled from the city of Edo, today's Tokyo. As cities grew, a prosperous class of merchants and artisans developed a lively popular culture of theatre, teahouses, fashion and pleasure districts. The Japanese word 'ukiyo' had once meant a sorrowful, fleeting world in a Buddhist sense, but it came to mean the 'floating world' of urban entertainment, enjoyed for the moment. Ukiyo-e, pictures of the floating world, were images of that culture. Early ones were paintings, but woodblock prints made them affordable to ordinary townspeople. Popular subjects included famous kabuki actors, celebrated beauties and courtesans, heroes from legend, and later landscapes and travel scenes. They were, in a sense, the posters and celebrity photos of their day."],
    ["A team effort", "A print was made by a publisher, a designer, a carver and a printer working together.", "We usually name a single artist, but a ukiyo-e print was a team product. The publisher came up with the project, paid for it and sold the results. The designer, the artist we remember, drew the image in ink on thin paper. A skilled carver pasted that drawing face down onto a block of cherry wood and carved away everything except the lines, destroying the original drawing in the process. Extra blocks were carved for each colour. A printer then brushed water-based ink onto each block in turn and pressed damp paper onto it by hand using a flat pad called a baren. Small notches cut into the blocks, called kento, made sure each colour lined up precisely. A single print could need a dozen or more blocks."],
    ["Brocade pictures", "Full-colour prints became possible from the 1760s.", "Early woodblock prints were black and white or had a few colours added by hand. In 1765 the artist Suzuki Harunobu and his collaborators produced prints using many separate colour blocks, made possible by the reliable registration system. These full-colour prints were called nishiki-e, or 'brocade pictures', because their rich colours reminded people of luxurious woven silk. Their arrival kicked off a golden age. Artists such as Kitagawa Utamaro became famous for elegant portraits of women, often shown as close-up half-length figures, while Toshusai Sharaku produced striking, almost caricature-like portraits of kabuki actors during a brief career of less than a year before vanishing from the record. Prints were produced in large editions and sold in shops, and many were relatively cheap, part of the everyday visual life of the city."],
    ["Hokusai and his wave", "Hokusai made the Great Wave around 1831, when he was about seventy.", "Katsushika Hokusai, born in 1760, worked for roughly seven decades, changed his artistic name around thirty times and produced an enormous body of work, from book illustrations to his sketchbooks known as Hokusai Manga. Around 1831, when he was about seventy, he designed a series called Thirty-six Views of Mount Fuji. Its most famous image, Under the Wave off Kanagawa, now usually called The Great Wave, shows fishing boats being dwarfed by a towering wave whose foam breaks into claw-like fingers, while Fuji appears small in the distance. The print makes striking use of Prussian blue, a synthetic pigment imported into Japan that was cheaper and more lasting than earlier blues. Thousands of copies were probably printed, and many surviving impressions are now held in museums around the world."],
    ["Hiroshige's journey", "Hiroshige's prints of the Tokaido road made travel scenes hugely popular.", "A younger rival, Utagawa Hiroshige, became famous for landscapes with a gentler, more atmospheric mood. His series The Fifty-three Stations of the Tokaido, published in the 1830s, followed the great road between Edo and Kyoto, showing travellers trudging through rain, snow, mist and dusk at each post town along the way. Travel was becoming more popular in Japan, and the prints worked partly like souvenirs and partly like a journey for people who could not make it themselves. Hiroshige was a master of weather. His slanting rain, drifting snow and soft gradations of colour, created by wiping the ink on the block so it faded smoothly, made viewers feel they were standing in the scene. Late in life he produced One Hundred Famous Views of Edo, a portrait of his home city."],
    ["Japan meets Europe", "When Japanese prints reached Europe, they inspired a craze known as Japonisme.", "In the 1850s Japan was forced to open its ports to foreign trade, and Japanese goods began flowing into Europe. A popular story says a French artist first discovered Hokusai's sketches because they had been used as packing material around porcelain; it may be partly legend, but prints certainly arrived in large numbers. Japanese art was shown at the great international exhibitions in Paris, and a fashion for all things Japanese, called Japonisme, swept through Western art and design. Artists were fascinated by what they saw: bold flat areas of colour, strong outlines, unusual high or low viewpoints, and compositions that cropped figures at the edge of the frame or placed the main subject off centre. These were ideas quite different from the European tradition of realistic perspective that had dominated since the Renaissance."],
    ["Van Gogh's Japan", "Van Gogh, Monet and others collected prints and absorbed their lessons.", "Few artists loved Japanese prints more than Vincent van Gogh. Living in Paris in the late 1880s, he and his brother Theo collected hundreds of them, and Vincent made oil paintings copying two Hiroshige prints, a flowering plum tree and a bridge in sudden rain, adding his own intense colours and invented borders. When he moved to Arles in the south of France, he said he hoped to find something like the clear light and colour he imagined in Japan. Claude Monet built up a large collection of prints that still hangs in his house at Giverny, and his Japanese-style footbridge appears in many of his garden paintings. Edgar Degas and Mary Cassatt borrowed the cropped, off-centre compositions. Through them, the floating world helped shape modern Western art."]
  ],
  [
    [0, "What does ukiyo-e mean?", ["Pictures of the floating world", "Pictures of the rising sun", "Paintings of the emperor", "Prints of the mountains"], 0, "Ukiyo-e means pictures of the floating world, the urban entertainment culture of Edo Japan."],
    [1, "Who carved the woodblocks for a ukiyo-e print?", ["The publisher", "The famous designer who drew the image", "A specialist carver", "The buyer"], 2, "A skilled carver cut the blocks, destroying the designer's original drawing in the process."],
    [3, "Which imported pigment features strikingly in The Great Wave?", ["Ultramarine", "Prussian blue", "Tyrian purple", "Vermilion"], 1, "Hokusai used Prussian blue, a synthetic pigment that was cheaper and more lasting than earlier blues."],
    [4, "What did Hiroshige's Fifty-three Stations of the Tokaido depict?", ["Kabuki actors on stage", "Battles from Japanese legend", "Famous beauties of Edo", "Scenes along the road between Edo and Kyoto"], 3, "The series showed travellers at the post towns along the great Tokaido road."],
    [5, "What was Japonisme?", ["A Japanese law closing the country to trade", "A type of woodblock carving", "A Western fashion for Japanese art and design", "A school of Japanese painting"], 2, "After Japan opened to trade, a craze for Japanese art swept through Western art and design."]
  ]);

WB.L("art-forgery", "arts", "intermediate", "Art forgery: the con artists who fooled the experts", "One forger sold a fake Vermeer to a Nazi leader. Another was caught by a single tube of white paint. The history of art forgery is full of daring tricks, and it raises a surprisingly hard question: why does a fake matter?",
  [
    ["The forger who fooled Goring", "Han van Meegeren sold fake Vermeers, including one to Hermann Goring.", "In May 1945, just after the Second World War, Dutch police arrested a painter and dealer named Han van Meegeren. A painting attributed to the seventeenth century master Johannes Vermeer had been found in the collection of Hermann Goring, the senior Nazi, and it had been traced back to him. Selling a national treasure to the enemy was a serious charge. Van Meegeren's defence was astonishing: the painting was not a national treasure at all, because he had painted it himself. Disbelieving investigators had him paint a new 'Vermeer' under supervision. He was eventually convicted in 1947 of forgery and fraud rather than collaboration and sentenced to a year in prison, but he died before serving it. To some Dutch people he had become a folk hero who had tricked Goring."],
    ["How he did it", "Van Meegeren used old canvases and a plastic resin to fake age.", "Van Meegeren did not copy existing Vermeers. Instead he invented new ones, cleverly painting religious scenes because some experts believed Vermeer might have had an early religious phase that was missing from the record. He bought genuine seventeenth century paintings of little value, scraped them back and reused the canvases. His biggest technical problem was that oil paint takes decades to harden fully, so fresh paint would give itself away. His solution was to mix his pigments with a synthetic phenol-formaldehyde resin, the material of Bakelite plastic, then bake the painting so it set hard. Rolling the canvas over a cylinder created a network of fine cracks like old craquelure, and he rubbed ink into them to look like dirt. In 1937 a leading expert hailed his Supper at Emmaus as a masterpiece."],
    ["A forger who invented a collection", "Wolfgang Beltracchi created 'lost' works and fake histories to go with them.", "Wolfgang Beltracchi, a German forger, may have been even more ambitious. Rather than copying known paintings, he created works that might plausibly have existed, often filling gaps where a real artist's painting was recorded in a catalogue but had been lost. Just as important was the paperwork. He and his wife invented a story that the pictures came from the collection of her grandfather, and they faked an old-looking photograph of her posing as her own grandmother in front of several of the forgeries. For years the works passed through auction houses and dealers, sometimes selling for millions. His undoing came from science. One painting supposedly from 1914 contained titanium white, a pigment that was not yet available to artists at that date. In 2011 he was sentenced to six years in prison."],
    ["The science of spotting fakes", "Laboratories use chemistry and physics to check whether a work could really be old.", "Today, suspicious paintings can be examined like crime scenes. Pigment analysis is powerful, because many pigments have known dates of invention, so a colour that did not exist yet is a giveaway, exactly what caught Beltracchi. X-ray images reveal hidden layers, such as an older painting underneath or changes the artist made along the way. Infrared light can show the underdrawing sketched beneath the paint. Tree-ring dating can estimate when the wood for an old panel painting was cut. Radiocarbon dating can help too: nuclear weapons tests in the 1950s and 1960s left a distinctive spike of radioactive carbon-14 in the atmosphere, absorbed by living plants, so canvas or binders made from plants grown after that period carry a modern chemical signature that old materials do not."],
    ["The human eye still matters", "Connoisseurship, the trained eye, remains important but can be fooled.", "Before laboratories, judgements about authenticity rested on connoisseurs: experts who had looked at so many works by an artist that they could recognise a hand, the way you might recognise a friend's handwriting. That skill still matters, but forgers exploit its weaknesses. Experts can be swayed by what they hope to find, such as a long-sought missing work, and by a convincing story about where a painting came from. The history of ownership of a work, known as its provenance, is often as important to buyers as the painting itself, which is why forgers like Beltracchi put so much effort into faking it. A large scandal in New York, involving the old Knoedler gallery, which closed in 2011, showed that convincing paperwork and confident dealers could carry fakes into major collections."],
    ["Fakes closer to home", "Australia has had its own authenticity disputes, and Aboriginal art faces particular challenges.", "Australia has not escaped. In a well-known case, a dealer and a restorer were convicted in 2016 over paintings said to be by the celebrated Australian artist Brett Whiteley, but their convictions were overturned on appeal the following year, showing how hard proving forgery in court can be. Aboriginal art faces its own problems. Because it is popular with tourists and collectors, cheap imitations made with no connection to the communities and cultures they copy have been widespread, which harms artists and misrepresents their culture. Many Aboriginal art centres now supply certificates and keep careful records of who made each work. If you are buying, it helps to look for works sold through community art centres or reputable dealers, and the Indigenous Art Code is a voluntary industry code worth checking."],
    ["Why does a fake matter?", "Forgery raises deep questions about what we value in art.", "Here is the puzzle. When experts believed Van Meegeren's Supper at Emmaus was a Vermeer, they found it profound. Once it was exposed, the same canvas seemed clumsy to many viewers, and its value fell dramatically. The paint did not change, so what did? One answer is that we value art partly as an achievement: a genuine Vermeer is the work of a particular person solving particular problems in seventeenth century Delft, and a forgery fakes that history. Another is that an artwork carries a connection to its maker, like a letter in someone's own handwriting. Fraud also causes real harm to buyers and to an artist's reputation, since fakes can distort what we think an artist was like. Forgery makes us ask what we really value in art."]
  ],
  [
    [0, "Why was Han van Meegeren first arrested in 1945?", ["For stealing paintings from a museum", "For apparently selling a Dutch national treasure to Hermann Goring", "For damaging a Vermeer", "For smuggling paint"], 1, "He was suspected of selling a 'Vermeer' to the Nazis, and defended himself by confessing he had painted it."],
    [1, "How did Van Meegeren make fresh paint seem old and hard?", ["He froze the canvas", "He used only watercolours", "He mixed in a synthetic resin and baked the painting", "He left the paintings in the sun for years"], 2, "A phenol-formaldehyde resin, the material of Bakelite, let the paint harden when baked, imitating centuries of ageing."],
    [2, "What clue exposed Wolfgang Beltracchi?", ["A signature spelled wrongly", "Titanium white in a painting supposedly from 1914", "A modern nail in the frame", "A fingerprint in the paint"], 1, "Titanium white was not commercially available until years after the painting's supposed date."],
    [3, "What can infrared light reveal in a painting?", ["The underdrawing beneath the paint", "The price the artist was paid", "The exact day it was finished", "The smell of the paint"], 0, "Infrared imaging can show the sketch an artist drew under the paint layers."],
    [4, "What is provenance?", ["A type of varnish", "A painting technique", "A forger's tool", "The history of a work's ownership"], 3, "Provenance is the record of who has owned a work, which forgers often fake."]
  ]);

WB.L("opera-explained", "arts", "beginner", "Opera, explained: drama at full volume", "Opera combines music, theatre, poetry, costume and spectacle, and its singers fill huge halls without microphones. Here is how the most extravagant art form began and how to enjoy it.",
  [
    ["Reviving the Greeks, inventing something new", "Opera was born in Italy around 1600 from an attempt to recreate ancient Greek drama.", "In the late 1500s a group of scholars, poets and musicians in Florence, often called the Florentine Camerata, became fascinated by ancient Greek tragedy. They believed, partly correctly, that Greek plays had been sung or chanted rather than simply spoken, and they wanted to recreate that power. Their experiments in setting drama to music, with a single voice singing words clearly over simple accompaniment, led to the first operas around 1600. The earliest opera whose music still regularly reaches the stage is Claudio Monteverdi's L'Orfeo, first performed in Mantua in 1607, which retells the Greek myth of Orpheus, the musician who travels to the underworld to rescue his wife. Monteverdi brought together vivid storytelling, a large and colourful orchestra and memorable songs, and opera was on its way."],
    ["A night at the opera, Venice style", "Public opera houses turned opera from a court luxury into popular entertainment.", "Early operas were performed for princes at court celebrations. That changed in 1637, when the first public opera house opened in Venice and anyone who could buy a ticket could attend. Within decades Venice had several opera houses competing for audiences with spectacular stage machinery: flying gods, storms at sea and sudden scene changes. Opera became fashionable across Europe. Audiences behaved very differently from today's hushed crowds. They chatted, ate, played cards in their boxes and paid attention mostly during the big numbers sung by their favourite stars. In the Baroque era, some of the most celebrated stars were castrati, male singers castrated before puberty to preserve a high voice combined with adult lung power, a practice now regarded as cruel that finally died out in the nineteenth century."],
    ["The words you need", "A few terms make opera much easier to follow.", "Knowing a little vocabulary helps enormously. The libretto, meaning 'little book', is the text of the opera, written by a librettist, while the composer writes the music. Many operas begin with an overture, an orchestral piece that sets the mood before the curtain rises. Much of the story moves forward in recitative, a style of singing close to the rhythms of speech, often with light accompaniment, where plot and conversation happen. Then the action pauses for an aria, a song for a solo voice in which a character expresses feelings at length, and this is where singers show off. Duets, trios and larger ensembles let several characters sing at once, sometimes each with different words and emotions, something spoken theatre cannot easily do. The chorus represents crowds, soldiers, villagers or spirits."],
    ["Mozart, Verdi and the greats", "A handful of composers wrote many of the operas most often performed today.", "Wolfgang Amadeus Mozart, writing in the 1780s and early 1790s, gave opera some of its most human characters. The Marriage of Figaro is a comedy about servants outwitting their aristocratic master, Don Giovanni follows a charming seducer to a fiery end, and The Magic Flute mixes fairy tale, comedy and grand ideas. In the early nineteenth century Rossini, Bellini and Donizetti perfected bel canto, meaning 'beautiful singing', which showcased dazzling vocal agility. Then came Giuseppe Verdi, whose operas such as Rigoletto, La Traviata and Aida combine thrilling melodies with intense personal drama, and Giacomo Puccini, whose La Boheme, Tosca and Madama Butterfly remain among the most performed operas anywhere. Many opera companies' seasons still lean heavily on this core group, so they are good starting points."],
    ["Wagner's total artwork", "Richard Wagner reimagined opera on a vast scale, even designing his own theatre.", "The German composer Richard Wagner wanted opera to be a total work of art, uniting music, poetry, drama and stagecraft. His four-opera cycle The Ring of the Nibelung, drawing on Norse and Germanic myth, takes around fifteen hours to perform and is usually staged over several evenings. Wagner wove short musical themes, called leitmotifs, through the music to represent characters, objects and ideas, such as a sword or a curse, so the orchestra comments on the drama, a technique film composers later borrowed widely. He even built his own theatre at Bayreuth in Germany, which opened in 1876, with the orchestra hidden under the stage and the auditorium darkened during performances, practices that helped create the modern habit of sitting quietly in the dark. Wagner's antisemitic writings also make him a troubling figure."],
    ["How singers fill a hall without microphones", "Trained opera voices use resonance to cut through an orchestra.", "An opera singer may have to be heard over an orchestra of dozens of players in a theatre seating a couple of thousand people, all without a microphone. How? Part of the answer is training, years of developing breath control and an efficient, open throat. Another part is acoustics. Researchers have found that trained classical singers, particularly men, often produce a concentration of energy at high frequencies, around three thousand cycles per second, sometimes called the singer's formant. An orchestra is comparatively quiet in that range, and human ears are especially sensitive to it, so the voice carries over the instruments. Voices are classified by range and colour, from high to low: soprano, mezzo-soprano and contralto for women, and tenor, baritone and bass for men. Composers write roles for particular voice types."],
    ["Melba, Sutherland and opera in Australia", "Australia produced two of the most famous sopranos in history.", "Australia has a proud opera tradition. Helen Porter Mitchell, born in Melbourne in 1861, took the stage name Nellie Melba in honour of her home city and became one of the most celebrated sopranos in the world in the late nineteenth and early twentieth centuries. Peach Melba and Melba toast were named after her. Joan Sutherland, born in Sydney in 1926, became a superstar of bel canto opera, nicknamed La Stupenda, and the main opera theatre at the Sydney Opera House now bears her name. Today Opera Australia is the national company, and state companies perform around the country. If opera seems intimidating, remember that most performances now show translated text as surtitles projected above the stage, a practice that spread from the 1980s, so you can follow every word."]
  ],
  [
    [0, "What were the Florentine Camerata trying to recreate?", ["Medieval church music", "Ancient Greek drama", "Roman gladiator shows", "Folk songs of Tuscany"], 1, "They believed Greek tragedy had been sung and tried to recreate its power, leading to opera."],
    [1, "What happened in Venice in 1637?", ["Mozart was born", "The first opera was written", "The first public opera house opened", "Opera was banned"], 2, "The first public opera house meant anyone with a ticket could attend."],
    [2, "In an opera, what is an aria?", ["The text of the opera", "An orchestral introduction", "A song for a solo voice expressing a character's feelings", "Speech-like singing that moves the plot along"], 2, "Arias pause the action so a character can express emotions at length."],
    [4, "What is a leitmotif?", ["A short musical theme representing a character, object or idea", "A type of stage machinery", "A high note sung by a tenor", "An interval between acts"], 0, "Wagner used leitmotifs to let the orchestra comment on the drama."],
    [6, "Where did Nellie Melba's stage name come from?", ["Her favourite dessert", "Her teacher's surname", "A character in an opera", "Her home city of Melbourne"], 3, "Helen Porter Mitchell took the name Melba in honour of Melbourne."]
  ]);

WB.L("tuning-and-temperament", "arts", "advanced", "Why every piano is slightly out of tune", "Pythagoras discovered that beautiful harmonies follow simple number ratios. Then musicians discovered those ratios don't quite fit together. The compromise they reached shapes every song you hear.",
  [
    ["Pythagoras and the vibrating string", "Pleasing musical intervals correspond to simple ratios of frequencies.", "Legend credits the ancient Greek thinker Pythagoras with noticing that musical harmony follows numbers, although the story of him hearing blacksmiths' hammers is almost certainly myth. The basic discovery is real, and you can test it on a guitar. Pluck an open string, then press it exactly at the halfway point and pluck again: the note is an octave higher, because the vibrating length has halved and the frequency has doubled, a ratio of 2 to 1. Press a third of the way along, so that two thirds of the string vibrates, and you get a perfect fifth, a ratio of 3 to 2, the interval at the start of many familiar tunes. A ratio of 4 to 3 gives a perfect fourth, and 5 to 4 a major third. Simple ratios sound smooth and stable together."],
    ["Why simple ratios sound sweet", "Notes in simple ratios share overtones and avoid clashing beats.", "Why should simple ratios sound pleasant? Part of the answer lies in overtones. When a string or voice sounds a note, it vibrates not only at its main frequency but also at whole-number multiples of it, faint higher tones that give each instrument its colour. If two notes are in a simple ratio, many of their overtones line up exactly. When two tones are close but not quite matched, they interfere with each other and produce a regular wobble in loudness called beating. Play two notes that differ by two cycles per second and you hear the sound pulse twice a second. Piano tuners listen for exactly these beats, slowing them down or speeding them up to set each interval. Simple ratios produce little beating, so they sound calm and clear."],
    ["The comma that won't go away", "Stacking pure fifths never quite returns to the starting note.", "Here is the snag. Start on a C and go up by a pure fifth to G, then D, then A, and keep going. After twelve fifths you have passed through every note of the keyboard and should land back on a C, seven octaves above where you began. But the numbers do not agree. Twelve pure fifths multiply out to about 129.7 times the starting frequency, while seven octaves give exactly 128. The gap is called the Pythagorean comma. Musicians measure intervals in cents, with 100 cents in a modern semitone and 1200 in an octave, and the comma is about 23.5 cents, roughly a quarter of a semitone. It is a mathematical fact: no keyboard can have all its fifths and octaves perfectly pure at once."],
    ["Wolves and meantone", "Earlier tuning systems made some keys beautiful and others unusable.", "For centuries musicians juggled the problem by choosing which intervals to make pure. Pythagorean tuning kept fifths pure, but its major thirds sounded harsh. As music came to rely more on chords built from thirds, Renaissance musicians adopted meantone temperaments, which narrowed the fifths slightly so that the most common major thirds came out pure or close to pure. The sweetness came at a price. All the leftover error had to go somewhere, and it piled up in one fifth that sounded so out of tune it howled, earning the name the wolf fifth. Keys near the starting point sounded lovely, while distant keys with many sharps or flats were sour or unusable. Composers wrote within those limits, and changing key on a keyboard instrument could mean retuning it."],
    ["Bach and well temperament", "Well temperaments made every key usable while keeping each key's character.", "By the late seventeenth and early eighteenth centuries, musicians wanted the freedom to write in any key. Various well temperaments spread the comma unevenly across the fifths, so no interval howled and every key was playable, though common keys stayed sweeter and remote keys sounded more tense. Each key therefore had its own flavour, which may help explain why composers associated particular keys with particular moods. In 1722 Johann Sebastian Bach completed the first book of The Well-Tempered Clavier, twenty-four preludes and fugues, one in every major and minor key, and he later compiled a second book. The collection showed that a well-tuned keyboard could handle them all. Scholars still debate exactly which tuning Bach preferred, but most agree it was probably not the modern equal temperament many people assume."],
    ["Equal temperament wins", "Modern pianos divide the octave into twelve exactly equal steps.", "The solution most of the world uses today is equal temperament: divide the octave into twelve exactly equal semitones, so the frequency ratio of each step is the twelfth root of two, about 1.0595. The idea was worked out mathematically in the late 1500s by the Chinese scholar Zhu Zaiyu and, around the same period, by European thinkers such as the Flemish mathematician Simon Stevin. It became the standard for pianos during the nineteenth century. Every key now sounds the same, and you can change key freely. The price is that almost every interval is slightly impure. Fifths are about two cents narrow, barely noticeable, but major thirds are about fourteen cents wider than the pure 5 to 4 ratio, a shimmer that our ears have simply learned to accept as normal."],
    ["Beyond the twelve notes", "Singers and string players still bend pitches, and other traditions divide the octave differently.", "Musicians who are not stuck with fixed keys often drift back towards pure intervals. Choirs, barbershop quartets and string quartets tend to tune chords by ear, nudging thirds lower than a piano would play them so that the harmony rings. Even pianos are not perfectly equal: because thick piano strings are stiff, their overtones run slightly sharp, so tuners stretch the octaves a little wider, especially at the extremes of the keyboard. The international standard for concert pitch sets the A above middle C at 440 cycles per second, although some orchestras tune slightly higher. Other musical cultures make different choices altogether. Indonesian gamelan uses scales that do not match Western steps, and Arabic music uses intervals that fall between the piano's keys. The twelve-note piano is one solution, not the only one."]
  ],
  [
    [0, "What frequency ratio produces an octave?", ["3 to 2", "2 to 1", "4 to 3", "5 to 4"], 1, "Halving a string's length doubles its frequency, giving an octave."],
    [1, "What are 'beats' in tuning?", ["The rhythm of a piece", "The hammers inside a piano", "A regular wobble in loudness when two tones are slightly mismatched", "The number of notes in a scale"], 2, "Slightly mismatched frequencies interfere, producing a pulsing that tuners listen for."],
    [2, "What is the Pythagorean comma?", ["The small gap between twelve pure fifths and seven octaves", "A pause marked in sheet music", "The interval between two piano keys", "A type of Greek lyre"], 0, "Twelve pure fifths overshoot seven octaves by about 23.5 cents."],
    [3, "What was the 'wolf fifth'?", ["A fifth played very loudly", "A tuning fork used by wolves in folk tales", "A fifth used only in church music", "One badly out-of-tune fifth where the leftover error piled up"], 3, "In meantone tuning, the accumulated error made one fifth howl, giving it the name."],
    [5, "In equal temperament, how do major thirds compare with the pure 5 to 4 ratio?", ["They are exactly pure", "They are about fourteen cents wide", "They are about two cents narrow", "They are a full semitone flat"], 1, "Equal-tempered major thirds are about fourteen cents wider than pure ones."]
  ]);
