/* WISEBYTE LESSONS · Life Skills (part 2): people and productivity */
WB.LESSONS.push(
{
  id: "public-speaking", audience: "adult", cat: "life", level: "intermediate",
  popularity: 76, added: "2026-09-13",
  title: "Speak with confidence",
  hook: "The nerves never fully go away, even for professionals. These habits make them work for you.",
  sections: [
    { h: "Nerves are normal", key: "Fear of public speaking is extremely common; the body's stress response is natural.",
      b: "Fear of public speaking is one of the most common fears there is; surveys regularly rank it alongside heights and spiders. The racing heart, dry mouth, shaky hands and sweaty palms are your body's fight-or-flight response, releasing adrenaline to prepare you for action. Even experienced speakers, actors and politicians feel it. The goal isn't to eliminate nerves but to manage them, and to understand that the audience notices them far less than you think, an effect psychologists call the illusion of transparency." },
    { h: "Reframe it as excitement", key: "Telling yourself you're excited, rather than trying to calm down, can improve performance.",
      b: "Anxiety and excitement feel remarkably similar in the body: both involve a racing heart and a surge of energy. Harvard researcher Alison Wood Brooks found that people who said 'I am excited' out loud before a speech or a stressful task performed better than those who tried to tell themselves to calm down. Calming down is hard when your body is revved up. Relabelling the feeling as excitement is easier and channels the energy into enthusiasm. Slow breathing, with long exhales, also helps settle the body." },
    { h: "One big idea", key: "Build the talk around one clear message you can say in a sentence.",
      b: "Audiences remember surprisingly little of what they hear. Decide the single message you want people to leave with, and build everything around it. If you can't say it in one sentence, it isn't clear yet, to you or to them. Then cut ruthlessly: anything that doesn't support the big idea is a distraction, however interesting. Most talks improve by being shorter. Nobody has ever complained that a good presentation finished five minutes early." },
    { h: "Structure and stories", key: "Tell them what you'll say, say it, sum up; stories and examples beat lists of facts.",
      b: "A simple structure works for almost any talk: open with a hook that grabs attention, like a question, a surprising fact or a short story; tell them what you'll cover; cover it in two or three main points; then sum up and finish with a clear takeaway or call to action. Stories and concrete examples stick far better than lists of facts or abstract ideas, because our brains are wired for narrative. One vivid example often does more than ten statistics." },
    { h: "Slides that help", key: "Slides should support you, not be your script: few words, big visuals.",
      b: "Slides should support what you're saying, not repeat it. People can't read dense text and listen to you at the same time, so they'll end up doing neither well. Use few words, large fonts, and images or simple charts that make a point at a glance. One idea per slide is a good rule. Never read your slides aloud. If the projector died, you should still be able to give the talk; if you couldn't, you're relying on the slides too much." },
    { h: "Practise out loud", key: "Rehearse aloud, standing, and record yourself once to spot filler words.",
      b: "Reading your notes silently is not practice. Rehearse the whole talk out loud, ideally standing up, at least three times. Time it; most people run long. Record yourself once on your phone and watch it back. It's uncomfortable, but you'll spot filler words like 'um', 'like' and 'you know', nervous habits like swaying, and the parts where you rush. Know your opening lines especially well, since that's when nerves peak; after the first minute, most people settle." },
    { h: "Pause and slow down", key: "Deliberate pauses sound confident and replace filler words.",
      b: "Nervous speakers rush. Deliberately slow down, and use pauses: before an important point, after a question, when moving to a new section. A pause feels like an eternity to you but reads as confidence to the audience, gives them time to think and naturally replaces filler words. Look at real people, one at a time, for a sentence or so each, rather than scanning the back wall or staring at your notes. Friendly faces help; find a few and return to them." },
    { h: "Handling questions and mistakes", key: "Repeat questions, it's fine to say 'I don't know', and keep going after a slip.",
      b: "When taking questions, repeat or paraphrase each question so everyone hears it and you gain a moment to think. It's perfectly fine to say, 'I don't know, but I'll find out and get back to you.' If you lose your place or make a mistake, pause, glance at your notes and carry on; audiences rarely notice and are almost always on your side. Every talk you give makes the next one easier, so look for low-stakes chances to practise, like team meetings or a Toastmasters club." },
  ],
  quiz: [
    { s: 1, q: "What can help with nerves before a talk, according to research?", o: ["Telling yourself to calm down", "Reframing the nerves as excitement", "Skipping practice", "Speaking faster"], a: 1, e: "Anxiety and excitement feel similar in the body." },
    { s: 2, q: "How many core messages should a talk aim for?", o: ["One clear big idea", "As many as possible", "At least ten", "None"], a: 0, e: "One idea people can remember." },
    { s: 4, q: "What makes a good slide?", o: ["Lots of text so you can read it", "Few words and a clear visual", "Every detail of your talk", "Small fonts to fit more"], a: 1, e: "Slides should support you, not be your script." },
    { s: 5, q: "Why record yourself practising?", o: ["To spot filler words and rushed parts", "To post it online", "It's required", "To memorise every word"], a: 0, e: "You'll hear what the audience hears." },
    { s: 6, q: "What does a deliberate pause do?", o: ["Makes you look lost", "Makes you sound confident and replaces filler words", "Wastes time", "Confuses people"], a: 1, e: "Pauses signal control." },
  ],
  related: ["communication", "negotiation"],
},
{
  id: "communication", audience: "adult", cat: "life", level: "beginner",
  popularity: 88, added: "2026-09-24",
  title: "How to really listen (and be heard)",
  hook: "Most arguments aren't about what they seem to be about. Better communication starts with listening.",
  sections: [
    { h: "Listening to reply", key: "Most people listen to reply rather than to understand.",
      b: "In most conversations, we're not really listening. We're waiting for our turn to talk, planning our response, or relating everything back to ourselves. Author Stephen Covey put it simply: most people listen with the intent to reply, not to understand. The other person can tell. Feeling genuinely heard is one of the most powerful things you can give someone, and it's the foundation for resolving disagreements, building trust and being heard in return." },
    { h: "Active listening", key: "Active listening means full attention, reflecting back what you heard and asking open questions.",
      b: "Active listening is a set of simple skills. Give your full attention: phone away, eye contact, no interrupting. Reflect back what you heard in your own words: 'So you're frustrated because you felt left out of the decision?' This shows you understood and lets them correct you if you didn't. Ask open questions that start with what, how or tell me, rather than yes-or-no questions. And resist the urge to jump in with solutions; often people want to be understood before they want advice." },
    { h: "Name the feeling", key: "Acknowledging emotions ('That sounds really stressful') calms conversations.",
      b: "Emotions drive most difficult conversations. Simply naming what someone seems to feel, like 'That sounds really stressful' or 'You seem disappointed', tends to lower the temperature. Brain-imaging research by psychologist Matthew Lieberman found that putting feelings into words reduced activity in the amygdala, a brain region involved in threat responses. You don't have to agree with someone to acknowledge how they feel. Validation says 'your feelings make sense', not 'you're right'." },
    { h: "'I' statements", key: "'I' statements describe your experience without blaming, making defensiveness less likely.",
      b: "When raising a problem, how you start matters. 'You never help around the house' is an attack, and the other person will defend themselves. An 'I' statement describes your experience instead: 'I feel overwhelmed when I do the dishes every night on my own. Could we take turns?' A useful formula: I feel [emotion] when [specific situation], because [why it matters]. Could we [specific request]? It focuses on behaviour and needs, not character." },
    { h: "The four horsemen", key: "Criticism, contempt, defensiveness and stonewalling predict relationship breakdown.",
      b: "Psychologist John Gottman studied thousands of couples and identified four communication patterns he called the four horsemen, because they predict relationship breakdown. Criticism attacks the person rather than the behaviour. Contempt, including sarcasm, eye-rolling and mockery, is the most damaging of all. Defensiveness means making excuses and refusing responsibility. Stonewalling is shutting down and withdrawing. The antidotes: complain without blame, express appreciation, take responsibility for your part, and take a break to calm down." },
    { h: "Take a break", key: "When flooded with emotion, pause for 20+ minutes before continuing.",
      b: "When an argument escalates, your heart rate climbs and your body floods with stress hormones. In this state, called flooding, it's very hard to think clearly or listen, and people say things they regret. Gottman's research suggests taking a break of at least 20 minutes, doing something calming, not rehearsing your arguments. Agree on a time to come back to it. Pausing isn't avoiding the issue; it's giving both of you the chance to discuss it productively." },
    { h: "Giving feedback", key: "Use Situation–Behaviour–Impact: specific, factual and about effects, not character.",
      b: "Feedback at work or home lands better when it's specific. The Situation–Behaviour–Impact model is simple. Describe the situation: 'In this morning's meeting…'. Describe the specific behaviour, not your interpretation: '…you interrupted Sam twice while she was presenting…'. Then the impact: '…and she didn't finish her point, so we missed her idea.' Then ask for their view. Give positive feedback the same way; 'Great job' is nice, but specific praise tells people what to repeat." },
    { h: "Small habits, big difference", key: "Put the phone away, remember details, and express appreciation often.",
      b: "Good communication is built from small habits. Put your phone out of sight in conversations; research suggests even a visible phone can make conversations feel less close. Remember details people tell you and ask about them later. Express appreciation out loud and often; Gottman found that stable couples have around five positive interactions for every negative one during conflict. And when you get it wrong, which everyone does, a sincere, specific apology without 'but' goes a long way." },
  ],
  quiz: [
    { s: 1, q: "Which is a key part of active listening?", o: ["Planning your reply while they talk", "Reflecting back what you heard", "Giving advice immediately", "Checking your phone"], a: 1, e: "Reflecting shows you understood and lets them correct you." },
    { s: 3, q: "Which is an 'I' statement?", o: ["You never help", "I feel overwhelmed when I do the dishes alone", "You're so lazy", "Why can't you ever listen?"], a: 1, e: "It describes your experience without blame." },
    { s: 4, q: "What does Gottman suggest as the antidote to criticism?", o: ["Stonewalling until it blows over", "Complaining about the behaviour without blaming the person", "Using sarcasm to lighten the mood", "Listing their past mistakes"], a: 1, e: "Criticism attacks the person; a complaint without blame focuses on the behaviour." },
    { s: 5, q: "How long a break does Gottman suggest when flooded with emotion?", o: ["30 seconds", "At least 20 minutes", "A week", "None"], a: 1, e: "Enough for your body to calm down." },
    { s: 6, q: "In the SBI feedback model, what does the 'B' stand for?", o: ["Blame", "Behaviour", "Belief", "Bias"], a: 1, e: "Situation, Behaviour, Impact." },
  ],
  related: ["negotiation", "public-speaking"],
},
{
  id: "time-management", audience: "adult", cat: "life", level: "beginner",
  popularity: 90, added: "2026-09-24",
  title: "Time management that works",
  hook: "You can't make more time. But you can stop losing it to the wrong things.",
  sections: [
    { h: "Urgent vs important", key: "The Eisenhower matrix sorts tasks by urgency and importance; important-not-urgent work matters most.",
      b: "In a 1954 speech, US President Dwight Eisenhower quoted a former college president: 'I have two kinds of problems, the urgent and the important. The urgent are not important, and the important are never urgent.' The Eisenhower matrix sorts tasks into four boxes. Urgent and important: do it now (a crisis, a deadline). Important but not urgent: schedule it (exercise, planning, relationships, learning). Urgent but not important: delegate or minimise (most interruptions and many emails). Neither: drop it. Most people live in the urgent boxes. The biggest gains come from protecting time for important-but-not-urgent work." },
    { h: "Work expands to fill time", key: "Parkinson's law: work expands to fill the time available, so set tighter limits.",
      b: "In 1955, British historian C. Northcote Parkinson wrote that 'work expands so as to fill the time available for its completion.' Give yourself a week to write a report and it takes a week; give yourself a day and it often takes a day. Setting your own shorter deadlines, or timeboxing, allocating a fixed block of time to a task, uses this to your advantage. It also helps to decide what 'good enough' looks like before you start, so perfectionism doesn't swallow the extra time." },
    { h: "We're bad at estimating", key: "The planning fallacy makes us underestimate how long tasks take; add a buffer.",
      b: "Psychologists Daniel Kahneman and Amos Tversky named the planning fallacy: we consistently underestimate how long tasks will take, even when we know similar tasks took longer in the past. We imagine the best-case scenario and forget interruptions and problems. Sydney's Opera House is the classic example: due to open in early 1963, it opened in 1973, ten years late and hugely over budget. Fix it by checking how long similar tasks actually took and adding a buffer, often 50% or more." },
    { h: "Time blocking", key: "Schedule your important tasks in your calendar like appointments.",
      b: "A to-do list tells you what to do, not when. Time blocking means scheduling your tasks in your calendar as if they were meetings: 9 to 10.30 am, write proposal; 2 to 2.30 pm, emails. It forces you to confront how much time you really have, reduces decision fatigue and protects focus. Put your most demanding work in your peak energy hours; for many people that's the morning. Leave buffer blocks for the unexpected, because something always comes up." },
    { h: "Protect your focus", key: "Multitasking is task-switching, and each switch costs time and focus.",
      b: "Multitasking is mostly a myth. The brain doesn't do two demanding things at once; it switches between them, and each switch costs time and attention. Research on interruptions suggests it can take many minutes to fully refocus on a complex task after a distraction. Batch similar small tasks, like emails and calls, into set times rather than responding to every notification. Turn off non-essential alerts. Even an hour of genuinely uninterrupted work can achieve more than a whole distracted afternoon." },
    { h: "The two-minute rule", key: "If something takes less than two minutes, do it now.",
      b: "David Allen, author of Getting Things Done, suggests a simple rule: if a task takes less than two minutes, do it immediately rather than writing it down or putting it off. Reply to the quick email, file the document, book the appointment. It stops small tasks piling up into a mental burden. Allen's broader insight is that your mind is for having ideas, not holding them: capture every task in one trusted list or app so your brain can stop trying to remember everything." },
    { h: "Learn to say no", key: "Every yes is a no to something else; protect time for your priorities.",
      b: "Every time you say yes to something, you're saying no to something else, even if you don't notice it. Before agreeing to a new commitment, ask what it will replace. You can decline politely without a long excuse: 'Thanks for thinking of me, but I can't take that on right now.' Some people use a rule: if it's not a clear yes, it's a no. Saying no to less important things is how you make room for what matters most to you." },
    { h: "The weekly review", key: "A short weekly review keeps your plans on track and your mind clear.",
      b: "Once a week, often Friday afternoon or Sunday evening, spend 20 to 30 minutes reviewing. Look at what you got done, what's still open and what's coming up. Clear your inboxes and notes into your task list. Choose your three most important priorities for the next week and block time for them. It's a small investment that stops tasks slipping through the cracks and turns vague stress into a clear plan. Many productive people say it's their single most useful habit." },
  ],
  quiz: [
    { s: 0, q: "In the Eisenhower matrix, what should you do with important but not urgent tasks?", o: ["Drop them", "Schedule them", "Delegate them", "Do them instantly"], a: 1, e: "These tasks deliver the biggest long-term gains." },
    { s: 1, q: "What does Parkinson's law say?", o: ["Work expands to fill the time available", "Work always takes two hours", "Deadlines don't matter", "Teams are faster than individuals"], a: 0, e: "Tighter time limits can make you more efficient." },
    { s: 2, q: "What is the planning fallacy?", o: ["Planning too much", "Underestimating how long tasks will take", "Refusing to plan", "Planning only on Mondays"], a: 1, e: "The Sydney Opera House ran ten years late." },
    { s: 4, q: "What really happens when you 'multitask' on demanding work?", o: ["You do both perfectly", "You switch between tasks, losing time and focus", "You work twice as fast", "Nothing"], a: 1, e: "Each switch has a cost." },
    { s: 5, q: "What is the two-minute rule?", o: ["Take a two-minute break every hour", "If a task takes under two minutes, do it now", "Work for two minutes at a time", "Reply to emails in two minutes"], a: 1, e: "It stops small tasks piling up." },
  ],
  related: ["procrastination", "habits"],
},
);
