/* WISEBYTE THINK & TEST CONTENT (part 2) */
WB.GK.push(
  // Geography
  { cat: "geography", q: "Which is the largest country in the world by area?", o: ["Canada", "China", "Russia", "Australia"], a: 2, e: "Russia covers about 17 million square kilometres, over twice the size of Australia." },
  { cat: "geography", q: "Which continent has the most countries?", o: ["Asia", "Europe", "Africa", "South America"], a: 2, e: "Africa has 54 countries recognised by the United Nations." },
  { cat: "geography", q: "The Strait of Gibraltar separates Europe from which continent?", o: ["Asia", "Africa", "North America", "Antarctica"], a: 1, e: "At its narrowest it's only about 14 km between Spain and Morocco." },
  { cat: "geography", q: "What is the world's deepest lake?", o: ["Lake Superior", "Lake Tanganyika", "Lake Baikal", "Crater Lake"], a: 2, e: "Siberia's Lake Baikal is over 1,600 metres deep and holds roughly a fifth of the world's unfrozen fresh surface water." },
  { cat: "geography", q: "Counting its overseas territories, which country has the most time zones?", o: ["Russia", "United States", "France", "China"], a: 2, e: "With territories scattered around the globe, France spans 12 time zones." },
  // History
  { cat: "history", q: "Which ship carried the Pilgrims from England to America in 1620?", o: ["Endeavour", "Mayflower", "Santa María", "Golden Hind"], a: 1, e: "Its passengers founded Plymouth Colony, in what is now Massachusetts." },
  { cat: "history", q: "Mansa Musa, often called one of the richest people in history, ruled which West African empire?", o: ["Songhai", "Mali", "Ghana", "Benin"], a: 1, e: "His 1324 pilgrimage to Mecca reportedly handed out so much gold that its value in Cairo fell for years." },
  { cat: "history", q: "Who was the first woman to win a Nobel Prize?", o: ["Florence Nightingale", "Marie Curie", "Rosalind Franklin", "Ada Lovelace"], a: 1, e: "Marie Curie shared the 1903 Physics prize, then won Chemistry in 1911." },
  { cat: "history", q: "The temple complex of Angkor Wat, the world's largest religious monument, is in which country?", o: ["Thailand", "Cambodia", "Vietnam", "Myanmar"], a: 1, e: "Built by the Khmer Empire in the early 1100s as a Hindu temple, it later became Buddhist and now appears on Cambodia's flag." },
  { cat: "history", q: "Who was the first woman to fly solo across the Atlantic?", o: ["Amy Johnson", "Amelia Earhart", "Nancy Bird Walton", "Bessie Coleman"], a: 1, e: "Amelia Earhart made the flight in 1932." },
  // Science
  { cat: "science", q: "Which pigment gives human skin, hair and eyes their colour?", o: ["Chlorophyll", "Melanin", "Keratin", "Haemoglobin"], a: 1, e: "People have roughly the same number of melanin-making cells. Skin colour depends on how much melanin those cells produce." },
  { cat: "science", q: "At sea level, at what temperature does water boil?", o: ["50°C", "100°C", "150°C", "212°C"], a: 1, e: "100°C, though it boils at lower temperatures up mountains where air pressure is lower." },
  { cat: "science", q: "What is the most abundant metal in Earth's crust?", o: ["Iron", "Aluminium", "Copper", "Gold"], a: 1, e: "Aluminium makes up about 8% of the crust by mass. Only oxygen and silicon are more abundant overall." },
  { cat: "science", q: "Roughly how fast does sound travel through air?", o: ["About 34 km/h", "About 1,200 km/h", "About 12,000 km/h", "About 300,000 km per second"], a: 1, e: "About 343 metres per second. To estimate a storm's distance, count the seconds between lightning and thunder and divide by 3 for kilometres." },
  // Technology
  { cat: "technology", q: "What does 'VPN' stand for?", o: ["Very Private Number", "Virtual Private Network", "Verified Public Node", "Virtual Protected Name"], a: 1, e: "A VPN encrypts your connection and routes it through another server, which is useful on public Wi-Fi." },
  { cat: "technology", q: "What does 'AI' stand for?", o: ["Automated input", "Artificial intelligence", "Advanced information", "Algorithmic integration"], a: 1, e: "Artificial intelligence: computers doing tasks that normally need human thinking." },
  { cat: "technology", q: "What is a CAPTCHA test designed to check?", o: ["Your internet speed", "That you're a human, not a bot", "How strong your password is", "Your age"], a: 1, e: "The name stands for 'Completely Automated Public Turing test to tell Computers and Humans Apart'." },
  { cat: "technology", q: "What does 'URL' stand for?", o: ["Universal Resource Link", "Uniform Resource Locator", "User Reference Line", "Unified Routing Language"], a: 1, e: "A URL is the address of a resource on the web." },
  { cat: "technology", q: "What is 'phishing'?", o: ["A way to speed up Wi-Fi", "Fake messages that trick you into giving away information", "A type of computer virus scanner", "Backing up files"], a: 1, e: "Phishers pose as banks, delivery companies or government agencies to steal logins and money." },
  // Space
  { cat: "space", q: "How many planets are in our solar system?", o: ["7", "8", "9", "10"], a: 1, e: "Eight. Neptune, the farthest, takes about 165 years to orbit the Sun once." },
  { cat: "space", q: "After the Sun, which star is closest to Earth?", o: ["Sirius", "Proxima Centauri", "Betelgeuse", "Polaris"], a: 1, e: "Proxima Centauri is about 4.2 light-years away." },
  { cat: "space", q: "Which planet has the most prominent ring system?", o: ["Mars", "Jupiter", "Saturn", "Mercury"], a: 2, e: "Saturn's rings are made mostly of chunks of ice and rock." },
  { cat: "space", q: "In 2003, which country became the third to launch a person into space on its own rocket?", o: ["India", "Japan", "China", "France"], a: 2, e: "Yang Liwei orbited Earth in Shenzhou 5, after the Soviet Union and the United States, both in 1961." },
  { cat: "space", q: "What is a 'shooting star'?", o: ["A star falling from the sky", "A small space rock burning up in Earth's atmosphere", "A comet's tail", "A satellite reflecting sunlight"], a: 1, e: "Most are no bigger than a grain of sand. Any piece that survives to reach the ground is called a meteorite." },
  // Animals
  { cat: "animals", q: "What is the tallest animal?", o: ["Elephant", "Giraffe", "Camel", "Moose"], a: 1, e: "Giraffes can grow to over 5 metres tall." },
  { cat: "animals", q: "What do we call an animal that eats only plants?", o: ["Carnivore", "Omnivore", "Herbivore", "Insectivore"], a: 2, e: "Herbivores like kangaroos and koalas eat plants." },
  { cat: "animals", q: "What is a group of lions called?", o: ["A pack", "A pride", "A herd", "A flock"], a: 1, e: "A pride usually includes several related females, their cubs and a few males." },
  { cat: "animals", q: "What is the largest living lizard?", o: ["Perentie", "Komodo dragon", "Green iguana", "Nile monitor"], a: 1, e: "Komodo dragons can reach about 3 metres and live on a handful of Indonesian islands." },
  { cat: "animals", q: "Koalas mainly eat the leaves of which trees?", o: ["Pine", "Eucalyptus (gum trees)", "Palm", "Oak"], a: 1, e: "Gum leaves are low in energy, which is one reason koalas sleep around 18 to 22 hours a day." },
  // Human body
  { cat: "body", q: "What do red blood cells carry around your body?", o: ["Oxygen", "White blood cells", "Antibodies", "Insulin"], a: 0, e: "They use a protein called haemoglobin to carry oxygen from your lungs." },
  { cat: "body", q: "Which organs filter your blood to make urine?", o: ["Lungs", "Liver", "Kidneys", "Stomach"], a: 2, e: "Your two kidneys filter around 180 litres of blood plasma a day." },
  { cat: "body", q: "What is the longest bone in the human body?", o: ["Spine", "Femur (thigh bone)", "Humerus", "Tibia"], a: 1, e: "The femur is also one of the strongest bones." },
  { cat: "body", q: "Roughly how much of an adult's body weight is water?", o: ["About 20%", "About 40%", "About 60%", "About 90%"], a: 2, e: "Around 60%, though it varies with age and body composition." },
  { cat: "body", q: "What are the tiny air sacs in your lungs, where oxygen passes into your blood, called?", o: ["Alveoli", "Bronchi", "Capillaries", "Villi"], a: 0, e: "You have hundreds of millions of them, with a combined surface area of around 70 square metres." },
  // Culture
  { cat: "culture", q: "Which instrument usually has 88 keys?", o: ["Guitar", "Piano", "Violin", "Trumpet"], a: 1, e: "52 white keys and 36 black keys." },
  { cat: "culture", q: "Which country gave the Statue of Liberty to the United States?", o: ["United Kingdom", "Spain", "France", "Italy"], a: 2, e: "It was a gift from the people of France, dedicated in 1886." },
  { cat: "culture", q: "Swahili is widely spoken in which part of the world?", o: ["West Africa", "East Africa", "South Asia", "South America"], a: 1, e: "It is an official language of Kenya, Tanzania and Uganda, and tens of millions more speak it as a second language." },
  { cat: "culture", q: "Chinese New Year is also known as what?", o: ["The Moon Festival", "The Spring Festival", "The Lantern Festival", "The Dragon Boat Festival"], a: 1, e: "It follows the lunar calendar, so the date changes each year." },
  // Economics
  { cat: "economics", q: "What is 'stagflation'?", o: ["Rapid growth with falling prices", "High inflation combined with weak growth and high unemployment", "A share market crash", "A long period of stable prices"], a: 1, e: "The word blends 'stagnation' and 'inflation'. Many economies suffered it after the 1970s oil shocks." },
  { cat: "economics", q: "What is 'bracket creep'?", o: ["When tax brackets are cut every year", "When pay rises push more of your income into higher tax brackets, even if they only keep up with inflation", "A slow rise in interest rates", "When prices creep up after a sale"], a: 1, e: "Australia's income tax thresholds aren't automatically indexed to inflation, so governments periodically cut taxes to hand some of it back." },
  { cat: "economics", q: "What is 'shrinkflation'?", o: ["When prices fall because demand shrinks", "When a product gets smaller but its price stays the same", "When the economy shrinks during inflation", "When wages shrink after tax"], a: 1, e: "A chocolate block that quietly drops from 200 g to 180 g at the same price is a hidden 11% price rise." },
  { cat: "economics", q: "What does 'ASX' stand for?", o: ["Australian Stock Index", "Australian Securities Exchange", "Asian Stock Exchange", "Australian Savings Exchange"], a: 1, e: "It's Australia's main stock exchange, based in Sydney." },
  { cat: "economics", q: "If a savings account pays interest, who pays whom?", o: ["You pay the bank", "The bank pays you", "The government pays the bank", "No one pays"], a: 1, e: "The bank pays you for letting it use your money." },
  // Australia
  { cat: "australia", q: "Which is Australia's largest state by area?", o: ["Queensland", "New South Wales", "Western Australia", "South Australia"], a: 2, e: "Western Australia covers about a third of the continent." },
  { cat: "australia", q: "Which Australian state is an island?", o: ["Victoria", "Tasmania", "Queensland", "South Australia"], a: 1, e: "Tasmania is a bit smaller than Ireland, and more than 40% of it is protected in parks and reserves." },
  { cat: "australia", q: "What is Australia's national floral emblem?", o: ["Waratah", "Golden wattle", "Kangaroo paw", "Banksia"], a: 1, e: "National Wattle Day is celebrated on 1 September." },
  { cat: "australia", q: "What is Australia's largest lake (when it fills)?", o: ["Lake Burley Griffin", "Kati Thanda–Lake Eyre", "Lake Macquarie", "Lake Argyle"], a: 1, e: "In South Australia, it's usually a dry salt pan and fills completely only rarely." },
  { cat: "australia", q: "In 1943, who became the first woman elected to the federal House of Representatives?", o: ["Edith Cowan", "Enid Lyons", "Dorothy Tangney", "Vida Goldstein"], a: 1, e: "At the same election Dorothy Tangney became the first woman in the Senate. Edith Cowan had been the first woman in any Australian parliament, in WA in 1921." },
  // Sport
  { cat: "sport", q: "How many players does a netball team have on court?", o: ["5", "6", "7", "9"], a: 2, e: "Seven, each restricted to certain zones of the court." },
  { cat: "sport", q: "In golf, what is one stroke under par called?", o: ["Bogey", "Birdie", "Eagle", "Albatross"], a: 1, e: "An eagle is two under and an albatross three under." },
  { cat: "sport", q: "How long is a marathon?", o: ["21.1 km", "30 km", "42.195 km", "50 km"], a: 2, e: "The odd distance was standardised after the 1908 London Olympics." },
  { cat: "sport", q: "In which sport would you see a slam dunk?", o: ["Cricket", "Basketball", "Tennis", "Swimming"], a: 1, e: "A slam dunk is when a player jumps and pushes the ball straight down through the hoop." },
  { cat: "sport", q: "Cathy Freeman won gold at the Sydney 2000 Olympics in which event?", o: ["100 m", "200 m", "400 m", "800 m"], a: 2, e: "She won the 400 m final in front of about 110,000 people." },
  // Art
  { cat: "art", q: "Which Dutch artist painted Girl with a Pearl Earring?", o: ["Rembrandt", "Johannes Vermeer", "Vincent van Gogh", "Piet Mondrian"], a: 1, e: "Vermeer painted it around 1665." },
  { cat: "art", q: "Which Dutch artist painted The Night Watch?", o: ["Johannes Vermeer", "Rembrandt", "Frans Hals", "Hieronymus Bosch"], a: 1, e: "Completed in 1642, it's more than 4 metres wide and hangs in Amsterdam's Rijksmuseum." },
  { cat: "art", q: "Which Australian artist painted a famous series about Ned Kelly?", o: ["Sidney Nolan", "Albert Namatjira", "Tom Roberts", "Margaret Preston"], a: 0, e: "Nolan painted the series in the 1940s, showing Kelly in his black box-like helmet." },
  { cat: "art", q: "Pablo Picasso co-founded which art movement?", o: ["Impressionism", "Cubism", "Surrealism", "Pop Art"], a: 1, e: "He developed Cubism with Georges Braque in the early 1900s." },
  // Literature
  { cat: "literature", q: "Who wrote To Kill a Mockingbird?", o: ["Harper Lee", "John Steinbeck", "Mark Twain", "Toni Morrison"], a: 0, e: "Published in 1960, it won the Pulitzer Prize." },
  { cat: "literature", q: "Which Charles Dickens story features Ebenezer Scrooge?", o: ["Oliver Twist", "Great Expectations", "A Christmas Carol", "David Copperfield"], a: 2, e: "Published in 1843, it helped shape how Christmas is celebrated." },
  { cat: "literature", q: "Who wrote the poem 'My Country', which includes 'I love a sunburnt country'?", o: ["Henry Lawson", "Banjo Paterson", "Dorothea Mackellar", "Judith Wright"], a: 2, e: "Mackellar wrote it while homesick in England; it was first published in 1908." },
  { cat: "literature", q: "Who wrote and illustrated The Magic Pudding?", o: ["May Gibbs", "Norman Lindsay", "Mem Fox", "Roald Dahl"], a: 1, e: "Published in 1918, it's about a grumpy pudding that never runs out." },
  { cat: "literature", q: "Who wrote Frankenstein?", o: ["Bram Stoker", "Mary Shelley", "Edgar Allan Poe", "Jane Austen"], a: 1, e: "She began it as a teenager; it was published in 1818 and is often called the first science-fiction novel." },
);

WB.CLAIMS.push(
  { c: "The Eiffel Tower can grow around 15 cm taller in hot weather.", t: true, e: "Iron expands when heated, so the tower's height changes with the temperature." },
  { c: "Mosquitoes kill more people each year than any other animal.", t: true, e: "They spread malaria, dengue and other diseases that kill hundreds of thousands of people a year." },
  { c: "You lose most of your body heat through your head.", t: false, e: "Your head loses heat roughly in proportion to its surface area, only around 10%. Cover up everywhere." },
  { c: "Australia is wider than the Moon.", t: true, e: "Australia is about 4,000 km from east to west; the Moon is about 3,475 km across." },
  { c: "Elephants drink through their trunks like a straw.", t: false, e: "They suck several litres of water up into the trunk, then squirt it into their mouths." },
  { c: "Ostriches bury their heads in the sand when scared.", t: false, e: "They lie flat or run. They do turn their eggs in ground nests, which may have started the myth." },
  { c: "Tomatoes are fruits.", t: true, e: "Botanically, a fruit contains seeds. Cooks treat tomatoes as vegetables." },
  { c: "Dogs can only see in black and white.", t: false, e: "Dogs see some colours, mainly blues and yellows, but not reds and greens the way we do." },
  { c: "Old windows are thicker at the bottom because glass slowly flows.", t: false, e: "Old glass was made unevenly, and builders often put the thick edge at the bottom. Glass doesn't flow noticeably." },
  { c: "Fortune cookies were invented in China.", t: false, e: "They were popularised in California in the early 1900s, probably adapted from a Japanese cracker, and are rarely seen in China." },
  { c: "You should wait 30 minutes after eating before swimming.", t: false, e: "There's no good evidence that eating before swimming causes dangerous cramps." },
  { c: "Shaving makes hair grow back thicker and darker.", t: false, e: "Shaving cuts hair at a blunt angle so it feels coarser, but it doesn't change thickness, colour or growth rate." },
  { c: "Touching a toad gives you warts.", t: false, e: "Warts are caused by a human virus (HPV). A toad's bumpy skin can't pass them on, though some toads, like cane toads, have toxins, so wash your hands." },
  { c: "Sound travels faster through water than through air.", t: true, e: "About four times faster, because water molecules are packed more closely." },
  { c: "A lightning bolt is hotter than the surface of the Sun.", t: true, e: "Lightning can heat the air to around 30,000°C; the Sun's surface is about 5,500°C." },
  { c: "Most of the oxygen we breathe comes from the Amazon rainforest.", t: false, e: "Ocean plankton produce around half of Earth's oxygen, and the Amazon uses up most of what it produces." },
  { c: "Going out with wet hair in the cold gives you a cold.", t: false, e: "Colds are caused by viruses, so you can't catch one without being exposed. Some research suggests a chill may help a virus you already carry take hold, and cold weather keeps people indoors together, where viruses spread." },
  { c: "The Atlantic Ocean is saltier than the Pacific.", t: true, e: "On average, yes. Winds carry moisture evaporated from the Atlantic across Central America, where it falls as rain on the Pacific." },
  { c: "An Australian turtle can breathe through its bottom.", t: true, e: "The Fitzroy River turtle in Queensland absorbs oxygen from water through its cloaca, letting it stay underwater for long periods." },
  { c: "Reading in dim light permanently damages your eyesight.", t: false, e: "It can cause temporary eye strain, but there's no evidence of lasting damage." },
  { c: "The Moon has no gravity.", t: false, e: "The Moon's gravity is about one-sixth of Earth's. It's also the main cause of our ocean tides." },
  { c: "Diamonds are made of carbon, the same element as pencil graphite.", t: true, e: "The difference is how the carbon atoms are arranged." },
  { c: "The Sun is yellow.", t: false, e: "The Sun gives off all colours of light, which mix to make white. From space it looks white; our air scatters blue light, making it look yellowish from the ground." },
  { c: "Crocodiles can't stick their tongues out.", t: true, e: "A crocodile's tongue is held in place by a membrane along the floor of its mouth." },
  { c: "All sharks must keep swimming or they'll suffocate.", t: false, e: "Some species must, but many, like the Port Jackson shark and wobbegongs, pump water over their gills while resting." },
  { c: "Your blood is blue until it touches air.", t: false, e: "Blood is always red: darker when low in oxygen. Veins only look blue because of how light passes through skin." },
  { c: "Olympic gold medals are made mostly of silver.", t: true, e: "Rules require at least 92.5% silver, plated with at least 6 grams of gold." },
  { c: "Coffee dehydrates you, so it doesn't count towards your fluid intake.", t: false, e: "For regular drinkers, moderate coffee adds to your daily fluids. The mild diuretic effect doesn't cancel it out." },
  { c: "Stainless steel can still rust.", t: true, e: "Chromium in the steel forms a thin, invisible layer that resists rust, but salt water, scratches or harsh cleaners can still cause rust spots." },
  { c: "The cells lining your stomach are replaced every few days.", t: true, e: "The surface lining is constantly renewed, which helps protect it from its own acid." },
);

WB.PUZZLES.push(
  { q: "Which weighs more: a kilogram of feathers or a kilogram of bricks?", o: ["Feathers", "Bricks", "They weigh the same"], a: 2, e: "A kilogram is a kilogram." },
  { q: "A doctor gives you three pills and says to take one every half hour. How long until they're all gone?", o: ["30 minutes", "1 hour", "90 minutes", "2 hours"], a: 1, e: "Take one now, one at 30 minutes and the last at 60 minutes." },
  { q: "If 3 people take 3 hours to dig 3 holes, how long does 1 person take to dig 1 hole?", o: ["1 hour", "3 hours", "9 hours", "20 minutes"], a: 1, e: "Each person digs one hole in 3 hours." },
  { q: "What comes next: 1, 1, 2, 3, 5, 8, ?", o: ["11", "12", "13", "16"], a: 2, e: "Each number is the sum of the two before it: 5 + 8 = 13. It's the Fibonacci sequence." },
  { q: "A snail is at the bottom of a 10-metre well. Each day it climbs 3 m; each night it slips back 2 m. On which day does it reach the top?", o: ["Day 7", "Day 8", "Day 10", "Never"], a: 1, e: "After 7 days it's at 7 m. On day 8 it climbs 3 m and reaches the top before slipping." },
  { q: "A rope ladder hangs over the side of a boat, with rungs 30 cm apart. The tide rises 1 metre. How many extra rungs go underwater?", o: ["3", "4", "None, because the boat rises with the tide", "1"], a: 2, e: "The boat floats, so it rises along with the ladder." },
  { q: "Jess is taller than Sam. Sam is taller than Ali. Who is the shortest?", o: ["Jess", "Sam", "Ali", "Can't tell"], a: 2, e: "Jess > Sam > Ali, so Ali is shortest." },
  { q: "Cutting a log into 3 pieces takes 6 minutes. At the same speed, how long does it take to cut an identical log into 4 pieces?", o: ["8 minutes", "9 minutes", "10 minutes", "12 minutes"], a: 1, e: "3 pieces need only 2 cuts, so each cut takes 3 minutes. 4 pieces need 3 cuts: 9 minutes." },
  { q: "A train leaves at 11:50 and the trip takes 45 minutes. When does it arrive?", o: ["12:25", "12:35", "12:45", "11:95"], a: 1, e: "10 minutes gets you to 12:00, then 35 more minutes: 12:35." },
  { q: "You have one match and walk into a dark room with a candle, a heater and a lamp. What do you light first?", o: ["The candle", "The heater", "The lamp", "The match"], a: 3, e: "You have to light the match before anything else." },
);

WB.SCENARIOS.push(
  { topic: "Bias", q: "Your last three home projects each ran well over budget, but you're sure this one will come in on time. What's the likely trap?", o: ["Anchoring", "The planning fallacy: underestimating time and cost despite past experience", "Survivorship bias", "Nothing: this time is different"], a: 1, e: "People plan for the best case. Start from your own track record, or how long similar projects really took." },
  { topic: "Bias", q: "A jacket is labelled 'Was $400, now $199'. Why does $199 feel like a bargain?", o: ["It's always a bargain", "The $400 acts as an anchor that shapes your sense of value", "Jackets are cheap", "Sales are regulated"], a: 1,
    e: "Anchoring: the first number you see sets the reference point. Ask what the jacket is worth to you, not what it 'was'." },
  { topic: "Bias", q: "You're convinced a diet works, so you only read articles that praise it. What's this called?", o: ["Critical thinking", "Confirmation bias", "Peer review", "The placebo effect"], a: 1,
    e: "Confirmation bias is seeking out information that supports what you already believe. Look for the best case against it." },
  { topic: "Decision making", q: "You paid $60 for a concert ticket, but you're exhausted and would rather stay home. What's the smartest way to decide?", o: ["Go, or the $60 is wasted", "Ignore the $60, because it's spent either way, and choose what you'd enjoy more now", "Go, but leave early so you get some value from the ticket", "Always stay home"], a: 1,
    e: "The $60 is a sunk cost. It's gone whatever you do, so it shouldn't drive the decision." },
  { topic: "Statistics", q: "In a street, nine people earn $60,000 and one earns $10 million. Which better describes a typical income there?", o: ["The mean (about $1 million)", "The median ($60,000)", "The highest income", "They're the same"], a: 1,
    e: "One extreme value drags the average up. The median, the middle value, better describes a typical person." },
  { topic: "Statistics", q: "A headline says crime in a small town is 'up 100%'. It rose from 2 incidents to 4. What's the best takeaway?", o: ["The town is now dangerous", "With tiny numbers, percentages can sound alarming but mean little", "Crime doubled everywhere", "Police are failing"], a: 1,
    e: "Always ask for the raw numbers. A big percentage change on a small base is often just noise." },
  { topic: "Statistics", q: "An online poll on a car website finds 80% of people want lower petrol taxes. Why be cautious?", o: ["Online polls are always right", "People chose to take part, and the audience is mainly drivers, so it's not representative", "80% is too low", "Petrol isn't taxed"], a: 1,
    e: "Self-selected samples reflect who shows up, not the whole population." },
  { topic: "Evidence quality", q: "A headline says 'Scientists say chocolate helps weight loss'. What should you check first?", o: ["Whether you like chocolate", "How big the study was, whether it was in people, and who funded it", "The journalist's name", "Nothing: scientists said it"], a: 1,
    e: "Small, animal or industry-funded studies are often overhyped. One study rarely settles anything." },
  { topic: "Scams", q: "An email from 'your bank' says your account is locked and gives you a link to log in. What's the safest move?", o: ["Click the link quickly", "Reply with your details", "Ignore the link and contact the bank through its official app or a number you look up yourself", "Forward it to friends"], a: 2,
    e: "Banks won't ask you to log in through an email link. Scammers rely on urgency to rush you." },
  { topic: "Money sense", q: "You invest $1,000 at 7% a year and reinvest the returns. Roughly what is it worth after 10 years?", o: ["$1,070", "$1,700", "About $2,000", "$7,000"], a: 2,
    e: "About $1,967. The rule of 72: divide 72 by the rate (72 ÷ 7 ≈ 10) to find how many years it takes to double." },
  { topic: "Money sense", q: "Two $20,000 loans both charge 6% interest. Loan A runs 5 years; loan B runs 10 years with lower repayments. Which costs more interest overall?", o: ["Loan A", "Loan B", "They cost the same", "Neither charges interest"], a: 1,
    e: "Lower repayments feel easier, but you pay interest for twice as long. Loan B costs roughly twice as much in interest." },
  { topic: "Logical fallacies", q: "\"This herbal remedy is completely natural, so it can't do any harm.\" What's the flaw?", o: ["No flaw: natural means safe", "Appeal to nature: being natural doesn't make something safe or effective", "It's a straw man", "It's circular reasoning"], a: 1, e: "Arsenic, death cap mushrooms and snake venom are all natural. Some herbal remedies also interact with prescription medicines." },
  { topic: "Logical fallacies", q: "A famous actor recommends a vitamin supplement in an ad. Why isn't that strong evidence it works?", o: ["Actors can't take vitamins", "They're not an expert in medicine and are being paid", "Ads are illegal", "It is strong evidence"], a: 1,
    e: "That's an appeal to (false) authority. Fame in one field doesn't make someone an expert in another." },
  { topic: "Risk", q: "Shark attacks get heavy news coverage. For Australian beachgoers, how does the risk of dying from a shark compare with drowning?", o: ["Sharks are far riskier", "About the same", "Drowning is far more common", "Neither ever happens"], a: 2,
    e: "Around 100 or more people drown on Australia's coast each year; fatal shark bites are typically a handful. Vivid news makes rare risks feel common." },
);

WB.CAPITALS.push(
  ["Malaysia", "Kuala Lumpur"], ["Belgium", "Brussels"], ["Ukraine", "Kyiv"], ["Saudi Arabia", "Riyadh"], ["Cuba", "Havana"],
  ["Jamaica", "Kingston"], ["Samoa", "Apia"], ["Tonga", "Nukuʻalofa"], ["Vanuatu", "Port Vila"], ["Solomon Islands", "Honiara"],
  ["Croatia", "Zagreb"], ["Romania", "Bucharest"], ["Ethiopia", "Addis Ababa"], ["Ghana", "Accra"], ["Bangladesh", "Dhaka"],
  ["Nepal", "Kathmandu"], ["Cambodia", "Phnom Penh"], ["Laos", "Vientiane"], ["Mongolia", "Ulaanbaatar"], ["Timor-Leste", "Dili"],
  ["United Arab Emirates", "Abu Dhabi"],
);
