/* WISEBYTE TIMELINE · events for the "Which came first?" quiz.
   y = year (negative = BC). c: 1 = approximate date. Pairs are only drawn when the
   gap is wide enough that the answer isn't in doubt (see buildTimeline in index.html). */
window.WB = window.WB || {};
WB.EVENTS = [
  // Ancient world
  { e: "Writing first appears in Mesopotamia", y: -3200, c: 1 },
  { e: "The Great Pyramid of Giza is built", y: -2560, c: 1 },
  { e: "Hammurabi's law code is carved in Babylon", y: -1754, c: 1 },
  { e: "Tutankhamun dies", y: -1323, c: 1 },
  { e: "The first recorded Olympic Games are held", y: -776 },
  { e: "Rome is founded, according to legend", y: -753 },
  { e: "The Battle of Marathon is fought", y: -490 },
  { e: "Confucius dies", y: -479 },
  { e: "The Parthenon in Athens is completed", y: -432 },
  { e: "Socrates is sentenced to death", y: -399 },
  { e: "Alexander the Great dies", y: -323 },
  { e: "Qin Shi Huang unites China", y: -221 },
  { e: "Archimedes is killed during the siege of Syracuse", y: -212 },
  { e: "Julius Caesar is assassinated", y: -44 },
  { e: "Cleopatra dies", y: -30 },
  { e: "Vesuvius buries Pompeii", y: 79 },
  { e: "Paper-making is described in China", y: 105, c: 1 },
  { e: "Work begins on Hadrian's Wall", y: 122 },
  { e: "The last Western Roman emperor is removed", y: 476 },
  // Middle Ages
  { e: "Vikings raid the monastery at Lindisfarne", y: 793 },
  { e: "Charlemagne is crowned emperor", y: 800 },
  { e: "Leif Erikson reaches North America", y: 1000, c: 1 },
  { e: "The Battle of Hastings is fought", y: 1066 },
  { e: "The First Crusade begins", y: 1096 },
  { e: "Angkor Wat is built in Cambodia", y: 1150, c: 1 },
  { e: "Work starts on Notre-Dame in Paris", y: 1163 },
  { e: "Work starts on the Leaning Tower of Pisa", y: 1173 },
  { e: "Genghis Khan becomes ruler of the Mongols", y: 1206 },
  { e: "King John seals Magna Carta", y: 1215 },
  { e: "Marco Polo sets out for China", y: 1271 },
  { e: "The Aztecs found Tenochtitlan", y: 1325, c: 1 },
  { e: "The Black Death reaches Europe", y: 1347 },
  { e: "Joan of Arc is executed", y: 1431 },
  { e: "Machu Picchu is built", y: 1450, c: 1 },
  { e: "Constantinople falls to the Ottomans", y: 1453 },
  { e: "The Gutenberg Bible is printed", y: 1455, c: 1 },
  // Early modern
  { e: "Columbus reaches the Americas", y: 1492 },
  { e: "Leonardo begins painting the Mona Lisa", y: 1503, c: 1 },
  { e: "Michelangelo finishes the Sistine Chapel ceiling", y: 1512 },
  { e: "Martin Luther posts his 95 Theses", y: 1517 },
  { e: "Magellan's round-the-world voyage sets out", y: 1519 },
  { e: "Copernicus publishes his Sun-centred universe", y: 1543 },
  { e: "Shakespeare is born", y: 1564 },
  { e: "The Spanish Armada is defeated", y: 1588 },
  { e: "Don Quixote is first published", y: 1605 },
  { e: "Willem Janszoon makes the first recorded European landing in Australia", y: 1606 },
  { e: "Galileo turns a telescope to the sky", y: 1609 },
  { e: "The King James Bible is published", y: 1611 },
  { e: "The Mayflower reaches America", y: 1620 },
  { e: "William Harvey describes the circulation of blood", y: 1628 },
  { e: "Abel Tasman reaches Tasmania", y: 1642 },
  { e: "The Taj Mahal is completed", y: 1653, c: 1 },
  { e: "The Great Fire of London", y: 1666 },
  { e: "Newton publishes his laws of motion", y: 1687 },
  { e: "Robinson Crusoe is published", y: 1719 },
  { e: "Benjamin Franklin flies his kite in a storm", y: 1752 },
  { e: "Mozart is born", y: 1756 },
  { e: "Captain Cook charts Australia's east coast", y: 1770 },
  { e: "The US Declaration of Independence is signed", y: 1776 },
  { e: "The First Fleet arrives at Sydney Cove", y: 1788 },
  { e: "Jenner tests the first smallpox vaccine", y: 1796 },
  { e: "French soldiers find the Rosetta Stone", y: 1799 },
  // 19th century
  { e: "Volta builds the first electric battery", y: 1800 },
  { e: "The USA buys Louisiana from France", y: 1803 },
  { e: "Napoleon crowns himself emperor", y: 1804 },
  { e: "Pride and Prejudice is published", y: 1813 },
  { e: "The Battle of Waterloo is fought", y: 1815 },
  { e: "Frankenstein is published", y: 1818 },
  { e: "Beethoven's Ninth Symphony premieres", y: 1824 },
  { e: "The first public steam railway opens in England", y: 1825 },
  { e: "The oldest surviving photograph is taken", y: 1826, c: 1 },
  { e: "Faraday discovers electromagnetic induction", y: 1831 },
  { e: "Britain passes the law abolishing slavery in its empire", y: 1833 },
  { e: "Darwin visits the Galápagos Islands", y: 1835 },
  { e: "Queen Victoria takes the throne", y: 1837 },
  { e: "Astronomers discover Neptune", y: 1846 },
  { e: "The Victorian gold rush begins", y: 1851 },
  { e: "Miners fight at the Eureka Stockade", y: 1854 },
  { e: "Darwin publishes On the Origin of Species", y: 1859 },
  { e: "Burke and Wills set out from Melbourne", y: 1860 },
  { e: "The first Melbourne Cup is run", y: 1861 },
  { e: "Alice's Adventures in Wonderland is published", y: 1865 },
  { e: "The Suez Canal opens", y: 1869 },
  { e: "The Overland Telegraph links Adelaide and Darwin", y: 1872 },
  { e: "Alexander Graham Bell patents the telephone", y: 1876 },
  { e: "The first Test cricket match is played in Melbourne", y: 1877 },
  { e: "Edison demonstrates a long-lasting light bulb", y: 1879 },
  { e: "Krakatoa erupts", y: 1883 },
  { e: "Karl Benz patents the motor car", y: 1886 },
  { e: "The Eiffel Tower opens", y: 1889 },
  { e: "New Zealand women win the vote", y: 1893 },
  { e: "Röntgen discovers X-rays", y: 1895 },
  // 20th century
  { e: "Australia becomes a federation", y: 1901 },
  { e: "The Wright brothers make the first powered flight", y: 1903 },
  { e: "Einstein publishes special relativity", y: 1905 },
  { e: "The Titanic sinks", y: 1912 },
  { e: "Anzac troops land at Gallipoli", y: 1915 },
  { e: "The Russian Revolution", y: 1917 },
  { e: "Qantas is founded", y: 1920 },
  { e: "Tutankhamun's tomb is discovered", y: 1922 },
  { e: "John Logie Baird demonstrates television", y: 1926 },
  { e: "Mickey Mouse first appears on screen", y: 1928 },
  { e: "Phar Lap wins the Melbourne Cup", y: 1930 },
  { e: "The Sydney Harbour Bridge opens", y: 1932 },
  { e: "The last known thylacine dies in Hobart", y: 1936 },
  { e: "The Hindenburg airship bursts into flames", y: 1937 },
  { e: "World War II begins", y: 1939 },
  { e: "The first Holden car rolls off the line", y: 1948 },
  { e: "Work starts on the Snowy Mountains Scheme", y: 1949 },
  { e: "Hillary and Tenzing reach the top of Everest", y: 1953 },
  { e: "Television broadcasting begins in Australia", y: 1956 },
  { e: "Sputnik becomes the first satellite", y: 1957 },
  { e: "Yuri Gagarin becomes the first person in space", y: 1961 },
  { e: "The Beatles release their first single", y: 1962 },
  { e: "Australia switches to decimal currency", y: 1966 },
  { e: "Humans first walk on the Moon", y: 1969 },
  { e: "The first email is sent", y: 1971 },
  { e: "The Sydney Opera House opens", y: 1973 },
  { e: "Cyclone Tracy destroys much of Darwin", y: 1974 },
  { e: "Star Wars is released", y: 1977 },
  { e: "Mount St Helens erupts", y: 1980 },
  { e: "Australia II wins the America's Cup", y: 1983 },
  { e: "The Chernobyl nuclear accident", y: 1986 },
  { e: "The Berlin Wall comes down", y: 1989 },
  { e: "The Hubble Space Telescope is launched", y: 1990 },
  { e: "The High Court decides the Mabo case", y: 1992 },
  { e: "The Channel Tunnel opens", y: 1994 },
  { e: "Dolly the cloned sheep is born", y: 1996 },
  { e: "Google is founded", y: 1998 },
  // 21st century
  { e: "Sydney hosts the Olympic Games", y: 2000 },
  { e: "Euro notes and coins enter circulation", y: 2002 },
  { e: "Facebook is launched", y: 2004 },
  { e: "The first iPhone goes on sale", y: 2007 },
  { e: "Bitcoin is created", y: 2009 },
  { e: "NASA's Curiosity rover lands on Mars", y: 2012 },
  { e: "The Gold Coast hosts the Commonwealth Games", y: 2018 },
  { e: "The WHO declares COVID-19 a pandemic", y: 2020 },
  { e: "The James Webb Space Telescope's first images are released", y: 2022 },
];
