/* WISEBYTE WORDS (part 2) · useful, everyday-improving vocabulary */
WB.WORDS.push(
/* ---------------- Everyday English ---------------- */
{ w: "ambiguous", pos: "adjective", ipa: "/æmˈbɪɡjuəs/", say: "am-BIG-yoo-us", lvl: 2, cat: "everyday",
  def: "Open to more than one interpretation; unclear.",
  ex: ["The email was ambiguous, so I rang to check what she meant.", "The contract's wording on refunds is ambiguous."],
  syn: ["unclear", "vague", "equivocal"], ant: ["clear", "definite"],
  origin: "From Latin ambiguus, 'doubtful', from ambigere, 'to waver' (literally 'to drive both ways').",
  blank: "The sign was ___: we couldn't tell if parking was allowed." },
{ w: "plausible", pos: "adjective", ipa: "/ˈplɔːzəbəl/", say: "PLAW-zuh-bul", lvl: 2, cat: "everyday",
  def: "Seeming reasonable or likely to be true.",
  ex: ["His excuse sounded plausible, but it didn't add up.", "It's a plausible explanation, though we need more evidence."],
  syn: ["believable", "credible", "reasonable"], ant: ["implausible", "unlikely"],
  origin: "From Latin plausibilis, 'deserving applause', from plaudere, 'to clap'.",
  blank: "Scammers make their stories sound ___ so you'll trust them." },
{ w: "obsolete", pos: "adjective", ipa: "/ˈɒbsəliːt/", say: "OB-suh-leet", lvl: 2, cat: "everyday",
  def: "No longer produced or used; out of date.",
  ex: ["Fax machines are almost obsolete.", "The update made my old charger obsolete."],
  syn: ["outdated", "outmoded", "defunct"], ant: ["current", "modern"],
  origin: "From Latin obsoletus, 'grown old, worn out'.",
  blank: "Streaming has made DVD players nearly ___." },
{ w: "frugal", pos: "adjective", ipa: "/ˈfruːɡəl/", say: "FROO-gul", lvl: 1, cat: "everyday",
  def: "Careful with money or resources; avoiding waste.",
  ex: ["Being frugal for a year helped them save a house deposit.", "A frugal lunch of leftovers saves more than you'd think."],
  syn: ["thrifty", "economical", "prudent"], ant: ["wasteful", "extravagant"],
  origin: "From Latin frugalis, from frux, 'fruit' or 'value'.",
  blank: "My grandparents were ___ and never threw anything useful away." },
{ w: "succinct", pos: "adjective", ipa: "/səkˈsɪŋkt/", say: "suk-SINKT", lvl: 2, cat: "everyday",
  def: "Briefly and clearly expressed.",
  ex: ["Keep your answer succinct: two sentences at most.", "Her succinct summary saved the meeting ten minutes."],
  syn: ["concise", "brief", "to the point"], ant: ["long-winded", "rambling"],
  origin: "From Latin succinctus, 'tucked up' (of clothing), so 'compact'.",
  blank: "A good email subject line is short and ___." },
{ w: "inevitable", pos: "adjective", ipa: "/ɪˈnevɪtəbəl/", say: "in-EV-ih-tuh-bul", lvl: 1, cat: "everyday",
  def: "Certain to happen; unavoidable.",
  ex: ["Some mistakes are inevitable when you learn something new.", "With the rain, delays were inevitable."],
  syn: ["unavoidable", "certain", "inescapable"], ant: ["avoidable", "unlikely"],
  origin: "From Latin inevitabilis: in- 'not' + evitare 'to avoid'.",
  blank: "Change is ___, so it pays to be adaptable." },
{ w: "mundane", pos: "adjective", ipa: "/mʌnˈdeɪn/", say: "mun-DAYN", lvl: 2, cat: "everyday",
  def: "Ordinary and unexciting; everyday.",
  ex: ["Even mundane jobs like filing can be done well.", "Podcasts make mundane chores go faster."],
  syn: ["ordinary", "dull", "routine"], ant: ["exciting", "extraordinary"],
  origin: "From Latin mundanus, 'of the world', from mundus, 'world'.",
  blank: "Folding washing is a ___ task, but someone has to do it." },
{ w: "nostalgia", pos: "noun", ipa: "/nɒˈstældʒə/", say: "nos-TAL-juh", lvl: 1, cat: "everyday",
  def: "A sentimental longing for the past.",
  ex: ["The old cartoon filled him with nostalgia.", "Retro games sell partly on nostalgia."],
  syn: ["wistfulness", "longing", "sentimentality"], ant: ["indifference"],
  origin: "Coined in 1688 from Greek nostos, 'homecoming', + algos, 'pain'. It first meant severe homesickness.",
  blank: "Hearing songs from high school brings a wave of ___." },
{ w: "paramount", pos: "adjective", ipa: "/ˈpærəmaʊnt/", say: "PAIR-uh-mount", lvl: 2, cat: "everyday",
  def: "More important than anything else; supreme.",
  ex: ["Safety is paramount on a building site.", "Trust is paramount in any friendship."],
  syn: ["foremost", "supreme", "primary"], ant: ["minor", "secondary"],
  origin: "From Old French par amont, 'above'.",
  blank: "When swimming at the beach, staying between the flags is ___." },
{ w: "reluctant", pos: "adjective", ipa: "/rɪˈlʌktənt/", say: "rih-LUK-tunt", lvl: 1, cat: "everyday",
  def: "Unwilling and hesitant.",
  ex: ["She was reluctant to lend her car.", "Many people are reluctant to ask for a pay rise."],
  syn: ["unwilling", "hesitant", "loath"], ant: ["eager", "willing"],
  origin: "From Latin reluctari, 'to struggle against'.",
  blank: "He was ___ to admit he'd got lost." },
{ w: "hindsight", pos: "noun", ipa: "/ˈhaɪndsaɪt/", say: "HYND-syte", lvl: 1, cat: "everyday",
  def: "Understanding of a situation only after it has happened.",
  ex: ["In hindsight, we should have booked earlier.", "Hindsight makes every decision look obvious."],
  syn: ["retrospect", "reflection"], ant: ["foresight"],
  origin: "From hind, 'behind', + sight.",
  blank: "With ___, buying the cheaper tyres was a mistake." },
{ w: "pivotal", pos: "adjective", ipa: "/ˈpɪvətəl/", say: "PIV-uh-tul", lvl: 2, cat: "everyday",
  def: "Of crucial importance, with other things depending on it.",
  ex: ["That meeting was pivotal to her career.", "The goal came at a pivotal moment in the match."],
  syn: ["crucial", "critical", "decisive"], ant: ["minor", "trivial"],
  origin: "From pivot, the point on which something turns.",
  blank: "Winning the first set was ___; it changed the whole match." },
{ w: "cynical", pos: "adjective", ipa: "/ˈsɪnɪkəl/", say: "SIN-ih-kul", lvl: 2, cat: "everyday",
  def: "Believing that people are motivated purely by self-interest; distrustful.",
  ex: ["After years of broken promises, voters are cynical.", "Don't be so cynical: some people really are just being kind."],
  syn: ["sceptical", "distrustful", "jaded"], ant: ["trusting", "optimistic"],
  origin: "From the Cynics, ancient Greek philosophers who scorned wealth and convention. Their name comes from kyon, 'dog'.",
  blank: "She's ___ about ads that promise overnight results." },
{ w: "tangible", pos: "adjective", ipa: "/ˈtændʒəbəl/", say: "TAN-juh-bul", lvl: 2, cat: "everyday",
  def: "Real and able to be touched or clearly seen.",
  ex: ["The program produced tangible results within a month.", "A house is a tangible asset."],
  syn: ["concrete", "real", "measurable"], ant: ["intangible", "abstract"],
  origin: "From Latin tangere, 'to touch'.",
  blank: "We need ___ progress, not just promises." },
/* ---------------- Business ---------------- */
{ w: "incentive", pos: "noun", ipa: "/ɪnˈsentɪv/", say: "in-SEN-tiv", lvl: 1, cat: "business",
  def: "Something that motivates a person to do something.",
  ex: ["The bonus is an incentive to hit targets.", "Cashback offers are an incentive to switch providers."],
  syn: ["motivation", "encouragement", "inducement"], ant: ["deterrent", "disincentive"],
  origin: "From Latin incentivus, 'setting the tune', from incinere, 'to sing'.",
  blank: "Free delivery is a strong ___ to buy online." },
{ w: "stakeholder", pos: "noun", ipa: "/ˈsteɪkhəʊldə/", say: "STAYK-hohl-duh", lvl: 2, cat: "business",
  def: "A person or group with an interest in or affected by an organisation or decision.",
  ex: ["Residents are key stakeholders in the new road plan.", "Keep all stakeholders updated as the project changes."],
  syn: ["interested party", "participant"], ant: ["outsider"],
  origin: "Originally the person who held the bets (stakes) in a wager.",
  blank: "Before closing the school, the council consulted every ___." },
{ w: "benchmark", pos: "noun", ipa: "/ˈbentʃmɑːk/", say: "BENCH-mark", lvl: 2, cat: "business",
  def: "A standard or point of reference against which things are compared.",
  ex: ["The ASX 200 is a common benchmark for Australian shares.", "Her first report set the benchmark for the team."],
  syn: ["standard", "yardstick", "reference point"], ant: [],
  origin: "A surveyor's mark cut into stone to rest a levelling rod on, like a bench.",
  blank: "Use last year's sales as a ___ for this year." },
{ w: "delegate", pos: "verb", ipa: "/ˈdeləɡeɪt/", say: "DEL-uh-gayt", lvl: 1, cat: "business",
  def: "To give a task or responsibility to someone else.",
  ex: ["Good managers delegate instead of doing everything themselves.", "She delegated the booking to her assistant."],
  syn: ["assign", "entrust", "hand over"], ant: ["retain", "keep"],
  origin: "From Latin delegare, 'to send on a commission'.",
  blank: "If you're overloaded, learn to ___." },
{ w: "feasible", pos: "adjective", ipa: "/ˈfiːzəbəl/", say: "FEE-zuh-bul", lvl: 2, cat: "business",
  def: "Possible to do easily or conveniently; practical.",
  ex: ["Is it feasible to finish by Friday?", "A cheaper design made the project feasible again."],
  syn: ["achievable", "practicable", "workable"], ant: ["impossible", "impractical"],
  origin: "From Old French faisable, from faire, 'to do'.",
  blank: "Moving interstate in a week isn't ___." },
{ w: "redundant", pos: "adjective", ipa: "/rɪˈdʌndənt/", say: "rih-DUN-dunt", lvl: 2, cat: "business",
  def: "No longer needed or useful; (of a worker) dismissed because the job no longer exists.",
  ex: ["The new software made the manual process redundant.", "He was made redundant when the branch closed."],
  syn: ["unnecessary", "superfluous", "surplus"], ant: ["essential", "necessary"],
  origin: "From Latin redundare, 'to overflow'.",
  blank: "Saying 'free gift' is ___: gifts are free by definition." },
{ w: "liquidity", pos: "noun", ipa: "/lɪˈkwɪdəti/", say: "lih-KWID-ih-tee", lvl: 3, cat: "business",
  def: "How easily an asset can be turned into cash without losing value.",
  ex: ["Cash in the bank has high liquidity; a house has low liquidity.", "Keep some liquidity for emergencies."],
  syn: ["cash availability", "convertibility"], ant: ["illiquidity"],
  origin: "From Latin liquidus, 'fluid', because the money can 'flow' freely.",
  blank: "Shares have more ___ than property because you can sell them in seconds." },
{ w: "collateral", pos: "noun", ipa: "/kəˈlætərəl/", say: "kuh-LAT-uh-rul", lvl: 3, cat: "business",
  def: "Something pledged as security for a loan, which the lender can take if you don't repay.",
  ex: ["The house is collateral for the mortgage.", "Some car loans use the car itself as collateral."],
  syn: ["security", "guarantee", "surety"], ant: [],
  origin: "From Latin collateralis, 'side by side', so something standing alongside the loan.",
  blank: "The bank asked for ___ before approving the business loan." },
/* ---------------- Academic ---------------- */
{ w: "hypothesis", pos: "noun", ipa: "/haɪˈpɒθəsɪs/", say: "hy-POTH-uh-sis", lvl: 2, cat: "academic",
  def: "A proposed explanation that can be tested.",
  ex: ["Her hypothesis was that sleep improves test scores.", "The data didn't support the hypothesis."],
  syn: ["theory", "proposition", "supposition"], ant: ["fact", "proof"],
  origin: "From Greek hypothesis, 'foundation, supposition': hypo 'under' + thesis 'placing'.",
  blank: "Scientists test a ___ by trying to prove it wrong." },
{ w: "inference", pos: "noun", ipa: "/ˈɪnfərəns/", say: "IN-fuh-runs", lvl: 2, cat: "academic",
  def: "A conclusion reached from evidence and reasoning rather than from direct statements.",
  ex: ["From the wet footprints, the inference was that someone had just come in from the rain.", "Be careful: that inference goes beyond the data."],
  syn: ["deduction", "conclusion", "reasoning"], ant: [],
  origin: "From Latin inferre, 'to bring in'.",
  blank: "The detective's ___ was based on the mud on the boots." },
{ w: "premise", pos: "noun", ipa: "/ˈpremɪs/", say: "PREM-iss", lvl: 2, cat: "academic",
  def: "A statement assumed to be true that an argument is built on.",
  ex: ["The argument fails because its premise is false.", "The show's premise is simple: strangers renovate a house."],
  syn: ["assumption", "basis", "proposition"], ant: ["conclusion"],
  origin: "From Latin praemissa, 'sent before'.",
  blank: "If the ___ is wrong, the conclusion can't be trusted." },
{ w: "coherent", pos: "adjective", ipa: "/kəʊˈhɪərənt/", say: "koh-HEER-unt", lvl: 2, cat: "academic",
  def: "Logical and consistent; clearly connected.",
  ex: ["Give a coherent explanation of your plan.", "After the long flight, he was barely coherent."],
  syn: ["logical", "consistent", "clear"], ant: ["incoherent", "muddled"],
  origin: "From Latin cohaerere, 'to stick together'.",
  blank: "A good essay makes a ___ argument from start to finish." },
{ w: "anecdotal", pos: "adjective", ipa: "/ˌænɪkˈdəʊtəl/", say: "an-ek-DOH-tul", lvl: 2, cat: "academic",
  def: "Based on personal stories rather than careful research.",
  ex: ["There's plenty of anecdotal evidence, but no proper trials.", "My uncle's experience is anecdotal; it doesn't prove anything."],
  syn: ["informal", "unscientific", "hearsay"], ant: ["empirical", "scientific"],
  origin: "From Greek anekdota, 'things unpublished'.",
  blank: "Reviews from friends are ___ evidence, not proof." },
{ w: "subjective", pos: "adjective", ipa: "/səbˈdʒektɪv/", say: "sub-JEK-tiv", lvl: 1, cat: "academic",
  def: "Based on personal feelings, tastes or opinions rather than facts.",
  ex: ["Whether a song is good is subjective.", "Try to separate subjective impressions from measurable results."],
  syn: ["personal", "individual", "biased"], ant: ["objective", "impartial"],
  origin: "From Latin subjectivus, 'relating to the subject' (the person thinking).",
  blank: "Taste in food is ___; there's no single right answer." },
{ w: "caveat", pos: "noun", ipa: "/ˈkæviæt/", say: "KAV-ee-at", lvl: 3, cat: "academic",
  def: "A warning or condition that limits a statement.",
  ex: ["The study is promising, with the caveat that it only involved mice.", "One caveat: the offer ends Friday."],
  syn: ["warning", "proviso", "qualification"], ant: [],
  origin: "Latin for 'let him beware', as in caveat emptor, 'let the buyer beware'.",
  blank: "The results look good, but there's an important ___." },
{ w: "rhetoric", pos: "noun", ipa: "/ˈretərɪk/", say: "RET-uh-rik", lvl: 2, cat: "academic",
  def: "The art of persuasive speaking or writing; also language that sounds impressive but lacks substance.",
  ex: ["Aristotle wrote a famous book on rhetoric.", "Voters want action, not rhetoric."],
  syn: ["oratory", "persuasion", "spin"], ant: ["plain speech"],
  origin: "From Greek rhetor, 'public speaker'.",
  blank: "The speech was full of ___ but short on actual plans." },
/* ---------------- Science ---------------- */
{ w: "extrapolate", pos: "verb", ipa: "/ɪkˈstræpəleɪt/", say: "ik-STRAP-uh-layt", lvl: 2, cat: "science",
  def: "To estimate or conclude something beyond the known facts by assuming a current trend will continue.",
  ex: ["You can't extrapolate from one hot week to a whole summer.", "If we extrapolate current growth, the town will double in size within 20 years."],
  syn: ["project", "infer", "extend"], ant: [],
  origin: "Coined in the late 1800s from extra-, 'outside', modelled on interpolate (estimating between known points).",
  blank: "Be careful not to ___ too much from a survey of ten people." },
{ w: "placebo", pos: "noun", ipa: "/pləˈsiːbəʊ/", say: "pluh-SEE-boh", lvl: 2, cat: "science",
  def: "A fake treatment with no active ingredient, used as a comparison in trials.",
  ex: ["Half the group got the drug; half got a placebo.", "Some people feel better even on a placebo."],
  syn: ["dummy pill", "sugar pill"], ant: [],
  origin: "Latin for 'I shall please'.",
  blank: "To test the medicine fairly, some patients were given a ___." },
{ w: "metabolism", pos: "noun", ipa: "/məˈtæbəlɪzəm/", say: "muh-TAB-uh-liz-um", lvl: 2, cat: "science",
  def: "The chemical processes in a living thing that turn food into energy and build and repair the body.",
  ex: ["Muscle uses more energy than fat, even at rest, so it affects metabolism.", "Hummingbirds have an extremely fast metabolism."],
  syn: ["energy use"], ant: [],
  origin: "From Greek metabole, 'change'.",
  blank: "Your ___ keeps working even while you sleep." },
{ w: "erosion", pos: "noun", ipa: "/ɪˈrəʊʒən/", say: "ih-ROH-zhun", lvl: 1, cat: "science",
  def: "The gradual wearing away of rock or soil by water, wind or ice; any gradual destruction.",
  ex: ["Coastal erosion is threatening some beachfront homes.", "Inflation causes an erosion of savings."],
  syn: ["wearing away", "deterioration"], ant: ["build-up", "accumulation"],
  origin: "From Latin erodere, 'to gnaw away'.",
  blank: "The Twelve Apostles were carved from cliffs by ___." },
{ w: "insulate", pos: "verb", ipa: "/ˈɪnsjəleɪt/", say: "IN-syuh-layt", lvl: 1, cat: "science",
  def: "To cover or protect something to stop heat, sound or electricity passing through.",
  ex: ["Insulating the ceiling can cut heating costs.", "Rubber insulates the wires."],
  syn: ["shield", "protect", "cushion"], ant: ["expose"],
  origin: "From Latin insula, 'island', as if making something an island.",
  blank: "A good jacket will ___ you from the cold." },
{ w: "velocity", pos: "noun", ipa: "/vəˈlɒsəti/", say: "vuh-LOS-ih-tee", lvl: 2, cat: "science",
  def: "Speed in a particular direction.",
  ex: ["The ball's velocity changed when it bounced.", "Escape velocity from Earth is about 11 km per second."],
  syn: ["speed", "rate", "pace"], ant: [],
  origin: "From Latin velox, 'swift'.",
  blank: "Speed tells you how fast; ___ also tells you which way." },
/* ---------------- Law & civics ---------------- */
{ w: "negligence", pos: "noun", ipa: "/ˈneɡlɪdʒəns/", say: "NEG-lih-juns", lvl: 2, cat: "law",
  def: "Failure to take proper care, especially when it causes harm to someone.",
  ex: ["The owner was sued for negligence after the wet floor caused a fall.", "Leaving the pool gate open was negligence."],
  syn: ["carelessness", "neglect"], ant: ["care", "diligence"],
  origin: "From Latin neglegere, 'to disregard'.",
  blank: "The court ruled that the builder's ___ caused the roof to collapse." },
{ w: "waive", pos: "verb", ipa: "/weɪv/", say: "wayv", lvl: 2, cat: "law",
  def: "To choose not to insist on a right, rule or fee.",
  ex: ["The bank agreed to waive the late fee.", "You may be asked to waive your right to sue."],
  syn: ["give up", "forgo", "set aside"], ant: ["enforce", "insist on"],
  origin: "From Old French weyver, 'to abandon'. Don't confuse it with 'wave'.",
  blank: "Ask politely and they might ___ the booking fee." },
{ w: "clause", pos: "noun", ipa: "/klɔːz/", say: "klawz", lvl: 1, cat: "law",
  def: "A particular section of a legal document, such as a contract.",
  ex: ["Read the cancellation clause before you sign.", "A 'cooling-off' clause lets you change your mind."],
  syn: ["section", "provision", "term"], ant: [],
  origin: "From Medieval Latin clausa, 'conclusion', from claudere, 'to close'.",
  blank: "The lease has a ___ banning pets." },
{ w: "testimony", pos: "noun", ipa: "/ˈtestɪməni/", say: "TES-tih-muh-nee", lvl: 2, cat: "law",
  def: "A formal statement given in court; any evidence that something is true.",
  ex: ["The witness's testimony changed the case.", "The crowd was testimony to the band's popularity."],
  syn: ["evidence", "statement", "declaration"], ant: [],
  origin: "From Latin testis, 'witness'.",
  blank: "Her ___ was the key evidence at the trial." },
{ w: "amend", pos: "verb", ipa: "/əˈmend/", say: "uh-MEND", lvl: 1, cat: "law",
  def: "To make changes to a document, law or statement, usually to improve it.",
  ex: ["Parliament voted to amend the law.", "Please amend the address on my account."],
  syn: ["change", "revise", "modify"], ant: ["keep", "preserve"],
  origin: "From Latin emendare, 'to free from faults'.",
  blank: "Only a referendum can ___ Australia's Constitution." },
{ w: "defamation", pos: "noun", ipa: "/ˌdefəˈmeɪʃən/", say: "def-uh-MAY-shun", lvl: 3, cat: "law",
  def: "Damaging someone's reputation by communicating false statements about them.",
  ex: ["Posting false claims online can lead to a defamation case.", "Truth is a defence against defamation in Australia."],
  syn: ["libel", "slander", "smear"], ant: ["praise"],
  origin: "From Latin diffamare, 'to spread abroad by ill report'.",
  blank: "He sued the newspaper for ___ after the false story ran." },
/* ---------------- People & character ---------------- */
{ w: "empathy", pos: "noun", ipa: "/ˈempəθi/", say: "EM-puh-thee", lvl: 1, cat: "people",
  def: "The ability to understand and share another person's feelings.",
  ex: ["Good doctors show empathy as well as skill.", "Empathy starts with listening."],
  syn: ["understanding", "compassion", "fellow feeling"], ant: ["indifference", "callousness"],
  origin: "From Greek empatheia: en- 'in' + pathos 'feeling'. Coined in English in 1908.",
  blank: "She showed real ___ when her friend lost his job." },
{ w: "complacent", pos: "adjective", ipa: "/kəmˈpleɪsənt/", say: "kum-PLAY-sunt", lvl: 2, cat: "people",
  def: "Too satisfied with yourself or a situation, so you stop trying or ignore risks.",
  ex: ["The team got complacent after leading at half-time.", "Don't get complacent about sunscreen in winter."],
  syn: ["smug", "self-satisfied", "careless"], ant: ["vigilant", "driven"],
  origin: "From Latin complacere, 'to please greatly'.",
  blank: "After years without a break-in, they'd become ___ about locking up." },
{ w: "diligent", pos: "adjective", ipa: "/ˈdɪlɪdʒənt/", say: "DIL-ih-junt", lvl: 1, cat: "people",
  def: "Hard-working and careful.",
  ex: ["A diligent student reviews notes every week.", "She was diligent about checking every invoice."],
  syn: ["industrious", "conscientious", "thorough"], ant: ["lazy", "careless"],
  origin: "From Latin diligere, 'to value highly'.",
  blank: "He's ___ about paying bills on time." },
{ w: "benevolent", pos: "adjective", ipa: "/bəˈnevələnt/", say: "buh-NEV-uh-lunt", lvl: 2, cat: "people",
  def: "Kind, well-meaning and generous.",
  ex: ["A benevolent donor paid for the new playground.", "She smiled with benevolent patience."],
  syn: ["kind", "charitable", "generous"], ant: ["malevolent", "cruel"],
  origin: "From Latin bene 'well' + volens 'wishing'.",
  blank: "The ___ neighbour mowed everyone's lawns for free." },
{ w: "condescending", pos: "adjective", ipa: "/ˌkɒndɪˈsendɪŋ/", say: "kon-dih-SEN-ding", lvl: 2, cat: "people",
  def: "Acting as if you are better or smarter than others.",
  ex: ["He explained it in a condescending tone.", "Asking questions isn't condescending; talking down is."],
  syn: ["patronising", "superior", "snobbish"], ant: ["humble", "respectful"],
  origin: "From Latin condescendere, 'to stoop'.",
  blank: "Nobody likes a ___ boss who treats them like children." },
{ w: "stoic", pos: "adjective", ipa: "/ˈstəʊɪk/", say: "STOH-ik", lvl: 2, cat: "people",
  def: "Enduring pain or hardship calmly without complaining.",
  ex: ["She stayed stoic through the long recovery.", "Stoic doesn't mean emotionless; it means steady."],
  syn: ["uncomplaining", "resilient", "composed"], ant: ["emotional", "excitable"],
  origin: "From the Stoics, Greek philosophers who taught in the Stoa Poikile, a painted porch in Athens.",
  blank: "The farmer remained ___ through the drought." },
{ w: "altruistic", pos: "adjective", ipa: "/ˌæltruˈɪstɪk/", say: "al-troo-IS-tik", lvl: 2, cat: "people",
  def: "Unselfishly concerned for the wellbeing of others.",
  ex: ["Donating blood is an altruistic act.", "Some animals show altruistic behaviour too."],
  syn: ["selfless", "generous", "charitable"], ant: ["selfish"],
  origin: "From French altruisme, from Italian altrui, 'somebody else'.",
  blank: "Volunteering at the food bank was a truly ___ choice." },
{ w: "pompous", pos: "adjective", ipa: "/ˈpɒmpəs/", say: "POM-pus", lvl: 2, cat: "people",
  def: "Self-important and showy, especially in speech.",
  ex: ["The pompous speech used big words to say very little.", "He's knowledgeable, but never pompous."],
  syn: ["arrogant", "self-important", "grandiose"], ant: ["modest", "humble"],
  origin: "From Latin pompa, 'procession, display'.",
  blank: "His ___ manner put everyone off." }
);
