/* =========================================================
   WISEBYTE — VOCABULARY LIBRARY
   ---------------------------------------------------------
   Useful words people actually say: sharp enough to lift your
   speech, common enough to use this week.
     w       the word (lowercase)
     pos     part of speech
     ipa     IPA pronunciation (Australian/British)
     say     plain-English respelling, stressed syllable in CAPS
     def     definition
     ex      two example sentences
     syn     synonyms   (at least 2 for "Which word doesn't belong?")
     ant     antonyms
     lvl     1 Common · 2 Intermediate · 3 Advanced
     cat     a WORD_CATS key
     origin  etymology
     blank   a sentence with ___ where the word goes (exact form of w)
   ========================================================= */
window.WB = window.WB || {};

WB.WORD_CATS = {
  everyday: { name: "Everyday English", color: "#3F6E8C" },
  business: { name: "Business",         color: "#8F7129" },
  academic: { name: "Academic",         color: "#55538A" },
  science:  { name: "Science",          color: "#3E7A5E" },
  law:      { name: "Law",              color: "#6E3F46" },
  people:   { name: "People & Character", color: "#8A5068" },
};

WB.WORD_LEVELS = { 1: "Common", 2: "Intermediate", 3: "Advanced" };

WB.WORDS = [
/* ---------------- Everyday English ---------------- */
{ w: "ubiquitous", pos: "adjective", ipa: "/juːˈbɪkwɪtəs/", say: "yoo-BIK-wih-tus", lvl: 2, cat: "everyday",
  def: "Present, appearing or found everywhere.",
  ex: ["Smartphones have become ubiquitous.", "Coffee shops are ubiquitous in Melbourne's laneways."],
  syn: ["widespread", "pervasive", "universal"], ant: ["rare", "scarce"],
  origin: "From Latin ubique, 'everywhere'.",
  blank: "Self-checkouts are now ___ in supermarkets." },
{ w: "meticulous", pos: "adjective", ipa: "/məˈtɪkjələs/", say: "muh-TIK-yuh-lus", lvl: 2, cat: "everyday",
  def: "Showing great attention to detail; very careful and precise.",
  ex: ["She kept meticulous records of every expense.", "The restoration was meticulous, right down to the original paint colours."],
  syn: ["thorough", "painstaking", "precise"], ant: ["careless", "sloppy"],
  origin: "From Latin meticulosus, 'fearful', from metus, 'fear'. It shifted from 'afraid of mistakes' to 'very careful'.",
  blank: "He's ___ about his car and cleans it every Sunday." },
{ w: "candid", pos: "adjective", ipa: "/ˈkændɪd/", say: "KAN-did", lvl: 1, cat: "everyday",
  def: "Truthful and straightforward; frank.",
  ex: ["Thanks for being candid about what went wrong.", "The coach gave a candid assessment of the team's form."],
  syn: ["frank", "honest", "open"], ant: ["evasive", "guarded"],
  origin: "From Latin candidus, 'white, pure, sincere'. Roman candidates for office wore bright white togas.",
  blank: "To be ___, I don't think the plan will work." },
{ w: "pragmatic", pos: "adjective", ipa: "/præɡˈmætɪk/", say: "prag-MAT-ik", lvl: 2, cat: "everyday",
  def: "Dealing with things sensibly and realistically, based on practical results rather than theory.",
  ex: ["We need a pragmatic solution, not a perfect one.", "She took a pragmatic approach to the renovation budget."],
  syn: ["practical", "realistic", "sensible"], ant: ["idealistic", "impractical"],
  origin: "From Greek pragmatikos, 'fit for business', from pragma, 'deed, act'.",
  blank: "Let's be ___ and fix the leak before we repaint the ceiling." },
{ w: "nuance", pos: "noun", ipa: "/ˈnjuːɑːns/", say: "NYOO-ahns", lvl: 2, cat: "everyday",
  def: "A subtle difference in meaning, expression, tone or feeling.",
  ex: ["The debate lacked nuance; everyone was either for or against.", "A good translator captures every nuance of the original."],
  syn: ["subtlety", "shade", "distinction"], ant: [],
  origin: "From French nuance, 'shade of colour', from nuer, 'to shade', linked to Latin nubes, 'cloud'.",
  blank: "The film handles grief with real ___." },
{ w: "resilient", pos: "adjective", ipa: "/rɪˈzɪliənt/", say: "rih-ZIL-ee-unt", lvl: 1, cat: "everyday",
  def: "Able to recover quickly from difficulties; tough.",
  ex: ["Kids are often more resilient than we give them credit for.", "The town proved resilient after the floods."],
  syn: ["tough", "hardy", "adaptable"], ant: ["fragile", "vulnerable"],
  origin: "From Latin resilire, 'to leap back, rebound'.",
  blank: "Small businesses had to be ___ to survive the downturn." },
{ w: "ambivalent", pos: "adjective", ipa: "/æmˈbɪvələnt/", say: "am-BIV-uh-lunt", lvl: 2, cat: "everyday",
  def: "Having mixed or contradictory feelings about something.",
  ex: ["I'm ambivalent about moving: great job, but I'd miss my friends.", "Voters seem ambivalent about the new policy."],
  syn: ["torn", "uncertain", "conflicted"], ant: ["certain", "decided"],
  origin: "From Latin ambi-, 'both', and valentia, 'strength'. Coined by the Swiss psychiatrist Eugen Bleuler around 1910.",
  blank: "She felt ___ about the job offer and asked for a few days to think." },
{ w: "serendipity", pos: "noun", ipa: "/ˌserənˈdɪpəti/", say: "sair-un-DIP-ih-tee", lvl: 2, cat: "everyday",
  def: "Finding something good by happy chance, without looking for it.",
  ex: ["By pure serendipity, we sat next to an old friend on the plane.", "Penicillin's discovery owed a lot to serendipity."],
  syn: ["luck", "chance", "fortune"], ant: ["misfortune", "design"],
  origin: "Coined by Horace Walpole in 1754, from a Persian fairy tale, The Three Princes of Serendip (an old name for Sri Lanka).",
  blank: "Meeting my business partner at that café was pure ___." },

/* ---------------- Business ---------------- */
{ w: "mitigate", pos: "verb", ipa: "/ˈmɪtɪɡeɪt/", say: "MIT-ih-gayt", lvl: 2, cat: "business",
  def: "To make something bad less severe, serious or painful.",
  ex: ["We added backups to mitigate the risk of data loss.", "Planting trees can mitigate the heat in cities."],
  syn: ["reduce", "lessen", "ease"], ant: ["worsen", "aggravate"],
  origin: "From Latin mitigare, 'to soften', from mitis, 'mild, gentle'.",
  blank: "Insurance helps ___ the cost of an accident." },
{ w: "viable", pos: "adjective", ipa: "/ˈvaɪəbl/", say: "VY-uh-bul", lvl: 1, cat: "business",
  def: "Capable of working successfully; workable.",
  ex: ["Is a four-day week viable for a small team?", "The idea is clever but not commercially viable."],
  syn: ["workable", "feasible", "practical"], ant: ["unworkable", "impractical"],
  origin: "From French viable, from vie, 'life'. Originally it meant 'able to live'.",
  blank: "We need a ___ plan before we talk to investors." },
{ w: "scrutinise", pos: "verb", ipa: "/ˈskruːtənaɪz/", say: "SKROO-tuh-nyz", lvl: 2, cat: "business",
  def: "To examine or inspect closely and thoroughly.",
  ex: ["The auditors will scrutinise every invoice.", "Always scrutinise the fine print before signing."],
  syn: ["examine", "inspect", "analyse"], ant: ["overlook", "skim"],
  origin: "From Latin scrutinium, 'a search', from scrutari, 'to examine'.",
  blank: "Journalists will ___ the minister's expenses." },
{ w: "contingency", pos: "noun", ipa: "/kənˈtɪndʒənsi/", say: "kun-TIN-jun-see", lvl: 2, cat: "business",
  def: "A possible future event that can't be predicted with certainty, or a plan made for it.",
  ex: ["We've budgeted 10% for contingencies.", "Have a contingency plan in case it rains on the day."],
  syn: ["eventuality", "possibility", "backup"], ant: ["certainty"],
  origin: "From Latin contingere, 'to touch, to happen'.",
  blank: "Our ___ plan kicks in if the supplier is late." },
{ w: "consensus", pos: "noun", ipa: "/kənˈsensəs/", say: "kun-SEN-sus", lvl: 1, cat: "business",
  def: "General agreement among a group.",
  ex: ["After an hour we finally reached a consensus.", "The scientific consensus is clear on this."],
  syn: ["agreement", "accord", "unity"], ant: ["disagreement", "dissent"],
  origin: "From Latin consentire, 'to agree', from con-, 'together', and sentire, 'to feel'.",
  blank: "The board reached a ___ to delay the launch." },
{ w: "leverage", pos: "verb", ipa: "/ˈliːvərɪdʒ/", say: "LEE-vuh-rij", lvl: 2, cat: "business",
  def: "To use something you have to maximum advantage.",
  ex: ["We can leverage our existing customers to launch the new product.", "She leveraged her language skills to land the job."],
  syn: ["exploit", "harness", "capitalise on"], ant: ["waste", "squander"],
  origin: "From lever, via Old French lever, 'to raise', from Latin levare.",
  blank: "Small cafés can ___ social media to compete with the chains." },
{ w: "prerogative", pos: "noun", ipa: "/prɪˈrɒɡətɪv/", say: "prih-ROG-uh-tiv", lvl: 3, cat: "business",
  def: "A right or privilege belonging to a particular person or role.",
  ex: ["It's the manager's prerogative to approve leave.", "Changing your mind is your prerogative."],
  syn: ["right", "privilege", "entitlement"], ant: ["obligation", "duty"],
  origin: "From Latin praerogativa, the group of Roman voters asked to vote first.",
  blank: "Choosing the final design is the client's ___." },
{ w: "lucrative", pos: "adjective", ipa: "/ˈluːkrətɪv/", say: "LOO-kruh-tiv", lvl: 2, cat: "business",
  def: "Producing a lot of money; profitable.",
  ex: ["Mining contracts can be very lucrative.", "He left a lucrative job in finance to open a bakery."],
  syn: ["profitable", "well-paid", "rewarding"], ant: ["unprofitable", "loss-making"],
  origin: "From Latin lucrum, 'profit, gain'.",
  blank: "Weekend weddings are the most ___ part of the florist's business." },

/* ---------------- Academic ---------------- */
{ w: "empirical", pos: "adjective", ipa: "/ɪmˈpɪrɪkl/", say: "im-PIRR-ih-kul", lvl: 2, cat: "academic",
  def: "Based on observation or experience rather than theory alone.",
  ex: ["There's little empirical evidence for that claim.", "The study took an empirical approach, measuring real traffic."],
  syn: ["observed", "evidence-based", "experimental"], ant: ["theoretical", "speculative"],
  origin: "From Greek empeirikos, 'experienced', from empeiria, 'experience'.",
  blank: "We need ___ data, not just opinions." },
{ w: "paradigm", pos: "noun", ipa: "/ˈpærədaɪm/", say: "PARR-uh-dym", lvl: 3, cat: "academic",
  def: "A typical model or pattern of thinking; a framework of ideas.",
  ex: ["Streaming created a new paradigm for how we watch TV.", "Remote work challenged the old office paradigm."],
  syn: ["model", "framework", "pattern"], ant: [],
  origin: "From Greek paradeigma, 'pattern, example'. Made famous by Thomas Kuhn's phrase 'paradigm shift' in 1962.",
  blank: "Electric cars represent a new ___ in transport." },
{ w: "cogent", pos: "adjective", ipa: "/ˈkəʊdʒənt/", say: "KOH-junt", lvl: 3, cat: "academic",
  def: "Clear, logical and convincing.",
  ex: ["She made a cogent case for hiring two more nurses.", "The report offers a cogent explanation of the delays."],
  syn: ["convincing", "compelling", "persuasive"], ant: ["weak", "unconvincing"],
  origin: "From Latin cogere, 'to compel, drive together'.",
  blank: "His essay made a ___ argument for lowering the voting age." },
{ w: "juxtapose", pos: "verb", ipa: "/ˌdʒʌkstəˈpəʊz/", say: "juk-stuh-POHZ", lvl: 3, cat: "academic",
  def: "To place two things side by side, especially to highlight a contrast.",
  ex: ["The exhibition juxtaposes old photos with modern ones of the same streets.", "The film juxtaposes wealth and poverty."],
  syn: ["contrast", "compare", "set side by side"], ant: ["separate"],
  origin: "From French juxtaposer, from Latin juxta, 'next to', and French poser, 'to place'.",
  blank: "The ad tries to ___ the calm of the beach with the chaos of the office." },
{ w: "salient", pos: "adjective", ipa: "/ˈseɪliənt/", say: "SAY-lee-unt", lvl: 3, cat: "academic",
  def: "Most noticeable or important.",
  ex: ["Let me summarise the salient points.", "The salient feature of the design is its simplicity."],
  syn: ["key", "main", "prominent"], ant: ["minor", "trivial"],
  origin: "From Latin salire, 'to leap': something that leaps out at you.",
  blank: "Just give me the ___ details; I don't need the whole story." },
{ w: "tenuous", pos: "adjective", ipa: "/ˈtenjuəs/", say: "TEN-yoo-us", lvl: 3, cat: "academic",
  def: "Very weak or slight; flimsy.",
  ex: ["The link between the two events is tenuous at best.", "They have a tenuous hold on first place."],
  syn: ["weak", "flimsy", "shaky"], ant: ["strong", "solid"],
  origin: "From Latin tenuis, 'thin'.",
  blank: "The evidence connecting him to the crime is ___." },
{ w: "corroborate", pos: "verb", ipa: "/kəˈrɒbəreɪt/", say: "kuh-ROB-uh-rayt", lvl: 3, cat: "academic",
  def: "To confirm or give support to a statement or theory.",
  ex: ["Two witnesses corroborated her account.", "Can anyone corroborate your story?"],
  syn: ["confirm", "support", "verify"], ant: ["contradict", "disprove"],
  origin: "From Latin corroborare, 'to strengthen', from robur, 'strength' (and 'oak').",
  blank: "Security footage helped ___ the driver's version of events." },
{ w: "dichotomy", pos: "noun", ipa: "/daɪˈkɒtəmi/", say: "dy-KOT-uh-mee", lvl: 3, cat: "academic",
  def: "A division or contrast between two things that are opposed or entirely different.",
  ex: ["It's a false dichotomy to say you must choose between work and family.", "The novel explores the dichotomy between city and country life."],
  syn: ["division", "split", "contrast"], ant: ["unity", "similarity"],
  origin: "From Greek dikhotomia, 'a cutting in two'.",
  blank: "There's a clear ___ between what the company says and what it does." },

/* ---------------- Science ---------------- */
{ w: "catalyst", pos: "noun", ipa: "/ˈkætəlɪst/", say: "KAT-uh-list", lvl: 2, cat: "science",
  def: "Something that speeds up a chemical reaction, or more broadly, something that causes change.",
  ex: ["The protest was a catalyst for reform.", "Enzymes act as catalysts in your body."],
  syn: ["trigger", "spark", "stimulus"], ant: ["obstacle", "hindrance"],
  origin: "From Greek katalysis, 'dissolution'. The chemist Jöns Jacob Berzelius coined 'catalysis' in 1835.",
  blank: "Losing her job was the ___ for starting her own business." },
{ w: "symbiotic", pos: "adjective", ipa: "/ˌsɪmbaɪˈɒtɪk/", say: "sim-by-OT-ik", lvl: 2, cat: "science",
  def: "Involving a close relationship in which both sides benefit.",
  ex: ["Clownfish and anemones have a symbiotic relationship.", "The café and the bookshop next door have a symbiotic arrangement."],
  syn: ["mutually beneficial", "cooperative", "interdependent"], ant: ["parasitic", "competitive"],
  origin: "From Greek symbiosis, 'living together'.",
  blank: "Bees and flowers share a ___ relationship." },
{ w: "entropy", pos: "noun", ipa: "/ˈentrəpi/", say: "EN-truh-pee", lvl: 3, cat: "science",
  def: "A measure of disorder; the tendency of things to move from order towards disorder.",
  ex: ["My desk is a perfect demonstration of entropy.", "Without maintenance, entropy wins and buildings decay."],
  syn: ["disorder", "decay", "chaos"], ant: ["order", "organisation"],
  origin: "Coined by the German physicist Rudolf Clausius in 1865, from Greek tropē, 'transformation'.",
  blank: "Leave a garden alone and ___ takes over." },
{ w: "anomaly", pos: "noun", ipa: "/əˈnɒməli/", say: "uh-NOM-uh-lee", lvl: 2, cat: "science",
  def: "Something that differs from what is standard, normal or expected.",
  ex: ["One hot day in July is an anomaly, not a trend.", "The scientists spotted an anomaly in the data."],
  syn: ["irregularity", "oddity", "exception"], ant: ["norm", "rule"],
  origin: "From Greek anomalia, 'unevenness', from an-, 'not', and homalos, 'even'.",
  blank: "The drop in sales last month was an ___; it bounced back quickly." },
{ w: "equilibrium", pos: "noun", ipa: "/ˌiːkwɪˈlɪbriəm/", say: "ee-kwih-LIB-ree-um", lvl: 2, cat: "science",
  def: "A state of balance between opposing forces or influences.",
  ex: ["Prices settle where supply and demand reach equilibrium.", "It took a while to regain my equilibrium after the news."],
  syn: ["balance", "stability", "steadiness"], ant: ["imbalance", "instability"],
  origin: "From Latin aequilibrium, from aequus, 'equal', and libra, 'balance, scales'.",
  blank: "Predators and prey keep the ecosystem in ___." },
{ w: "dormant", pos: "adjective", ipa: "/ˈdɔːmənt/", say: "DOR-munt", lvl: 1, cat: "science",
  def: "Temporarily inactive or asleep, but able to become active again.",
  ex: ["The volcano has been dormant for centuries.", "Her interest in painting lay dormant until she retired."],
  syn: ["inactive", "sleeping", "latent"], ant: ["active", "awake"],
  origin: "From Old French dormant, 'sleeping', from Latin dormire, 'to sleep'.",
  blank: "The seeds can stay ___ in the soil until the rains come." },
{ w: "volatile", pos: "adjective", ipa: "/ˈvɒlətaɪl/", say: "VOL-uh-tyl", lvl: 2, cat: "science",
  def: "Liable to change rapidly and unpredictably, often for the worse; (in chemistry) evaporating easily.",
  ex: ["Crypto prices are notoriously volatile.", "Petrol is a volatile liquid."],
  syn: ["unstable", "unpredictable", "erratic"], ant: ["stable", "steady"],
  origin: "From Latin volatilis, 'flying', from volare, 'to fly'.",
  blank: "The situation at the border remains ___." },
{ w: "inert", pos: "adjective", ipa: "/ɪˈnɜːt/", say: "ih-NURT", lvl: 2, cat: "science",
  def: "Lacking the ability or strength to move or act; (in chemistry) not reacting with other substances.",
  ex: ["Helium is an inert gas.", "He lay inert on the couch all Sunday."],
  syn: ["inactive", "motionless", "unreactive"], ant: ["active", "reactive"],
  origin: "From Latin iners, 'unskilled, idle', from in-, 'without', and ars, 'skill'.",
  blank: "Gold is useful in electronics because it's almost chemically ___." },

/* ---------------- Law ---------------- */
{ w: "precedent", pos: "noun", ipa: "/ˈpresɪdənt/", say: "PRESS-ih-dunt", lvl: 2, cat: "law",
  def: "An earlier event or decision used as an example or guide for later ones.",
  ex: ["The ruling set a precedent for future cases.", "There's no precedent for a storm this size."],
  syn: ["example", "model", "standard"], ant: [],
  origin: "From Latin praecedere, 'to go before'.",
  blank: "Letting one person work from home sets a ___ for everyone." },
{ w: "liable", pos: "adjective", ipa: "/ˈlaɪəbl/", say: "LY-uh-bul", lvl: 2, cat: "law",
  def: "Legally responsible for something; also, likely to do or experience something.",
  ex: ["The landlord was found liable for the damage.", "Glass bottles are liable to break in transit."],
  syn: ["responsible", "accountable", "answerable"], ant: ["exempt", "immune"],
  origin: "From Anglo-French lier, 'to bind', from Latin ligare.",
  blank: "If you cause the crash, you could be ___ for the repairs." },
{ w: "stipulate", pos: "verb", ipa: "/ˈstɪpjuleɪt/", say: "STIP-yoo-layt", lvl: 3, cat: "law",
  def: "To demand or specify something as part of an agreement.",
  ex: ["The lease stipulates no pets.", "The contract stipulates payment within 30 days."],
  syn: ["specify", "require", "set out"], ant: ["waive"],
  origin: "From Latin stipulari, 'to demand a formal promise'.",
  blank: "The rules ___ that entries must be under 500 words." },
{ w: "arbitrary", pos: "adjective", ipa: "/ˈɑːbɪtrəri/", say: "AH-bih-truh-ree", lvl: 2, cat: "law",
  def: "Based on random choice or personal whim rather than reason or a system.",
  ex: ["The 5 pm cut-off seems arbitrary.", "Staff complained about arbitrary changes to the roster."],
  syn: ["random", "unreasoned", "capricious"], ant: ["reasoned", "systematic"],
  origin: "From Latin arbitrarius, from arbiter, 'judge': left to a judge's discretion.",
  blank: "The dress code felt completely ___." },
{ w: "mandate", pos: "noun", ipa: "/ˈmændeɪt/", say: "MAN-dayt", lvl: 2, cat: "law",
  def: "An official order or authority to do something, often given by voters to a government.",
  ex: ["The government claims a mandate for its reforms.", "The committee has a mandate to review safety."],
  syn: ["authority", "order", "instruction"], ant: [],
  origin: "From Latin mandatum, 'something commanded', from mandare, 'to entrust'.",
  blank: "After winning by a landslide, the party had a clear ___ for change." },
{ w: "jurisdiction", pos: "noun", ipa: "/ˌdʒʊərɪsˈdɪkʃn/", say: "joor-is-DIK-shun", lvl: 3, cat: "law",
  def: "The official power to make legal decisions, or the area in which that power applies.",
  ex: ["Parking fines fall under the council's jurisdiction.", "The case was outside the court's jurisdiction."],
  syn: ["authority", "control", "domain"], ant: [],
  origin: "From Latin iurisdictio, from ius, 'law', and dictio, 'saying'.",
  blank: "Schools fall under the state government's ___." },
{ w: "verbatim", pos: "adverb", ipa: "/vɜːˈbeɪtɪm/", say: "vur-BAY-tim", lvl: 2, cat: "law",
  def: "In exactly the same words as were used originally; word for word.",
  ex: ["She repeated the instructions verbatim.", "The minutes record the discussion verbatim."],
  syn: ["word for word", "exactly", "precisely"], ant: ["loosely", "roughly"],
  origin: "From Medieval Latin verbatim, from verbum, 'word'.",
  blank: "He copied the paragraph ___ from Wikipedia." },
{ w: "impartial", pos: "adjective", ipa: "/ɪmˈpɑːʃl/", say: "im-PAH-shul", lvl: 1, cat: "law",
  def: "Treating everyone equally; fair and not taking sides.",
  ex: ["A referee must be impartial.", "We need an impartial review of the complaint."],
  syn: ["neutral", "unbiased", "fair"], ant: ["biased", "partial"],
  origin: "From im-, 'not', and partial, 'taking a part or side'.",
  blank: "Judges have to stay ___, whatever their personal views." },

/* ---------------- People & Character ---------------- */
{ w: "gregarious", pos: "adjective", ipa: "/ɡrɪˈɡeəriəs/", say: "grih-GAIR-ee-us", lvl: 2, cat: "people",
  def: "Fond of company; sociable.",
  ex: ["Our gregarious neighbour knows everyone on the street.", "He's gregarious at parties but quiet at work."],
  syn: ["sociable", "outgoing", "convivial"], ant: ["introverted", "reserved"],
  origin: "From Latin gregarius, from grex, 'flock, herd'.",
  blank: "She's so ___ she can't eat lunch alone." },
{ w: "punctilious", pos: "adjective", ipa: "/pʌŋkˈtɪliəs/", say: "punk-TIL-ee-us", lvl: 3, cat: "people",
  def: "Showing great attention to correct behaviour, rules or small details.",
  ex: ["He's punctilious about replying to every email within a day.", "The punctilious host remembered everyone's dietary needs."],
  syn: ["scrupulous", "conscientious", "exacting"], ant: ["careless", "lax"],
  origin: "From Italian puntiglio, 'a fine point', from Latin punctum, 'point'.",
  blank: "She's ___ about etiquette and always sends a handwritten thank-you card." },
{ w: "magnanimous", pos: "adjective", ipa: "/mæɡˈnænɪməs/", say: "mag-NAN-ih-mus", lvl: 3, cat: "people",
  def: "Generous or forgiving, especially towards a rival or someone less powerful.",
  ex: ["She was magnanimous in victory and praised her opponent.", "It was magnanimous of him to share the credit."],
  syn: ["generous", "gracious", "big-hearted"], ant: ["petty", "spiteful"],
  origin: "From Latin magnus, 'great', and animus, 'soul'.",
  blank: "The winning captain gave a ___ speech thanking the other team." },
{ w: "obstinate", pos: "adjective", ipa: "/ˈɒbstɪnət/", say: "OB-stih-nut", lvl: 2, cat: "people",
  def: "Stubbornly refusing to change your opinion or course of action.",
  ex: ["My obstinate toddler refused to wear shoes.", "He was obstinate about doing it his way."],
  syn: ["stubborn", "headstrong", "inflexible"], ant: ["flexible", "compliant"],
  origin: "From Latin obstinare, 'to persist'.",
  blank: "Don't be so ___; just try the new system for a week." },
{ w: "affable", pos: "adjective", ipa: "/ˈæfəbl/", say: "AF-uh-bul", lvl: 2, cat: "people",
  def: "Friendly, good-natured and easy to talk to.",
  ex: ["The affable barista remembers everyone's order.", "Despite his fame, he was relaxed and affable."],
  syn: ["friendly", "amiable", "approachable"], ant: ["unfriendly", "cold"],
  origin: "From Latin affabilis, 'easy to speak to', from ad-, 'to', and fari, 'to speak'.",
  blank: "Our new manager is ___ and always has time for a chat." },
{ w: "tenacious", pos: "adjective", ipa: "/təˈneɪʃəs/", say: "tuh-NAY-shus", lvl: 2, cat: "people",
  def: "Holding firmly to something; persistent and determined.",
  ex: ["She's a tenacious negotiator.", "The tenacious defender never gave up on the ball."],
  syn: ["persistent", "determined", "dogged"], ant: ["irresolute", "yielding"],
  origin: "From Latin tenax, 'holding fast', from tenere, 'to hold'.",
  blank: "It took a ___ reporter to uncover the story." },
{ w: "sanguine", pos: "adjective", ipa: "/ˈsæŋɡwɪn/", say: "SANG-gwin", lvl: 3, cat: "people",
  def: "Optimistic or positive, especially in a difficult situation.",
  ex: ["She's sanguine about the team's chances this season.", "Investors are less sanguine after the latest figures."],
  syn: ["optimistic", "hopeful", "upbeat"], ant: ["pessimistic", "gloomy"],
  origin: "From Latin sanguis, 'blood'. Medieval doctors believed a blood-dominated temperament made people cheerful.",
  blank: "Despite the delays, the builder remained ___ about finishing on time." },
{ w: "pensive", pos: "adjective", ipa: "/ˈpensɪv/", say: "PEN-siv", lvl: 2, cat: "people",
  def: "Engaged in deep or serious thought.",
  ex: ["He looked pensive, staring out at the rain.", "The song has a pensive, gentle mood."],
  syn: ["thoughtful", "reflective", "contemplative"], ant: ["carefree", "thoughtless"],
  origin: "From Old French pensif, from penser, 'to think', from Latin pensare, 'to weigh'.",
  blank: "She grew ___ when the conversation turned to her dad." },
];
